### ISSUE TITLE
Headline box gets larger after every restart of liferea

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#1000]
Every time I restart liferea, the number of lines displayed in the headline box grows (it seems by twice) in size.

**Comment by sunwire** [comment]
Did you see https://github.com/lwindolf/liferea/issues/901 ?

**Comment by rich-coe** [comment]
argh.  yet another regression that hasn't been merged yet.  thanks.

**Comment by sunwire** [comment]
FYI Workaround (as a plugin) for this issue has been merged https://github.com/lwindolf/liferea/commit/9a62436c02ff0e65f0b797fe13cd794c5f5b4938
