### ISSUE TITLE
Liferea does not respect system font settings

### ISSUE THREAD

**Issue by mgorny** [lwindolf/liferea#1008]
While most of the Liferea GUI seems to use system fonts correctly, the feed and headline view force tiny fonts that are completely unreadable on my screen. While I do realize that it is possible to workaround this, I believe it is a bug not to respect system settings like this.

![liferea](https://user-images.githubusercontent.com/110765/123742662-55c6d280-d8ac-11eb-9dae-3f4ca66ed939.png)

**Comment by lwindolf** [comment]
Which desktop are you using?

Please note that Liferea supports fetching the GNOME style default font setting via dconf.

**Comment by mgorny** [comment]
> Which desktop are you using?

Xfce.

Well, other parts of the UI look fine. I suspect this has something to do with webkit :-(.

**Comment by sunwire** [comment]
@mgorny You can change the webkit font size in the context menu (right mouse button).

**Comment by mgorny** [comment]
I've changed it via CSS already but I'm one of these guys who'd like to see it fixed for everyone.

**Comment by lwindolf** [comment]
The problem here is the number of desktop environments to support. Even doing it for XFCE and KDE would mean checking and merging (in a sane manner) 3 different sources of font configs from multiple config backends.

I understand the wish, but it is quite hard. 

I'm not even sure if XFCE already uses dconf...

**Comment by dunrix** [comment]
@lwindolf What about adding an option to set font parameters manually then?

I also do use lot of GTK+/GNOME applications in non-GNOME desktop/WM environments and find this annoying issue.

**Comment by lwindolf** [comment]
@mgorny @dunrix Sorry this problem is not fixable. It just doesn't make sense for all GTK/GNOME apps to add font settings for other DEs.

I fear this is the cost of us using different desktop environments. It is just not possible targetting all of those.
