### ISSUE TITLE
Unable to show Tools->Plugins window because "GObject.__init__() takes exactly 0 arguments"

### ISSUE THREAD

**Issue by macias** [lwindolf/liferea#1009]
openSUSE Leap 15.3, I tried both the latest stable version 1.12.9 and cloning github repo and compiling code myself. The outcome is the same, Liferea starts, works, but I cannot access Plugins window, because when I try to open it (by clicking Tools->Plugins) I get following error:
```
Traceback (most recent call last):
  File "/usr/lib64/liferea/plugins/plugin-installer.py", line 52, in _run
    self._browser = PluginBrowser()
  File "/usr/lib64/liferea/plugins/plugin-installer.py", line 73, in __init__
    self._notebook.append_page(PeasGtk.PluginManager(None), Gtk.Label("Activate Plugins"))
TypeError: GObject.__init__() takes exactly 0 arguments (1 given)
```

The above stacktrace comes from the stable version.

**Comment by sunwire** [comment]
I've just installed openSUSE 15.3 (GNOME if it's important) and everything works fine.
![2021-07-01_14-08](https://user-images.githubusercontent.com/50745572/124122357-869e3780-da65-11eb-98fe-b2e24814c860.png)

**Comment by macias** [comment]
Oh, thank you for the reply. I installed "minimal x server" version, after your reply I added "Gnome pattern" and indeed this time it worked.

So this leads me to two questions:

  1. do you know/can you guess which library is the culprit? (either I did something wrong or this is the Gnome way -- 588 new packages were installed so sifting through them... :-) )
  2. while (1) would be handy it would be great to add check against this library in Liferea code -- either at build stage or even as late as when triggering Plugins window so the user would see more informative message "Library XYZ is missing".

**Comment by sunwire** [comment]
@macias 
Ad.1 The Missing dependency is python3-gobject-Gdk and it looks like gnome-keyring is also missing
Ad.2 Build and run have different dependencies. The package manager should do this task.
You should report this issue to [openSUSE bugzilla](https://bugzilla.opensuse.org/)

**Comment by macias** [comment]
Many thanks for your help.

ad.1. "python3-gobject-Gdk "did the trick. I will report this against openSUSE of course.
ad.2. When installing with package sure thing, but on many occassions when reporting an issue reporter is asked to run the latest version, and since the code itself does not have any safeguard it would be useful to add such. If for any reason it is troublesome maybe at least mentioning it as dependency on main page?

**Comment by lwindolf** [comment]
@macias regarding point 2.) on Debian you do not need python3-gobject (I guess python3-gi is the package allowing the necessary bindings). So it is very hard to give a definitive dependency. As I'm developing on Ubuntu I can only safely provide the Debian style deps. Sorry that this is causing troubles.
