### ISSUE TITLE
Fix CI test error (memcheck)

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#1010]
Build https://github.com/lwindolf/liferea/runs/3092864091

reports lost memory.

**Comment by sunwire** [comment]
Honestly, I do not know why memcheck.sh fails.
I tested it on Fedora 34/35 and Ubuntu 18.04 (CI use it) and I've never had any problems.
Maybe, for now just remove memcheck.sh form workflow.

**Comment by lwindolf** [comment]
Hmm... the check helps a lot. I think we just have to filter the small "noise" (e.g. stuff <500 bytes) that appears on strange conditions.

**Comment by lwindolf** [comment]
I've solved the issue by introducing a suppression for selinuxfs_exists(). Seems to be caused by the docker execution, but should not affect Liferea. I also added more detailed output with a collapsible group per check so we can drill down to the causes.
