### ISSUE TITLE
Certificate problems with some URLs

### ISSUE THREAD

**Issue by mokraemer** [lwindolf/liferea#1013]
Some URLs like
https://www.php.net/releases/feed.php
Produce just "HTTP-Error 0: ".
I assume there is some problem/warning with the certificate the server uses.

**Comment by sunwire** [comment]
Do you use Fedora Linux? If yes you have to change the crypto policy to legacy, long story short, some old/unsecure protocols are not allowed anymore.
Check current policy:
`update-crypto-policies --show`
It probably returns DEFAULT.
Set policy to LEGACY:
`update-crypto-policies --set LEGACY`
and restart system
more info:
https://fedoraproject.org/wiki/Changes/CryptoPolicy
https://fedoraproject.org/wiki/Changes/StrongCryptoSettings2

**Comment by mokraemer** [comment]
yeah that solves the problem. Should lifera support older protocols w/o changing this setting?

**Comment by sunwire** [comment]
> yeah that solves the problem. Should lifera support older protocols w/o changing this setting?

I don't think so. These settings are global for the entire system.
Rather, website owners should stop using outdated algorithms.

**Comment by mokraemer** [comment]
Good idea, but firefox and chrome do not even complain about these certificates.
So, if epiphany and liferea stop showing contents from these sites, no one blames php.net, but liferea and others. this is a very weak situation. Event just showing "Error 0" is not very useful to anyone.

**Comment by sunwire** [comment]
I assume that Firefox/Chrome uses other libraries (ssl/tls) than Liferea and the settings do not affect Firefox/Chrome
You are right error reporting in this case is useless.

**Comment by mokraemer** [comment]
=> it would be great to show sth. why the connection fails. E.g. cipher for this host not supported, or too weak. Without your reply (thanks again) I would never looked for this system setting.

**Comment by sunwire** [comment]
I did a little research and found liferea shows the wrong message
https://github.com/lwindolf/liferea/blob/master/src/net.c#L442
Based [on this documentation](https://developer.gnome.org/libsoup/stable/libsoup-2.4-soup-status.html#SoupStatus), the message should be "SSL/TLS negotiation failed"
