### ISSUE TITLE
Firefox support for adding feeds

### ISSUE THREAD

**Issue by hermann-san** [lwindolf/liferea#1020]
some websites have a RSS link/symbol and when I click on it, my expectations would be that it opens (or gives me the option) to open it in Liferea. However, Liferea is not on the list. Is there a way to get it on the list?
Thanks.

https://forum.yunohost.org/c/announcement/security/12.rss

![image](https://user-images.githubusercontent.com/7679654/129263133-7f5f9517-97ce-4c58-8ece-6a380c359159.png)

**** UPDATE ****
I think I've fixed it by making Firefox to ask me what to do when a URL when .rss is encountered by Firefox. I did use the Firefox extension "Content-Type Fixer" to solve it. First one has to turn on Content-Type Fixer and then open the .rss URL once. Then, via in the Add-on symbol click on "add/edit content types. Then I've added "./user/bin/liferea". I'm not sure if this is right, but the result was that Firefox asked me what to do when encountering a .rss URL.  Then in the pop-up you can select Liferea and let it open Liferea once or always.

A Peertube URL doesn't have a .rss link but a XML link and it work similar to .rss.  I was worrying that XML is not at the end of the URL, but that doesn't matter. Example URL below.
https://video.ploud.fr/feeds/videos.xml?videoChannelId=26970

This time I've selected in Content-Type Fixer the following "application/x-xmlfile (fictitious)"   instead of adding the path to Liferea "./user/bin/liferea"  . It still works fine.

![image](https://user-images.githubusercontent.com/7679654/129267128-40967f96-6ff7-495a-921c-fffd39ce0edb.png)

Maybe there is a better way of doing it, but this way it works at least for me.

**Comment by lwindolf** [comment]
Your approach is the right one. In the past it was much easier, but nowadays browsers think offering online services only is best...
