### ISSUE TITLE
Image Not Found / Not Loading

### ISSUE THREAD

**Issue by FX9ZVI** [lwindolf/liferea#1030]
![liferea bug](https://user-images.githubusercontent.com/43688083/137037343-f35e9412-b5f7-4c91-99d2-08e575e34ba6.png)
Feed (https://rss.app/feeds/sR4mbXvYUn2aIrzW.xml) doesn't load images, not sure if it's Liferea's fault or the feed. Willing to provide any further info needed.

**Comment by lwindolf** [comment]
Hmmm... responding too late as rss.app link has timed out already.

But what is visible even from the error feed content the URLs inside are correct

https://scontent-dfw5-2.cdninstagram.com/v/t51.2885-19/s150x150/123375001_409670250047928_7499710174248614861_n.jpg?_nc_ht=scontent-dfw5-2.cdninstagram.com&amp;_nc_ohc=NcwvAgih_UQAX9n3dju&amp;edm=AAuNW_gBAAAA&amp;ccb=7-4&amp;oh=4999c1b74fee44f8933880d63212ec84&amp;oe=61772082&amp;_nc_sid=498da5

But calling them returns "URL signature expired". You can reproduce this by right clicking the broken image icon and select "View Image".

I think this is intended behaviour by rss.app. Right now I can see no bug in Liferea.
