### ISSUE TITLE
webview show bright white html page when my GTK Theme is Arc-Dark and the rest of liferea has this theme applied

### ISSUE THREAD

**Issue by claf** [lwindolf/liferea#1031]
My issue might be quite close to https://github.com/lwindolf/liferea/issues/100 .
window manager is i3, distrib is xubuntu, liferea version is 1.13.1, GTK theme is arc-dark (applied with lxappearance)

![2021-10-13-09:20:08_337x156_capture](https://user-images.githubusercontent.com/1221911/137085870-fd7ebdbd-1cbd-4d23-8998-b8d919c7952a.png)

```
$> liferea --debug-html
HTML   : theme color "GTK-COLOR-FG" is D3DAE3
HTML   : theme color "GTK-COLOR-BG" is 383C4A
HTML   : theme color "GTK-COLOR-LIGHT" is 454C64
HTML   : theme color "GTK-COLOR-DARK" is 292B32
HTML   : theme color "GTK-COLOR-MID" is 373B4B
HTML   : theme color "GTK-COLOR-BASE" is 383C4A
HTML   : theme color "GTK-COLOR-TEXT" is D3DAE3
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is A9CAF1
HTML   : theme color "GTK-COLOR-VISITED-LINK" is D3DAE3
HTML   : Dark GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_BG" is D3DAE3
HTML   : theme color "FEEDLIST_UNREAD_FG" is 383C4A
HTML   : Feed list unread CSS: foreground='#383C4A' background='#D3DAE3'
```

Any other info I might need to add?

**Comment by lwindolf** [comment]
Reproduced

**Comment by lwindolf** [comment]
@claf What I can reproduce is that right after switching the theme the item view stays in the wrong them until the next item is selected. Then the theme is correct again.

Is this the same for you?

**Comment by claf** [comment]
@lwindolf seems I cannot reproduced anymore, webview seems to be fixed for me.

**Comment by lwindolf** [comment]
@claf Thanks for the feedback. I'll use the ticket to track one remaining effect that the item view is not immediately in correct theme colors.

**Comment by lwindolf** [comment]
Seems like an expose related problem. Upon theme switch the entire pane redraws when hovering with a mouse...

**Comment by lwindolf** [comment]
Upon thinking about this, I think this is actually ok. So closing this.
