### ISSUE TITLE
Reader Mode hides Read More link

### ISSUE THREAD

**Issue by LiohMoeller** [lwindolf/liferea#1032]
If a feed contains a Read More link after some articles, the link is not displayed in Reader Mode:

e.g. rss part:

```
<description>
...the power of free and open-source software" Anfang September erschienen ist.</p> <p><br><br><a href="https://test.gnulinux.ch/freie-software-in-der-wissenschaft">Weiterlesen</a>
</description>
```
The _Weiterlesen_ Links is just not shown in Reader Mode.

**Comment by lwindolf** [comment]
This is actually hard to value. One user might want to see the link another might not...

How to decide this?
