### ISSUE TITLE
How to rectify "auto discovery found no feeds on this page"

### ISSUE THREAD

**Issue by kyrofa** [lwindolf/liferea#1034]
I have a Hugo-powered blog at https://kyrofa.com. I have the following in my `head`:
```
<link rel="alternate" type="application/rss&#43;xml" href="https://kyrofa.com/index.xml">
<link rel="alternate" type="application/json" href="https://kyrofa.com/index.json">
```
If I hand https://kyrofa.com/index.xml to Liferea it's happy, but if I try to give it http://kyrofa.com, it bombs with:

```
There were errors while parsing this feed! (Parser Error Details) Details
Could not detect the type of this feed! Please check if the source really points to a resource provided in one of the supported syndication formats!

XML Parser Output:
The URL you want Liferea to subscribe to points to a webpage and the auto discovery found no feeds on this page. Maybe this webpage just does not support feed auto discovery.Source points to HTML document.

You may want to contact the author/webmaster of the feed about this!
Feed:	New Subscription
Source:	https://kyrofa.com/
```

I'm sure this isn't a bug in Liferea, but it's not giving me enough information to go on. I'd like to get autodiscovery working, how do I proceed to debug this?

**Comment by mozbugbox** [comment]
Obviously liferea doesn't know `&#43;` means `+` in your rss mimetype.

 Just use then plain old `+` like `type="application/rss+xml"` will make it work.

**Comment by lwindolf** [comment]
Liferea relies on libxml for all HTML/XML/XHTML processing and it does not seem to accept the &#43;

Closing this a won't fix.
