### ISSUE TITLE
No scrool bar in the window that displays content

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#1041]
This in version liferea-1.13.6

The scroll works with the wheel mouse, but if I want to go to the end of the content I don't have a scroll bar to do this.,

**Comment by lwindolf** [comment]
Are you using Ubuntu?

**Comment by ndias** [comment]
No, sorry for not report the system, I'm using Fedora 35

**Comment by sunwire** [comment]
What desktop are you using? Gnome, XFCE, Mate?
I'm using Fedora 35/Mate desktop and I have all scroll bars.

**Comment by ndias** [comment]
gnome-shell X11

**Comment by lwindolf** [comment]
Strange. Do you see scrollbars in the left pane (feeds) and the item list pane? If yes, and the scrollbars are only missing in the article view it could be a webkit issue.

And no other GNOME apps are affected?

**Comment by sunwire** [comment]
Scrollbars are visible, but they are hidden  and appear only after hovering on them.

https://youtu.be/TlSEnMPXbz8

If you want, you can turn off this beahvior
`gsettings set org.gnome.desktop.interface overlay-scrolling false`
This method does not work on the browser panel

**Comment by ndias** [comment]
Yes I can see scrollbars in the left and pane feeds, only in the article view is missing the scrollbars.
 And yes, I have the same problem in Evolution mail reader.

> Strange. Do you see scrollbars in the left pane (feeds) and the item list pane? If yes, and the scrollbars are only missing in the article view it could be a webkit issue.
> 
> And no other GNOME apps are affected?

**Comment by lwindolf** [comment]
Closing old ticket.
