### ISSUE TITLE
Cannot open Liferea on ElementaryOS 5.1 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by anjutahanuta** [lwindolf/liferea#1055]
I tried to install several versions (starting with 1.12.1. from the repositories) and always get errors about the gnome-keyring. 
As a last step I added this [PPA]( http://ppa.launchpad.net/ubuntuhandbook1) and installed Liferea 1.13.3 from there. I see this error: 
`(liferea:13442): libpeas-WARNING **: 19:33:13.983: Error importing plugin 'gnome-keyring':
Traceback (most recent call last):
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py", line 27, in <module>
    gi.require_version('Secret', '1')
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 130, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Secret not available
`
Before the errors were a bit different, something like "no keyring with that name found".

Do you have any ideas? I already tried to compile it myself, but always ran into glib errors and not found dependencies like pango and gtk+?

ElementaryOS is a fork of Ubuntu and usually I don't experience any problems installing Ubuntu packages.

**Comment by anjutahanuta** [comment]
I should maybe add that installing the package worked fine. Dependencies were identified and installed. It's just that I cannot open and use it.

**Comment by sunwire** [comment]
Is libsecret installed?

**Comment by anjutahanuta** [comment]
Thank you for your help.
Part of it was installed:
`Hinweis: »libsecret-1-0« wird für das Suchmuster »libsecret*« gewählt.
Hinweis: »libsecret-common« wird für das Suchmuster »libsecret*« gewählt.
Hinweis: »libsecret-tools« wird für das Suchmuster »libsecret*« gewählt.
Hinweis: »libsecret-1-dev« wird für das Suchmuster »libsecret*« gewählt.
libsecret-1-0 ist schon die neueste Version (0.18.6-1).
libsecret-1-0 wurde als manuell installiert festgelegt.
libsecret-common ist schon die neueste Version (0.18.6-1).
libsecret-common wurde als manuell installiert festgelegt.
Die folgenden zusätzlichen Pakete werden installiert:
  gir1.2-secret-1
Die folgenden NEUEN Pakete werden installiert:
  gir1.2-secret-1 libsecret-1-dev libsecret-tools
`
This is the German text, but I hope you can understand what was done.
After that I tried to start liferea again by typing `liferea` into the terminal.
I didn't see any errors and the process stayed open, but no window is visible. It looked like some invisible window opened, I don't know how to exactly describe that. It shows in the dock and when I click on it it changes to the desktop on which I opened it. I just don't see the application.

Any more ideas?

**Comment by anjutahanuta** [comment]
I managed to run configure, make, and make install after installing a number of packages. I had problems to find the ones that were necessary, because the installer complained about, e.g., "sqlite3" and I had to install "libsqlite3-dev" or something like that. Maybe that's a knowledge gap on my side, but I never had to compile packages on my own before...
However, I still have the problem described above: The application opens without any error, but does not show up.

Maybe this helps for debugging? I saw these errors on running make:

`ui/icons.h:59: Warning: Liferea: "@icon" parameter unexpected at this location:
 * @icon:	the icon
    ^
(liferea:16016): GLib-GIO-CRITICAL **: 18:37:41.304: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_get_string: assertion 'value != NULL' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_unref: assertion 'value != NULL' failed

(liferea:16016): GLib-GIO-CRITICAL **: 18:37:41.304: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_get_type: assertion 'value != NULL' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_unref: assertion 'value != NULL' failed

(liferea:16016): GLib-GIO-CRITICAL **: 18:37:41.304: g_settings_get_value: assertion 'G_IS_SETTINGS (settings)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_get_type: assertion 'value != NULL' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_type_is_subtype_of: assertion 'g_variant_type_check (type)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_get_boolean: assertion 'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(liferea:16016): GLib-CRITICAL **: 18:37:41.304: g_variant_unref: assertion 'value != NULL' failed

(liferea:16016): GLib-GObject-WARNING **: 18:37:41.304: invalid (NULL) pointer instance

(liferea:16016): GLib-GObject-CRITICAL **: 18:37:41.304: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(liferea:16016): GLib-GObject-WARNING **: 18:37:41.304: invalid (NULL) pointer instance

(liferea:16016): GLib-GObject-CRITICAL **: 18:37:41.304: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
  GICOMP   Liferea-3.0.gir`

**Comment by nekohayo** [comment]
@anjutahanuta you shouldn't have to compile packages by hand unless you really know what you're getting into. Instead, considering how extremely old and outdated your Linux distribution is (4 years is an eternity), it would make much more sense if you installed it using flatpak at least, from https://flathub.org/apps/details/net.sourceforge.liferea

**Comment by anjutahanuta** [comment]
Hi @nekohayo,
yeah, you're right, I didn't know what I was doing ;) 
Well, yes, my distro is outdated, but that's the downside of using ElementaryOS :(
I never heard of flatpak before, but will have a look at it.
I actually managed to install Liferea in the end, but I cannot remember how ... I have version 1.12.2 successfully running :)
