### ISSUE TITLE
Cygwin Compile Error

### ISSUE THREAD

**Issue by Whoareyouagain** [lwindolf/liferea#1062]
Hello, I am need of help if you don’t mind. I been wanting to try out Liferea on Windows 10. I haven’t found the right RSS reader for myself (tried RSSOwl, RSSGuard & QuiteRSS). I don’t know If I am doing wrong with Cygwin to compile Liferea. I did try that Cygwin Liferea binary link but to led to 404 (assuming the link is completely dead). I been wanting to try to compile a software and this is all new for me. 
[terminal.cygwin.log](https://github.com/lwindolf/liferea/files/7772221/terminal.cygwin.log)

I keep running into compile issue during ./configure, I am assuming I am missing dependencies that Liferea needs. It seems to show me one at the time, I reinstalled Cygwin few times to get the dependencies for Liferea. And I am stuck, and I don’t know where to go from there. I followed an instruction of how to compile LIfearea with Cygwin. 

It looks like it couldn’t find glib package(?), so I tried to look at the package and only see millions of them and not sure where to go from there. First, it couldn’t find GCC, managed to get it find it. Then it is intltool, then I installed the package. And tried again, then it got to glib issue. 

I attached the command prompt and the config.log. This is on Windows 10 Pro 21H2

[config.log](https://github.com/lwindolf/liferea/files/7772215/config.log)

[terminal.cygwin.log](https://github.com/lwindolf/liferea/files/7772221/terminal.cygwin.log)

**Comment by lwindolf** [comment]
Sorry about the late response.

You are missing some dependencies on Windows. I cannot tell how to get hold of those dependencies.

An easier solution for Win10 would be installing WSLv2 and a X server like GWSL. Then you could install an Ubuntu distro into WSLv2 and could easily compile according to the Ubuntu compilation instruction in the README.

HTH!

**Comment by seflerZ** [comment]
Also remember to use "sudo apt liferea build-dep” to install the building essentials.

**Comment by lwindolf** [comment]
Closing old issue
