### ISSUE TITLE
Content display problems

### ISSUE THREAD

**Issue by jfbauer432** [lwindolf/liferea#1063]
I noticed that sometimes part of the content doesn't display at all.  But if you make a small change to it, it will display properly.

I attached a small example xml (as .txt) that show the problems.  If you add this file as a new feed and look at it, you'll only see part of the content (the part with all the x's).  If you then do any of the following, it'll render ok

- change the long string of digits (123456789012345...) to be 1 character less
- change any of the ","s in the section with all the x's to a letter (I used "Z")
- add some text (1 letter is enough) before or after the link

[bad.xml.txt](https://github.com/lwindolf/liferea/files/7774970/bad.xml.txt)

Ran this on Ubuntu 21.10.  liferea version 1.13.4 (from ubuntu repository) as well as 1.13.7 built from the git repo (also on Ubuntu 21.10) and both showed the same problem.

Also If you run liferea with the --debug-html option and view the output.html in a browser (I used firefox), it rendered as expected.  (Only tied that with liferea 1.13.4)

**Comment by mozbugbox** [comment]
see if issue #971 helps, i.e. turn off the `reader mode`.
