### ISSUE TITLE
View mode of liferea doesn't work globally

### ISSUE THREAD

**Issue by larryw3i** [lwindolf/liferea#1067]
## View mode of liferea doesn't work globally  
Normal view and Wide view just works for recent feed individually, it doesn't work for all feeds, I have to set each feed to Wide view if Wide view is my favorite.  
I expect it to be repaired soon.  

OS: Ubuntu 21.10 x86_64   

Regards
larryw3i.

**Comment by lwindolf** [comment]
You are in violation of the license of Liferea. You did accept the use AS IS clause in the license, your expectation is violation the clause. Please refrain from this violation :-)

Best Regards

**Comment by larryw3i** [comment]
> You are in violation of the license of Liferea. You did accept the use AS IS clause in the license, your expectation is in violation of the clause. Please refrain from this violation :-)
> 
> Best Regards

Ah? I didn't make any changes! I didn't even check the source code. I just feedback a bug.

**Comment by lwindolf** [comment]
Thanks for your feedback!

Looking at the issue there are two possible views on this:

1. one group of users wanting a global setting (this includes you)
2. another group of users wanting per-feed settings

The decision some time ago was to support only one use case and this being the 2nd one.

**Comment by larryw3i** [comment]
@lwindolf , thank for your reply, maybe I don't ever explain this issue clearly, what my mean is "Tool bar --> View --> Normal/Wide View" doesn't work for all my feed, it just works for current feed which is opening/reading.

**Comment by lwindolf** [comment]
@larryw3i Yes, this is how I understood it. This behavior was implemented like this. It is intentional.

**Comment by larryw3i** [comment]
Ok, in short, Liferea is excellent and thank you again.
