### ISSUE TITLE
[Refactor] Drop all proxy handling in Liferea

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#1068]
To simplify our code base drop all proxy preferences and environment logic as this is properly covered by libsoup nowadays (see GProxyResolver docs).

Change documentation to hint on desktop environment settings or (for non-standard users) to use environment variables to allow for full proxy flexibility.

**Comment by RedHoodHacker** [comment]
Hey is it okay if I take a crack at this? I know Python and Bash and I know that isn't relevant right now but I'll
do what this says and then ask you to take a look at it? I am a Noob at opensource projects and want to get into them to work on coding and such...

**Comment by lwindolf** [comment]
Turned out to be unrealistic.
