### ISSUE TITLE
Fullscreening HTML5 videos should really fullscreen them

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#107]
Like most Webkit-based apps I've seen in the past, clicking the "fullscreen" button on HTML5 videos does not put them in fullscreen of the screen, only "full-webkit-area". It is somewhat okay-ish in Liferea's normal layout mode, but the concept breaks down pretty quickly in "wide" view mode:

![capture d ecran de 2014-10-24 20 36 59](https://cloud.githubusercontent.com/assets/479401/4778182/355b9cba-5be0-11e4-9ea1-158a146bdea8.png)

I'm not sure exactly how the Epiphany/WebkitGTK folks did it, but this works fine with Epiphany 3.12 so there must be a way to do true fullscreen natively these days...

**Comment by lwindolf** [comment]
This was implemented with #178
