### ISSUE TITLE
Allow custom bookmark sites

### ISSUE THREAD

**Issue by Lucidiot** [lwindolf/liferea#1070]
I tried to look for a way to add a URL to post on https://tilde.news/ from within Liferea (`https://tilde.news/stories/new?title=%s&url=%s`). I saw the `social_register_bookmark_site` function calls and tried to find something related to it in the GTK inspector and the python console plugin, to maybe make my own plugin to add the URL since that is not possible from the UI, but could not find anything.

Would it be possible to add a way to add custom sites, or should I write a plugin that creates a whole another menu button?

**Comment by mozbugbox** [comment]
I guess you can make a filter for that feed. 

In each item of the feed, append an html `<form>` to the `<description>` element of RSS. Use the form for submitting new post to that site.

**Comment by lwindolf** [comment]
The relevant API in social.c is already exposed. Adding a plugin would make sense.

**Comment by lwindolf** [comment]
d5618c7a switched social bookmark registration to simpler URLs with placeholders instead of positional %s

**Comment by lwindolf** [comment]
Implemented as a new plugin.

![Screenshot from 2022-10-14 22-44-55](https://user-images.githubusercontent.com/3315368/195940530-ba3536b6-3820-407d-b2b1-f28b14b6f640.png)
![Screenshot from 2022-10-14 22-45-14](https://user-images.githubusercontent.com/3315368/195940548-a68eaa04-ef6f-450b-82b8-eb25ce029723.png)
