### ISSUE TITLE
URLs inside descriptions are not parsed/rendered correctly

### ISSUE THREAD

**Issue by ao2** [lwindolf/liferea#1072]
Hi,

I generate RSS with [tweeper](https://git.ao2.it/tweeper.git/) and I put HTML content in the description element using CDATA, the feed is valid, which means that HTML entities are escaped in attributes, like for example in the `src` attribute of `img`.

The HTML parser used in the description view should unescape the attributes itself (e.g. the `&amp;` in URLs should be converted back to `&`), but apparently it does not, and in my case this results in images not directly viewable in the description view.

See for example the following feed generated from Instagram: 
[Instagram_Gaiola.xml.gz](https://github.com/lwindolf/liferea/files/7831420/Instagram_Gaiola.xml.gz)

The images are not displayed in the description view, even though the URLs are valid: if you right-click and select "View Image" the image is opened correctly in another tab. 

Can we have this fixed please?

I can work around that by using Data URLs and inlining images inside the `src` attribute, but this can broke other feed readers.

Thanks, Antonio

**Comment by lwindolf** [comment]
![Screenshot from 2022-10-12 01-26-24](https://user-images.githubusercontent.com/3315368/195216438-38bd0184-f758-436c-9278-fd024912f5f2.png)

I checked with your example feed. The rendered HTML is as shown above. The `<img src="">` tag contains no escaped entities which is what you expect right?

This means I cannot reproduce this. If you want to check this for yourself install the Webkit Inspector plugin and press F12 after focussing the HTML pane.
