### ISSUE TITLE
Cpu buzzer beeper sounds at the top and bottom of the list

### ISSUE THREAD

**Issue by fbm224** [lwindolf/liferea#1075]
Hi, 

When at the bottom or top of a list and trying to get to the next (in-existing one) with the down or up key (respectively) the motherboard buzzer / beeper is activated. I cannot say this is not what the programmers intended to happen. But I'm really uncomfortable by it, because is not like really important system issue, like overheating o something else.

I'm using opensuse tumbleweed,  Liferea V 1.13.6-3.1-noarch, it also occurred on the previous version I had installed. 

Thank you.

**Comment by lwindolf** [comment]
I'd guess this is an accessibility feature of GTK that is enabled on your desktop.

This does not happen on my system and there is no feature implemented in Liferea doing any beeping.
