### ISSUE TITLE
Get Focus plugin fails to save/read settings under Flatpak

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#1077]
Steps:

1. Run the flatpak `flatpak run net.sourceforge.liferea`
2. Enable Get Focus plugin
3. Change the opacity value, save and restart Liferea
4. See that the setting is not saved and no setting file is created.

I haven't tested this but I think the issue is here

https://github.com/lwindolf/liferea/blob/69cdf4c0ca820353131994732272c4395a438b45/plugins/getfocus.py#L36-L37

It tries to get the config directory relative to home directory but under the sandbox it is: `XDG_CONFIG_HOME=/home/user/.var/app/net.sourceforge.liferea/config`. (check with flatpak run --command='sh' net.sourceforge.liferea then printenv)

So it tries to save the setting to `/home/user/.config/liferea/plugin/...` but the sandbox has no access there, so it fails silently.

Instead it should try to save config relative to `XDG_CONFIG_HOME` as set in the environment.

**Comment by sunwire** [comment]
@bbhtt If you have time, please test this PR #1078
