### ISSUE TITLE
Embedded webkit feed item preview is missing background color for the preview pane, for dark mode

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#1096]
When running Liferea 1.13.7 with GNOME 41's Adwaita-dark theme (I haven't yet tried with GNOME 42's true dark mode... I guess we'll see in May!), this is what you get for feed items for feeds that are configured to load the full page instead of the feed item:

![Screenshot from 2022-03-12 01-05-34](https://user-images.githubusercontent.com/479401/158006277-f2382092-5c1c-49d0-92a6-7d9cd8728a6e.png)

As you can see, the preview pane inherits the GTK theme's background color, instead of hardcoding white by default if the webpage doesn't specify a background color (like what seems to be the case in the Atlantic, such as [this article page](https://www.theatlantic.com/health/archive/2022/03/long-covid-risk/627031/)).

However, if opening the same item in a "new tab" in Liferea, it gets rendered with the correct white background color:

![Screenshot from 2022-03-12 01-05-09](https://user-images.githubusercontent.com/479401/158006359-159ca295-647c-4bdf-8806-668026c11f0a.png)

So maybe you already have the code for this, and need to apply it to the preview pane in the corner case where a web view is shown in that pane instead of RSS contents or "reader mode" contents?

**Comment by lwindolf** [comment]
Reproduced

**Comment by lwindolf** [comment]
There is also another related bug: tabs do not follow dark mode.

**Comment by lwindolf** [comment]
Fixed a regression, that the user stylesheet has to be reapplied when switching back to another item.
