### ISSUE TITLE
"reader mode" needs some margins around the text

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#1097]
In 1.13.7, when a feed item's contents are shown in "reader mode" in the preview pane, the text goes flush against the left and right edges of the pane, which looks and feels "wrong".

To look coherent with other GTK applications (and be a bit easier to read, too) it should have margins all around (or at least on the left and right) of 12 pixels; this is a guess, as I suppose that 6 pixels would be insufficient (the GNOME-2-era HIG had standard increments-of-6-pixels spacing/margins standards, and I'm not sure if those are still the exact same numbers nowadays, but still use them).

**Comment by lwindolf** [comment]
Proper layout is planned! It just still in implementation... :-(

**Comment by lwindolf** [comment]
Fix already in place in PR #1102

**Comment by lwindolf** [comment]
Fix was merged.
