### ISSUE TITLE
Keyboard shortcut for open in external browser

### ISSUE THREAD

**Issue by Davidy22** [lwindolf/liferea#1098]
A keyboard shortcut for opening feeds in a browser would be nice, so I can keep my hands fully on the keyboard when pushing through my feeds. There's some amount of stuff on my feed that only renders right in the browser,  so I want to open those in Firefox while I'm churning through the feeds list then afterwards go through the firefox tabs to see the rest of the stuff I wanted to see.

A way to scroll the current viewed article without taking my hands off the keyboard would be nice too, but I feel like this is something that's already in the program and I just haven't found it yet.

**Comment by lwindolf** [comment]
Good idea!

**Comment by mozbugbox** [comment]
There is an action call 'launch selected item in the  browser' action. You just need to bind it to a specific key.

**Comment by Davidy22** [comment]
Went in real quick, took a short look around, [made a tiny bit of additions](https://github.com/Davidy22/liferea/commit/0d8a36b160bc5ee242d2c7c1c517a44aba8d65a9) but haven't actually tested or compiled yet because random libs that I have installed it thinks aren't installed and I don't have time to get the build working right now. If this is pretty much it that'll be great, otherwise I'll maybe find time in the next month to come back and get the build to work so I can test and finish a pr

**Comment by lwindolf** [comment]
@Davidy22 Looks good. For completeness we should add the hotkey to the help document in doc/html/reference_en.html. Feel free to make a PR!

**Comment by Davidy22** [comment]
Still haven't actually run it but if it worked for you I'll make the PR.

**Comment by Davidy22** [comment]
This is the first time I've made a pull request without building and testing and somehow this was the one PR I make where I get it in on the first try
