### ISSUE TITLE
Leaving web page hangs app in poll() called from g_tls_connection_gnutls_close

### ISSUE THREAD

**Issue by badshah400** [lwindolf/liferea#110]
Originally reported at:
https://bugzilla.opensuse.org/show_bug.cgi?id=902622

While running liferea, I loaded the webpage from here:
https://www.backblaze.com/blog/hard-drive-reliability-update-september-2014/

I can scroll up and down within the webpage, but if I try and switch to the
next item, the application hangs in poll() called from g_tls_connection_gnutls_close().

Stack trace follows in next comment.

**Comment by lwindolf** [comment]
Judging from the backtrace I believe there is nothing Liferea can do differently. The API invocation in frame 29 is webkit_web_frame_load_data() which just passes HTML to Webkit. No controlling of SSL connection behaviour :-(
