### ISSUE TITLE
Dates are overwritten every update with some RSS feeds

### ISSUE THREAD

**Issue by Davidy22** [lwindolf/liferea#1100]
I have some RSS feeds that probably have improperly formed date fields (elbowing the github blog here as the main apparent offender https://github.com/blog.atom), and it would be nice if liferea could just store the date that stories were first added, instead of the last update date. The entries from the github blog aren't being marked as unread every update, so liferea seems to still have some concept that they're not completely new stories. Currently, their attached date is being reset to the last update date, which messes up the story sorting.

**Comment by mvz** [comment]
Here's probably another example: https://progrium.com/blog/index.xml. All items show the feed's lastBuildDate as their date instead of the individual items' pubDate.

**Comment by lwindolf** [comment]
@mvz @Davidy22 I believe the issue to be fixed. Please retest!
