### ISSUE TITLE
Synchronization with FreshRSS.

### ISSUE THREAD

**Issue by guillaumesoucy94** [lwindolf/liferea#1113]
Hello, 

I don’t know if I’m at the right place but, I will ask my question in anyway. 

I do use FreshRSS to get my RSS feeds but, when trying to synchronize Liferea with FreshRSS, only 400 of all the articles get downloaded. 

On my iPhone, I have another RSS reader and I can synchronize all the articles. 

I’m using Liferea on Linux Mint 20.3 Una, using the distro’s version 1.12.7

Is someone can please provide some help?

Thank-you,

Guillaume

**Comment by guillaumesoucy94** [comment]
Hello, 

Anyone? Please

**Comment by Alkarex** [comment]
Liferea does not yet support adding a generic server implementing a Google Reader API https://github.com/lwindolf/liferea/issues/962

Explanation of the confusion https://github.com/FreshRSS/FreshRSS/issues/4328#issuecomment-1108888084

**Comment by lwindolf** [comment]
> Hello,
> 
> Anyone? Please

@guillaumesoucy94 This

**Comment by lwindolf** [comment]
Generic Google Reader API support has landed in master.
