### ISSUE TITLE
Content are minimized to 0px at start

### ISSUE THREAD

**Issue by Nudin** [lwindolf/liferea#1123]
When liferea is started after a crash, the content area (lower area on the right) is 0px (or 1px?) high:
![lifera2m1](https://user-images.githubusercontent.com/509205/175023340-2411d942-f6b8-41f5-bc79-abdb19f95cf3.png)

One needs to really carefully move the cursor to the lower edge of the window and only if the cursor is at the exact right height (1px precision) one can move the slider back up to be able to read content again.

For me, this bug appears since many years, I only was too lazy to report earlier.

Maybe the easiest fix would be to set the height to at least N pixel at startup?

I use:
- Liferea 1.13.6
- Arch linux
- Mate on X11

**Comment by sunwire** [comment]
It looks like issue https://github.com/lwindolf/liferea/issues/901

**Comment by lwindolf** [comment]
Now we resize view panes to sensible positions when they were at min or max position on last shutdown. Makes left pane 30% window width and item list pane 50% height/width when pane position is 0 or 95% of height/width.

Note: that the pane position workaround plugin must not be used anymore for this!
