### ISSUE TITLE
h-feed h-entry support

### ISSUE THREAD

**Issue by sjehuda** [lwindolf/liferea#1127]
This can be a very useful addition, no less than it's ability to [guess](https://lzone.de/liferea/blog/Subscribing-to-HTML5-websites-that-have-no-feed) news entries from `</article>` elements.

Unlike the guessing feature this is a constructive format and by so makes it easy to allocate information like author, categories etc. (just like Liferea does with XML).

h-feed is a simple, open format for publishing a stream or feed of h-entry posts, like complete posts on a home page or archive pages, or summaries or other brief lists of posts. h-feed is one of several open microformat draft standards suitable for embedding data in HTML.

https://microformats.org/wiki/h-feed
https://microformats.org/wiki/h-entry
https://github.com/kurtmckee/feedparser/issues/309#issuecomment-1184461650

**Comment by lwindolf** [comment]
I agree that it is an easy and well-parseable format. Yet I do not see it beneffiting Liferea users, due to its missing distribution (aside from WordPress which already provides proper Atom/RSS feeds).

**Comment by sjehuda** [comment]
Yes, but some websites might not do so.
Mastodon [claim](https://github.com/mastodon/mastodon/issues/18845) to support it.
Some webmasters might disable xml feeds, but they still will use h-feed/h-entry.

For instance, SearxNG instance of https://searx.be/ has xml feeds disabled.

**Comment by lwindolf** [comment]
I'll checkout both.

**Comment by lwindolf** [comment]
I thought a bit on this and believe the use case is not wide-spread enough. Closing as won't be implemented. I hope you understand.

**Comment by sjehuda** [comment]
Pardon me for my expression, but I think your attitude is wrong.

Liferea is a feed reader which is used by many people, hence YOU are
a market maker, YOU are one of a very few people that influence and
reflect on the future of popularity and standards of web feeds.

If Liferea would publish in "Help > Contents" a list of type of feeds
that are supported, people will be more exposed to h-entry and h-feed,
and show their interest.

Example:

# Feeds and Technologies used in Liferea

## Supported Feeds

ActivityStream
Atom 1.0
hAtom 0.1
h-entry
h-feed
JSON Feed 1.0
JSON Feed 1.1
RSS 0.9
RSS 0.91
RSS 0.92
RSS 0.93
RSS 0.94
RSS 1.0
RSS 2.0
RSS-in-JSON 2.0
Simple Machines Forum

## Supported Technologies

Flash (ruffle plugin)
HTML
(x)HTML
JavaScript
OPML Outline

@lwindolf, think of determining the market, not following it.

P.S.

I think a forum (i.e. interest group) should be established where we
get more confidence in ourselves, not the flawed IETF or other jokey
systems that are so-called "by the people".

Such interest group must not be sponsored by tech companies nor any
other company - we contact the past and present developers and invite
them to a group (e.g. web forum) where we get together and share out
thoughts and ideas.

Of note:

The OMEMO encryption was made by a bright German person, Mr. Daniel
Gultsch aka @iNPUTmice, the creator of the most engaged and forked XMPP
messaging client called Conversations.

Mr. Gultsch is in my mind at least once a week, and I'm thinking of a
person who didn't follow anyone, he has just proposed a solution
integrated into his own program which he developed and everyone else
have followed and show their support.

Without Mr. Gultsch, we would probably be still attempting to use SASL
and OTR - which are not equally supported on all clients as OMEMO is
today - and pray for something to happen.

Look at how many support the OMEMO standard https://omemo.top/

**Comment by lwindolf** [comment]
@sjehuda I believe you are right about this possibility that you describe, still I do not want to spend my personal time on this. So you are right about my wrong attitude :-)

**Comment by sjehuda** [comment]
Time is a hard factor.

Do you agree to label this with something like "patches welcome"?

**Comment by lwindolf** [comment]
@sjehuda I do try this all the time. There are labels like "help-wanted", "easy-to-fix" ... Almost no response to those.

As I have to work with all those ticket and keep them up-to-date I just have to close a lot all the time. I does not make sense to check hundreds of tickets periodically.
