### ISSUE TITLE
[Debian bug 1016365] liferea (sometimes) causes WebKitNetworkProcess crashes? to be logged

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#1130]
This is a forward of a [Debian bug](https://bugs.debian.org/1016365) I got reported today. I have to admit I couldn't reproduce it myself, but the reported has it on two different systems on two different versions of Debian (and hence `liferea`).

So, this applies to both `liferea` 1.13.5 and 1.13.8.

Original report
===========
When openning Liferea it logs these lines under /var/log/mesages, dmesg, journatlctl:

```
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 1   0x7fea3c64a34f
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 2   0x7fea3c4ff9ba
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 3   0x7fea3c7c7e8b
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 4   0x7fea3c7c817a
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 5   0x7fea3c7c845a
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 6   0x7fea3adcbd30
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 7   0x7fea3ae2cc66
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 8   0x7fea3ae2c0da
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 9   0x7fea3789dd6f g_main_context_dispatch
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 10  0x7fea3789e118
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 11  0x7fea3789e40b g_main_loop_run
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 12  0x7fea3ae2c6b6 WTF::RunLoop::run()
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 13  0x7fea3c79bff6
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 14  0x7fea3728cd0a __libc_start_main
Jul 29 18:02:51 stt008 WebKitNetworkProcess[26567]: 15  0x40106a
```

Note sure if this is normal or expected, but to my eyes looks like a trace or some kind of error.

I experience no visible/noticeable errors on the application and this log is also visible on Debian testing.

Followup info
==========
Try by setting «Open links in Lifea's window» and click on a feed to load. This way I always get the above messages.

**Comment by lwindolf** [comment]
I can reproduce those crashes when running on Wayland. When I open the websites/resources causing them with Epiphany I get the same crashes. Usually they are highly reproducible both in Liferea and Webkit. Rarely retrying the load helps.

When running with an XOrg session both Epiphany and Liferea successfully load the pages.

I fear the combination of WebkitGTK+Wayland is the root cause here.

**Comment by strigops-kakapo** [comment]
I can confirm the bug with liferea 1.13.5-3 (Debian stable) and liferea 1.14-RC1, both running on Debian stable with Xorg.


1. The following WebKitNetworkProcess dump is shown every time I click on the title of an item:
>     WebKitNetworkProcess[163875]: 1   0x7f0e8eec351f
>     WebKitNetworkProcess[163875]: 2   0x7f0e8ed413c3
>     WebKitNetworkProcess[163875]: 3   0x7f0e8eec1005
>     WebKitNetworkProcess[163875]: 4   0x7f0e8f030b4a
>     WebKitNetworkProcess[163875]: 5   0x7f0e8f030e0a
>     WebKitNetworkProcess[163875]: 6   0x7f0e8f0310ea
>     WebKitNetworkProcess[163875]: 7   0x7f0e8d46a9b0
>     WebKitNetworkProcess[163875]: 8   0x7f0e8d4ca9b6
>     WebKitNetworkProcess[163875]: 9   0x7f0e8d4c9e1a
>     WebKitNetworkProcess[163875]: 10  0x7f0e89d5bd6f g_main_context_dispatch
>     WebKitNetworkProcess[163875]: 11  0x7f0e89d5c118
>     WebKitNetworkProcess[163875]: 12  0x7f0e89d5c40b g_main_loop_run
>     WebKitNetworkProcess[163875]: 13  0x7f0e8d4ca3f6 WTF::RunLoop::run()
>     WebKitNetworkProcess[163875]: 14  0x7f0e8f002986
>     WebKitNetworkProcess[163875]: 15  0x7f0e89847d0a __libc_start_main
>     WebKitNetworkProcess[163875]: 16  0x40106a
This happens whether liferea is configured to use the internal browser or an external browser. Meanwhile, liferea --debug-all shows:
>     GUI    : handle URL: false false true
>     CONF   : Setting last-window-state to 0

(As a side note, the "handle URL" printing code, located in src/ui/liferea_browser.c, reads:
>       debug2 (DEBUG_GUI, "handle URL: %s %s %s",
>             browse_inside_application?"true":"false",
>             browser->forceInternalBrowsing?"true":"false");
There are three %s in the format string but only two strings are given. This should be fixed)


2. But, when I open the link by right-click and then choosing "Open Link in External Browser" or "Open Link in Browser", the WebKitNetworkProcess dump is not printed and liferea --debug-all only shows:
>     CONF   : Setting last-window-state to 0

**Comment by lwindolf** [comment]
@strigops-kakapo Thanks for hinting on the wrong format string. Fixed.
