### ISSUE TITLE
All default example spanish feeds in feedlist_es.opml are dead.

### ISSUE THREAD

**Issue by darkshram** [lwindolf/liferea#1134]
`opml/feedlist_es.opml` has the following contents:

```
     <outline text="Fuentes de ejemplo (castellano)">
      <outline text="OSS">
        <outline text="Hispalinux" htmlUrl="http://www.hispalinux.es/" xmlUrl="http://www.hispalinux.es/node/feed" />
	<outline text="Barrapunto" htmlUrl="http://barrapunto.com/" xmlUrl="http://backends.barrapunto.com/barrapunto.rss" />
	<outline text="BulmaLUG" htmlUrl="http://bulma.net/" xmlUrl="http://bulma.net/xml.php" />
      </outline>	
    </outline>
```

All these example feeds are from defunct websites.

**Comment by GreenLunar** [comment]
@darkshram then correct them or post new ones and ask @lwindolf to accept your changes.

I suggest to add less-popular feeds, instead of the top media and press outfits of Spain, for it would help to increase decentralization on the web.

**Comment by lwindolf** [comment]
@darkshram Suggesting new feeds would help!

I think I need to write a test script (e.g. running on make dist-check) checking all the URLs for still existing and serving something.

**Comment by darkshram** [comment]
> @darkshram Suggesting new feeds would help!
> 
> I think I need to write a test script (e.g. running on make dist-check) checking all the URLs for still existing and serving something.

I do maintain a rebooted (switched from Geeklog to Grav CMS) Linux/FLOSS-related news blog. Have been around for +15 years.
```
<outline text="Alcance Libre" htmlUrl="https://www.alcancelibre.org/" xmlUrl="https://www.alcancelibre.org/noticias.atom" />
```
And have have cooperation with a FLOSS/Geek-related podcast:
```
<outline text="Tuxteno" htmlUrl="https://www.tuxteno.com/" xmlUrl="https://www.tuxteno.com/podcast.xml" />
```
Forgetting my own interests:
```
<outline text="Genbeta" htmlUrl="https://www.genbeta.com/" xmlUrl="https://www.genbeta.com/index.rss" />
```
@lwindolf : If you approve these suggested feeds, I will make a push request with the correct URLs for Hispalinux. Not very sure about Bulma, because it has an expired certificate for over a year and that means there is not much interest from webmasters. So, I would not include it.

My suggested list will be:
```
     <outline text="Fuentes de ejemplo (español)">
      <outline text="OSS">
	   <outline text="Alcance Libre" htmlUrl="https://www.alcancelibre.org/" xmlUrl="https://www.alcancelibre.org/noticias.atom" />
	   <outline text="Genbeta" htmlUrl="https://www.genbeta.com/" xmlUrl="https://www.genbeta.com/index.rss" />
	   <outline text="Hispalinux" htmlUrl="https://hispalinux.es/" xmlUrl="https://hispalinux.es/node/feed" />
	   <outline text="Tuxteno" htmlUrl="https://www.tuxteno.com/" xmlUrl="https://www.tuxteno.com/podcast.xml" />
      </outline>	
    </outline>
 ```

**Comment by lwindolf** [comment]
PR merged, thanks for fixing!
