### ISSUE TITLE
Links in documentation for scrapping are not valid

### ISSUE THREAD

**Issue by 2e8** [lwindolf/liferea#1136]
Hi, links to "General Script Repository" are not valid anymore. Is there any other script repository?

**Comment by lwindolf** [comment]
Sadly not. It is gone. I plan to create a new github repo to host stuff, update documentation and to provide some good example scapers. Once done I'll blog to let everyone know.

**Comment by lwindolf** [comment]
I started a new repo here https://github.com/lwindolf/rss-scraping. If you know of any scripts please contribute them there!

Will update the scraping documentation to point there next.

**Comment by lwindolf** [comment]
Online documentation https://lzone.de/liferea/scraping.htm is now fixed.
