### ISSUE TITLE
libsoup3 and webkit2gtk-4.1

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#1142]
GNOME 43 removed webkit2gtk-4.0 and now has webkit2gtk-4.1 linked against libsoup3 only https://gitlab.gnome.org/GNOME/gnome-build-meta/-/issues/511. Libsoup2 will be deprecated.

This blocks using the latest runtime for the Flatpak package at the moment and also locks distributions to webkit2gtk-4.0 which some are planning to drop in the near future https://fedoraproject.org/wiki/Changes/libsoup_3:_Part_One#Detailed_Description

I assume Liferea will need to be ported the use the newer API. Will there be such a port?

The GNOME 42 runtime is supported for another year.

Thanks!

**Comment by lwindolf** [comment]
For Liferea development I follow closely the Ubuntu release cycle (using the dependencies as given in the current Ubuntu release e.g. 22.04 right now).

**Comment by lwindolf** [comment]
So I guess the update will happen with 22.10 or 23.04

**Comment by mgorny** [comment]
According to https://packages.ubuntu.com/search?suite=jammy&searchon=names&keywords=webkit2gtk, there's 4.1 for 22.04. I'd really appreciate a port a lot since this is the last package requiring webkit2gtk-4.0 on my system.

**Comment by rezso** [comment]
Any news about this?

**Comment by lwindolf** [comment]
Won't happen soon as I'm short on time.

**Comment by lwindolf** [comment]
Did a test today https://github.com/lwindolf/liferea/pull/1225 and it is really bad. libsoup added a safety check to prevent usage of libsoup2 and 3 mixed. This makes Liferea stop to work if Webkit somehow uses libsoup2 (e.g. on Ubuntu 22.10) or *any* Liferea plugin tries to access libsoup2. With the plugins being user installed and out of upstream control any user setup with a libsoup2 using plugin will stop working.

Searching for "libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported." shows how many other projects are experiencing this too.

Given this I don't see how we can safely upgrade.

**Comment by lwindolf** [comment]
Will do another test once Webkit on Ubuntu uses libsoup3 exclusivly. Before that I fear any effort is futile.

**Comment by lwindolf** [comment]
Currently blocked by missing Github Actions hosted runner for Ubuntu 22.10+ which has libsoup3.2 which is required for CI tests

**Comment by mattst88** [comment]
Is this still blocked?

**Comment by lwindolf** [comment]
@mattst88 I've unblocked this now by using dockerhub images for the build pipeline. Will be released with 1.15.0

**Comment by lwindolf** [comment]
Implemented with #1225
