### ISSUE TITLE
Please add the media:description field when available

### ISSUE THREAD

**Issue by bhrgunatha** [lwindolf/liferea#1145]
I have a request for display of entries with media tags like from youtube.   
For example:  The Cracking the Cryptic channel feed: https://www.youtube.com/feeds/videos.xml?channel_id=UCC-UOdK8-mIjxBQm_ot1T-Q  

When I read an entry that has media tags I see:

Author Cracking The Cryptic (Website)   
View count 1283   
Rating 5.00 / 5 (64 votes)   
<thumbnail (I think)>   
<embedded video or link> 

I'd also like to see the media:description tag as well if it's present.   

QuiteRSS does display that fields and I find it useful.

**Comment by lwindolf** [comment]
This is actually a bug. The extraction and rendering is implemented, but does not seem to work. Needs fixing.

**Comment by lwindolf** [comment]
I provided a fix that now ensures the description is there.

**Comment by bhrgunatha** [comment]
Thank you that was very quick!
