### ISSUE TITLE
still version  1.13.9 in about dialog

### ISSUE THREAD

**Issue by PandaJim** [lwindolf/liferea#1153]
Hi, I've built the new 1.14 rc release and tried it out in Ubuntu 22.04. But the about dialog still shows v1.13.9, though I'm sure v1.14 packages were installed.

Here's the build log:

https://launchpadlibrarian.net/628674700/buildlog_ubuntu-jammy-amd64.liferea_1.14+rc1-0build1~ubuntu22.04_BUILDING.txt.gz

**Comment by lwindolf** [comment]
The version number is inserted based on the compile time value in https://github.com/lwindolf/liferea/blob/master/configure.ac. Which has the correct value...
