### ISSUE TITLE
A string impossible to translate

### ISSUE THREAD

**Issue by sunwire** [lwindolf/liferea#1162]
In the advanced search window where is a string that I cannot translate.
https://github.com/lwindolf/liferea/blob/4c79b8128f650d005e4cc04541f098e4998ef14c/src/ui/rule_editor.c#L256
The missing gettext macro _() seems to be a problem.

**Comment by lwindolf** [comment]
Good catch! Will fix.

**Comment by lwindolf** [comment]
Include fixed. POs are updated.
