### ISSUE TITLE
Custom liferea.css no longer working

### ISSUE THREAD

**Issue by mhoran** [lwindolf/liferea#1163]
Testing out the latest RC I found that my custom `liferea.css` no longer works. I had to revert both 4d911024934949bc9f012eecbb8e64717d69758b and 6ddbf9372a47de1541a51bb9060f302704dc39ae to get it working again.

Also, editing my `liferea.css` used to automatically update the stylesheet currently applied in Liferea. I now have to quit and restart in order to get it to apply. IIRC there used to be some signal that would trigger `render_get_css` when the `liferea.css` was modified.

I use a custom `liferea.css` to hide various nonsense in the internal browser. Not sure how to best go about fixing this as the above changes look related to the dark theme which I'm unfamiliar with.

**Comment by lwindolf** [comment]
Thanks for reporting this! I did some simplifcation there where I was asking myself, why was the code a bit complicated :-) 

Will be fixed!

**Comment by mhoran** [comment]
I looked into this a bit more today and realized it's just 6ddbf9372a47de1541a51bb9060f302704dc39ae that is responsible for the change in behavior. But it seems that what I want the behavior to be is at odds with #1096.

I'm not sure how best to rectify this, especially given the interaction with themes. Ideally I could override styles for external websites in the internal browser. But this means other themeing might be applied, which could be undesirable as per #1096.

I'm hesitant to introduce another option. I looked at the code that applies themes to the default and user stylesheet, and while the theme logic could be skipped in this case, that would leave invalid CSS markup (the color placeholders) in the resulting stylesheet. I guess they could simply be stripped, but that seems a bit hacky (and confusing.)

**Comment by mhoran** [comment]
Fixed in #1176. The custom user stylesheet is always loaded for any URL, but the default CSS is only used for internal URLs.

For some reason I couldn't use the `whitelist` with `liferea://*/*` as the allowed path. So I inversed and used the `blacklist` with `http://*/*` and `https://*/*`.
