### ISSUE TITLE
segfault with bad feed entry

### ISSUE THREAD

**Issue by vindarel** [lwindolf/liferea#117]
Hi there,
I found a segfault when I try to read a particular feed, the one entitled "my ideal python setup for statistical computing" by Nathan Lemoine from november 26th on Planet Python: http://planetpython.org/ 
I think the feed is malformed because clicking on the title redirects to Planet Python (but clicking on "reading" redirects correctly to the blog).

Launching liferea with --debug-verbose doesn't bring anything helpful:

    Liferea did receive signal 11 (Erreur de segmentation).
    You have probably triggered a program bug. I will now try to 
    create a backtrace which you can attach to any support requests.

I use v 1.8.3 on Ubuntu 12.04.

**Comment by lwindolf** [comment]
Sorry I cannot reproduce the crash. The feed entry from 26.11. is also not visible anymore.

If you get another crash please attach a copy of the feed and a backtrace (for instructions check README.md).
