### ISSUE TITLE
Missing dates for some feeds

### ISSUE THREAD

**Issue by jfbauer432** [lwindolf/liferea#1174]
I found some feeds that don't display any date in the Item List (headlines).  I manually downloaded the feed data with wget and there are both _updated_ and _published_ fields for each entry.  The "Date" heading is visible and clicking on it to change the sort does not have any affect of the order of the items.  I have only seen this on feeds from one site, everything else is ok.

Example feed that does not display date in Item List.
https://forum.freecadweb.org/app.php/feed/forum/3

**Comment by jfbauer432** [comment]
OS: Ubuntu 22.10
Liferea's Help->About says liferea 1.13.8
however Ubuntu dpkg -l liferea shows the version as 1.13.9-1

**Comment by jfbauer432** [comment]
Got more info on this.  I noticed that sometimes when doing a query of the above URL I got date/times with timezone offset and sometimes without.  I eventually figured out I would get the dates with timezone when logged in, and without when logged out.  I can also confirm that the times when there is not timezone offset if really UTC.  So it might be an easy workaround.

**Comment by lwindolf** [comment]
Reproduced effect with entries in the feed without login. Entries look like this 

		<entry>
		<author><name><![CDATA[drmacro]]></name></author>
		<updated>2022-12-14T22:02:55</updated>

		<published>2022-12-14T22:02:55</published>
		<id>http://forum.freecadweb.org:80/viewtopic.php?t=74450&amp;
		[...]
            </entry>

The date is correct ISO8601 so Liferea should parse it. The problem seems the implicit UTC timezone and us calling `g_date_time_new_from_iso8601 (date, NULL)` with `NULL` as default timezone. When passing `g_time_zone_new_utc()` instead the parsing works.

Needs to be fixed.

**Comment by lwindolf** [comment]
Test added for this. Solution implemented as described above.

Feed has now the proper timestamps. Please retest!
