### ISSUE TITLE
Plugin Tutorial Part3 Example Doesn't Work

### ISSUE THREAD

**Issue by jfbauer432** [lwindolf/liferea#1180]
Trying the tutorial at https://lzone.de/liferea/blog/Writing+Liferea+Plugins+Tutorial+Part+3
results in the following error

```
Traceback (most recent call last):
  File "/home/jfb/.local/share/liferea/plugins/tutorial3.py", line 22, in do_activate
    self._ui_manager = self.shell.get_property("ui-manager")
TypeError: object of type `LifereaShell' does not have property `ui-manager'
```

liferea version 1.13.7

**Comment by lwindolf** [comment]
Yes, we switch from GtkUIManager to GtkBuilder. Plugin tutorial needs to be updated to reflect this.

**Comment by lwindolf** [comment]
I've updated the blog post to reflect the GtkBuilder way to do it. Should be online shortly.

The link in the post to the plugin installer plugin already did point to an up-to-date solution.

HTH
