### ISSUE TITLE
Subscription discontinuation is too sticky

### ISSUE THREAD

**Issue by ap** [lwindolf/liferea#1181]
I have subscribed a publication on medium.com which was using a custom domain. Medium has dropped support for custom domains, and the hosting for the custom domain for this publication is now set up to return 410 for every URL. So Liferea now shows the “feed was discontinued” error pane.

So far, as expected.

However, the publication still exists on Medium, and I want to stay subscribed. So I changed the feed URL from the custom domain to the `medium.com/feed/blah`.

Problem: Liferea continues to show the “feed was discontinued” pane. And both the Update Monitor and the debug output show that it doesn’t even try to fetch the new URL. Even though the new URL would work, Liferea refuses to try.

**Comment by lwindolf** [comment]
I see the discontinued flag is currently permanent, but it should be reset when changing the subscription URL.

**Comment by ap** [comment]
Thanks!
