### ISSUE TITLE
Liferea stays offline

### ISSUE THREAD

**Issue by sunwire** [lwindolf/liferea#1185]
I accidentally discovered that Liferea does not go into online mode when the network starts to work again and stays offline.
Liferea 1.14-RC3 ( commit https://github.com/lwindolf/liferea/commit/ec8b4cb21025697d2e232981684bbe61cd5950e9 ) distro Fedora 37 x86

Demo
Turn off network and Liferea goes offline
Turn on network but Liferea stays offline
https://youtu.be/YVGeEpvghMc

**Comment by lwindolf** [comment]
@sunwire I cannot reproduce the effect. Running `nmcli networking on` and then `nmcli networking off` gives me:

      $ src/liferea --debug-net --debug-update 2>&1 | egrep "(network manager:|Changing online)"
      NET    : network manager: connecting to StateChanged signal
      NET    : network manager: connected to StateChanged signal: yes
      NET    : network manager: no network connection -> going offline
      NET    : Changing online mode to offline
      NET    : network manager: active connection -> going online
      NET    : Changing online mode to online

The new logic introduced in ec8b4cb is that we wait for NetworkManager to ping the internet. This introduces noticable delay (1-2s for me) until Liferea becomes online again.

Also there is a chance that this breaks intranet use cases where there is no internet target to ping. Are you in such a setup?

**Comment by sunwire** [comment]
I've tested liferea on the new vm (same os) and it works fine, so there is definitely something wrong with my system not with liferea.
Strangely enough, sometimes it works properly until it stuck in the offline mode. So I'm closing it now.

**Comment by lwindolf** [comment]
Feel free to reopen once it becomes reproducible!
