### ISSUE TITLE
Feature request: limit number of stories per channel?

### ISSUE THREAD

**Issue by d33tah** [lwindolf/liferea#1188]
Hi! Thanks for creatinf Liferea! I'm writing on behalf of my friend, who's using it. He showed me that pretty much all RSS readers have this problem that if you subscribe to many feeds, inevitably stories from one of them will outnumber the remaining ones and the "unread" view is basically going to be all about one feed. His proposed solution is to add a way to limit the number of stories displayed per channel - so that when you receive many new stories, only a limited number of them would actually get displayed.

I was trying to implement a prototype of this feature, but couldn't quickly tell where to add that limitation. I was looking for a function which is responsible for adding stories and adding something like "only add the first three ones" as an experiment, but failed to find one so far. Could someone give me a clue?

**Comment by lwindolf** [comment]
There is already such a feature: if you open the feed properties and set a cache limit to the number of intended headlines then you should get what you want.
