### ISSUE TITLE
Captive portal NetworkManager support, vs intranet detection

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#1193]
I think I remember Liferea not handling captive portals (or MitMs and [Ponies-in-the-Middle](https://github.com/lwindolf/liferea/issues/1156) attacks) well, although I haven't travelled and tested this recently.

From a quick search, I see in Liferea's `net_monitor.c` file, in the `is_nm_connected` function (currently [line 101 here](https://github.com/lwindolf/liferea/blob/db6ded331f5c5e23c94470e48d5ab2d772ed828d/src/net_monitor.c#L101)), that it considers both `NM_STATE_CONNECTED_SITE` and `NM_STATE_CONNECTED_GLOBAL` as equivalent, which seems... wrong? Presuming this is because @lwindolf has some restrictive firewall at work that they need to poke through, maybe there needs to be a hidden gsetting/dconf option for this edge case, and for most users expect full Internet reachability to be considered "online"? But wait... The [NetworkManager API documentation](https://networkmanager.dev/docs/api/latest/nm-dbus-types.html) also has the `NMConnectivityState` statuses instead of just the above `NMState`... and in there, you would have the distinction between:

* NM_CONNECTIVITY_UNKNOWN: I'm not sure what Liferea should do in this case
* NM_CONNECTIVITY_NONE: Liferea should consider itself offline
* NM_CONNECTIVITY_PORTAL: Liferea should consider itself offline
* NM_CONNECTIVITY_LIMITED: Not sure if this might be Lars' intranet usecase...
* NM_CONNECTIVITY_FULL: Liferea can probably safely assume to be online and unrestricted?

Shouldn't those be used instead (or in addition)? Just guessing...

**Comment by lwindolf** [comment]
Judging from the lack of bug reports I'd say the current implementation is fine. 

The intranet use case being hidden by a DConf flag show be causing no problems either. Closing this if you are ok with this...
