### ISSUE TITLE
1.14.0 release tarball lis missing ./configure script

### ISSUE THREAD

**Issue by trofi** [lwindolf/liferea#1196]
Looking at https://github.com/lwindolf/liferea/releases/tag/v1.14.0 there is only an autogenerated release tarball from git tag. It is missing `./configure` script.

Is it an intended change in packaging or a minor omission?

I'm asking if `nixpkgs` should switch to git tags as well and adapt to build process changes outlined in https://lzone.de/liferea/install.htm

Thank you!

**Comment by lwindolf** [comment]
I actually forgot to add the release tarball... 

It is now attached. Sorry about that!

**Comment by trofi** [comment]
Thank you! Fetched and built successfully ([nixpkgs update proposal](https://github.com/NixOS/nixpkgs/pull/211288)).
