### ISSUE TITLE
Latest flatpak update (1.14.0) doesn't launch maximized anymore

### ISSUE THREAD

**Issue by Froggy232** [lwindolf/liferea#1197]
Hi,
I have a strange bug : since the latest update (v1.14.0) liferea launch windowed, not maximized.
If I downgrade to previous version, it launch maximized as it should.
Am I the only one with this bug?
Does someone know how to correct this?
I use the flathub version.
Thanks you

**Comment by Froggy232** [comment]
I think the issue reside in the file ~/.var/app/net.sourceforge.liferea/config/glib-2.0/settings/keyfile

This file has an entry named "last-window-state" which is on 0. I have tried to put it on 1, but it revert to 0 everytime I open liferea.

**Comment by lwindolf** [comment]
Restoring to maximized size works for me (not using Flatpak). Please report a flatpak related bug against https://github.com/flathub/net.sourceforge.liferea/ !
