### ISSUE TITLE
Dark theme variant detection does not work with Adwaita/GTK+ 3.14

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#120]
With GTK 3.14, if I enable the global dark theme setting for GTK, Liferea's feed items contents are shown as white text on a white background...

**Comment by lwindolf** [comment]
Did you already test the fix for #100?

**Comment by nekohayo** [comment]
Did not test it but the description for bug #100 seems the same, so closing as it's a duplicate I guess
