### ISSUE TITLE
Liferea 1.14.0 [Makefile:486: all] Error 2

### ISSUE THREAD

**Issue by LloydLynx** [lwindolf/liferea#1209]
Did "./configure" successfully. "make -j2" produces the following errors. 

```
make[3]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src/tests'
Making all in .
make[3]: Entering directory '/home/james/Downloads/liferea-1.14.0/src'
  CC       main.o
make[3]: *** No rule to make target 'Liferea-3.0.typelib', needed by 'all-am'.  Stop.
make[3]: *** Waiting for unfinished jobs....
  CC       js.o
make[3]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[2]: *** [Makefile:861: all-recursive] Error 1
make[2]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[1]: *** [Makefile:724: all-recursive] Error 1
make[1]: Leaving directory '/home/james/Downloads/liferea-1.14.0'
make: *** [Makefile:486: all] Error 2
```

With "make VERBOSE=1"

```
make[3]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src/tests'
Making all in .
make[3]: Entering directory '/home/james/Downloads/liferea-1.14.0/src'
glib-compile-resources --generate --target=js.c --c-name js --sourcedir=../js ../js/gresource.xml
make[3]: glib-compile-resources: No such file or directory
make[3]: *** [Makefile:1239: js.c] Error 127
make[3]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[2]: *** [Makefile:861: all-recursive] Error 1
make[2]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[1]: *** [Makefile:724: all-recursive] Error 1
make[1]: Leaving directory '/home/james/Downloads/liferea-1.14.0'
make: *** [Makefile:486: all] Error 2
```

Void Linux 6.1.11_1
Make version 4.3
Liferea 1.14.0 downloaded from releases page
All listed dependencies installed

Any other information I'll be happy to provide

**Comment by sunwire** [comment]
Missing glib-devel?

**Comment by mozbugbox** [comment]
```
$ dpkg -S glib-compile-resources
libglib2.0-dev-bin: /usr/bin/glib-compile-resources
libglib2.0-doc: /usr/share/gtk-doc/html/gio/glib-compile-resources.html
libglib2.0-dev-bin: /usr/share/man/man1/glib-compile-resources.1.gz
```

**Comment by jconnolly837** [comment]
> ```
> $ dpkg -S glib-compile-resources
> libglib2.0-dev-bin: /usr/bin/glib-compile-resources
> libglib2.0-doc: /usr/share/gtk-doc/html/gio/glib-compile-resources.html
> libglib2.0-dev-bin: /usr/share/man/man1/glib-compile-resources.1.gz
> ```

Void is not a debian based distro.

**Comment by mozbugbox** [comment]
Then you need to find the build-depends or makedepends of liferea in your Void distro, and install those depends.

`glib-compile-resources` is a build time depend, not runtime depend.

**Comment by jconnolly837** [comment]
> Then you need to find the build-depends or makedepends of liferea in your Void distro, and install those depends.
> 
> `glib-compile-resources` is a build time depend, not runtime depend.

I already have glib-devel and glibc-devel installed. I'm not seeing anything else that could be an equivalent.

**Comment by sunwire** [comment]
> Installing glib-devel made no difference

Are the errors exactly the same? Especially "make[3]: glib-compile-resources: No such file or directory"

**Comment by jconnolly837** [comment]
> > Installing glib-devel made no difference
> 
> Are the errors exactly the same? Especially "make[3]: glib-compile-resources: No such file or directory"

My mistake. There is a difference I didn't notice; the lack of that glib error. 

```
make[3]: Entering directory '/home/james/Downloads/liferea-1.14.0/src'
make[3]: *** No rule to make target 'Liferea-3.0.typelib', needed by 'all-am'.  Stop.
make[3]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[2]: *** [Makefile:861: all-recursive] Error 1
make[2]: Leaving directory '/home/james/Downloads/liferea-1.14.0/src'
make[1]: *** [Makefile:724: all-recursive] Error 1
make[1]: Leaving directory '/home/james/Downloads/liferea-1.14.0'
make: *** [Makefile:486: all] Error 2
```

**Comment by lwindolf** [comment]
@jconnolly837 Can you try a build with `./configure --enable-introspection`? 

The build target for the typelib is usually provided by `/usr/share/gobject-introspection-1.0/Makefile.introspection` which gets included when introspection is on.

**Comment by duskull88** [comment]
Same here, Void Linux with latest updates.

Complete _make_ log - https://nekobin.com/lifiguvaya

**Comment by lwindolf** [comment]
@duskull88 You log looks like the situation described by @jconnolly837. No indication of the GIR scanner running at all. There might be a general problem in Void with the gobject-introspection setup.
