### ISSUE TITLE
Liferea doesn't respect the -w hidden option

### ISSUE THREAD

**Issue by heyzsh** [lwindolf/liferea#1219]
I'm trying to start Liferea with `liferea -w hidden` and the main window still shows up instead of quietly minimizing it to the tray.

`Version: 1.14.3`
`DE: XFCE 4.18`
`Linux hey 6.2.8-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 22 Mar 2023 22:52:35 +0000 x86_64 GNU/Linux`

**Comment by cheese1** [comment]
the same here with 1.14.1 under fedora 37 and xfce

**Comment by cheese1** [comment]
seems to be a problem with the trayicon
#447

**Comment by lwindolf** [comment]
Closing as won't fix. @cheese1 is right pointing out #447. The situation described there has not changed. Hiding the main window and relying on the tray icon be visible is not achievable/supportable on multiple desktop environments.

That's just how the Linux desktop ecosystem is. Sorry!
