### ISSUE TITLE
How do I fix my issue with font rendering for the articles?

### ISSUE THREAD

**Issue by Hund** [lwindolf/liferea#1222]
Hi! I'm trying out Liferea, for the first time in a decade or so. :) It's working good, except for some font issues.

This is Liferea (with bad font rendering for the article, but with good font rendering in the UI itself):

![Liferea article font rendering](https://user-images.githubusercontent.com/320498/228813475-d32e5499-5ffe-4123-9c05-b1a713bc83b4.png)

This is Firefox (with good font rendering):

![Firefox font rendering](https://user-images.githubusercontent.com/320498/228813483-4e6198dc-3422-4b03-8ba7-e043d016b05e.png)

I understand that this is due to the article is being rendered using Webkit. How do I fix this issue?

**Comment by lwindolf** [comment]
Which desktop environment do you use (Liferea tries to get a good font via dconf)?

**Comment by Hund** [comment]
> Which desktop environment do you use (Liferea tries to get a good font via dconf)?

I'm using Xfce. I'm not really that familiar with graphical applications. I'll look up dconf.

**Comment by lwindolf** [comment]
Using XFCE explains the problem. DConf is GNOME stuff, which is missing on your setup. Liferea fails back more or less gracefully by using the font default of Webkit which turns out to look ugly.

As it is impossible (for me) to support multiple desktop environments I can only point you at this workaround to manually set a good font: https://lzone.de/liferea/blog/Liferea-Trick-10-Custom-CSS-for-Article-Rendering.html Try setting a font definition in `div.content`

**Comment by Hund** [comment]
Thanks. I have tried that already, but I couldn't make it work. What exactly should I add?

**Comment by lwindolf** [comment]
Replace the

    // div.content {}

with e.g.

    div.content {
        font-family: Sans;
        font-size: 12pt;
    }

**Comment by lwindolf** [comment]
Sorry, I cannot help further. Above is the way how to fully control the fonts Liferea does use. It's probably all about finding a good font combination on your system. So something not simply "Sans".

**Comment by Hund** [comment]
I tried using "DejaVu Sans Book", but that didn't work it. I'm not even sure it's possible to use anything like it.

Thank you for you time anyway. I'm hoping I'll be able to solve it somehow, so I can start using Liferea again. :)
