### ISSUE TITLE
crash on startup

### ISSUE THREAD

**Issue by mokraemer** [lwindolf/liferea#1224]
the latest release 14.3 crashes directly on startup:

strace shows it is endless iterating over the same directories:
....
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/feeds", {st_mode=S_IFDIR|0700, st_size=1, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/favicons", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/plugins", {st_mode=S_IFDIR|0700, st_size=1, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.config/liferea", {st_mode=S_IFDIR|0700, st_size=172032, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.local/share/liferea", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/feeds", {st_mode=S_IFDIR|0700, st_size=1, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/favicons", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea/plugins", {st_mode=S_IFDIR|0700, st_size=1, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.config/liferea", {st_mode=S_IFDIR|0700, st_size=172032, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.local/share/liferea", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
[pid 48694] newfstatat(AT_FDCWD, "/home/marc/.cache/liferea", {st_mode=S_IFDIR|0700, st_size=4096, ...}, 0) = 0
...

**Comment by bbhtt** [comment]
Possibly https://github.com/lwindolf/liferea/issues/1217, it's fixed but unreleased.

**Comment by mokraemer** [comment]
Yes. Fixed the problem.

**Comment by lwindolf** [comment]
Closing as fixed. Will be released with 1.14.4
