### ISSUE TITLE
Assertion failures when deleting feeds too quickly

### ISSUE THREAD

**Issue by tatokis** [lwindolf/liferea#1229]
While testing something else, I noticed that this would get printed in the console when deleting feeds relatively quickly.

```
** (liferea:1257857): CRITICAL **: 07:53:21.887: comments_process_update_result: assertion 'item != NULL' failed
```

Steps to reproduce:

1. Select a feed.
2. Make sure the top most item is selected.
3. Hold down the <kbd>Delete</kbd> key.

Tested at commit: 330caf40f4e4ebf2dd8b097e51339aded9e34e87.

**Comment by lwindolf** [comment]
Was not dangerous (just an assertion). Fixed.
