### ISSUE TITLE
Master branch not in sync with release 1.14.4

### ISSUE THREAD

**Issue by sunwire** [lwindolf/liferea#1230]
I've noticed that the source code from master branch is older (1.14.3) than the source code from the release page (1.14.4)
Is it intentional/mistake  or a problem with github?
When I build a new package for my system I use master branch so I'm slightly confused.

**Comment by lwindolf** [comment]
This is intentional, although confusing. Traditionally Liferea does trunk-based development and I started the `liferea-1_14` maintenance branch rather late. So right now `master` is for 1.15.

To avoid confusion I'll update versions and strip the ChangeLog to indicate this.

**Comment by lwindolf** [comment]
I did check the important bugfixes from 1.14.4 were all back-merged for 1.15. ChangeLog was missing, which I've updated.

So effectively from my pov master is in sync with 1.14.4
