### ISSUE TITLE
Miniflux as new source not working

### ISSUE THREAD

**Issue by pragmaticus** [lwindolf/liferea#1234]
If you try to add miniflux as a new source via  _Subscriptions > New Source ..._ an dialog with "Please enter the details of the new Google Reader API compatible subscription" pops up. After adding the right credentials, Liferea is not able to connect to miniflux and a popup with username and password inputs appears everytime i try to connect.

I'm on Linux the latest Manjaro Linux Build with Xfce Version 4.18 and Liferea 1.14.3

![screencast-liferea-miniflux](https://user-images.githubusercontent.com/4392015/229721201-726907ce-aa45-4365-8ddf-ab84cb20ddf9.gif)

**Comment by lwindolf** [comment]
I cannot reproduce the effect when subscribing to a free account on `https://reader.miniflux.app`. Did you activate the "Google Reader" integration in Miniflux under Settings -> Integrations?

**Comment by pragmaticus** [comment]
Activating the "Google Reader" integration in the Miniflux Settings did work.

**Comment by Medic-2016** [comment]
I'm having the same issue, I have enabled the google reader api and used an app password to sign in and I'm still having the same problem.

**Comment by lwindolf** [comment]
@Medic-2016 Can you please open a new issue and post a log trace when running with 

    liferea --debug-all
