### ISSUE TITLE
Feed url preview above "Headline" gone?

### ISSUE THREAD

**Issue by Ottaviocr** [lwindolf/liferea#1238]
I am using Liferea 1.13.4 official package from Debian Bullseye, which is way behind the current version. 

I am pretty sure that, in the past, I could have clicked on any feed on the left pane, and then, just above the "Headline" pane, I could have seen the url of the feed (the one that is otherwise available by right clicking the feed > Properties > Source). But I can't see it now.

Was it removed or have I messed about with some settings?

**Comment by lwindolf** [comment]
The feature was not removed and still works in 1.13 up to 1.15

**Comment by Ottaviocr** [comment]
Thanks. So how can I restore it? I completely purge and reinstalled liferea and liferea-data, then removed 

.cache/liferea
.local/share/liferea
.config/liferea/

And restarted liferea, but that feature is still not there.

**Comment by lwindolf** [comment]
I'm not sure of the cause yet. One guess I have is that the minimum size check for the HTML view pane does not work in your case. But it is hard to guess from the description.

Can you provide a screenshot please?

**Comment by Ottaviocr** [comment]
Please accept my apologies.. This is the standard behaviour when using "Wide view". For some reason all my feeds were converted to standard view and I couldn't see the url. Sorry for the inconvenience,

**Comment by lwindolf** [comment]
@Ottaviocr Don't worry. I'm glad we could find out the problem.
