### ISSUE TITLE
Images from the XKCD "What If?" feed don't show up

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#124]
If you add http://what-if.xkcd.com/feed.atom to Liferea, you'll see that for most (all?) posts, the images don't show up in liferea... but if you look at that feed.atom in Firefox, the images do show up.

**Comment by hyperair** [comment]
Liferea doesn't though. I just copied an image location, and got this: file:/imgs/a/128/why.png. That can't be correct under any circumstance.

**Comment by asl97** [comment]
somebody should tell the people at xkcd about this, i will just leave this cc here:
cc: @davean
