### ISSUE TITLE
Social register bookmark for identi.ca does not work

### ISSUE THREAD

**Issue by teseu** [lwindolf/liferea#1241]
In the url /index.php is mistaken by user param, resulting in a 404 error
![image](https://user-images.githubusercontent.com/3169307/235809308-cbb33514-3c98-4f61-b065-7c16dcf9482a.png)

**Comment by teseu** [comment]
The url in file /src/social.c
`	social_register_bookmark_site ("identi.ca",	"https://identi.ca/index.php?action=bookmarklet&status_textarea=%%E2%%80%%9C{title}%%E2%%80%%9D%%20%%E2%%80%%94%%20{url}");`

**Comment by lwindolf** [comment]
Thank you for reporting this.

As I understand the Wikipedia page all of identi.ca users were migrated to pump.io (as also indicated by the screenshot). I guess the old submission URL does not exist with pump.io anymore. Will remove the bookmark entry from Liferea.
