### ISSUE TITLE
Social register bookmark for Pocket does not work

### ISSUE THREAD

**Issue by teseu** [lwindolf/liferea#1242]
The api has changed and has more than one url to visit, Authentication and Add:

If you try to authenticate with a Firefox account, nothing loads, it's a eternal spin:
![image](https://user-images.githubusercontent.com/3169307/235810195-951705a0-e5c9-4083-b592-934840202235.png)

If you try the email option, or you get an 503 error or nothing happens:
![image](https://user-images.githubusercontent.com/3169307/235810467-9c98512e-0e7d-4930-b985-4a4dcf63f155.png)

**Comment by teseu** [comment]
For reference, in src/social.c file:
`	social_register_bookmark_site ("Pocket",	"https://getpocket.com/save?url={url}&title={title}");`

Links for [Add](https://getpocket.com/developer/docs/v3/add) and [Authentication](https://getpocket.com/developer/docs/authentication) pages in pocket api.

**Comment by lwindolf** [comment]
Arg... the current implementation is a simple link loading. Adding OAuth2 support on top is something I'd like not to support. Therefore also removing Pocket from the offered bookmarking services :-(
