### ISSUE TITLE
Cannot add a feed source

### ISSUE THREAD

**Issue by dikel** [lwindolf/liferea#1246]
When I try to add this [RSS source](https://e.cash/blog/rss.xml) I get `XML Parser: Could not parse document:`

But I was able to import it in rss.app, Feedly, Brave News and Gnome Feeds

**Comment by lwindolf** [comment]
Sorry, this feed is invalid https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fe.cash%2Fblog%2Frss.xml

The XML parser used by Liferea does not support non-valid XML, which I consider correct behaviour. XML is a machine readable format after all and needs to be well-formed and valid.

**Comment by dikel** [comment]
Thank you. It makes sense to not support invalid XML
