### ISSUE TITLE
Internal browser only works in tabs

### ISSUE THREAD

**Issue by nat-418** [lwindolf/liferea#1247]
Running Liferea version 1.14.5 on latest NixOS / Xfce, I can right click to open articles in a new tab using the internal browser, but I cannot get them to open "normally" under the feeds from the "main" window (excuse my quotation marks, I am not sure what is the correct terminology).

**Comment by lwindolf** [comment]
You can click the item title or double click in the item list to open the article link directly without a tab.

**Comment by nat-418** [comment]
> You can click the item title or double click in the item list to open the article link directly without a tab.

That does not work. Neither does right-clicking an item and clicking "Open in Browser"

**Comment by lwindolf** [comment]
Did you check the "Open links in Liferea's window" option in the preferences dialog (tab "Browser")?

This option needs to be enabled for it to work.

**Comment by nat-418** [comment]
> Did you check the "Open links in Liferea's window" option in the preferences dialog (tab "Browser")?
> 
> 
> 
> This option needs to be enabled for it to work.

Yes

**Comment by nat-418** [comment]
After upgrading to NixOS 23.05, this issue is resolved. Strange as the Liferea version is still 1.14.5.

**Comment by lwindolf** [comment]
@nat-418 Thanks for following up on this. There were no other similar reports, so I don't think there is an issue.
