### ISSUE TITLE
Can’t maximize for reading feeds

### ISSUE THREAD

**Issue by ksso83** [lwindolf/liferea#1248]
Can’t maximize for reading feeds

When I try to maximize the windows in xubuntu, the feeds hid the content and only can be seen the titles, there is no way to customize the view (old issue)

https://github.com/lwindolf/liferea/assets/12177142/2d23cdb8-824a-449f-ac0d-20572d349f24

**Comment by lwindolf** [comment]
Similar to #1237 and other reports. We have a general problem with pane layout restoration.

**Comment by lwindolf** [comment]
I can reproduce your behaviour if I minimize (manually set to 0 pixel width) the right-most pane in "Wide View" mode. In this case once the view mode switches to "Wide View" upon window resize it switches back to the 0 pixel width and the pane is effectively invisible.

When in "Wide View" mode can you grab and drag the invisible right pane border? It should allow resizing it, although it is hard to do. This is actually more of a GTK/GNOME theme usability issue the an application bug.

Nonetheless I think we should add a minimum restore width for the reading pane in "Wide View" mode too.

**Comment by lwindolf** [comment]
Turned out the code was already there, but buggy. Fixed. Now upon startup (and only on startup) Liferea sets a minimum width so the pane becomes visible.
