### ISSUE TITLE
[Discussion] DecSync

### ISSUE THREAD

**Issue by sjehuda** [lwindolf/liferea#1256]
This is a project from @39aldo39 which I want to start a discussion about.

https://github.com/39aldo39/DecSync
https://github.com/39aldo39/libdecsync

I'm not always able to use Liferea everywhere because I don't use online readers and therefore I have synchronicity issues with local Feed Readers.

To mitigate this issue, I have wrote a [Web Feed bot](https://gitgud.io/sjehuda/slixfeed) (it's not complete yet. I need to fix a database lock issue in it).

However, I think that a solution like DecSync is viable to all feed readers.

**Comment by lwindolf** [comment]
@sjehuda Please try to open a discussion in the Github discussions tab. Several people are reading and posting there.

Closing this ticket.
