### ISSUE TITLE
Cannot read from finanzen.net

### ISSUE THREAD

**Issue by martin3000** [lwindolf/liferea#1263]
When I want to subscribe to https://www.finanzen.net/rss/news , I get the error "HTTP 403: You're not allowed to access this resource"

**Comment by lwindolf** [comment]
Reproduced. Seems like finanzen.net doesn't allow non-browser user agents to download stuff. Which does not make sense for RSS feeds. Looks like a server configuration mistake on their side. You might want to contact them about it.

Not a problem in Liferea.

If you need a workaround change your Liferea subscription properties to run a command and pass a browser user agent. For example: `curl -H "User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0" https://www.finanzen.net/rss/news` which works for me.

**Comment by martin3000** [comment]
It works with thunderbird and it works with 
>curl -H "User-Agent: X/5.0" https://www.finanzen.net/rss/new
So at least any well formed User-Agents works.
