### ISSUE TITLE
Using Liferea with Shadowsocks

### ISSUE THREAD

**Issue by sepremento** [lwindolf/liferea#1268]
Hello, I am trying to configure proxying Liferea via Shadowsocks proxy.

I have `ss-local` service running on my localhost on port 1234. Firefox works fine and requests are proxied via this port successfully. I am trying to make Liferea proxy via the same port. I've set address: 127.0.0.1 and port 1234 in Tools -> Preferences -> Proxy, but feeds fail to update.

I have tried to run Liferea with `--debug-all` flag and the only thing I've gotten out of it is that the responses come back with `HTTP/1.1 8 Message Corrupt`. Can please someone tell me how to use Liferea with Shadowsocks?

Thank you!

**Comment by lwindolf** [comment]
The setting in Tools -> Preferences -> Proxy is only for HTTP proxy configs, so this won't work.

You can still configure a SOCKS proxy using GNOME settings: check out https://lzone.de/liferea/blog/Liferea-SOCKS-Proxy-Workaround
