### ISSUE TITLE
Where are unread article counts stored?

### ISSUE THREAD

**Issue by reahari** [lwindolf/liferea#1269]
I have moved my liferea config from (located in /home/$USER/.config/liferea) to a new computer. Upon launching lifrea the feeds are restored but the unread article counts are reset and every feed is showing that it has unread articles.

Is the unread article count stored somewhere different? Is there a way to restore it?

**Comment by lwindolf** [comment]
Liferea follows the XDG directory standard: 

- config is in `$HOME/.config/liferea`
- data is in `$HOME/local/share/liferea` 

So the article states are in the other directory. If you restore the directory you get your old state.
