### ISSUE TITLE
Enhancement request: simple content filter

### ISSUE THREAD

**Issue by kwill** [lwindolf/liferea#127]
It would be useful in some cases to add very simple filters to feeds based on their title (or body).

Use cases:

 * Exclude posts with "Daily update" in the title
 * Include only posts with "Release" in the title

Elaborations (beyond this request) might include:

 * Regex filtering
 * Multiple filters for the same feed (not sure what logic to suggest here, perhaps see https://github.com/FredJul/Flym which has this feature)

**Comment by voidus** [comment]
Yes please. Writing/Downloading a script just to white/blacklist is pretty hard.

**Comment by asl97** [comment]
tbh, i think writing a script is easier than adding a filtering function to liferea.

in any case, to me, this sound like a feature request, see [faq](http://lzone.de/liferea/faq.htm#feature-x)

**Comment by kwill** [comment]
Apologies, I hadn't read the FAQ (or I did and have since forgotten).
