### ISSUE TITLE
Favicon for specific feed is corrupt

### ISSUE THREAD

**Issue by tatokis** [lwindolf/liferea#1271]
Running Liferea 1.14.5 on Ubuntu 20.04.

The favicon for https://store.steampowered.com/feeds/news.xml ends up as follows:
![ggheqia](https://github.com/lwindolf/liferea/assets/6003656/9fff7317-7590-44e9-b01a-54c1a83ceb8d)
(File taken from `~/.cache/liferea/favicons/`.)

Deleting the icon from the cache and updating the feed results in an identical png.

**Comment by yaneti** [comment]
This is probably this gdk-pixbuf issue https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/issues/227

**Comment by lwindolf** [comment]
@yaneti Thanks for tracing this to gdk-pixbuf.

@tatokis Cannot be fixed by Liferea! Closing this report.
