### ISSUE TITLE
Liferea freezes and crash when moving feed to empty directory

### ISSUE THREAD

**Issue by jcubic** [lwindolf/liferea#1272]
I use this tool a lot and I love it. First time reporting a bug.

I've created a new empty directory and wanted to move the feed to that directory. It freezes and finally crashes.

You need to have at least one feed in the directory to be able to drag and drop a feed into that directory.

**Comment by lwindolf** [comment]
Reproduced. Thanks for reporting this!

**Comment by lwindolf** [comment]
Also affects latest 1.4. It seems the exit condition of the iterating loop of the childs of the new folder does not work. The line 226 of src/ui/ui_dnd.c

				valid = gtk_tree_model_iter_next (GTK_TREE_MODEL (drag_dest), &iter2);

Does not return FALSE when running on the last iterator and causes a crash afterwards.
