### ISSUE TITLE
Gnome Dark Mode

### ISSUE THREAD

**Issue by padorange** [lwindolf/liferea#1275]
Liferea 1.14.4
Debian 12 stable (bookworm) 
Gnome 43.6

The FAQ tell dark-mode is automatically selected since 1.14
There should be a problem, with my configuration liferea is not un dark mode and it make difficult to read. ie the number of unread article is invisible.
![image](https://github.com/lwindolf/liferea/assets/741204/83db3674-b5f9-446d-9c17-11e68b74ca34)

**Comment by padorange** [comment]
i run in debug from console but it produce no output (don't know where is the output file, if any).
But when i switch "live" (before running liferea or after launch liferea) if do nothing in liferea (no change, no output). All other software switch)

**Comment by padorange** [comment]
I post too quickly.
Runnng liferea from console as admin (sudo) i got an output to the console.
Running in darkmode show that liferea detect "light mode" : 
```
HTML   : theme color "GTK-COLOR-FG" is FFFFFF
HTML   : theme color "GTK-COLOR-BG" is F6F5F4
HTML   : theme color "GTK-COLOR-LIGHT" is FFFFFF
HTML   : theme color "GTK-COLOR-DARK" is B2ACA6
HTML   : theme color "GTK-COLOR-MID" is D9D6D3
HTML   : theme color "GTK-COLOR-BASE" is F6F5F4
HTML   : theme color "GTK-COLOR-TEXT" is FFFFFF
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is 1B6ACB
HTML   : theme color "GTK-COLOR-VISITED-LINK" is 2E3436
HTML   : Light GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_FG" is F6F5F4
HTML   : theme color "FEEDLIST_UNREAD_BG" is B2ACA6
HTML   : Feed list unread CSS: foreground='#F6F5F4' background='#B2ACA6'
```

**Comment by lwindolf** [comment]
@padorange Thanks for posting this trace. Can you do an additional run with `--debug-html --debug-conf` this should give some more output whether the FreeDesktop.org, GNOME settings or defaulting does happen in your case.

A strange thing in you debug output is 

     HTML   : theme color "GTK-COLOR-FG" is FFFFFF
     HTML   : theme color "GTK-COLOR-BG" is F6F5F4

This background against this foreground color sounds weird...

**Comment by padorange** [comment]
@lwindolf 
GTK-COLOR-FG and BG are weird, there must be very light, but as you can see on my initial message the color seems "normal" for a light mode (except is was in "dark mode").

This new trace give a bit more information. 
But when i do "sudo liferea" it launch another "config", i do not have my feeds (just examples) and the color are not exactly the same (the counter for unread messages is more visible but still light-mode) : see a new screenshot...
```
CONF   : proxy auto detect is configured
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
HTML   : theme color "GTK-COLOR-FG" is FFFFFF
HTML   : theme color "GTK-COLOR-BG" is F6F5F4
HTML   : theme color "GTK-COLOR-LIGHT" is FFFFFF
HTML   : theme color "GTK-COLOR-DARK" is B2ACA6
HTML   : theme color "GTK-COLOR-MID" is D9D6D3
HTML   : theme color "GTK-COLOR-BASE" is F6F5F4
HTML   : theme color "GTK-COLOR-TEXT" is FFFFFF
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is 1B6ACB
HTML   : theme color "GTK-COLOR-VISITED-LINK" is 2E3436
CONF   : GNOME reports color-schema 'default'
CONF   : Determined dark theme mode to be 0
HTML   : Light GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_FG" is F6F5F4
HTML   : theme color "FEEDLIST_UNREAD_BG" is B2ACA6
HTML   : Feed list unread CSS: foreground='#F6F5F4' background='#B2ACA6'

CONF   : Scheduling feedlist save
HTML   : theme color "GTK-COLOR-FG" is 2E3436
HTML   : theme color "GTK-COLOR-BG" is F6F5F4
HTML   : theme color "GTK-COLOR-LIGHT" is FFFFFF
HTML   : theme color "GTK-COLOR-DARK" is B2ACA6
HTML   : theme color "GTK-COLOR-MID" is D9D6D3
HTML   : theme color "GTK-COLOR-BASE" is F6F5F4
HTML   : theme color "GTK-COLOR-TEXT" is 2E3436
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is 1B6ACB
HTML   : theme color "GTK-COLOR-VISITED-LINK" is 2E3436
CONF   : GNOME reports color-schema 'default'
CONF   : Determined dark theme mode to be 0
HTML   : Light GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_FG" is F6F5F4
HTML   : theme color "FEEDLIST_UNREAD_BG" is B2ACA6
```

**Comment by padorange** [comment]
@lwindolf if i do not use sudo the debugs options output nothing in the terminal.
I do not know where the output is located (if any)

**Comment by lwindolf** [comment]
@padorange Debug output only goes to the terminal (to STDOUT), nowhere else. So what you did was fine.

Now the problem seems to be why Liferea does not see the theme switch at all. Technically it listens to the GNOME DConf key for the color schema, but the callback (according to your trace is just never triggered). So color does not change.

Sadly I cannot reproduce this.

**Comment by padorange** [comment]
Thanks to have taken time on this.
Perhaps there is a right privilege problem...
