### ISSUE TITLE
Screenshots gone from lzone.de

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#1279]
The following screenshots are gone from the website I guess you updated it yesterday since it was working when we released 1.14.6 on Flathub https://github.com/lwindolf/liferea/blob/bcd8732debe56de600900ca0a15c5b310362278f/net.sourceforge.liferea.appdata.xml.in#L36-L73

They are downloaded by appstream-util during the build process. Not having them will make the build fail.

If you want I can create 1:1 copies. You can host it on GitHub or on the website.

**Comment by bbhtt** [comment]
Also, the donation link to your paypal seems to be gone as well https://github.com/lwindolf/liferea/blob/bcd8732debe56de600900ca0a15c5b310362278f/net.sourceforge.liferea.appdata.xml.in#L76 If you have something we can link it :)

**Comment by bbhtt** [comment]
<details>
<summary>Screenshot dump</summary>

Reading newsfeeds in an email client interface: 

![1](https://github.com/lwindolf/liferea/assets/62639087/44a5baee-6817-4c6e-a37f-e57f8b18dbce)

Browse the web with tabs inside Liferea:

![2](https://github.com/lwindolf/liferea/assets/62639087/c30c4700-3bfe-4439-b187-e7afa6303c39)

Privacy settings:

![3](https://github.com/lwindolf/liferea/assets/62639087/f7f0a0e6-1391-4ad2-a86d-ef9fceff1ec8)

New subscriptions:

![4](https://github.com/lwindolf/liferea/assets/62639087/9329e1f7-5f64-4257-9e37-d72850a5a137)

Browse webcomics:

![5](https://github.com/lwindolf/liferea/assets/62639087/a0a625e0-4826-4ccc-b4ee-f6741c8fbe84)

Play podcasts:

![6](https://github.com/lwindolf/liferea/assets/62639087/95ebd456-ccaa-48de-84da-6b24636b8b8c)

Dark theme/full text view:

![7](https://github.com/lwindolf/liferea/assets/62639087/75398371-a9cb-401c-bc19-98fb5d01f704)

</details>

**Comment by lwindolf** [comment]
I've fixed the screenshots. This was a webserver misconfiguration. Sorry about it!

Also the donation link was intentionally dropped. Please remove it!
