### ISSUE TITLE
Enchancement request: import OPML at root level & detect duplicates

### ISSUE THREAD

**Issue by kwill** [lwindolf/liferea#128]
Steps to reproduce:

 * Click "All" folder
 * From menu, select "Import feed list..."
 * Select OPML file
 * Click "Import"

What should happen:

 * OPML imported at same level as existing folders

What happens instead:

 * OPML imported into new subfolder

Test case:

If you exported to OPML and then imported the same OPML file what should happen? In an *ideal* scenario, nothing, as duplicates would be detected and ignored. In the worst case, the option to import such that you can manually sort through duplicates could be supported.

This would provide a simple way to synchronise feedlists between different feedreaders. (Although not, of course, read/unread status and all that.)

**Comment by lwindolf** [comment]
I understand your use case. But won't fix/implement due to missing manpower.

**Comment by kwill** [comment]
What a pity, but thanks anyway. I will investigate external OPML-merging libraries.
