### ISSUE TITLE
Subscription Update with no available update signals an error

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#1285]
when update fetches a subscription url and the return status is 304 with 0 bytes received, the subscription is in the error state.

**Comment by rich-coe** [comment]
Found during investigating #1276

**Comment by rich-coe** [comment]
created pull request

When a subscription is requested to update, and it hasn't updated since the last time in the current liferea session,
and the status is 304, liferea was setting the subscription into the error state.

**Comment by lwindolf** [comment]
PR merged. Will be included in 1.15.1
