### ISSUE TITLE
deprecated webkit functions

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#1287]
I'm getting these warnings when building with the current webkit libwebkit2gtk-4_1-0 (2.40.4)
I'll try to fix these when I can, unless someone else gets it done first.

    liferea_browser.c:413:9: warning: ‘webkit_web_view_run_javascript_finish’ is deprecated: Use 'webkit_web_view_evaluate_javascript_finish' instead [-Wdeprecated-declarations]
      413 |         js_result = webkit_web_view_run_javascript_finish (WEBKIT_WEB_VIEW (object), result, &error);
    --
    liferea_web_extension.c:93:9: warning: 'webkit_web_page_get_dom_document' is deprecated [-Wdeprecated-declarations]
       93 |         document = webkit_web_page_get_dom_document (page);
    --
    liferea_web_extension.c:94:9: warning: 'webkit_dom_document_get_default_view' is deprecated [-Wdeprecated-declarations]
       94 |         window = webkit_dom_document_get_default_view (document);
    --
    liferea_web_extension.c:110:9: warning: 'webkit_dom_dom_window_get_scroll_y' is deprecated [-Wdeprecated-declarations]
      110 |         old_scroll_y = webkit_dom_dom_window_get_scroll_y (window);
    --
    liferea_web_extension.c:111:9: warning: 'webkit_dom_dom_window_get_inner_height' is deprecated [-Wdeprecated-declarations]
      111 |         increment = webkit_dom_dom_window_get_inner_height (window);
    --
    liferea_web_extension.c:112:9: warning: 'webkit_dom_dom_window_scroll_by' is deprecated [-Wdeprecated-declarations]
      112 |         webkit_dom_dom_window_scroll_by (window, 0, increment);
    --
    liferea_web_extension.c:113:9: warning: 'webkit_dom_dom_window_get_scroll_y' is deprecated [-Wdeprecated-declarations]
      113 |         new_scroll_y = webkit_dom_dom_window_get_scroll_y (window);
    --
    webkit.c:463:9: warning: ‘webkit_web_view_run_javascript’ is deprecated: Use 'webkit_web_view_evaluate_javascript' instead [-Wdeprecated-declarations]
      463 |         webkit_web_view_run_javascript (WEBKIT_WEB_VIEW (widget),
    --
    liferea_web_view.c:607:41: warning: ‘webkit_web_view_run_javascript’ is deprecated: Use 'webkit_web_view_evaluate_javascript' instead [-Wdeprecated-declarations]
      607 |                                         webkit_web_view_run_javascript (view, "document.webkitExitFullscreen();", NULL, NULL, NULL);

**Comment by lwindolf** [comment]
I sadly do not have enough time to work on those.

**Comment by rich-coe** [comment]
I'll submit a patch when I get done with the current libsoup issue.

**Comment by lwindolf** [comment]
I found time for a refactoring and believe to have fixed all of them in b0b1d89647631d06cdc0908cd20274fed8a963b1
