### ISSUE TITLE
1.15.1 shows 1.15.0 in About dialogue

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#1289]
I think you forgot to update it in configure.ac

https://github.com/lwindolf/liferea/blob/39cf0f8e7f75a3a8daad080f895c095e53e32280/configure.ac#L3

**Comment by bbhtt** [comment]
I already added a patch for the Flatpak release, and 1.15.x line is on Flathub beta. So no need to hurry on re-tagging ;)

**Comment by lwindolf** [comment]
Found the problem. I forgot to push and thereby I tagged one commit to early :-( So changelog and configure.ac was not tagged properly. Functionality wise everything should have been fine.

I think I won't fix the 1.15.1 release to avoid confusion as I just made a new 1.15.2...
