### ISSUE TITLE
sorting by feed for tt-rss

### ISSUE THREAD

**Issue by pcause** [lwindolf/liferea#129]
I have a tt-rss server and I use tt-rss categories and each category has multiple feeds.  When I display a category and click the column header to sort by feed the item list isn' t sorted correctly.  I can't see a pattern in how it is sorted but a guess might be that the items are sorted by feed id returned by tt-rss instead of the feed name / feed URL.

**Comment by lwindolf** [comment]
The sorting order is by internal node pointer. The idea is that sorting by feed means "grouping items by feed". As you click a column containing an icon, there is no logical ordering. Thus the implementation was simplified to pointer sorting.

So from my point of view sorting is correct.

**Comment by pcause** [comment]
what i want *is* group by feed and the UI doesn't do that.  I have a category, which is basically a folder, and withing that category feeds.  When displaying the folder I can't get the grouping by feed.  I don't think this should be different than any folder/feed/items type for normal feeds.  I think the way the node is synthesized for tt-rss is juts slightly off.  If you still think this sin't a correct view, I will try to understand the code better and see if I can make a suggestion.  Thanks for the product, it is great.
