### ISSUE TITLE
UI weirdness showing duplicated titles in headline view

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#1290]
![ui-weirdness](https://github.com/lwindolf/liferea/assets/6563203/f5f940a8-c292-4ec0-84ab-1c27d8a75bad)

I've been seeing duplicated titles in headline view for a while now.   
At first I thought it was a mistake of mine, but I suspect its a bug in the display handler.
Also, I cannot capture it in a screenshot, but sometimes when I roll over the headlines, the headline 'flashes' and changes to another in the same list.  
Sometimes same headline is repeated over many of the item entries. 
As shown in the screen shot, the title is correctly displayed in the item view.

**Comment by rich-coe** [comment]
libglib-2_0-0-2.76.4-1.1.x86_64
libgtk-3-0-3.24.38-1.2.x86_64
libsoup-3_0-0-3.4.2-1.1.x86_64
libwebkit2gtk-4_1-0-2.40.4-1.1.x86_64

**Comment by lwindolf** [comment]
@rich-coe Is this gone with the recent 1.15.3 release? There was at least one bugfix repairing a memory corruption that might lead to this.

**Comment by rich-coe** [comment]
@lwindolf I upgraded to master 16 Sep 2023 (32eaf33eeedeeae460f82dd3e087fe1f4fe2eb5d) and still see the issue.

**Comment by lwindolf** [comment]
@rich-coe Thanks for retesting. Right now I'm also seeing quite some instability although not the same visual effect... Sounds like a persisting memory corruption. Needs more valgrind runs :-(

**Comment by rich-coe** [comment]
I wonder if its a display/update bug in glib table display.  
Moving the mouse over the title entries and having them change does not seem correct for static strings.

**Comment by lwindolf** [comment]
I can reproduce this in Ubuntu 23.10 seems like a GTK toolkit issue. Scrolling the item list or mouse movement clears the effect. Setting this to won't fix.

**Comment by rich-coe** [comment]
libglib-2_0-0-2.80.3-1.1.x86_64
libgtk-3-0-3.24.42-1.2.x86_64
libwebkit2gtk-4_1-0-2.44.2-2.1.x86_64

Still having the issue.
Scrolling changes the value in the headline be never shows the correct value.

**Comment by rich-coe** [comment]
@lwindolf  I think I've discovered the issue with this.
I noticed this message 

    (liferea:1015362): Gtk-WARNING **: 21:10:04.821: Failed to set text from markup due to error parsing markup: Error on line 1: Entity did not end with a semicolon; most likely you used an ampersand character without intending to start an entity — escape amp
ersand as &amp;.

Corresponding to the previous title being displayed repeatedly,
The titles that are broken have non-escaped '&' in their titles.

If the title has an & without &amp; or other escaped value, replace it with &amp;
When I have a solution I'll submit a PR.

**Comment by rich-coe** [comment]
Argh.  My bug.  Never mind.
