### ISSUE TITLE
Add articles to favourites / star articles

### ISSUE THREAD

**Issue by reahari** [lwindolf/liferea#1293]
Can a method be added to add an article to favourites, for example by starring them? I am using liferea 1.14.4 on Ubuntu 23.04

**Comment by lwindolf** [comment]
There is the feature that you can flag articles. Flagged articles are never delete and kept forever. I believe this feature matches your use case.

**Comment by reahari** [comment]
ok. I didn't realise that that is what flag meant as usually, in other situations, you flag something when there's an error

**Comment by lwindolf** [comment]
@reahari Yeah that might be confusing. The funny thing is 20 years ago when I started Liferea and based it on existing mail and nntp client a lot of them had the flag feature. Somewhere along the way many application that had it from the start exchanged it for the nowadays common :star:  icon. Somehow we never did this in Liferea...

**Comment by lwindolf** [comment]
@reahari Will definitively think about it.
