### ISSUE TITLE
[Feature Request] Sync articles with Feeder

### ISSUE THREAD

**Issue by sbadux** [lwindolf/liferea#1298]
Hello,
Feeder has a Sync feature (in beta). Since Feeder ([https://gitlab.com/spacecowboy/Feeder](https://gitlab.com/spacecowboy/Feeder)) is probably the most used open-source feed reader on Android it would be great to make Liferea and Feeder sync together.

This is just a request to consider this opportunity, but I don't know if it's technically possible. Thanks in advance

**Comment by lwindolf** [comment]
I don't think this is technically possible as neither application exposes any endpoint on the internet that the other could use to sync :-(

Also supporting dozens of different sync protocols is not this small project can do.

**Comment by sbadux** [comment]
Thanks anyway :-)
