### ISSUE TITLE
Can No Longer Bookmark Articles in Pocket

### ISSUE THREAD

**Issue by jvaccaro** [lwindolf/liferea#1301]
Ever since Mozilla announced/implemented using Firefox authentication for logging into Pocket, the option to bookmark a Liferea article in Pocket fails with a Mozilla 500 Error. Not sure where the fault lies between Mozilla and Liferea.
I am using Liferea 1.14.5 on Ubuntu 20.04.6 LTS.

The url that produces the error is https://getpocket.com/ff_signin?s=pocket&t=login

FWIW, I have attached a screen shot of the error screen.
![liferea-mozilla-error](https://github.com/lwindolf/liferea/assets/153742/767d7d8c-c73a-432f-b92c-5f145aff09da)

**Comment by lwindolf** [comment]
Cannot reproduce this. I get a login prompt.

Maybe this was a temporary issue with Pocket?
