### ISSUE TITLE
Preview window empty with webkitgtk-2.42.0

### ISSUE THREAD

**Issue by z1atk0** [lwindolf/liferea#1306]
When running with the newly released `webkitgtk-2.42.0`, the preview window _appears_ to be empty. The darker grey header bar is still there (the mouse pointer changes to its "clickable" icon when hovering above it, and clicking it actually works), but it is invisible. When grabbing the text area with the mouse and starting to drag, the text (but not the image) becomes visible in the drag-and-drop "blob", but remains invisible in its actual window part or frame (not sure about the proper GTK terminology).

Recompiling against `webkitgtk-2.42.0` does not fix the problem. It still also works fine when running with the earlier `webkitgtk-2.40.5`, though. So it doesn't seem to matter which webkitgtk version `liferea` is _compiled_ against, but which version it is _running_ with.

Screenshot running with `webkitgtk-2.40.5`:
![Screenshot from 2023-09-19 05-38-43](https://github.com/lwindolf/liferea/assets/12568948/5f71e867-d60e-49ee-8415-b91a20909519)

Screenshot running with `webkitgtk-2.42.0`:
![Screenshot from 2023-09-19 05-37-56](https://github.com/lwindolf/liferea/assets/12568948/e86525f7-d2fe-47d4-b79b-05b996276d24)

**Comment by z1atk0** [comment]
Well, this is what my "Inspect" Window looks like:
![Screenshot from 2023-09-21 06-14-59](https://github.com/lwindolf/liferea/assets/12568948/581430bc-ec2d-4189-8076-b9750a2cedfe)
:thinking: :man_shrugging: 
Looks like the same problem as with the preview window itself: if I hover around with the mouse, the cursor changes from the pointer arrow to the text selection cursor at various spots, and if I hold the left mouse button and move around (as if I wanted to select some regions), various UI elements pop up (and vanish again if I let go of the LMB). So it seems that everything is actually _there_, but for some reason everything is invisible.

Here's the terminal output from running `liferea --debug-html 2>&1 &> liferea--debug-html.log`, there's a bunch of HTML parsing errors, but I don't know if those are related to the problem at hand: 
[liferea--debug-html.log.gz](https://github.com/lwindolf/liferea/files/12680225/liferea--debug-html.log.gz)

**Comment by bbhtt** [comment]
Are you using a NVIDIA GPU by any chance? Does `WEBKIT_DISABLE_COMPOSITING_MODE=1 liferea` work?

**Comment by z1atk0** [comment]
> Are you using a NVIDIA GPU by any chance? Does `WEBKIT_DISABLE_COMPOSITING_MODE=1 liferea` work?

Oh, wow! Yes and yes. Looks just fine now:
![Screenshot from 2023-09-21 06-47-14](https://github.com/lwindolf/liferea/assets/12568948/65509f77-8b3a-4e0c-a791-0760217d750a)
Cool, thanks! :sunglasses: :+1:

**Comment by z1atk0** [comment]
I'm not using a desktop compositor at all, maybe that's the problem?
```
[zlatko@disclosure:~]$ gsettings get org.gnome.metacity compositor
'none'
```
Other applications using WebkitGTK as a rendering backend (like GNOME's Epiphany, for example) work fine, though. Hm.

**Comment by bbhtt** [comment]
> Oh, wow! Yes and yes. Looks just fine now...

It's possibly this webkit2gtk bug in 2.42.0 https://bugs.webkit.org/show_bug.cgi?id=228268 that affects NVIDIA users. I suggest opening an issue there or asking in the webkit2gtk Matrix room to confirm.

**Comment by z1atk0** [comment]
> > Oh, wow! Yes and yes. Looks just fine now...
> 
> It's possibly this webkit2gtk bug in 2.42.0 https://bugs.webkit.org/show_bug.cgi?id=228268 that affects NVIDIA users. I suggest opening an issue there or asking in the webkit2gtk Matrix room to confirm.

Thanks, I added a comment to the bug report you pointed me to. Let's see what the webkitgtk devs have to say about it. :slightly_smiling_face:

@lwindolf feel free to close this issue if there's nothing you can do about it from within `liferea`.

**Comment by lwindolf** [comment]
@z1atk0 Great that it is fixed for you. 

@bbhtt I totally forgot about the issue with the compositor in the meantime, thanks for reminding us about it!
