### ISSUE TITLE
Add Bookie - bookmark your web

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#131]
Python based delicious.com replacement
https://github.com/bookieio/Bookie
https://bookie.io/
http://bmark.us/

**Comment by lwindolf** [comment]
Could you provide an example bookmark URL? Or maybe even a patch (you find the relevant code in src/social.c).

**Comment by GreenLunar** [comment]
@mitechie, please provide an example bookmark URL of Bookie. I have tried to register an account and failed several times.

**Comment by GreenLunar** [comment]
Bookmarklet
`javascript:(function() {location.href='https://example.org/bookie/username/new?url='+encodeURIComponent(location.href)+'&description='+encodeURIComponent(document.title)}())`

URL
https://example.org/bookie/username/new?url=http%3A%2F%2Flzone.de%2Fliferea&description=Liferea%20-%20the%20Free%20News%20Aggregator%20on%20your%20Linux%20desktop%20
