### ISSUE TITLE
1.15.x "New Subscription" -> "Advanced" stopped working, dialog doesn't show

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#1328]

**Comment by sunwire** [comment]
Strange, it works for me. (Commit 13d2d197e0dc52fc71970ebd7d863cf5b2aeff77)
![2023-12-30_07-28](https://github.com/lwindolf/liferea/assets/50745572/23be522e-ae89-4bbc-ac98-91ab592ba270)

**Comment by lwindolf** [comment]
@sunwire Must be a race condition or memory corruption of some kind. For me the GUI partially freezes up when it happens and I have to kill the application.

**Comment by lwindolf** [comment]
Launching the dialog with g_idle_add() solved the problem. But honestly I do not know the exact reason.
