### ISSUE TITLE
Update website screenshots

### ISSUE THREAD

**Issue by bbhtt** [lwindolf/liferea#1341]
As discussed in https://github.com/lwindolf/liferea/pull/1340 I went ahead with Yaru themed GNOME to follow the current screenshots.

These are on Ubuntu 24.04 (Noble daily build)

At least one screenshot with the default application state is required, so the first one is for that.

Captions are above.

<details>

Main window with feeds

![sc1](https://github.com/lwindolf/liferea/assets/62639087/db725da7-080b-4748-ac44-faae3b486ce4)

Read feeds in an email like interface

![sc2](https://github.com/lwindolf/liferea/assets/62639087/a8d0b9b2-947d-4059-ae8c-07536ece1f2b)

Read your favourite comics

![sc3](https://github.com/lwindolf/liferea/assets/62639087/6a5289cd-f9da-49bc-a8a5-5969c86f8a72)

Integrated browser support

![sc4](https://github.com/lwindolf/liferea/assets/62639087/4f5706e0-faa9-4246-b185-358d3dc08309)

Play and download podcasts

![sc5](https://github.com/lwindolf/liferea/assets/62639087/289ce5a9-d368-44b9-a074-6fa831cdb582)

Preferences

![sc6](https://github.com/lwindolf/liferea/assets/62639087/1cf4203a-032c-4729-9dbe-f9b35fe5b485)

Privacy settings

![sc7](https://github.com/lwindolf/liferea/assets/62639087/9e517f8e-d86c-45a6-b6f0-37ca7e2165fd)

Plugins from the community

![sc8](https://github.com/lwindolf/liferea/assets/62639087/250c90ea-3510-4ee9-9f87-9a85c859c116)

Add feed sources

![sc9](https://github.com/lwindolf/liferea/assets/62639087/fd045260-b76a-46cf-b083-f93bf05b94cf)

</details>

**Comment by lwindolf** [comment]
@bbhtt Sorry for me taking so long to update the screenshots. I've replaced 8 of the 9 screenshots you provided. I did not use the first one, because it shows a buggy behaviour, that I'd like not to advertise :-)

The problem is that the item view pane is not shown. This should not happen.

**Comment by bbhtt** [comment]
Thank you. That's fine, I'll update the captions in the appdata file and remove the dead link.
