### ISSUE TITLE
Positioning main window overrules windowmanger settings

### ISSUE THREAD

**Issue by dunadoo** [lwindolf/liferea#1350]
I'm using fvwm with 3x3 pages. Fvwm configuration tells liferea to open it's window in page 2x2, but with the update from 1.13.5 (debian oldstable) to 1.14.4 (debian stable) this does not work anymore: The window now opens in the active page. This is considered to be not well behaved.

The reason is the call to gtk_window_move in liferea_shell.c. When commenting this call out, everything works fine, but this is obviously not the best way to fix this bug. Alternative to fixing this issue, it might suffice to add an option to disable this behavior.

See also [discussion in fvwm forum](https://fvwmforums.org/t/after-update-startsonpage-does-not-work-anymore-for-liferea/4600/14).

**Comment by lwindolf** [comment]
Thanks for reporting this. I agree that the implemented behaviour is not well behaved regarding to WM standards.

Still it is necessary when considering trayicon use cases. Different trayicon implementations and quirks have lead to a multitude of end user reports that could not restore the Liferea icon anymore. Thus we have the aggressive gtk_window_move() implementation. Without it trayicon quirks often render Liferea completely useless to a subset of users.

I don't plan to change the behaviour as I rate the trayicon problem higher than the non-well behavedness in terms of multi-screen users. The choice is based on ticket numbers of the years and the impact of the problem for each use case.

**Comment by dunadoo** [comment]
Just in case you change your mind: It might be helpful to look at other tools (e.g. GIMP, Firefox, Sylpheed). I guess they should have the same problem with icons (I do never use icons thus I cannot tell anything about them). But at least the comply to the WM standards regarding window placement.

Liferea has been a very good companion for me for more than a decade. (Many thanks for the good work done here.) But as it is often in life, there is a time when the ways diverge. So Im gonna look for something else to replace liferea...
