### ISSUE TITLE
Feature request: Reverse "Headline" and read without scrolling from the top

### ISSUE THREAD

**Issue by geekdiop** [lwindolf/liferea#1353]
Hello there,

When reversing the Headline to read the previous feeds first, I have to scroll from the first feeds to the most recent (as in the picture), which is tiresome when dealing with some websites. Could you please add an option/button that allows unread (previous) feeds to appear at the top without scrolling. 

![image](https://github.com/lwindolf/liferea/assets/68657906/cf4703d0-09c4-4f2e-b4f5-190503c8db2c)

**Comment by lwindolf** [comment]
While Liferea will be supported for some time more we do not accept feature requests anymore.

What could help you is working with folders and the "Hide read items" preference. In a folder you can revert the order of unread items.
