### ISSUE TITLE
Important does not show total of tagged items

### ISSUE THREAD

**Issue by AndyM48** [lwindolf/liferea#1360]
My "Important" group, which I have renamed "Flagged", has a rule to include all flagged items. 

I have several feeds flagged and if I open the group they are included, but the group does not show the total number of feeds.
![2024-05-09_08-25](https://github.com/lwindolf/liferea/assets/3006039/0949655d-2606-4846-a6ab-355d236acba2)

**Comment by lwindolf** [comment]
I understand the expectation for the count on search folders to have a number corresponding to items matching their rules. Still the number display feature is implemented as an unread item counter. As your search folder has no unread items it shows no number. So implementation wise there is no bug.

**Comment by AndyM48** [comment]
Of course - silly of me
Thank you
