### ISSUE TITLE
reader mode, no preview

### ISSUE THREAD

**Issue by mexsudo** [lwindolf/liferea#1364]
### Discussed in https://github.com/lwindolf/liferea/discussions/1363

<div type='discussions-op-text'>

<sup>Originally posted by **mexsudo** May 15, 2024</sup>
Debian Stable, Mate
the "preview" is blank in reader mode and also when I in browser
I still have the ability to open in external browser. 
![Liferea 2024-05-15 08-49-26](https://github.com/lwindolf/liferea/assets/7226539/31e25baf-68f0-4ea9-93ec-6bf7dbf9dd7c)
</div>

**Comment by lwindolf** [comment]
If you have an NVidia graphics card you might be affected by #1308 which is not caused by Liferea and has a workaround.

You can check this by using GNOME web (epiphany) to load a page. Does it have the same problem?

**Comment by mexsudo** [comment]
the NVidia workaround.
nope, same result

I don't have epiphany installed

**Comment by lwindolf** [comment]
Ok. Then it can be a Liferea problem. Can you start from a terminal with

    liferea --debug-html

The you will have a new context menu option in the item content pane "Inspect". Clicking it will open the Web developer tools. Once you opened it please navigate to another icon and check for errors in the "Console" tab.

**Comment by mexsudo** [comment]
liferea does open, same issue
*no new context menu option

**Comment by mexsudo** [comment]
peter@z840-1:~$ liferea --debug-html
HTML   : theme color "GTK-COLOR-FG" is FFFFFF
HTML   : theme color "GTK-COLOR-BG" is D4D4D4
HTML   : theme color "GTK-COLOR-LIGHT" is FFFFFF
HTML   : theme color "GTK-COLOR-DARK" is 949494
HTML   : theme color "GTK-COLOR-MID" is CACACA
HTML   : theme color "GTK-COLOR-BASE" is D4D4D4
HTML   : theme color "GTK-COLOR-TEXT" is FFFFFF
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is 61BF00
HTML   : theme color "GTK-COLOR-VISITED-LINK" is 61BF00
HTML   : Light GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_FG" is D4D4D4
HTML   : theme color "FEEDLIST_UNREAD_BG" is 949494
HTML   : theme color "GTK-COLOR-FG" is 2C2C2C
HTML   : theme color "GTK-COLOR-BG" is D4D4D4
HTML   : theme color "GTK-COLOR-LIGHT" is FFFFFF
HTML   : theme color "GTK-COLOR-DARK" is 949494
HTML   : theme color "GTK-COLOR-MID" is CACACA
HTML   : theme color "GTK-COLOR-BASE" is D4D4D4
HTML   : theme color "GTK-COLOR-TEXT" is 2C2C2C
HTML   : theme color "GTK-COLOR-NORMAL-LINK" is 61BF00
HTML   : theme color "GTK-COLOR-VISITED-LINK" is 61BF00
HTML   : Light GTK theme detected.
HTML   : theme color "FEEDLIST_UNREAD_FG" is D4D4D4
HTML   : theme color "FEEDLIST_UNREAD_BG" is 949494
HTML   : Feed list unread CSS: foreground='#D4D4D4' background='#949494'

HTML   : XSLT localisation: setlocale(LC_MESSAGES, NULL) reports 'en_US.UTF-8'
HTML   : XSLT localisation: lang='en_US.UTF-8' shortlang='en'
[Errno 2] No such file or directory: '/home/peter/.config/liferea/plugins/add-bookmark-site/add-bookmark-site.ini'
HTML parser error : Tag rss invalid
	>
	^
HTML parser error : Tag channel invalid
<channel>
        ^
HTML parser error : Tag atom:link invalid
:link href="https://techcrunch.com/feed/" rel="self" type="application/rss+xml" 
                                                                               ^
HTML parser error : Unexpected end tag : link
	<link>https://techcrunch.com/</link>
	                                    ^
HTML parser error : Tag description invalid
	<description>Startup and Technology News</description>
	            ^
HTML parser error : Tag lastbuilddate invalid
	<lastBuildDate>Tue, 21 May 2024 13:39:52 +0000</lastBuildDate>
	              ^
HTML parser error : Tag language invalid
	<language>en-US</language>
	         ^
HTML parser error : Tag sy:updateperiod invalid
	<sy:updatePeriod>
	                ^
HTML parser error : Tag sy:updatefrequency invalid
	<sy:updateFrequency>
	                   ^
HTML parser error : Tag generator invalid
	<generator>https://wordpress.org/?v=6.5.3</generator>
	          ^
HTML parser error : Tag image invalid
<image>
      ^
HTML parser error : Tag url invalid
	<url>https://techcrunch.com/wp-content/uploads/2015/02/cropped-cropped-favicon-
	    ^
HTML parser error : Unexpected end tag : link
	<link>https://techcrunch.com/</link>
	                                    ^
HTML parser error : Tag width invalid
	<width>32</width>
	      ^
HTML parser error : Tag height invalid
	<height>32</height>
	       ^
HTML parser error : Tag site invalid
<site xmlns="com-wordpress:feed-additions:1">136296444</site>	<item>
                                            ^
HTML parser error : Tag item invalid
<site xmlns="com-wordpress:feed-additions:1">136296444</site>	<item>
                                                             	     ^
HTML parser error : Unexpected end tag : link
/2024/05/21/stack-ai-wants-to-make-it-easier-to-build-ai-fueled-workflows/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Ron Miller]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 14:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Startups]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[AI]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Y Combinator]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[workflow]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Generative AI]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2782196</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>Stack AI’s co-founders, Antoni Rosinol and Berna
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2782196</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
024/05/21/pinecone-launches-its-serverless-vector-database-out-of-preview/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Frederic Lardinois]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 13:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Enterprise]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[TC]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[AI]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Pinecone]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2782034</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>Pinecone, the vector database startup founded by E
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2782034</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
05/21/special-mud-helps-xgs-energy-get-more-power-out-of-geothermal-wells/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Tim De Chant]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 13:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Startups]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Climate]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[geothermal energy]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[renewable power]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[XGS Energy]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2781971</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>Young geothermal energy wells can be like budding 
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2781971</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
link>https://techcrunch.com/2024/05/21/sonos-finally-made-some-headphones/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Brian Heater]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 13:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Hardware]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Gadgets]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Sonos]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[headphones]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[sonos ace]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2781723</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>The market play is clear from the outset: The $449
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2781723</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
2024/05/21/adobe-brings-firefly-ai-powered-generative-remove-to-lightroom/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Brian Heater]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 13:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[AI]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Apps]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Adobe]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[firefly]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[lightroom]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[adobe lightroom]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Generative AI]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Adobe Firefly]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2781377</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>Adobe says the feature is up to the task, regardle
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2781377</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
e-invests-in-battery-startup-south-8-to-boost-cold-weather-ev-performance/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Tim De Chant]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 12:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Startups]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Transportation]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Climate]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[lithium-ion battery]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[battery materials]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[South 8 Technologies]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2781956</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>All cars suffer when the mercury drops, but electr
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2781956</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
21/data-labeling-startup-scale-ai-raises-1b-as-valuation-doubles-to-13-8b/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Paul Sawers]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 11:11:03 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[AI]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Fundraising]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Amazon]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[data labeling]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[meta]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Scale AI]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2782172</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>Scale AI has raised a $1 billion Series F round fr
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2782172</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
-match-coinbase-and-others-team-up-to-fight-online-fraud-and-crypto-scams/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Sarah Perez]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 11:00:00 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Crypto]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Fintech]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Social]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[scams]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[meta]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[fraud]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Tech Against Scams]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2781862</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>The new coalition, Tech Against Scams, will work t
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2781862</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
/05/21/eu-council-gives-final-nod-to-set-up-risk-based-regulations-for-ai/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Natasha Lomas]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 10:49:51 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[AI]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Government & Policy]]></category>
		         ^
HTML parser error : htmlParseEntityRef: no name
		<category><![CDATA[Government & Policy]]></category>
		                               ^
HTML parser error : Tag category invalid
		<category><![CDATA[AI regulation]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[EU AI Act]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[eu ai act final approval]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2782143</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>It's a wrap: European Union lawmakers have given t
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2782143</post-id>	</item>
		                                               ^
HTML parser error : Tag item invalid
		<item>
		     ^
HTML parser error : Unexpected end tag : link
treasury-management-platform-for-insurers-raises-93m-to-fuel-us-expansion/</link
                                                                               ^
HTML parser error : Tag dc:creator invalid
		<dc:creator><![CDATA[Paul Sawers]]></dc:creator>
		           ^
HTML parser error : Tag pubdate invalid
		<pubDate>Tue, 21 May 2024 08:54:48 +0000</pubDate>
		        ^
HTML parser error : Tag category invalid
				<category><![CDATA[Fintech]]></category>
				         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Fundraising]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[payments processing]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[treasury management]]></category>
		         ^
HTML parser error : Tag category invalid
		<category><![CDATA[Vitesse]]></category>
		         ^
HTML parser error : Tag guid invalid
		<guid isPermaLink="false">https://techcrunch.com/?p=2782137</guid>
		                         ^
HTML parser error : Tag description invalid
					<description><![CDATA[<p>London-based fintech Vitesse has closed a $93 mill
					            ^
HTML parser error : Tag post-id invalid
		<post-id xmlns="com-wordpress:feed-additions:1">2782137</post-id>	</item>

**Comment by sjehuda** [comment]
@mexsudo please try this shell command:

```
WEBKIT_DISABLE_DMABUF_RENDERER=1 liferea
```

---

This problem was observed on Arch Linux and postmarketOS.

> Rendering works, though nothing is displayed.
> 
> Please see more information at Arch Linux and postmarketOS
> 
> Arch Linux
> https://bbs.archlinux.org/viewtopic.php?pid=2170335#p2170335
> 
> postmarketOS
> https://gitlab.com/postmarketOS/pmaports/-/issues/2793

Source: https://bugs.webkit.org/show_bug.cgi?id=274465

**Comment by laaameche** [comment]
thanks @sjehuda , it solve my problem on Kubuntu 24.04

**Comment by tuananh** [comment]
> WEBKIT_DISABLE_DMABUF_RENDERER=1

this fixes it for me.
