### ISSUE TITLE
Unlimited number of items per feed?

### ISSUE THREAD

**Issue by Anrock** [lwindolf/liferea#1366]
So I've found a "Default number of items per feed to save" setting in preferences and cranked it up to a big number which kinda solves my case.

But is there a way to keep unlimited number of items? I realize that it may cause issues when too much items accumulate so maybe it can be made to keep unlimited numbers of unread items and keep only N read items?

**Comment by lwindolf** [comment]
Please have a look at the feed properties. You can enable "Unlimited cache" in the "Archive" tab.

It is not supported to enabled this for all feeds at once. If you want this I'd suggest to set a very large number instead. But you might run into performance problems over time.
