### ISSUE TITLE
Doesn't recognize atom:link element with no rel attribute

### ISSUE THREAD

**Issue by ed-davies** [lwindolf/liferea#1382]
If an Atom feed entry element contains a link element without a rel attribute Liferea seems not to recognize it as `rel="alternate"` despite RFC 4287 4.2.7.2 saying:

> atom:link elements MAY have a "rel" attribute that indicates the link relation type.  If the "rel" attribute is not present, the link element MUST be interpreted as if the link relation type is "alternate".

An example of such a feed is: [https://justine.smithies.me.uk/atom.xml](https://justine.smithies.me.uk/atom.xml) which contains elements such as

`<link href="void-linux-with-encrypted-root-on-zfs.html"/>`

Right clicking on this item and selecting “Open in external browser” results in a “This item has no link specified” dialog box.
 
![dialog box](https://github.com/user-attachments/assets/8a4e0142-268e-4129-86df-f71c92abcfb1)

This is with Liferea 1.14.4 in Debian Stable. I tried to install a more recent version of Liferea on a test system but see issue [#1381](https://github.com/lwindolf/liferea/issues/1381).

**Comment by lwindolf** [comment]
Thanks for reporting I've fixed it accordingly.
