### ISSUE TITLE
Download Manager

### ISSUE THREAD

**Issue by AndyM48** [lwindolf/liferea#1388]
Would you consider adding curl and wget to the supported download managers?

**Comment by sjehuda** [comment]
I would agree that the inteface for download manager could be improved.

Perhaps utilizing configurations files (e.g. `INI`, `TOML` or `.desktop`) would be a flexible solution.

_P.S. Same to the interface for bookmark managers._

**Comment by sjehuda** [comment]
I have open a ticket at #1392 which is a really duplicate of this, if my comment is also considered.

**Comment by AndyM48** [comment]
`consider adding curl and wget to the supported download managers`

I really don't want to install another download manager. I believe that either curl or wget are often installed by default by a linux distibution. Please add them to the list of download managers.

**Comment by lwindolf** [comment]
I've just merged a solution for the download manager problem. I decided to get rid of the external dependencies (every changing/missing tools) and go for a self-implemented download manager.

With the new solution there is a new menu options "Tools" -> "Downloads" where you can find a simple download manager.

While optics are not yet perfect, functionality should be ok. The basic idea is to provide similar features to what Firefox and Chrome provide for downloads.
