### ISSUE TITLE
Possible cache header issue

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#1390]
Quote from https://rachelbythebay.com/w/2024/10/25/fs/

> Liferea/1.15.3. Something is very wrong with the caching on this thing. It drops to unconditionals a lot, and recently started sending some bullshit 1970 IMS header with things like 5s and 14s intervals. No idea what the hell is going on there. 

Should be investigated.

**Comment by rich-coe** [comment]
This might be one of my test versions.  I'll need to check my code and with rachelbythebay to confirm.
I did not change the version number of the liferea version I've been using, and I signed up to participate in the rss reader survey.

**Comment by lwindolf** [comment]
Good to know. Still it might be worth to have test cases for such an important feature like network cache headers.
