### ISSUE TITLE
Ignored the last position of the vertical panel.

### ISSUE THREAD

**Issue by UdongeinChan** [lwindolf/liferea#140]
If the program runs in the system tray coiled, when you expand the window, the panel headers is to compact.

http://i.imgur.com/IQV8T7g.png

**Comment by foresto** [comment]
This is a regression. I never ran into this problem until a year or two ago, when a new OS release upgraded liferea to a new version. I think I was using version 1.8 before that.

**Comment by lwindolf** [comment]
Fixed with the PR from @foresto
