### ISSUE TITLE
Liferea and libappindicator

### ISSUE THREAD

**Issue by avDuma** [lwindolf/liferea#142]
Hi,
I'm using Bodhi Linux 3.0 (Ubuntu Trusty + E19) and I've seen that liferea doesn't display on system tray icon / notification area.
I've read that Ubuntu's package strip out tray support from liferea, so I've compiled liferea 1.11.2 from sources.

Compiling was fine, I've also installed libindicate and libnotify packages, but on E19 tray icons doesn't appear nothing.
E19 system tray works with libappindicator (and dropped down xembed) and other applications like steam or network manager work good.

Is there in your programs to use libappindicator support for liferea tray icons?

Thank you for your time,
regards,
Alberto

**Comment by lwindolf** [comment]
Hello,

Liferea doesn't support libappindicator.

If you want you could try using libappindicator from Python and implement support similar to the current GtkStatusIcon based trayicon in git master.
