### ISSUE TITLE
images too wide

### ISSUE THREAD

**Issue by hfiguiere** [lwindolf/liferea#144]
The way Wordpress handle images in blog post is that it set the width/height attribute to the native size of the picture and then use CSS to resize it. And that's in the RSS minus the CSS, so we end up with excessively large images that overflow.

To fix this we can have in the default CSS the following rule:

````
img {
	max-width: 550px;
	height: auto;
}
````

This will set the max width of the image to 550px (a different value could be used) and allow resizing the height to keep the aspect ratio.

**Comment by hfiguiere** [comment]
I'm running 1.10.13 as package in Fedora 21.

**Comment by lwindolf** [comment]
In 1.11 we already have 

    div.content * img, video {
        border:0;
        margin:2px;
        max-width:100%;
        height:auto;
    }

could you test if this solves your issue (by adding it to ~/.config/liferea/liferea.css)?

If it works I'd just backport it.

**Comment by hfiguiere** [comment]
This works for the case I made the fix. Better as it as 100% instead of a fixed pixel width.
