### ISSUE TITLE
SubToMe support

### ISSUE THREAD

**Issue by julien51** [lwindolf/liferea#146]
Several blogs I read have a [SubToMe](https://www.subtome.com/#/) button and I use their extension in my browser. It would be nice if Liferea was an option there.

**Comment by asl97** [comment]
people sure don't read the faq do they?

anyway, there is that rss option in the `view full list of service`, if that doesn't work, you could always just export the [OPML](https://www.subtome.com/#/subscriptions) and import it into liferea

**Comment by lwindolf** [comment]
Thanks for suggesting the feature. Still no time to implement it. Please consider contributing an implementation!
