### ISSUE TITLE
Gwget is not started automatically

### ISSUE THREAD

**Issue by openhs** [lwindolf/liferea#150]
1. Set gwget as program to download enclosures.
2. Right-click on an enclosure in Liferea and select "Save As"
   => Observe that nothing happens.

User has to start Gwget manually before attempting to download an enclosure in Liferea.  KGet is started automatically.

The other report for this issue (#105), which I wrote was closed due to suspicion of incorrect configuration in my system.  I have checked my system and it behaves correctly but I am not able to reopen the bug therefore I wrote the new one.  Please see below copy&paste of the last comment from the previous bug:

---

Oh, I did not know that applications can actually be started via D-Bus.  Now that I know, I have tried and successfully able to start Gwget by following Python code:

```
#!/usr/bin/env python
import dbus
sessionBus = dbus.SessionBus()
xgetProxy = sessionBus.get_object("org.gnome.gwget", "/")
```

Replacing "org.gnome.gwget" by "org.kde.kget" it starts KGet as well.  One problem that I have observed is that Gwget does not send a reply so Python program times out at the last line (even though Gwget is started).  Maybe it is because it creates org.gnome.gwget.ApplicationService D-Bus node instead of org.gnome.gwget (as can be seen by qdbusviewer)?  Just guessing.

In Liferea code file preferences_dialog.c enclosure_download_commands[] array contains "dbus-send --session --print-reply --dest=org.gnome.gwget.ApplicationService ..." for Gwget and "kget %s" for KGet (and similar for others).  So it seems that only Gwget is being started via D-Bus and since the --dest is org.gnome.gwget.ApplicationService, it is not started because the name of registered service in the/my system is org.gnome.gwget.  Perhaps it could simply be changed to "gwget %s" similarly to others?

**Comment by openhs** [comment]
This is actually a bug in Gwget application.  The DBus service file that It installs is wrong.  So the DBus interface actually can not be used.  If 'org.gnome.gwget' is used the application starts but no further communication is possible.  If 'org.gnome.gwget.ApplicationService' is used the application does not start (but once started manually the communication works).

The only option that would work is to start Gwget via its binary.

You may also consider removing Gwget support since now it is possible to specify custom command for downloaders.

**Comment by lwindolf** [comment]
Just removing would break the preference for users still (somehow) working with gwget.
I believe changing the DBUS invocation to a binary call might be best.
