### ISSUE TITLE
Rendering Latex or Mathjax

### ISSUE THREAD

**Issue by gonenc96** [lwindolf/liferea#155]
I noticed that Liferea does not render Latex equations, which results in a messy text when reading a mathematical rss-feed. Is it possible to work around this problem or has the latex-feature already been implemented and I am missing it?

**Comment by lwindolf** [comment]
Liferea use WebkitGtk to render HTML and websites. AFAIK WebkitGtk supports MathML, which can be used to render math equations. I don't think any render engine natively supports Latex/Mathjax. 

Can you paste an example snippet or even a feed URL?
Can you test the same page with the Epiphany browser (because it also uses WebkitGtk)?
Can you check if plugins are enabled in Liferea preferences (and retry with enabled plugins if the option is disabled)?

**Comment by gonenc96** [comment]
The url of the feed is http://physics.stackexchange.com/feeds. And I think that I have described my problem in an ambiguous way. What I try to say was that I cannot see the formulas in the Liferea main screen. (the screen, where I can also see the headlines)(s. screenshot1). However everything is fine when I open the browser of Liferea(s. screenshot2). BTW if the feature that I describe, namely rendering latex in the main screen has not yet been implemented in Liferea it would be really nice if you implement this feature do that. 

I am new to github, so I don't really know if I can make any request for new features, if I am not allowed to do so, please do ignore the last sentence. 
Screenshot 1:
![screenshot1](https://cloud.githubusercontent.com/assets/10942319/6318272/350372f4-ba92-11e4-8513-94922b39ba49.png)

Screenshot 2:
![screenshot2](https://cloud.githubusercontent.com/assets/10942319/6318276/5833bd4c-ba92-11e4-9fdc-4dff3fe6f0ce.png)

**Comment by asl97** [comment]
it's not that github disallow feature request, it's just this project.

in any case, MathJax is a JavaScript display engine and [JavaScript is disable for security reason](https://github.com/lwindolf/liferea/issues/116#issuecomment-64276201)

**Comment by lwindolf** [comment]
@asl97 Thanks for the analysis.

@gonenc96 AFAIK using MathML in the feed (or rendered images) is the only realistic way to add formulas to news feeds. Maybe asking the feed author to provide only MathML formulas would help...

**Comment by qazip** [comment]
Is there any news regarding this @lwindolf. Is supporting latex still something that's not easy to do?

**Comment by lwindolf** [comment]
@qazip Let's say it like this: noone is working on it and it is hard from a security perspective (as @asl97 hinted on #116). For security reasons we have to heavily sanitize HTML which we put into a HTML widget which has access to the local filesystem (for loading icons and CSS). Right now I value security and low complexity higher than MathML as a use case.

As a workaround I suggest enabling auto-load link in the feed properties to directly load the article source that correctly renders the MathML.
