### ISSUE TITLE
Italian translation: orthography error in preferences

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#156]
Reported in Debian [1] : typo in the Italian translation

"Abilitare plugin del broser" is wrong, "broser" should be "browser".

Confirmed in 1.10.14 release.

[1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776056

**Comment by lwindolf** [comment]
Am 27.02.2015 um 22:58 schrieb paulgevers:
>
> Reported in Debian [1] : typo in the Italian translation
>
> "Abilitare plugin del broser" is wrong, "broser" should be "browser".
>
> Confirmed in 1.10.14 release.
>
> [1] https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776056
>
>

Thank you for the hint fixed for 1.10.15 and 1.11.4.

Cheers,
Lars
