### ISSUE TITLE
Pane placement is forgotten

### ISSUE THREAD

**Issue by macias** [lwindolf/liferea#158]
I have 3 panes, list of all RSS feeds taking 50% of the space on the left, list of topics for given RSS feed taking 50% of top from what was left on the right, and article taking remaining 50% on right.

Hover on each run of Liferea it drops those pane placement/sizes and resets it to 50%, 1 line, the rest accordingly. So each time I run Liferea I have to manualy restore the pane sizes.

Please, store the placement and restore it.

**Comment by asl97** [comment]
http://lzone.de/liferea/faq.htm#feature-x

**Comment by tilt-me** [comment]
Hi,
maybe I'm facing the same issue: I use the _wide view_ and each time I run Liferea I have to manually restore the pane sizes.
The first one on the left (containing the list of all my RSS feeds) is fine, while I have to restore the width of the middle (topics of selected feed) and right (preview of single article) ones.

Thanks in advance, bye!

**Comment by foresto** [comment]
This is a regression. I never ran into this problem until a year or two ago, when a new OS release upgraded liferea to a new version. I think I was using version 1.8 before that.

**Comment by lwindolf** [comment]
Fixed with the PR from @foresto

**Comment by tilt-me** [comment]
Just installed 1.10.16 and pane placement is remembered, thanks a lot :)
