### ISSUE TITLE
Scrollbar functionality change ?

### ISSUE THREAD

**Issue by testguyct** [lwindolf/liferea#161]
If I recall correctly, Liferea used to incrementally move the scrollbar in the upper headline pane no matter where on the scrollbar "track" the mouse is clicked.  It seems that now, the scrollbar moves the full distance to the position where the mouse was clicked. For example, in the current functionality, if the mouse is clicked on the very bottom of the scrollbar track, the scrollbar will move all the way down to the bottom of the track. The old functionality seemed to do a single "page down" no matter where the mouse was clicked on the scrollbar track.

**Comment by asl97** [comment]
iirc, it was cause gtk changes, nothing we can do about it, use right click instead.

**Comment by testguyct** [comment]
Ah, thanks. That works.

**Comment by asl97** [comment]
just letting you know, it also effect other gtk app like gedit, try using right click if left click just move the scroll bar to where the mouse is pointing.

to be honest, it is a good change, sometimes the scroll bar is so small that it is hard to click and drag it, so they move the `page by page` to the right click and you can left click anywhere to do the `click and drag`.
