### ISSUE TITLE
Don't load images automatically

### ISSUE THREAD

**Issue by onpon4** [lwindolf/liferea#164]
Liferea acts like a Web browser in that it automatically loads any external images automatically. I'm not fond of this behavior. It means that if I look at an entry that embeds an image link, as is the case for the xkcd feed, for example, the owners of the servers sending me the images are essentially automatically notified of when I checked my feed reader. I'm sure most servers aren't set up to take advantage of this, but that doesn't change the fact that this behavior gratuitously invites this kind of tracking.

As Liferea currently is, the only way I can see to prevent images from being loaded is to check the "Work offline" box in the Subscriptions menu. This isn't convenient to do at all; you have to check "work offline" every time you want to look at entries, and then remember to uncheck it again if you want to get updates later in the day. There needs to be a better mechanism to prevent automatic remote loading of images. A checkbox to disable the behavior, for example.

But what I would suggest is to do what email clients do: just don't load linked images automatically, unless the user opts in to the behavior of loading all images automatically. Instead, add a button that causes such images to be loaded, so the users can decide _each time_ whether or not they want to see the images (and whether or not they're OK with the people sending the images knowing about it). Treating <img> tags as <a> tags while images are not loaded would also be helpful.

**Comment by GreenLunar** [comment]
I am interested in such ability too.  It would be great when roaming with a limited cellular plan.
`/Tools/Preferences/Browser/Load images automatically`
Right-click on image, select `Load Image` to load an image.

**Comment by erie88** [comment]
I thought I'm the only one who would want to see option"disable fetching / loading images" on liferea. 
I really hope they would add this option since most of my feeds are from tumblr. And the feeds have lots of images (even in 1 page can have 20 or more images). 
With limited internet connection, I prefer to just read excerpt of the feed content. Thus if I want to see what the images content, I can view in browser if I want. 
With liferea, I'm kinda forced to view all the content. The feed title doesn't give enough information of what the feed content is.   I'm talking about tumblr feed where tumblr writers can write whatever title they wants.

**Comment by GreenLunar** [comment]
Liferea can either have an InfoBar with buttons to load images on demand, similarly to some email clients or let user to load each single image on click/demand.

**Comment by asl97** [comment]
all the idea that been stated all sound easy to implement directly into liferea but it isn't.

it is however easy to implement it as a script.
____

ie:
make a script for the feed,  replace all image link with a button with javascript in the on_click which replace it with the image.

**Comment by balonballot** [comment]
@asl97 script as plugins? how do I create one? I want to (if possible) make it so liferea does not display images at all and just text and url.

**Comment by GreenLunar** [comment]
> make a script for the feed, use the script to replace all image link with a button with javascript in the `on_click` which replace it with the image.

Please deliver us such script! ^_^

**Comment by asl97** [comment]
@balonballot : not as a plugin, iirc, it's impossible to modify how webkit works from the plugin system on liferea.

it's a script as a filter (see http://lzone.de/liferea/scraping.htm )

@GreenLunar : there is no method that would work everywhere, it would be hard to make a script that would work for every site.

but it's really a simple script once you know the what to turn the `img` tag into, so i will leave it to other people to code it themselves, however i will just give an example of the resulting `html code`.
____

anything in `<!-- -->` is just a comment to help you understand the code and reason why it was done this way, there no need to add them in your script.

from `<img src='http://i.imgur.com/HrpRySJ.jpg'><img>`
to:
```html
<!-- example using img+p pair, onclick inject method -->
<!-- note: liferea will strip all script tag so it is impossible to do it using it so we need to use javascript in onclick and other method -->

<!-- there can't be a src in the img tag since it would make the browser load it, instead it must be injected when you want to load it -->
<img hidden=true id="image"></img>
<!-- hide the text once it is click + un-hide the image and inject the src-->
<p onclick="this.hidden=true;document.getElementById('image').hidden=false;document.getElementById('image').src='http://i.imgur.com/HrpRySJ.jpg'">http://i.imgur.com/HrpRySJ.jpg</p>
```

note:
1. the `id` in a tag need to be unique,  if there is more than one image,  you would need to code an index,  don't worry, it not as complex as it sound,  a little googing and you should know how to do it.
2. don't try to make a single script work on lots of site, it might get too complex and impossible to understand, instead, keep it simple and make a custom script for each site that doesn't work with your basic filter script*.

\* basic as in it (only) handle basic `img` tag, ie: `<img src="some link"></img>`

____

( @lwindolf )
ps: has anyone notice that the liferea website main page seem to be broken?

**Comment by minhja** [comment]
Anyone had some luck with modifying the liferea.css file?

**Comment by sjehuda** [comment]
> Anyone had some luck with modifying the liferea.css file?

@minhja editing CSS would solve this issue only on the visual level.

We might be able to utilize XPath for this task.

**Comment by Perflyst** [comment]
Any updates here? Or is this a wont fix?

**Comment by lwindolf** [comment]
I extended the webkit-settings plugin (available in the plugin installer) with an "Auto-Load images" check button. While it is a quite hidden setting I believe it solves the use case of globally disabling download and display of images.

**Comment by Perflyst** [comment]
Where can we find this plugin? It is not visible in Liferea itself and not available here: https://github.com/lwindolf/liferea/tree/master/plugins

**Comment by Leiaz** [comment]
@Perflyst It is in the list of plugins of the "Plugin installer" plugin. The "Plugin installer" plugin ships with Liferea. When you enable it, you have a "Install plugins" item in the "Tools" menu. This lets you download and install other plugins that don't ship with Liferea.

The webkit setting disables automatic loading of images but doesn't give you a nice GUI to pick and choose which images to load. They load or they don't.

**Comment by Perflyst** [comment]
I don't have a plugin installer in my plugins list.

There is only "GNOME Keyring Support" and "Media Player". I am on v1.10.17

**Comment by Leiaz** [comment]
You are using a very old version of Liferea, those plugins won't work with it.

You should be able to compile the newest release even on an older distro (minimum is Debian 8).
