### ISSUE TITLE
[Plugin Request] Feed Builder/Scrapper

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#165]
A plugin to scrap pages into feeds instead of using site-specific scripts provided at https://kiza.eu/software/snownews/snowscripts/

See also http://createfeed.fivefilters.org/
* Look for links inside HTML elements whose id or class attribute contains:
[e.g. entry-title]
* Only keep links if link URL contains:
[e.g. /article/]

**Comment by GreenLunar** [comment]
Please open a new repository for plugins (e.g. liferea-plugins) or add a new label (like bug, enhancement, help-wanted) called plugin, for issues that plugin may be the most appropriate way to solve them.

**Comment by lwindolf** [comment]
Done.

Personally for this type of request I believe a GIR plugin does not work

**Comment by GreenLunar** [comment]
What is GIR?

**Comment by lwindolf** [comment]
GIR is probably the wrong abbreviation. I think GI would be more correct. Please have a look at https://wiki.gnome.org/Projects/GObjectIntrospection

**Comment by GreenLunar** [comment]
> Done.

Done a label or a repository?

**Comment by lwindolf** [comment]
Label

**Comment by GreenLunar** [comment]
PThen please label this issue.

**Comment by GreenLunar** [comment]
Please label this issue.

**Comment by pizzamaker** [comment]
Sounds good!

**Comment by GreenLunar** [comment]
@pizzamaker Do you know a developer who would want to add this feature?

**Comment by pizzamaker** [comment]
Alas, I do not.

**Comment by mozbugbox** [comment]
See also:
* nukehtml: https://gitlab.com/mozbugbox/nukehtml

**Comment by GreenLunar** [comment]
Thank you.  I will try it!

**Comment by GreenLunar** [comment]
@mozbugbox, aside from content that coordinates with XMLHttpRequest, which requires Javascript to be revealed, did you think of utilizing [Libxml2], as a scrapping engine, to get this work done?

I think XPath expressions would be good to locate items.
https://www.w3.org/TR/xpath/
https://www.w3.org/TR/xpath-3/

XPath is easy; The difficulty is how to program the front-end for end-users.

[Libxml2] http://xmlsoft.org/
[XPath] http://xmlsoft.org/examples/xpath1.c
