### ISSUE TITLE
[Feature request] Make liferea compatible with FreshRSS Google Reader based API

### ISSUE THREAD

**Issue by PodCol** [lwindolf/liferea#172]
FreshRSS is a self-hostable RSS agregator that tries to be lightweight. It is quite popular, at least in the french community. See https://github.com/FreshRSS/FreshRSS

FreshRSS tries to implement a Google Reader based API. See https://github.com/FreshRSS/FreshRSS/issues/443 and https://github.com/FreshRSS/FreshRSS/blob/beta/p/api/greader.php

**Comment by lwindolf** [comment]
I understand the wish, still there are so many online services it is impossible to support them all.

**Comment by GreenLunar** [comment]
Future plan for Liferea is to move all online source subscription support into Python plugins that can be easily copied/adapted to other online services. See https://github.com/lwindolf/liferea/issues/338#issuecomment-218602690
