### ISSUE TITLE
Combined view not showing media files

### ISSUE THREAD

**Issue by cesar-rickinho** [lwindolf/liferea#175]
While using the combined view option I couldn't see the media items that the news had.

I was able to see the media items on the other views, and play them.

Using openSUSE Tumbleweed and Liferea Version 1.10.14.

![captura de tela de 2015-04-14 14-42-40](https://cloud.githubusercontent.com/assets/11948362/7143785/b0a5e5ac-e2b7-11e4-9044-30fa6b711aae.png)
![captura de tela de 2015-04-14 14-42-27](https://cloud.githubusercontent.com/assets/11948362/7143790/b6eb9d58-e2b7-11e4-9c84-39235080402a.png)

**Comment by lwindolf** [comment]
Closing this ticket as the combined view is being removed in 1.13
