### ISSUE TITLE
liferea: poor error reporting for "command" sourced feeds

### ISSUE THREAD

**Issue by marceloslacerda** [lwindolf/liferea#179]
Bug upstreamed from debian bts:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779967

Liferea 1.10.12

When feeds generated by a command fail to produce a working feed, the
error messages are both misleading and useless. Pretty much no matter
what the problem is, it outputs:

>    The last update of this subscription failed!
>    There were errors while parsing this feed!
> 
>    Details
> 
>    Could not detect the type of this feed! Please check if the source
>    really points to a resource provided in one of the supported
>    syndication formats!
> 
>    XML Parser Output:
> 
> ```
>    The URL you want Liferea to subscribe to points to a webpage
>    and the auto discovery found no feeds on this page. Maybe this
>    webpage just does not support feed auto discovery.Source points
>    to HTML document.
> ```
> 
>    You may want to contact the author/webmaster of the feed about
>    this!

(Strangely, that error even sometimes included saying that it got an
HTTP 404 which makes no sense for a local resource.)

My understanding is that once Liferea fails to parse an input as a feed,
it tries to parse it as a webpage that has a link to a feed and it only
reports the error for the second failure, despite the first failure
almost always being the relevant one.

As a workaround, using the same command as a conversion filter (not
caring what the input being "filtered" is) gives more useful errors. In
case that led to this bug report, telling me that the command was
returning an exit code of 1 (although actually seeing the error message
in output would have been more helpful).

This is a very minor issue because in addition to the workaround just
mentioned, I suspect this is a rarely used feature and except in edge
cases like the one I ran into (it turned out the script worked with my
bash environment variables but not with my X session's), simply running
the command from a terminal would give the desired debugging
information.

**Comment by lwindolf** [comment]
I agree the error handling is not helping much at all. Simply displaying "There was an error" is almost as informative. This surely warrants a refactoring of the code.
