### ISSUE TITLE
Sync with ownCloud

### ISSUE THREAD

**Issue by jancborchardt** [lwindolf/liferea#18]
Hey @lwindolf :)

It would be cool if Liferea would support sync with [ownCloud](http://owncloud.org) next to The Old Reader and Tiny-Tiny-RSS.

ownCloud has a News app: http://apps.owncloud.com/content/show.php?content=158434
And that News app has an API: https://github.com/owncloud/news/wiki/API-1.2

There’s already great sync clients for Android and iOS, so now it would be cool to have one for Linux. :)

cc'ing the ownCloud News devs @Raydiation @cosenal

**Comment by 6ahodir** [comment]
I've started working on this. Contributors are welcome: https://github.com/6ahodir/liferea-owncloud-news

**Comment by jancborchardt** [comment]
@6ahodir awesome! Feel free to spread the word on the ownCloud users/developers mailing lists. :)

**Comment by lwindolf** [comment]
@6ahodir Great to hear. If you need help with the liferea code base please drop a mail.

**Comment by 6ahodir** [comment]
@jancborchardt, thanks for the heads up.
@lwindolf, thanks for offering help. I will definitely ping you soon. ;)

**Comment by cosenal** [comment]
@6ahodir is there something working that I can try already?

**Comment by 6ahodir** [comment]
@cosenal, unfortunately, no. But keep an eye on the repo, hopefully we'll have something working in a couple of weeks.

**Comment by lwindolf** [comment]
@6ahodir: With above change a new plugin interface is expose allowing to register plugins providing new "Sources". The plugin boiler-plate would look like this:

    from gi.repository import GObject, Peas, PeasGtk, GLib, Gtk, Liferea
    class OwnCloudPlugin(GObject.Object, Liferea.NodeSourceActivatable):
    __gtype_name__ = 'OwnCloudPlugin'

    object = GObject.property(type=GObject.Object)

    def __init__(self):
        # Setup a feed subscription type (for updating single feeds)
        self.fst = Liferea.subscriptionType.new()
        self.fst.prepare_update_request = ...
        self.fst.process_update_request = ...

        # Setup source subscription type (for updating the list of feeds)
        self.sst = Liferea.subscriptionType.new()
        self.sst.prepare_update_request = ...
        self.sst.process_update_request = ...

        self.nst = Liferea.nodeSourceType.new()
        self.nst.id = 'fl_owncloud'
        self.nst.name = 'OwnCloud'
        self.nst.capabilities = Liferea.NODE_SOURCE_CAPABILITY_DYNAMIC_CREATION + 
                                          Liferea.NODE_SOURCE_CAPABILITY_ADD_FEED +
                                          ...
        self.nst.feedSubscriptionType = self.fst
        self.nst.sourceSubscriptionType = self.sst
        self.nst.method1 = ...
        self.nst.method2 = ...
        ...

    def do_activate (self):
        Liferea.node_source_type_register (self.nst)

(Note: entirely untested)
