### ISSUE TITLE
[Minor] Inconsistent use of config.h to cause conflicting types

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#182]
Forwarded bug from Debian. [ I am not sure if this is still an issue, but better safe than sorry ]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=749900

Reported against Liferea Version 1.10.8

During a rebuild of all Debian packages in a clean sid chroot (using cowbuilder and pbuilder) the build failed with the following error. Please note that we use our research compiler tool-chain (using tools from the cbmc package), which permits extended reporting on type inconsistencies at link time.

[...]
libtool: link: gcc -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wl,-z -Wl,relro -Wl,-z -Wl,now -o liferea auth.o auth_activatable.o browser.o browser_history.o comments.o common.o conf.o date.o db.o dbus.o debug.o e-date.o enclosure.o export.o favicon.o feed.o feed_parser.o feedlist.o folder.o html.o htmlview.o item.o item_history.o item_loader.o item_state.o itemset.o itemlist.o json.o metadata.o migrate.o net.o net_monitor.o newsbin.o node.o node_type.o plugins_engine.o render.o rule.o social.o subscription.o update.o main.o vfolder.o vfolder_loader.o xml.o -pthread -Wl,--export-dynamic -pthread  -Wl,--as-needed parsers/libliparsers.a fl_sources/libliflsources.a ui/libliui.a webkit/libwebkit.a -lxslt -lxml2 /usr/lib/x86_64-linux-gnu/libsqlite3.so -lgthread-2.0 -lwebkitgtk-3.0 -lsoup-2.4 -ljavascriptcoregtk-3.0 -ljson-glib-1.0 -lpeas-gtk-1.0 -lpeas-1.0 -lgmodule-2.0 -lgirepository-1.0 notification/libnotify.a -lnotify -lindicate-gtk3 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 /usr/lib/x86_64-linux-gnu/libcairo-gobject.so /usr/lib/x86_64-linux-gnu/libcairo.so -lgdk_pixbuf-2.0 -lgio-2.0 -lindicate -lgobject-2.0 -lglib-2.0 -ldbusmenu-glib -pthread

error: conflicting function declarations "e_utf8_strftime_fix_am_pm"
old definition in module date file e-date.h line 28
unsigned long int (char *, unsigned long int, const char *, struct tm *)
new definition in module e-date file e-date.c line 97
unsigned long int (char *s, unsigned long int max, const char *fmt, const struct tm *tm)

reason for conflict at tm->__tm_gmtoff in types listed below (struct/struct):
names of component 10 differ (__tm_gmtoff/tm_gmtoff)
struct tm {
  signed int tm_sec;
  signed int tm_min;
  signed int tm_hour;
  signed int tm_mday;
  signed int tm_mon;
  signed int tm_year;
  signed int tm_wday;
  signed int tm_yday;
  signed int tm_isdst;
  unsigned int $pad0;
  signed long int __tm_gmtoff;
  const char * __tm_zone;
}
struct tm {
  signed int tm_sec;
  signed int tm_min;
  signed int tm_hour;
  signed int tm_mday;
  signed int tm_mon;
  signed int tm_year;
  signed int tm_wday;
  signed int tm_yday;
  signed int tm_isdst;
  unsigned int $pad0;
  signed long int tm_gmtoff;
  const char * tm_zone;
}
Makefile:618: recipe for target 'liferea' failed
make[4]: *** [liferea] Error 64
make[4]: Leaving directory '/srv/jenkins-slave/workspace/sid-goto-cc-liferea/liferea-1.10.8/src'
Makefile:799: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1

While identical at the bit level, the C standard mandates that the identifiers of each component match for types to be compatible. The differences here are caused by config.h being included here:

http://sources.debian.net/src/liferea/1.10.8-1/src/e-date.c?hl=25#L25

while it is missing from src/date.c. Instead that file has this

http://sources.debian.net/src/liferea/1.10.8-1/src/date.c?hl=35#L35

which, however, only enabled a subset of _GNU_SOURCE that would be defined in config.h.

**Comment by lwindolf** [comment]
Fixed in 1.10 and 1.11
