### ISSUE TITLE
[i18n] Plugins are not subjected to language localization

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#187]

**Comment by lwindolf** [comment]
You mean any specific plugins should be translated? Or do you mean that there is no mechanism to translate plugin literals?

**Comment by GreenLunar** [comment]
There is no mechanism to translate plugin.

Maybe, plugins should be named in form `liferea-pluginame`, so a separate `.mo` be made for each  plugin, in order to make it possible for external Liferea plugins to be available in different locales.

**Comment by lwindolf** [comment]
Was found to be invalid in #203
