### ISSUE TITLE
dont hide latest articles read until i refresh view

### ISSUE THREAD

**Issue by voidplayer** [lwindolf/liferea#190]
its very common to misclick one line and then the current one is gone!

Or that you want to go back to a line you just read a few secs ago

You gotta be careful where you click on liferea or you won't even know what line you just hide by accident

I think it would be nicer to mark it as read but only hide it from the view when i click the feed entry again or the refresh button

**Comment by GreenLunar** [comment]
Good idea.

**Comment by lwindolf** [comment]
@voidplayer I see the problem. One mitigation was done by adding the item history feature, so once you accidentally click away, you can use the history to find the item again.

The idea of not immediately hiding the items can be activated in the preferences dialog (with the exception for the Unread folders).

With two features already existing to mitigate this effect I consider this as won't fix. I hope you agree!

**Comment by GreenLunar** [comment]
> @voidplayer I see the problem. One mitigation was done by adding the item history feature, so once you accidentally click away, you can use the history to find the item again.

But user is booted out of the folder and is directed to the source feed, which is not desirable.

**Comment by voidplayer** [comment]
i kinda agree with @GreenLunar

I  do still consider this weird behaviour a bug, even with the history button...

but as a user, it is only a suggestion. Is for the developer to tell if this a bug or a feature :)
