### ISSUE TITLE
add source popup visually broken

### ISSUE THREAD

**Issue by k0377** [lwindolf/liferea#194]
I'm trying to add my tiny tiny rss as source to liferea. When I go to `Abonnements -> Neue Quelle...` some window pops up, but the list is visually hidden, as I still can tab trough and choose the type with the cursor keys blind.

![bildschirmfoto vom 2015-05-31 11-28-50](https://cloud.githubusercontent.com/assets/1057526/7901449/61bdfcae-0788-11e5-8a51-a2bde6e22c9f.png)

**Comment by lwindolf** [comment]
Is this git master or another version?

**Comment by soerenk** [comment]
Using 1.10.16 with ArchLinux I can confim the issue.

**Comment by DragoonAethis** [comment]
On Arch as well, 1.10.16 with Gtk+3 3.16.6, Numix theme, broken as well. Using git master, this is fixed.

**Comment by criztovyl** [comment]
1.10.16 on Debian Sid, GTK+3 3.16.6-1, broken too
