### ISSUE TITLE
Disable overlay scrollbar

### ISSUE THREAD

**Issue by Yenya** [lwindolf/liferea#197]
I have just upgraded to Fedora 22 (liferea 1.10.15), and now the left column of the liferea window (the list of feeds) has its scrollbar autohiding, This means that as soon as I move the cursor to this column, the scrollbar appears and covers the rightmost area of the column with the numbers of unread items for each feed. It is extremely annoying.

I run XFCE and the Clearlooks-Phenix GTK3 theme, and liferea is the only application with this behavior. How can make the scrollbars in liferea use its dedicated screen space? Thanks!

**Comment by asl97** [comment]
screenshot always helps

**Comment by Yenya** [comment]
Here you are.

![liferea](https://cloud.githubusercontent.com/assets/1055951/7963925/7a5680e4-0a15-11e5-955e-f10a6fc9be9e.png)

**Comment by GreenLunar** [comment]
OFF TOPIC (this post will be deleted)

@Yenya 

RE: http://www.fi.muni.cz/~kas/blog/index.cgi/computers/desktops/gnome-only-apps.writeback

Atril as document viewer
Engrampa as archive manager
Eye of MATE as graphics viewer

For more, see links below:
http://mate-desktop.org/
https://github.com/mate-desktop/
https://wiki.archlinux.org/index.php/MATE

**Comment by lwindolf** [comment]
The auto-hiding of the scrollbar doesn't come from the Liferea code. The GTK settings set by Liferea is just automatic toolbars on overflow. Hiding is a theme property that we cannot control. I have no problems on Debian 7, Ubuntu 14.10/15.04 and different MATE versions.

**Comment by Yenya** [comment]
Well, the problem is that no other application in my desktop has the same problem, even though there are both GTK2 and GTK3 apps. So liferea has to do something differently than other GTK apps. Also, it is not theme-specific: I have verified that the default theme in Fedora - Adwaita - behaves the same in liferea.

**Comment by Yenya** [comment]
I have filled the downstream bug in Fedora for this issue. For the reference, it is https://bugzilla.redhat.com/show_bug.cgi?id=1234340
