### ISSUE TITLE
Add Pocket support

### ISSUE THREAD

**Issue by Mno-hime** [lwindolf/liferea#199]
Since Firefox 38.0.5 added Pocket support (https://getpocket.com/) I thought of using it. Having it integrated with Liferea's Bookmarks would be helpful.

**Comment by lwindolf** [comment]
If Pocket allows placing bookmarks via a HTTP GET call it can be implemented. Can you investigate this?

Please check out the code in src/social.c, you might want to add a line there.

Closing this ticket as it is a feature request.

**Comment by Mno-hime** [comment]
Pocket is unfortunately POST only (also I am not interested in Pocket anymore since I realized I am quite happy with Save-To-Read Firefox addon). Sorry for the feature request.

**Comment by mathew42** [comment]
_Note: I'm not asking for this issue to be re-opened, as I apreciate it is a feature request. I'm adding this for others who want integration with pocket to find._

I was able to implement this feature by:

1. Downloading the [pocket-cli python script](https://github.com/dadrc/pocket-cli)
2. Run the script to configure oauth
3. In preferences changing the External Browser Settings to Manual
4. Set the "Manual:" text field to `python <path-to-script>/python-cli.py -a %s`

Obviously the drawback of the approach is that you cannot view the article in an external browser, but I find the internal browser adequate the majority of the time.

**Comment by lwindolf** [comment]
@mathew42 Thanks for this hint. I blogged about it here: https://lzone.de/liferea/blog/How%20to%20use%20Liferea%20with%20Pocket

**Comment by uriel1998** [comment]
Another solution (as I just saw all this, and *do* use the external browser) is to use the social bookmarking feature in combination with IFTTT. I currently have mine set to delicious, and then have an IFTTT recipe that then saves it to Pocket. (You could also use Instapaper -> Pocket, or other channels of that sort).

**Comment by GreenLunar** [comment]
Do not fall to another Mozilla trap that yet again suggests of web services that contradict its alleged "freedom" doctrine; use [free alternatives](https://prism-break.org/en/subcategories/servers-bookmark-sync/).

**Comment by uriel1998** [comment]
I don't think offering the *option* of using Pocket is somehow bad.
Offering other options right alongside seems a better option.

**Comment by GreenLunar** [comment]
Yes, you are correct.

Problem with such services is that they either do not provide a sensible API, if any, or do not provide a data import/export option for easier migration to other services.
