### ISSUE TITLE
After closing the search window results just disapear - please leave them there

### ISSUE THREAD

**Issue by tpo** [lwindolf/liferea#200]
So here's what I do:

I'm displaying some RSS feed. I press CTRL-F to search some posting, the search pop-up appears in the middle of the screen/window, I type in the search sting and type Return. The postings window at the top gets empty and results start appearing.

Wanting to read one of the postings I close the search pop-up to be able to click on the wanted postingm but - at the moment I close the pop-up, all search results disappear and I am left without anything.

There might be a reason for this behavior but, to me as a user it is completely unexpected/weird.

I think leaving the results there after closing the search pop-up would be more natural.

**Comment by asl97** [comment]
i agree too but:
http://lzone.de/liferea/faq.htm#feature-x

**Comment by lwindolf** [comment]
@tpo I understand the use case, still for simplicity the lifetime of the result set of items is tied to the view displaying them. And to have a fixed point in the control flow to clean it up we do it on dialog close.

**Comment by asl97** [comment]
if the search result is in the close dialog, the behavior would be expected.
however, would it be weird to do it that way?

or maybe embed the search dialog into the main window,  that should look ok.

**Comment by lwindolf** [comment]
@asl97 The first variant isn't suitable as the item list by design is a singleton.

The 2nd variant would be a possibility. It was like this in the past...
