### ISSUE TITLE
Use .desktop instead of .plugin

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#203]
media-player.plugin
```
[Plugin]
Module=media-player
Loader=python
IAge=2
Name=Media Player
Description=Play music and videos directly from Liferea
Authors=Lars Windolf <lars.lindner@...>; Simon Kagedal Reimer <skagedal@...>
Copyright=Copyright © 2012 Lars Windolf
Website=http://lzone.de/liferea/
Help=http://lzone.de/liferea/
```

media-player.desktop
```
[Desktop Entry]
Name=Media Player
Name[de]=
Comment=Play music and videos directly from Liferea
Comment[de]=
Icon=media-playback-start
Type=Plugin
X-Liferea-Module=media-player
X-Liferea-Loader=python
X-Liferea-IAge=2
X-Liferea-Authors=Lars Windolf <lars.lindner@...>; Simon Kagedal Reimer <skagedal@...>
X-Liferea-Copyright=Copyright © 2012 Lars Windolf
X-Liferea-Website=http://lzone.de/liferea/
X-Liferea-Help=http://lzone.de/liferea/
```

Notes:
`Type=Plugin` is made up. There is `Type=Application` and `Type=Link`.
I prefer `Icon=audio-x-generic` over `Icon=media-playback-start`.
Maybe `Exec` should replace `X-Loader`.

**Comment by GreenLunar** [comment]
This solves, partially, issue #187.

**Comment by asl97** [comment]
https://wiki.gnome.org/Apps/Gedit/PythonPluginHowTo

it the same as (gedit and) the link above and i quote below
____
**examplepy.plugin**

```
[Plugin]
Loader=python
Module=examplepy
IAge=3
Name=Example py
Description=A Python plugin example
Authors=Jesse van den Kieboom <jesse@icecrew.nl>
Copyright=Copyright © 2006 Jesse van den Kieboom <jesse@icecrew.nl>
Website=http://www.gedit.org
```

**Comment by GreenLunar** [comment]
I did not know about that.  Do they propose on a way to localize plugin stirrings?

**Comment by lwindolf** [comment]
@GreenLunar According to libpeas documentation the file extension has to be .plugin: https://developer.gnome.org/libpeas/1.14/PeasPluginInfo.html

**Comment by lwindolf** [comment]
I found the solution. It already works :-)

According to the libpeas documentation the .plugin syntax is GKeyFile syntax (https://developer.gnome.org/libpeas/1.14/PeasPluginInfo.html) which according to the GKeyFile documentation is following the .desktop specification.

Did you test without renaming the files? Because this works for me. Just write

     Name=My Plugin
     Name[de]=Mein Plugin

in the .plugin files to get proper translations. Feel free to make a PR with your favourite translations :-)

**Comment by GreenLunar** [comment]
> Feel free to make a PR with your favourite translations :-)

Do we have to do this manually or is it possible to use gettext to generate a .pot file for .plugin and .py files?

**Comment by lwindolf** [comment]
This needs to be done manually (same as with the desktop files) as there is no gettext hook in the plugin loading in libpeas.
