### ISSUE TITLE
"Error resolving 'example.com': No address associated with hostname" after resume from suspend

### ISSUE THREAD

**Issue by Mno-hime** [lwindolf/liferea#204]
After resume from suspend liferea kicks in and tries to automatically update feeds. It generally results in most of the feeds marked as "failed to update" and appropriate icon is presented instead of the feed-specific one.

![failedfeedupdate](https://cloud.githubusercontent.com/assets/4632197/8272837/b44050c2-1853-11e5-867b-2ff6ad2a3214.png)

In the log I can see e.g.:

```
< HTTP/1.1 2 Error resolving 'malakim.cz': No address associated with hostname
< Soup-Debug-Timestamp: 1434909389
< Soup-Debug: SoupMessage 0 (0x199ce70)
  
NET    : download status code: 2
NET    : source after download: >>>http://malakim.cz/feed/<<<
NET    : 0 bytes downloaded
```

And many other similar ones.

Shouldn't liferea check with the environment (Fedora's GNOME in my case) to make sure internet connection is present and postpone the feed update otherwise?

**Comment by lwindolf** [comment]
Thank you for reporting this. I think I know what is happening. First: Liferea implements a network monitor using DBUS and is registered for NetworkManager state changes.

If your laptop is opened and there is no signal from NetworkManager to Liferea that your laptop is offline Liferea cannot know and will try to update all feeds.

I actually do not really see this as a problem. There is no data loss and a good visual indication of the problem which auto-fixes itself once you are online again.

To solve your problem I suggest to check if your NetworkManager is working properly upon resume.
