### ISSUE TITLE
HTTP error code 0: There was an internal error in the update process

### ISSUE THREAD

**Issue by eternal-sorrow** [lwindolf/liferea#207]
Since yesterday Liferea refuses to update any feed in my list with this error. My internet connection is OK, feed host is accessible.

**Comment by lwindolf** [comment]
Sorry, this is not enough information to help you. 

One possible cause could be your proxy configuration (Tools/Preferences).

**Comment by eternal-sorrow** [comment]
I do not use proxy. For now this problem is gone, so I'm closing this issue. Will reopen it if problem returns.
