### ISSUE TITLE
Add image icons to plugins

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#209]
media-player.plugin
Icon=audio-x-generic

libnotify.plugin
Icon=preferences-system-notifications

gnome-keyring.plugin
Icon=security-medium

trayicon.plugin
Icon=preferences-desktop-accessibility

**Comment by lwindolf** [comment]
Thanks. Nice improvement.

I think the way to change multiple files via GUI is to fork, edit all three of them and the PR it.

**Comment by GreenLunar** [comment]
One Pull Request with several commits #211.  GitHub staff need to provide an ability to turn several commits into a single commit.
