### ISSUE TITLE
Disable cache does not work

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#213]
Option: Feed/Properties/Archive/Disable cache

Disable cache appears to be doing the same as Unlimited cache.

"Disable cache" is useful with subscriptions of current *currency rate* or *weather* or *available jobs* or even of limited stock of second-hand products.

**Comment by lwindolf** [comment]
I totally agree. 

But what is this ticket about?

**Comment by GreenLunar** [comment]
This ticket is noting that *Disable cache* does not work.

**Comment by GreenLunar** [comment]
> "Disable cache" is useful with subscriptions of current currency rate or weather or available jobs or even of limited stock of second-hand products.

Also to check the results of a query with searx https://searx.me/?q=liferea&format=rss&category_general=1&pageno=1

**Comment by GreenLunar** [comment]
This is a bug.

**Comment by GreenLunar** [comment]
@Leiaz do you know how to correct this problem?

**Comment by Leiaz** [comment]
The size of the cache determines how many items to keep when merging. You could check the cache setting in the merge code and only keep as many as you have fetched to merge (hacky, breaks if the feed remove newer items before older ones), or remove the items you have which aren't in the set you just fetched (require more changes to merge code). But both will break if the server supports deltas and only sends items you don't have, so you'd have to modify that too ...
