### ISSUE TITLE
Permanent icon on a button

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#214]
Button: Search/Search All Feeds.../Advanced.../Search Folder...

*Search Folder...* button always has a *gtk-add* stock icon (deprecated), even when `.config/gtk-3.0/settings.ini` has `gtk-button-images` set to `0`.

**Comment by lwindolf** [comment]
I understand what you mean, but I fail to get the impact of this.

**Comment by GreenLunar** [comment]
I just like not to have icons on text buttons, it looks more elegant, to me.

Icons alone on buttons are fine by me, though, but this is off topic.

**Comment by lwindolf** [comment]
I understand. Will be fixed once all deprecations for GTK 4 are resolved.

**Comment by GreenLunar** [comment]
Some people suggest that this is a GTK+ bug.  See https://github.com/geany/geany/issues/987
