### ISSUE TITLE
[Media Player] Standard Icon Naming Specification

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#215]
Stock|Standard
---|---
gtk-media-play|media-playback-start
gtk-media-pause|media-playback-pause
gtk-media-previous|media-skip-backward
gtk-media-next|media-skip-forward

See http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html

**Comment by lwindolf** [comment]
Good point. Can you make a pull request?

**Comment by GreenLunar** [comment]
I do not know how I should modify this plugin. @mozbugbox, would you like to do it?  This is not an urgent thing.

**Comment by GreenLunar** [comment]
@glitsj16, would you like to do it?

**Comment by glitsj16** [comment]
@GreenLunar: sure, glad to help out. I'll do some testing and will report back.

**Comment by GreenLunar** [comment]
Thank you very much!

@lwindolf, I suggest to add a tag called "easy-fix" for people who are willing to bother for smaller contributions; this issue, for instance, is an appropriate issue to be marked as such.

**Comment by glitsj16** [comment]
@GreenLunar: proposed fix is available in a seperate branch so you (and other people) can test it: https://github.com/glitsj16/liferea/tree/fix-%23215
Looking good here with my custom theme :-) Thanks for pointing me to this.

I've been using liferea for several years now, and if my current skill-set permits making these kind of smaller contributions, I'm willing to contribute. Having such an "easy-fix" tag surely would make triage easier.

**Comment by GreenLunar** [comment]
Thank you, glitsj16.

There are two icon enhancement I proposed at #241 and #251, the latter is is a new form of #242 so it won't get closed.

I have proposed several slight changes in most recent issues I have opened. See https://github.com/lwindolf/liferea/issues?q=is%3Aissue+is%3Aclosed+author%3AGreenLunar

**Comment by GreenLunar** [comment]
@lwindolf, please reopen this issue.

**Comment by GreenLunar** [comment]
@glitsj16, please send a pull request.

**Comment by glitsj16** [comment]
@GreenLunar, the pull request for this got merged some time ago https://github.com/lwindolf/liferea/pull/266.

**Comment by GreenLunar** [comment]
Sorry.  Thank you for the reference.

@glitsj16, please contact me at genghiskhan@gmx.ca
