### ISSUE TITLE
[i18n] Untranslatable strings

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#216]
Three strings:

* Cancel
* Delete
* Saved Search

**Comment by lwindolf** [comment]
Thanks for the hint!

**Comment by GreenLunar** [comment]
Please update PO files.

**Comment by GreenLunar** [comment]
* Remove

See dialog Search Folder Properties.

**Comment by GreenLunar** [comment]
String in `liferea.ui`
* Developers:
* Contributers: Code, Patches, Debugging
* and many more...

**Comment by GreenLunar** [comment]
P.S. Contributers > Contributors
