### ISSUE TITLE
[gnome-keyring] Hide warning message

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#219]
The following message should be hidden when plugin *gnome-keyring* is enabled and working properly.

Note: *The username and password will be saved to your Liferea feedlist*
*file without using encryption.*

**Comment by GreenLunar** [comment]
@asl97 is the above feasible using Libpeas API?

**Comment by asl97** [comment]
i rather keep all warning about username and password shown than hiding them.

in any case, it is embedded into the ui, it might be possible but i don't recommend editing the ui through the plugin system.

**Comment by GreenLunar** [comment]
> i rather keep all warning about username and password shown than hiding them.

Would you prefer to have the text replaced by "Your credentials will be encrypted with gnome-keyring" or "Your credentials will be encrypted with kwallet"?
