### ISSUE TITLE
My feeds are being overwritten

### ISSUE THREAD

**Issue by bojs** [lwindolf/liferea#222]
I've validated my XML with a few online checks, so I suppose it's not that. Like a cancer, my feeds get overwritten, gradually one by one with some 'universeofluxury' feed.

**Comment by asl97** [comment]
you didn't post your feed nor the 'universeofluxury' feed.

we don't have anything to work with to find out what's wrong.

**Comment by bojs** [comment]
Well I suspect it's not the xml since I validated it with http://www.w3schools.com/xml/xml_validator.asp and http://www.xmlvalidation.com/

I'd rather not post my feed for privacy reasons.

Is there nothing else I could provide?

**Comment by asl97** [comment]
the only thing i can think of without the data is conflicting id or something.

**Comment by bojs** [comment]
iconosquare.com/feed/teciatorres

all of these feeds seem to double, tripple, quadruple up and often have 'new' posts from months ago

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
