### ISSUE TITLE
Notifications under GNOME 3.16

### ISSUE THREAD

**Issue by DoctorJellyface** [lwindolf/liferea#225]
They work fine, but not in the notification/calendar menu. When you click on there, nothing happens (liferea should open with the feed in the notification) and all the Liferea notifications underneath get closed!

**Comment by asl97** [comment]
imo, this seem like a feature request, see: http://lzone.de/liferea/faq#feature-x

the file is here: https://github.com/lwindolf/liferea/blob/master/plugins/libnotify.py

i don't blame you for not knowing about it, the website main page is broken

**Comment by DoctorJellyface** [comment]
Why is this a feature request? It's existing functionality being broken?

**Comment by asl97** [comment]
it never existed before afaik.

**Comment by DoctorJellyface** [comment]
I mean support for notifications. They need to be changed only slightly to work once more.

**Comment by asl97** [comment]
there is already support for notification, it's in the form of a plugin,  when a new feed is receive, it should pop up,  and as you said, when you click it, it close and doesn't open the feed.  that is how it always works.

if you want it to open the feed when you click the notification, as the faq as stated: `please take the time to write a patch `

**Comment by DoctorJellyface** [comment]
Well, partly. The other thing is that clicking on closes all that appeared before it, which is weird.

> if you want it to open the feed when you click the notification, as the faq as stated: `please take the time to write a patch`

Well, I'm on a new machine and I'm thinking of switching to GNOME News to get a purer GNOME experience. I don't know whether I'll be using Liferea. I just reported this so that other users could get a fix.

**Comment by GreenLunar** [comment]
Is [this](https://wiki.gnome.org/Design/Apps/Potential/News) GNOME News?

I recently installed Salix Mate 14.1 on a new machine of my sister, and I thought of installing KDE or Xfce, but anti-standard GNOME3 was not on my mind.  Eventually, obviously, I have installed MATE, because it was a new machine.

Today, every component of MATE can now be built with GTK2 and GTK3, though GTK3 support is still considered experimental.

Consider using MATE http://mate-desktop.org/

**Comment by DoctorJellyface** [comment]
OK, so it turns out that a750715 fixes this! The original bug report was #90. So my half-an-hour hacking session was laid to waste. But at least I learnt some stuff, like what an GObject introspection is, and refreshed some of my python skills. Ah well.

@GreenLunar yeah, that's GNOME News, it's in very early alpha and not yet usable for daily use, as I found out. I do know about MATE, but my heart has grown too attached to GNOME for me to change (ever probably, unless GNOME dies, which I hope it doesn't).

**Comment by DoctorJellyface** [comment]
And btw I had to build liferea from git to get the fix.
