### ISSUE TITLE
Feedburner feeds — including the official Liferea blog — have no timestamps and thus constantly reset

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#226]
Image says it all, mostly:

![liferea feedburner broken timestamps](https://cloud.githubusercontent.com/assets/479401/9020274/4e852d10-37d0-11e5-9fc6-1ac8664b9a74.png)

The issue occurs with feeds such as
http://rss.slashdot.org/Slashdot/slashdotLinux
http://feeds.feedburner.com/LifereaBlog

There's gotta be a way to do something about this? The blog posts from "Liferea's blog" keep shifting their timestamps to whatever last time I opened Liferea and triggered a refresh...

**Comment by asl97** [comment]
that is cause the feed doesn't contain the time, there no way to do anything about it.

but the time shouldn't be shifting after it got the added to the database.

**Comment by lwindolf** [comment]
Yup. I need to fix this.

**Comment by lwindolf** [comment]
Finally got to fix this.
