### ISSUE TITLE
Add tooltips to navigation buttons

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#230]
Previous
*Go back one item*

Next
*Go forward one item*

Next Unread Item
*Go to next unread item*
*Display next unread item*

**Comment by GreenLunar** [comment]
Next Unread Item
*Go to next unread item*
*Display next unread item*

**Comment by lwindolf** [comment]
There are intentionally no tooltips. The reason being the use case when you use "Next Unread" or "Next" via mouse button. The tooltip would pop up after each click anew. Quite disturbing.

Usability is actually higher without tooltips.
