### ISSUE TITLE
[Media Player] Segmentation fault upon end of playing of an audio file

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#231]
Liferea 1.11.5 crashes after it is done playing an audio file of feed http://feeds.kexp.org/kexp/songoftheday which is listed in */opml/feedlist_en.opml*

**Comment by lwindolf** [comment]
Any GStreamer messages/assertions visible when run from the command line?

**Comment by GreenLunar** [comment]
Nothing, just the following message appears 10 times at startup:
```
(liferea:30389): libsoup-WARNING **: (soup-uri.c:581):soup_uri_copy: runtime check failed: (SOUP_URI_IS_VALID (uri))
```
