### ISSUE TITLE
Sponsored News URLs [IMPORTANT]

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#233]
Before Mozilla has decided to support the centralization of the World Wide Web and and gradually killing RSS, which is immoral, it had a Web Feed (one feed for every locale) titled in English as Recent Headlines.  Below are several of these feeds and news websites who are currently paying to Mozilla for a redirect.
```
    Feed: http://fxfeeds.mozilla.com/de/firefox/headlines.xml
Redirect: http://www.**********.de/xml/rss2

    Feed: http://fxfeeds.mozilla.com/en/firefox/headlines.xml
Redirect: http://feeds.****.co.uk/news/rss.xml?edition=int

    Feed: http://fxfeeds.mozilla.com/ru/firefox/headlines.xml
Redirect: http://news.*******.ru/rss/head/
```
Unlike Mozilla, Liferea can, obviously, use more than a Web Feed, which means that the Liferea project may be payed on behalf of several feeds for a locale, not just (General) News, but for subtopics, too!

Of course, for Liferea to keep generating money from such URLs, this means that Liferea should have its automated URL update disabled in whole or only for sponsored feeds by adding an option to do so.

Also to add a menu to restore Liferea Default Feed List, similarly to a Restore Default buttons of search engine management dialog of some web browsers.

**Comment by GreenLunar** [comment]
@kfogel, what do you think of the above suggestion?

**Comment by GreenLunar** [comment]
Also to add a menu to restore Liferea Default Feed List, similarly to a Restore Default buttons of search engine management dialog of some web browsers.

**Comment by lwindolf** [comment]
@GreenLunar Liferea is not about sponsoring. Did never happen, won't happen.

About an option for restoring the default feed list: just remove ~/.cache/liferea and ~/.config/liferea and you have it again. Alternatively reimport the list from /usr/share/liferea/opml/... . I do not consider this a very important use case.

**Comment by GreenLunar** [comment]
What difference would it make?
If user is not interested then they can delete them at anytime.

The reason I suggested a GUI option for restoration of feeds is to have better chances to keep sponsored feeds for profit.

Mozilla RAM Cracker is not about sponsoring... OF COURSE IT IS, it has been since its start, from its default selection of search engines* to the aforementioned web feed to the "malware" and "phishing" websites mechanism spying for big G.

*Which its developers were rude enough to lie and claim that they have them by a genuine decision "for their users" (LIES! it was because MOST OF THEM PAYED TO MOZILLA).

I am about to send a PR for the Hebrew feed list which would have popular Israeli news websites which are really nonsensical and low quality.  I prefer Liferea to earn money from having such bad feeds.

I did not suggest a perversive spying on users, I did suggest to easily restore default feed list in a couple of clicks for profit.

THINK ABOUT SPONSORS.

**Comment by GreenLunar** [comment]
You may also add to welcome screen #236 a plain (not in secret, as the red lizard does it) note about these sponsored feeds and ask users to use these feeds to raise Liferea's revenue for insuring a continues and a product of higher quality over time.

**Comment by lwindolf** [comment]
@GreenLunar The feeds you refer to are not included in upstream. Please, please check the sources!!!

**Comment by GreenLunar** [comment]
What feeds?

**Comment by GreenLunar** [comment]
Are you referring to fxfeeds.mozilla.com?  I am not the administrator of that server, and I know about it be examining Latest Headlines Live Feed on Bookmarks bar.  As I stated above "Before Mozilla has ... and gradually killing RSS".  They are being paid to eliminate RSS.

**Comment by lwindolf** [comment]
Maybe I totally do not get the ticket.

1.) What is the symptom/problem in Liferea version xxxx?
2.) What is the expected behaviour?

**Comment by GreenLunar** [comment]
First, make a decision (yes/no), and then we can see how we continue on with this issue.

**Comment by lwindolf** [comment]
A decision on what exactly? You know this is an issue tracker. To track issues. Not to discuss political stuff. The best place for politics is the mailing list.

**Comment by GreenLunar** [comment]
I understand. I will start a discussion by email, then.

**Comment by asl97** [comment]
@GreenLunar you aren't making any sense

what is "Mozilla RAM Cracker"?
there isn't anything on google or ddg.

why does liferea need to generate money?
adding any kind of ads or whatnot to generate money will be the death of liferea,
downstream would most likely remove those money generating stuff even if they doesn't kill liferea.

why should liferea add more links?
as far as some users are concern, those (money making) links would most likely track and store information about them.

**Comment by GreenLunar** [comment]
1. I meant to the bloated product called Firefox.

2. If user does not ant sponsored feeds, URLs of Liferea, they can erase them.

3. I did not understand this question (more links).

**Comment by GreenLunar** [comment]
Those revenue generating links (e.g. `http://fxfeeds.*******.com/`) would be under the control of Lars.

**Comment by GreenLunar** [comment]
Those revenue generating links (e.g. `http://fxfeeds.*******.com/`) would be under the control of Lars, or some CDN server, so, yes, it might be, but many do not care.

**Comment by asl97** [comment]
ads and other money making link are infamously known for storing user information so they could give targeted ads/link.

it would be too late to erase them when liferea start, it would have already send out information to those unwanted link unless they aren't connected to the internet.

liferea would be exchanging the user privacy for some meager amount of money.

**Comment by GreenLunar** [comment]
Yes, this is true, and this is the way for Liferea and sponsors to make sure where hits are originating from.  Mozilla has rapped internet privacy and has caused to catastrophic projections on its users, and there are too few who actually protest against it.

Assume Liferea revives its Welcome dialog, it may detail there the existence and purpose of it sponsored links and user may decide whether or not to have them and/or directly subscribe to a link of a current sponsor.  On the other hand, Mozilla has kept such information, on many levels, secret from its end users.

When several news websites would be aware of sponsored links, Liferea would be able to generate a fair some of revenue.

**Comment by asl97** [comment]
what is your source for that?  where did "Mozilla has rapped internet privacy and has caused to catastrophic projections on its users"?

**Comment by GreenLunar** [comment]
> what is your source for that? where did "Mozilla has rapped internet privacy and has caused to catastrophic projections on its users"?

Mostly, User-Agent and so called Phishing Detector which really sends a list of websites of user to big G.  Today, since web standards are no longer at fault, there is no need to have them, unless you want to ID users.

> also, those site doesn't need to pay liferea just cause it add a link to them, a deal would need to be make first.

Indeed, that is why I suggested dedicated URLs.

**Comment by GreenLunar** [comment]
@asl97 I will start a discussion on [Liferea-Devel](https://lists.sourceforge.net/lists/listinfo/liferea-devel) mailing list.  We can continue there.

**Comment by asl97** [comment]
checking user-agent is just a stupid unreliable thing, people who use them see me as using flock or lynx on a nokia 3310* when i am really using other browser.

ether way, like i said, those site don't have to pay anyone just because someone link to them, regardless of whether it is a dedicated link or not.  a deal/contract need to be make first with them (which i highly doubt would happen).

* the nokia 3310 doesn't even have internet access xD

**Comment by GreenLunar** [comment]
> a deal/contract need to be make first with them

I know.

**Comment by GreenLunar** [comment]
@asl97, I will stat a discussion at Liferea-Devel mailing list.  Please subscribe if you are not already.

> 4. DuckDuckGo supports the open source community in general, and it supports porteus.org specifically. DuckDuckGo has directly [contributed](http://www.porteus.org/donate.html) funds to porteus.org, and has entered into an agreement to pay us back a small amount of the revenue that they generate from searches made inside the DuckDuckGo seach menu we've set in Firefox. This is a small amount of money per click, but it does add up and is helping to pay the costs of keeping porteus.org up and running. So please consider using this seach button for your next web search!

From: http://www.porteus.org/use-duckduckgo.html

**Comment by GreenLunar** [comment]
I am about to send an email in this concern to liferea-devel mailing-list.

Please `~~strike-through~~` the following comment so users would not get confused by it:

> ~~@GreenLunar The feeds you refer to are not included in upstream. Please, please check the sources!!!~~

**Comment by GreenLunar** [comment]
Gentlemen.  This is an important matter.  Please reply to this message http://sourceforge.net/p/liferea/mailman/message/34437871/
