### ISSUE TITLE
Segmentation fault upon attempting to add an OPML

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#234]
1. Open /Subscriptions/News Source/Planet, BlogRoll, OPML
2. Try to add any /usr/share/liferea/opml/feedlist_xx.opml
3. **Segmentation fault.**

---

1. Open /Subscriptions/Import Feed List...
2. Add OPML from local machine.
3. Success.

---

Liferea 1.11.5

**Comment by GreenLunar** [comment]
Reproduce it with /Subscriptions/News Source/Planet, BlogRoll, OPML

**Comment by lwindolf** [comment]
Reproduced. Also in 1.10
