### ISSUE TITLE
Core Dump on start

### ISSUE THREAD

**Issue by elthommy** [lwindolf/liferea#237]
Hi All,
Unfortunatly my liferea no longer want to work :'(
Everytime I try to launch it it crashes with core dump.
I can also attach the core file if needed.

Can you please help me? :)

[thomas@samoth tmp]$ coredumpctl gdb 5334
           PID: 5334 (liferea)
           UID: 1000 (thomas)
           GID: 100 (users)
        Signal: 11 (SEGV)
     Timestamp: jeu. 2015-08-13 23:50:39 CEST (14min ago)
  Command Line: liferea --debug-all
    Executable: /usr/bin/liferea
 Control Group: /user.slice/user-1000.slice/session-c1.scope
          Unit: session-c1.scope
         Slice: user-1000.slice
       Session: c1
     Owner UID: 1000 (thomas)
       Boot ID: 1a5edf1684bd4fe6a35d1a92023d2405
    Machine ID: 3d0b0bad96fe4ada9c1c6ab290a43e82
      Hostname: samoth
      Coredump: /var/lib/systemd/coredump/core.liferea.1000.1a5edf1684bd4fe6a35d1a92023d2405.5334.1439502639000000.lz4
       Message: Process 5334 (liferea) of user 1000 dumped core.

GNU gdb (GDB) 7.9.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/liferea...(no debugging symbols found)...done.
[New LWP 5334]

warning: Could not load shared library symbols for linux-vdso.so.1.
Do you need "set solib-search-path" or "set sysroot"?
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `liferea --debug-all'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f4ccf3a43e1 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2

(gdb) bt
#0  0x00007f4ccf3a43e1 in _dl_relocate_object () from /lib64/ld-linux-x86-64.so.2
#1  0x00007f4ccf39cf23 in dl_main () from /lib64/ld-linux-x86-64.so.2
#2  0x00007f4ccf3af440 in _dl_sysdep_start () from /lib64/ld-linux-x86-64.so.2
#3  0x00007f4ccf39dd8a in _dl_start () from /lib64/ld-linux-x86-64.so.2
#4  0x00007f4ccf399d88 in _start () from /lib64/ld-linux-x86-64.so.2
#5  0x0000000000000002 in ?? ()
#6  0x00007ffef9922783 in ?? ()
#7  0x00007ffef992278b in ?? ()
#8  0x0000000000000000 in ?? ()

(gdb)

**Comment by lwindolf** [comment]
Sorry, the core dump does not help as your binary has no symbols.

Can you recompile with symbols? Also which version do you run?

**Comment by lwindolf** [comment]
Closing old ticket.
