### ISSUE TITLE
Launch Liferea at system startup

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#238]
Suggestion for Liferea 1.11.5

/Tools/Preferences/GUI
 ☐ Launch Liferea at system startup
  ◉ Hidden
  ◌ Iconified

When *Hidden* is selected, file `liferea.desktop` with the following entries be created in `~/.config/autostart/`

```
[Desktop Entry]
Categories=Network;Feed;
Exec=liferea --mainwindow-state=hidden
Icon=liferea
Name=Liferea
GenericName=News Aggregator
Comment=Start Liferea hidden in the background
Terminal=false
Type=Application
Version=1.0
```

When *Iconified* is selected, file `liferea.desktop` with the following entries be created in `~/.config/autostart/`

```
[Desktop Entry]
Categories=Network;Feed;
Exec=liferea --mainwindow-state=iconified
Icon=liferea
Name=Liferea
GenericName=News Aggregator
Comment=Start Liferea iconified
Terminal=false
Type=Application
Version=1.0
```

**Comment by GreenLunar** [comment]
Why?

**Comment by asl97** [comment]
you should know, it is cause this is (imo) a feature request

**Comment by GreenLunar** [comment]
Indeed so, but, I think, this is not difficult to implement.  It is a matter of copy/delete files.

**Comment by asl97** [comment]
then why don't you implement it and make a pull request if you think it's so simple?

this involve editing the glide (gui) files, adding a handle to those buttons, logic to grey out the option if `Launch Liferea at system startup` isn't mark, figuring out which of the radio button is selected and finally copying/writing the files.

i might have miss a few other stuff but those are what need to be implemented.

**Comment by GreenLunar** [comment]
I will try to work on the GUI side, but I am not sure how to do it on the programming side.
