### ISSUE TITLE
[liferea-add-feed] Use Zenity to display warning dialog

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#248]
The message `Liferea is not running! You need to start it first.` is not be visible to end-users.
Add a Zenity dialog, when terminal is not opened.

Zenity dialog would show the same message and would let user to launch Liferea.

1. Liferea icon in title bar
2. Icon: Warning
3. Message: Liferea is not running! You need to start it first.
4. Buttons: [Start Liferea] [Close]

**Comment by GreenLunar** [comment]
We can do this:
```
if [ -t 1 ]; then
  echo error to console
else
  zenity
fi
```
The above condition checks whether shell is open or not; if not, it would launch zenity.
Would you agree to accept a patch that would utilize Zenity?

**Comment by GreenLunar** [comment]
I did not test it with great detail, but it should work:
```
if ! pgrep -x liferea >/dev/null 2>&1; then
	if [ -t 1 ]; then
		echo "Liferea is not running! You need to start it first."
		exit 1
	else
		zenity --question --title=Liferea \
		--text="Liferea is not running! You need to start it first. \
		\nDo you want to launch Liferea" \
		--ok-label="Launch Liferea" \
		--cancel-label="Close"
		ANS=$(echo $?)
		if [[ ${ANS} == 0 ]]; then
			@prefix@/bin/liferea
		fi
		exit 1
	fi
fi
```

**Comment by GreenLunar** [comment]
Calling for KDE users.

I want to add KDialog support to liferea-add-feed script.  I need KDE users to send a screenshot of each of these commands.

```
kdialog --title=$0 --sorry "Liferea is not running! You need to start it first"
kdialog --title=$0 --icon-name=liferea --sorry "Liferea is not running! You need to start it first"
```

**Comment by Leiaz** [comment]
Another possibility is to remove the check, and let Liferea start and open the feed. It currently doesn't need to be already running.

**Comment by GreenLunar** [comment]
This would require adding a new (hidden) desktop file. See #244

**Comment by GreenLunar** [comment]
Irrelevant. See #396
