### ISSUE TITLE
Liferea does not always use theme icons when is launched at system startup

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#251]
Liferea: 1.11.5
Xfce: 4.10.0

Currently, when Liferea is set to launch on system start, it sometimes uses icons from `/usr/share/liferea/pixmaps/` instead of theme icons. (From: #242)

File: `~/.config/autostart/liferea-autostart.desktop`

```
[Desktop Entry]
Categories=Network;Feed;
Exec=liferea --mainwindow-state=hidden
Icon=liferea
Name=Liferea
GenericName=News Aggregator
Comment=Start Liferea hidden in the background
Terminal=false
Type=Application
Version=1.1
```

![liferea-pixmap-icons](https://cloud.githubusercontent.com/assets/2053884/9771328/083f2a76-573e-11e5-8811-440a4a4b77c6.png)

**Comment by GreenLunar** [comment]
![liferea-pixmap-icons](https://cloud.githubusercontent.com/assets/2053884/9771328/083f2a76-573e-11e5-8811-440a4a4b77c6.png)

**Comment by GreenLunar** [comment]
@Leiaz, this issue, and the referenced issues, might interest you.

**Comment by Leiaz** [comment]
Currently liferea loads the icons when the GUI is created. I guess Liferea starts before whatever is managing your theme.

The icons would have to be reloaded when the theme changes (`icons_load` in `src/ui/icons.c`), and currently all the rows from the feed list and item list GtkTreeStores would have to be modified to get the new icons ...  The code can be refactored to avoid that. Some parts like how the different node types are handled, also don't expect the icon to be freed and replaced and need to be modified too ...

Or we could also use the GtkIconTheme system and add Liferea icons to the fallback default theme. I think this is what Gajim is doing, as you noted in issue #242. This also requires changing how the feed list and item list get their icons. With this I think we can use icon names and the theme system updates them on theme change.

@lwindolf What do you think about using the Gtk icon theme system ?

**Comment by lwindolf** [comment]
@Leiaz Thanks for solving this!
