### ISSUE TITLE
Notifications aren't cleared on reading the associated feed entry

### ISSUE THREAD

**Issue by ketsuban** [lwindolf/liferea#253]
This relates to Liferea 1.10.12 from the Ubuntu 15.04 repositories. I checked the release notes and searched issues for any likely candidates, but found nothing to indicate if this has already been reported, fixed in one of the four point releases since Ubuntu 15.04 was frozen and not backported as it's not a security bugfix. If it's already been recognised and dealt with in some manner then I apologise in advance for wasting your time.

When Evolution notifies me about a new email, marking it as read also clears the notification. I would expect the same behaviour to be true of Liferea notifications and marking feed entries as read, but that isn't the case; as a result I end up with an icon full of hours-old notifications which I need to remember to periodically clean out.

Is it possible to implement the expected behaviour?

**Comment by lwindolf** [comment]
Yes, it is possible to implement this, but right now I cannot work on it. Contributions are welcome!
