### ISSUE TITLE
GUI won't raise under xubuntu 14.04.x

### ISSUE THREAD

**Issue by godfree2** [lwindolf/liferea#254]
liferea --debug-all
provides little information on why GUI won't rise

**Comment by GreenLunar** [comment]
Please post the output of `liferea --debug-all`.

**Comment by godfree2** [comment]
liferea --debug-all
is too large

liferea -w shown
will raise the GUI
and it has toggled the hidden setting to show
so now liferea will start with GUI


On Fri, Sep 18, 2015 at 6:18 AM, GreenLunar <notifications@github.com>
wrote:

> Please post the output of liferea --debug-all.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lwindolf/liferea/issues/254#issuecomment-141391246>.
>



-- 
I've been on-line since late 1992
My computer recommendations: Puppy Linux operating system, passwordsafe,
truecrypt (private storage for hard drive/flash sticks), Pidgin Internet
Messenger, tor anonymous browsing bundle.
My information recommendations: antiwar.com therealnews.com alternet.org
quackwatch.com
Please join my boycott of: Eastlink, Facebook,Yahoo!, Microsoft

**Comment by GreenLunar** [comment]
Upload it to https://dpaste.de/ or;
Save it to plain text file, compress it in GZip and upload to http://www.filedropper.com/

**Comment by marukuru** [comment]
Just an idea (as I had the same issue after upgrading to latest unstable [1.11.5]):
The internal tray feature has been moved to a plugin. If you had "start to tray" enabled before upgrading Liferea will start hidden AND no tray icon is shown, as the Python-based plugin hasn't been enabled yet.

**Comment by godfree2** [comment]
that makes sense & something for the FAQ wiki

On Fri, Sep 25, 2015 at 7:25 AM, marukuru <notifications@github.com> wrote:

> Just an idea (as I had the same issue after upgrading to latest unstable
> [1.11.5]):
> The internal tray feature has been moved to a plugin. If you had "start to
> tray" enabled before upgrading Liferea will start hidden AND no tray icon
> is shown, as the Python-based plugin hasn't been enabled yet.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lwindolf/liferea/issues/254#issuecomment-143182642>.
>



-- 
I've been on-line since late 1992
My computer recommendations: Puppy Linux operating system, passwordsafe,
truecrypt (private storage for hard drive/flash sticks), Pidgin Internet
Messenger, tor anonymous browsing bundle.
My information recommendations: antiwar.com therealnews.com alternet.org
quackwatch.com
Please join my boycott of: Eastlink, Facebook,Yahoo!, Microsoft

**Comment by lwindolf** [comment]
I added a FAQ entry http://lzone.de/liferea/faq.htm

**Comment by lwindolf** [comment]
Additional blog post http://lzone.de/liferea/blog/Why%20doesnt%20Liferea%20start%20anymore to make it more present in search engines...

**Comment by lwindolf** [comment]
Above commit should prevent the scenario @marukuru describes.

Won't fix for 1.10 as tray icon hidden scenarios cannot be prevented (which is why the trayicon is a plugin now).
