### ISSUE TITLE
Tray icon plugin doesn't offer any visual feedback about new headlines

### ISSUE THREAD

**Issue by marukuru** [lwindolf/liferea#255]
Since the tray icon (gnome classic) support moved to a plugin there's no visual feedback (changing of tray icon color or number of unread feeds) from the tray icon. [This is more of a feature request, not an issue, as it's simply not implemented in trayicon.py]

**Comment by lwindolf** [comment]
Sorry this is technically impossible since GTK moved the trayicon support into the toolkit (was libegg previously). Because with this move the GtkTrayIcon is now a static (undrawable image).
