### ISSUE TITLE
Feed update setting: Respect server’s cache settings

### ISSUE THREAD

**Issue by Aeyoun** [lwindolf/liferea#259]
Currently, the user must make a choice for how often a feed should be updated. However, not all feeds are created equal. Some sites update several times per hours and others only once a week or once a month.

I’d like to see a new option where users choose the max age they want to accept or feeds beore rechecking, and otherwise defer to the feeds‘ `Cache-Control: max-age=seconds` HTTP header to see how often it should be updated. I could imagine the UI looking like this:

    [X] Update feeds as often as indicated by the server,
        but at least every [ Interval in days drop-down ].

In an ideal world, users would waste less of their own and the servers’ bandwidth and only frequently pull the feeds that need to be updated often deferring the rest to slower refresh cycles.

Just a request from an admin on a site with a lot of feeds that are updated at different frequency and cache settings but also observe Liferea users pull in every feed every hour regardless of the suggested cache options.

**Comment by lwindolf** [comment]
Closing this feature request.
