### ISSUE TITLE
PyGIWarning on media-player plugin

### ISSUE THREAD

**Issue by glitsj16** [lwindolf/liferea#261]
More warnings for the media-player plugin:

/usr/lib/liferea/plugins/media-player.py:28: PyGIWarning: Peas was imported without specifying a version first. Use gi.require_version('Peas', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, GLib, Gtk, Liferea, Gst
/usr/lib/liferea/plugins/media-player.py:28: PyGIWarning: PeasGtk was imported without specifying a version first. Use gi.require_version('PeasGtk', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, GLib, Gtk, Liferea, Gst
/usr/lib/liferea/plugins/media-player.py:28: PyGIWarning: Liferea was imported without specifying a version first. Use gi.require_version('Liferea', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, GLib, Gtk, Liferea, Gst

Correcting these cfr. #256 & #257. Pull request will be there soon.

**Comment by lwindolf** [comment]
This is fixed in recent releases.
