### ISSUE TITLE
PyGIWarnings on gnome-keyring plugin

### ISSUE THREAD

**Issue by glitsj16** [lwindolf/liferea#264]
/usr/lib/liferea/plugins/gnome-keyring.py:24: PyGIWarning: Peas was imported without specifying a version first. Use gi.require_version('Peas', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, Gtk, Liferea, GnomeKeyring
/usr/lib/liferea/plugins/gnome-keyring.py:24: PyGIWarning: PeasGtk was imported without specifying a version first. Use gi.require_version('PeasGtk', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, Gtk, Liferea, GnomeKeyring
/usr/lib/liferea/plugins/gnome-keyring.py:24: PyGIWarning: Liferea was imported without specifying a version first. Use gi.require_version('Liferea', '3.0') before import to ensure that the right version gets loaded.
  from gi.repository import GObject, Peas, PeasGtk, Gtk, Liferea, GnomeKeyring

Missed these, will fix on fork and do another pull request.

**Comment by thecountoftuscany** [comment]
Can confirm still facing the issue on Ubuntu. On launching from terminal, the following is output:
```
/usr/lib/x86_64-linux-gnu/liferea/plugins/gnome-keyring.py:6: PyGIWarning: GnomeKeyring was imported without specifying a version first. Use gi.require_version('GnomeKeyring', '1.0') before import to ensure that the right version gets loaded.
  from gi.repository import GnomeKeyring
```

System information:
Ubuntu 16.04
Liferea 1.10.17 (from Ubuntu repositories)

**Comment by glitsj16** [comment]
@thecountoftuscany The fixes for this probably aren't backported to 1.10.17 from the Ubuntu repo. You can try the latest stable Liferea 1.12.4 on 16.04 LTS via [this PPA](https://launchpad.net/~ubuntuhandbook1/+archive/ubuntu/apps).

**Comment by thecountoftuscany** [comment]
Liferea updated to version 1.12.4 after using the mentioned ppa and while no error is output to the terminal now, the application still doesn't start on launching.

**Comment by glitsj16** [comment]
@thecountoftuscany You might get more visibility to your situation by opening a new issue. These PyGIWarnings are just that, warnings, and shouldn't stop Liferea from starting/working as expected.

That being said, without more info (exact command used to start Liferea, debug log etc.) it's going to be nearly impossible for people here to provide any kind of help. Please try using the available debug arguments when starting Liferea (more info on these via `man liferea` or `liferea --help-debug`).

E.g. `liferea --debug-conf --debug-gui > liferea.debug.txt` would be a good start. If needed, you can upload that debug file to a pastebin service and post the link to it in your thread. The most verbose option would be `--debug-all`, allthough that will produce rather large output, making debugging more difficult. Experiment with some of these debug options I'd say. Goodluck!

**Comment by Leiaz** [comment]
If you used the tray icon before, Liferea may start minimized. The tray icon is now a plugin. Try starting Liferea with `liferea -w shown`.
