### ISSUE TITLE
[Feature Request] Profile support and Profile Manager

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#268]
Add profile support to Liferea.
```
firefox --help
Firefox options
  -P <profile>       Start with <profile>.
  --profile <path>   Start with profile at <path>.
  --migration        Start with migration wizard.
  --ProfileManager   Start with ProfileManager.
```

**Comment by lwindolf** [comment]
Sorry as always: no feature requests.

**Comment by GreenLunar** [comment]
I know, thus I closed this ticket.

If you may, turn me into collaborator so I can label Feature Request issues with feature-request labels for future reference for contributors who would want to look into past Feature Requests.
