### ISSUE TITLE
[Feature Request] Block Cookies

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#270]
I see there is a Privacy tab.

I propose to add a simple option to block Cookies by setting `$XDG_CONFIG_DIR/liferea/cookies.txt` as read-only, until someone would add an advanced Cookie firewall/manager.

**Comment by g4jc** [comment]
Not a bad idea, however the program does support HTTP proxy. So, It is possible to use Privoxy via Tools --> Preferences --> Proxy. 

Then modify /etc/privoxy/default.action file to include +session-cookies-only, or +filter{content-cookies} respectively.
http://www.privoxy.org/user-manual/actions-file.html#FILTER-CONTENT-COOKIES

This method also allows you to block JS and other strange stuff you might want to filter out from your feeds.

**Comment by GreenLunar** [comment]
I, too, use Privoxy with Liferea, to block and filter advertisements and cookies.

By the way, would you like to add a section about Privoxy to the Liferea documentation?

**Comment by GreenLunar** [comment]
I think most users of Liferea who have heard of DNT are well aware of its ineffectiveness and how phony it really is.

Dear strangers around my house.  I am leaving my door unlocked, but there is a sign on that door which says "Please, do not enter this door".

Cookies are SO MUCH MORE critical than the idiotic and fake thing that is known as Do Not Track.
http://www.zdnet.com/article/why-do-not-track-is-worse-than-a-miserable-failure/

**Comment by GreenLunar** [comment]
Cookies and Referer (sic) are SO MUCH MORE critical than the idiotic and fake thing that is known as Do Not Track.

**Comment by asl97** [comment]
calling it idiotic and fake is just rude, DNT is just a request for the site to not track them and there are sites which honor the DNT header.
____
anyone who know how the web works know it's hard if not impossible to stop people from tracking.

even if cookies and the referer header are block, they might be able to use the HTML5 Local Storage to store those instead info and send them using js.

even without them, they could also track by ip, most proxy doesn't use a new ip for every request.
user agent could be use to track too, those method are less reliable but it does work.

the browser might be track you and send those info as well, in fact, the os itself might be doing it too

**Comment by GreenLunar** [comment]
> calling it idiotic and fake is just rude, DNT is just a request for the site to not track them and there are sites which do honor the DNT header.

I call DNT for what it is.  I did not apply this on Liferea, if this is what you think.

Even though this issue is a Feature Request, I do not think it should be closed, and I certainly do not think that a DNT feature is to be implemented before an at least basic cookie blocker.

> even without them, they could also track by ip, most proxy doesn't use a new ip for every request.

This is true.

> user agent could be use to track too, those method are less reliable but it does work.

This is a problem that dear Mozilla has decided to keep, instead of deprecating; their last excuse would probably be "we must market web browsers that support free web".

User-Agent header is needless due to widely adopted standards.

> the browser might be track you and send those info as well, in fact, the os itself might be doing it too

All the major web browsers do exactly that.

**Comment by asl97** [comment]
definition of fake by The Free Dictionary: 1. One that is not authentic or genuine; a sham.

i wouldn't call DNT idiotic, it might be a little too idealistic but it is definitely not fake.

**Comment by GreenLunar** [comment]
DNT is displayed for the masses in order to stir discussion on true concerning problems.
DNT makes User-Agent fingerprint more accurate and more special; in the circumstances of today, DNT offers more problems than benefits, if there are any benefits or even just a benefit.

User agents role, today, is to market a product, not to ask server what sort of layout to load for any web browser or small screen device, since CSS handles any resolution much better.

Referer (sic) is a popularity tracker and also a marketing tool; user might not have a spyware on a given machine, but they certainly gave us standards that would still tell some information about us.

The only identifying detail that user needs to send is what is the locale to be used if a website has multi-lingual interfaces to offer, unless locality can be managed privately on client-side without impacting bandwidth.

**Comment by asl97** [comment]
just because DHT is abuse doesn't make it fake.

**Comment by GreenLunar** [comment]
You are correct, I should not have called DNT fake, but even if I still would, DNT implementation in Liferea is not fake, it is just an implementation of what is known as DNT.

What do you mean by DHT?

**Comment by asl97** [comment]
@GreenLunar typo...

**Comment by lwindolf** [comment]
@GreenLunar All feature request issues are closed, because it makes the tracker unusable and eats up time.

**Comment by GreenLunar** [comment]
Please provide me with permissions to add labels to issues.

> @GreenLunar typo...

I have erased the last line of my last comment.

**Comment by TjWallas** [comment]
Bump.

I believe the privacy issues (e.g. Header/canvas/JS fingerprinting, cookies, hidden pixels, web bugs, ... etc) with any browser are inherent to the embedded webkit browser in liferea. 

It would be nice if there is an option to disable the embedded webkit browser completely and just show the content as plain text (with all inner HTML/XML tags stripped out). Perhaps, in a fashion to how thunderbird does it when the plaintext option is chosen in its rss reader settings.
