### ISSUE TITLE
asking for the keyring password even tho is not necesary

### ISSUE THREAD

**Issue by voidplayer** [lwindolf/liferea#272]
It used to ask for the password when I had a tt-rss configuration

I have removed such configuration now and there is no trace of it in the liferea.db. It still asks for the keyring password in opening and closing liferea

**Comment by lwindolf** [comment]
The keyring is aquired once on startup. This causes the password prompt.

This aquiring right now simply happens unconditionally. Please disable the GnomeKeyring plugin to workaround.
