### ISSUE TITLE
[Usability] Truncate URL and Title

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#275]
Some forums, search engines and bittotrrent indexers provide custom feeds that may result with many *query strings* which, consequently, lead to a URL (that is, Source) with a couple or even more lines, this is something that is not ideal for users with smaller screens.

Truncate feed URL and Title exceed the width of Liferea window with an ellipsis `…`.

Before
```
----------------------------------------
Feed: http://lzone.de/liferea/
Source: http://lzone.de/taxonomy/term/15/0/feed

Feed: https://github.com/lwindolf/liferea/commits/master
Source: https://github.com/lwindolf/liferea/commits/master.atom
----------------------------------------
```

After
```
----------------------------------------
Feed: http://lzone.de/liferea/
Source: http://lzone.de/…/term/15/0/feed

Feed: https://github.co…a/commits/master
Source: https://github.c…its/master.atom
----------------------------------------
```

Maybe relevant resources:
https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--truncate-multiline
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
http://html5hub.com/ellipse-my-text/
https://css-tricks.com/line-clampin/

**Comment by GreenLunar** [comment]
I am attempting to do so by editing liferea.css

Maybe relevant resources:
https://developer.gnome.org/gtk3/stable/GtkEntry.html#GtkEntry--truncate-multiline
https://css-tricks.com/snippets/css/truncate-string-with-ellipsis/
http://html5hub.com/ellipse-my-text/
https://css-tricks.com/line-clampin/

**Comment by GreenLunar** [comment]
![liferea_long_url](https://cloud.githubusercontent.com/assets/2053884/10695995/7d815096-79af-11e5-8134-cb005a7163de.png)

**Comment by GreenLunar** [comment]
Please reopen this issue.

**Comment by GreenLunar** [comment]
Doing so would also fix this problem (see animated image) for RTL users.

Animation
![liferea_bad_rtl](https://cloud.githubusercontent.com/assets/2053884/10963424/fbc01cf0-83a8-11e5-810f-042b6ead1fd6.gif)

First screen (this is how Liferea looks on selecting a feed)
![liferea_bad_rtl](https://cloud.githubusercontent.com/assets/2053884/10963428/00701408-83a9-11e5-84bb-d7ceb745a9b5.png)

**Comment by GreenLunar** [comment]
@kalkin, may you provide a patch or a guideline to solve this issue?

I have seen [this patch](https://trac.gajim.org/attachment/ticket/8218/Shorten%20name%20of%20a%20gc%20entry.diff) and figured if you would be able to help to solve the above problem here.

Please excuse me for this direct reach to you.

**Comment by kalkin** [comment]
@GreenLunar :question::grey_question::question: 
1) I have no idea what lifearea is
2) The patch you mention is no rocket science, you could do something similar on your own
3) If you need professional support, I'm available for hire.
