### ISSUE TITLE
Multiline feed titles in wide/large view mode

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#28]
This is something I've been thinking about, and it seems someone else reported the same issue in the old bug tracker: http://sourceforge.net/p/liferea/bugs/1068/

Basically, in "wide mode", on laptops the "Title" column is usually cut off too short (in my case: after 4 words, on average) because the date/timestamp column takes roughly 30% of the available listview width (in French, on my laptop screen).

A solution would be to have a different listview arrangement in "wide" mode, similar to what mail clients (Evolution, Geary, etc.) do.

So instead of

```
(!) Ajourd'hui 09:44   Some amazing news from...
```

You would see:

```
(!) Some amazing news from the Liferea project
    Aujourd'hui 09:44 
```

...With bonus points due to the fact that this would be more touch-friendly, as the target would be bigger (I have a touch-enabled laptop and those are becoming increasingly common).

**Comment by lwindolf** [comment]
I'm now using more often in wide mode + fullscreen and I'm suffering from the effect too. It's somehow paradox by using more screen width, the width suddenly is not enough :-)

**Comment by lwindolf** [comment]
I've made a first implementation. The problem I have with it is that this rendering causes a lot of visual noise. It's hard to focus on the headline with the (more or less) irrelevant data being there.

@nekohayo How can we render the date (with Pango features) so it doesn't disturb?

**Comment by lwindolf** [comment]
Made some more tries to make it readable:

- appended date (without bold style)
- enforced row grid lines to help distinguish headlines

The grid lines are quite disturbing and unexpected, but they solve the readability issue for me.

One GTK cell renderer issue that is left is the resizing of rows where normal text uses less vertical space than the bold one. This causes jumping...

**Comment by kallus** [comment]
Oh, if I understand that diff correctly I will now be forced to see the date again?

I'm starting to wonder if one line feed titles where each column is possible to hide is better, considering that it's simpler. If the change to multi line won't be optional, I would really wish for the possibility to hide all information that I don't need (which is everything but the title for me).

Anyways, I'm really happy that the initial problem is being worked with!

**Comment by lwindolf** [comment]
@kallus I understand your worry and I do value your input. There are two things to consider: first having multi-line titles is in principle independant of the request to be able to customizing columns. Second I believe the majority of the users doesn't want to hide the date column. Given those two priorities and my unwillingness to increase complexity with a column preferences dialog handling I tend to care more about the multi-line-thing.

![screenshot from 2015-01-08 20 25 00](https://cloud.githubusercontent.com/assets/3315368/5669079/f04bc1c4-9774-11e4-9b43-1117c972e022.png)

I attached a screenshot of my current attempt to make it work. Note the absense of column headers, larger icons and the small date appended to large titles. My testing showed that with this rendering you do not notice the date much, but it is there if you need it.

**Comment by lwindolf** [comment]
@nekohayo BTW for testing I added a button-press listener on the lower right unread counter in the status bar. It triggers the "Next Unread" function. I guess this could be helpful for thumb based browsing on touchpads. But I'm not happy with the responsiveness...

**Comment by kallus** [comment]
@lwindolf Looks great! I agree that it's not worth adding extra complexity to preferences to make it possible to remove date.

**Comment by nekohayo** [comment]
Hi Lars, just wanted to say that it's awesome that you're experimenting with this direction, and that what I'm seeing in the screenshot looks pretty neat! Some questions/nitpick about what I'm seeing there:

* It's slightly odd that the row heights varies, but that's probably not a dealbreaker.
* Instead of "---", I suggest just using the (unicode) emdash character: —
* Are the parentheses around the date necessary?
* Crazy alternative idea you could experiment with, if actually possible: right-aligning the date (dunno if the cell/pango allows doing that to a portion of the text there?)

I'm afraid I can't help testing building multiple dev branches/variants of this feature, I'm totally swamped for the coming month or two, and afterwards I'm not sure - so if you want something reviewed I think the easiest approach is to post screenshots of the variants (if any).

**Comment by lwindolf** [comment]
Hi Jeff, thank you for the feedback.

The constant height is possible, but really aweful if you have 1000 items in the view and one of it forces a height of 200px, then you waste an absurd amount of space. So it is just not possible to use it.

I'll check how it looks with emdash and without parantheses...

The right-aligning is impossible aside from implementing a new GtkCellRenderer, Pango doesn't allow aligning like CSS :-(

**Comment by lwindolf** [comment]
@nekohayo: I changed to emdash, but didn't drop the parantheses as IMO those actually help to identify the date string as a label block more easily.

Closing this change for now, I'm using the mode now for some weeks and find quite usable. I'm open to further improvements of the feature and we should track them in separate tickets.

**Comment by asl97** [comment]
it look great at first but i don't like it because the reason i use wide mode is because i want to be able to see a large amount of feed at any one time.
i have a group of feed which sometimes has overlapping feed item (duplicate) and liferea is smart enough to mark the item as read in all the feed.

this reduce the number of visible feed from 24(.5) to a mere 6+ due to ridiculously long feed title so it's a little hard to scroll using the scroll bar when there are a lot of feed item and slow using the `PgUp & PgDn` key.

what would be great is if we have both wide mode available.

**Comment by QmwJlHuSg9pa** [comment]
> i want to be able to see a large amount of feed at any one time.

Indeed. Can we please have an option to show columns in "Wide View" (much like "Normal View). I just want the preview pane on the right, with columns intact!

I've burnt through at least half-a-dozen RSS reader front-ends for Linux; Liferea best hits the mark in terms of usability and customisation (Thunderbird comes close, but its sidebar doesn't display individual feeds that are within subfolders). Lack of columns in "Wide View" is Liferea's only apparent shortcoming, in my view.
