### ISSUE TITLE
Mark as read button is disabled on filters

### ISSUE THREAD

**Issue by dvachaiev** [lwindolf/liferea#280]
Even when a filter folder contains unread records mark as read button in toolbar is disabled.

**Comment by lwindolf** [comment]
Reproduced

**Comment by elpocko** [comment]
Can you please fix this? Seems like a pretty simple bug, but it's really annoying.

**Comment by lwindolf** [comment]
@elpocko You are not helping. Did you try to fix the "simple bug" in the code?

**Comment by lwindolf** [comment]
Caused by itemlist.c:311 doing

     liferea_shell_update_allitems_actions (0 != node->itemCount, 0 != node->unreadCount);

with node->unreadCount for search folders always being 0

**Comment by elpocko** [comment]
@lwindolf I'm good, thanks. I have long switched to reader software with working UI, better working basic features and quick bug fixes that the reporting users don't have to do themselves. Thanks anyway.

**Comment by lwindolf** [comment]
@elpocko Still not helping. You are talking to a human being spending his free evening here for others. I know it's not enough for you. Still it might be for others. By insulting the project you sap motivation and make it worse and hurt the other users in the end. Maybe you don't want to do this...

**Comment by smaragdus** [comment]
@lwindolf 
It is none of my business but for me it is a waste of time to respond to idiotic comments.
I also think that a project cannot be insulted, it is just an opinion, no matter whether it is praise or denigration, no matter whether it is sincere or far-fetched.

**Comment by smaragdus** [comment]
@lwindolf 
My attitude towards open source software- better unresolved issues than abandoned projects- for example I am not happy that [RSSOwl](http://www.rssowl.org/) was [archived](https://github.com/rssowl/RSSOwl/) and abandoned but I cannot do anything about that- it is the developer's decision and I respect it no matter whatever reasons may stand behind it. In the open source world anyone can [fork](https://github.com/Xyrio/RSSOwlnix) and for me forking is far better than complaining.
In fact I am very interested in #339 but I wait patiently without asking more questions- when there is some developement I know I will be notified. Although I am not using Liferea (I have Windows-only system right now) I appreciate your and other contributors' efforts.

**Comment by lwindolf** [comment]
@smaragdus Thanks for the feedback. My problem with #339 is I can't test the windows part. I can only test the Linux side. We need someone to track compilation on windows and point out new code places (over time) that break it again.
