### ISSUE TITLE
No media files are shown referenced by <media:group> and media:content

### ISSUE THREAD

**Issue by Johann-Tree** [lwindolf/liferea#284]
In liferea 1.10.3 media files within <media:group> referenced by media:content are not shown. For example the Feed of Arte TV: http://www.arte.tv/papi/tvguide-flow/feeds/videos/de.xml?type=ARTE_PLUS_SEVEN&player=false

**Comment by Leiaz** [comment]
I posted a patch to get the group content, but this particular feed gives only "mp4" in the `type` attribute that should be the MIME type. And Liferea will only list enclosures with "audio/*" or "video/*" MIME types. 

But `type` and `medium` are also optional attributes in `media:content` elements [according to here](http://www.rssboard.org/media-rss#media-content). Liferea needs the MIME type for the "open with" action.

**Comment by lwindolf** [comment]
I agree with @Leiaz the Arte feed is broken. It's an invalid MIME type.

@Johann-Tree Please contact the Arte webmaster about it.
