### ISSUE TITLE
Debian/Ubuntu don't have steadyflow or gwget; is adding support for uget an option?

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#285]
Conform Ubuntu bug 1503352¹, default installations in Debian and Ubuntu now pull in nearly all of KDE because the Liferea package in Debian recommends steadyflow OR kget, but steadyflow was dropped due to being unmaintained. How difficult would it be to add support for other download managers (or even plain wget/curl)?

For now I'll just drop kget from Recommends to Suggests. Do you agree?

¹https://bugs.launchpad.net/ubuntu/+source/liferea/+bug/1503352

**Comment by asl97** [comment]
@paulgevers see: https://github.com/lwindolf/liferea/issues/70

@lwindolf imo, that issue need to be relabel from `invalid` to `won't fix`

**Comment by lwindolf** [comment]
@paulgevers I 100% agree with dropping kget. I'd suggest replacing steadyflow with uget-gtk which is already supported.

Additional download managers can be defined in src/ui/preferences_dialog:73

**Comment by lwindolf** [comment]
Closing this as uget-gtk is already supported in 1.11

**Comment by paulgevers** [comment]
@lwindolf: side note: in Debian we still track your stable branch. When do you think the time is ripe to start building from the 1.11 branch?

**Comment by lwindolf** [comment]
@paulgevers My maybe unrealistic plan is to get 1.12.0 at christmas like most other years. There are several active users and code quality is getting to an acceptable level...

BTW made a blog post to let users know http://lzone.de/liferea/blog/Dependency%20Problem%20on%20Debian%20Jessie,%20Ubuntu%20Wily
