### ISSUE TITLE
[RTL] Size of status column is not always fixed

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#288]
_As I recall, I have noticed this issue when I used the GTK+3 builds of Liferea_

When contents of all columns are filling the width of the columns surface, the size of status column is too wide.
1. Add feed http://www.claws-mail.org/releases.rss
2. Select feed http://www.claws-mail.org/releases.rss
3. Close Liferea
4. Execute `LANG=ar_SY.utf8 liferea` or `LANG=he_IL.utf8 liferea`

What I sometimes see
![liferea_column_before](https://cloud.githubusercontent.com/assets/2053884/10969396/c308a620-83d0-11e5-9257-b5fa46482180.png)

What I only want to see
![liferea_column_after](https://cloud.githubusercontent.com/assets/2053884/10969395/c2f22616-83d0-11e5-8eca-101c930f9998.png)

I achieve a correct width after I select a feed that does fill the width of the columns surface

**Comment by lwindolf** [comment]
I understand the effect, but have no idea how to fix or mitigate. This is a GtkTreeView / GtkCellRenderer internal behaviour...

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
