### ISSUE TITLE
Auto-loaded item link replaced with embedded content in internal browser during update

### ISSUE THREAD

**Issue by mhoran** [lwindolf/liferea#289]
I have a few feeds configured to load items via the internal browser for sites that don't provide useful embedded content. When reading such an item during an update cycle, the browser reloads and displays the embedded content, replacing the auto-loaded item link. The issue persists until the update cycle is complete.

**Comment by lwindolf** [comment]
Reproduced.

**Comment by mhoran** [comment]
I can't reproduce this anymore.

**Comment by mhoran** [comment]
Well it still seems to happen but I haven't been able to come up with a reliable way to reproduce. I tried digging in a while ago but didn't make much progress.

**Comment by mhoran** [comment]
It took me a while to figure out how to reproduce this reliably, but I finally figured it out. It does not happen when items are selected by mouse; only when browsing by next unread or history buttons.

1) Configure a feed to launch in the internal browser
2) Mark an item as unread in the feed
3) Navigate to the item with n
4) Update the feed
5) Internal browser content will be replaced with rendered feed item

**Comment by lwindolf** [comment]
I could reproduce the bug as described by you and your PR does fix it!

I also like it when there is already a FIXME in the code that did predict the issue :-)

Thank you!
