### ISSUE TITLE
Do not use bold text for feeds/folders with unread items in the leftmost treeview

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#29]
I just realized something... the use of bold type for "unread items" in the feed list on the left is redundant:
- We already have very nice indicators/"counters" hinting at the exact amount of unread items for each feed/folder
- The bold type takes up more space, allowing less words to fit in and creating many unnecessary ellipses in my case
- It's visually overloading; in most cases, people will have almost every item in bold (especially if using folders to regroup feeds)

I humbly suggest just removing the bold from there and leaving that job to the "counter" widget.

**Comment by ao2** [comment]
FWIW I preferred the previous behavior, it was more consistent with how my email client behaves (Sylpheed), and folders with new content were **popping out** more to my lazy brain.

I guess I'll just have to get used to the new behavior. :)

**Comment by nekohayo** [comment]
AFAIK this didn't change inside the feed view, just on the list on the left, right?
Anyway, my arguments are above and still stand... in my case every item is always in bold as I can't possibly consume all of the content produced by the Internet on a regular basis, and the bold overpowers the "unread counters" visually so it's actually detrimental to attracting my attention; YMMV etc.

**Comment by ao2** [comment]
The change of behavior occurred only in the folder view, yes.

It also depends on **how** you group by folders, of course.
In my case I can notice that the update period for some folders is systematically smaller than other folders, so the bold text make me see when the frequent ones get updated.

Also I have a couple of folders always **expanded** in order to see the individual feeds, and the bold text allows me to pinpoint the updated feeds in a folder more quickly.

But that's just me.

**Comment by shartge** [comment]
I am sorry to pull this old issue back, but Debian just recently upgraded to 1.12-RC1.

This change really reduces the usability of liferea for me. Before, I was able to quickly see which feeds had updated with a simple glance, but now, I have to really look at the light grey square at the right side of the feed name.

You said yourself in 2014: "It is slightly offsetting though that we divert from the email client look" and this is also my opinion. (I don't really care that other feed readers also don't use bold text for the feed list, since I don't compare the look and feel of liferea to other feed readers but to Thunderbird.)

My eye (and mind) is trained to look for **bold** text and I would really like to get that look back, maybe as a configurable option?

**Comment by GreenLunar** [comment]
I like the new appearance.

Perhaps there should a switch to toggle new/old appearance.

**Comment by shartge** [comment]
No option Lars chooses as the default will satisfy anyone. And because of this fact, there should be some option to configure the look, in my opinion.

**Comment by nekohayo** [comment]
The simple presence of a grey square makes it easy to spot, if your goal is to look for feed with unread items you can simply glance to look at areas where there are gray squares, or use the special search folder for "Unread items". I don't see how having almost everything bold in the screen helps...

Adding Yet Another Option would add more code complexity and increase the test matrix, options have a cost... my 2¢.

**Comment by shartge** [comment]
Sorry, but I find it really patronizing that you assume how my workflow, my screen setup and my usage pattern of liferea is and thus think you can tell me how to use it.

Most feeds I read for example only update once or twice a week, so "having almost everything bold" does not apply here.

Changing the long long established look and feel (established not only by liferea but by other applications, where bold universally means "something new here") without the possibility for the user to adapt it the way s/he wants it has a certain GNOMEish ring to it. They also said "we and only we know best" and removed nearly all configuration options, to much chagrin of its users.

Note that I am not advocating to revert the change, as I can see how the different look and feel appeals to other users but I am petitioning to introduce an option for the user to choose, what he wants.

And of course does every bit of code have its costs, but we are not talking about providing a completely different UI for liferea here, just a toggle to restore the old behavior.

**Comment by ao2** [comment]
> The simple presence of a grey square makes it easy to spot,

I'd say that the presence of a grey square make it **possible** to spot...

In my opinion the bold text and the square box serve two different purpose, the former tells that **there is** new info, the latter tells you **how much**.

As I said, how **easy** it is for the user to rely on the gray box to spot new info depends on the usage pattern, so in this case an option would make sense to me. But I am biased of course, because I also **like** the old style better.

If @lwindolf would accept to add the choice (defaulting to the new style) we could try to come up with a patch ourselves.

Ciao ciao,
   Antonio

**Comment by nekohayo** [comment]
> Sorry, but I find it really patronizing that you assume how my workflow, my screen setup and my usage pattern of liferea is and thus think you can tell me how to use it.

Not meant to be that way.

> Changing the long long established look and feel (established not only by liferea but by other applications, where bold universally means "something new here") [...]

It's _not_ universal. I can point out a bunch of applications that use only the counters balloons as indicators, without resorting to boldface. I've tried them out and I don't miss anything (once you get used to the fact that there's been a sligth visual change). Bold made sense when there were no other means of conveying that information. "It always looked exactly that way" does not really sound like a convincing argument to me, with all due respect.

> [...] just a toggle to restore the old behavior.

"Just" one option here, one option there, and then you end up with a gazillion toggles because nobody dares to make a decision ;)

> I'd say that the presence of a grey square make it possible to spot... In my opinion the bold text and the square box serve two different purposes, the former tells that there is new info, the latter tells you how much.

My point is that the presence of the grey square does _both_, really. If a feed does not have "new info", then there is no square/counter, period...

> As I said, how easy it is for the user to rely on the gray box to spot new info depends on the usage pattern, so in this case an option would make sense to me. But I am biased of course, because I also like the old style better.

That's the thing: _any_ change is going to feel weird at first, because you're not used to it... and after a while it just starts feeling normal. Give it a few weeks. I've had that happen to me multiple times over the years when people would make changes to theming engines and I would think "this is so wrong" and after a while I just got used to them, to my own surprise.

But then if Lars et al. want to add another option for this, that's up to them, I don't control the project, I merely give feedback and advice.

**Comment by ao2** [comment]
> > I'd say that the presence of a grey square make it possible to spot... In my opinion the bold text and the square box serve two different purposes, the former tells that there is new info, the latter tells you how much.
> 
> My point is that the presence of the grey square does both, really. If a feed does not have "new info", then there is no square/counter, period...
>

I get it, of course you can derive that there is new info from how much there is, our point is a matter of convenience induced (admittedly) by habit, but also by **consistency** with other programs we use (e.g. the sylpheed MUA in my case uses both the bold colored text and a number to indicate that there are new messages in a folder and how many).

>  >   As I said, how easy it is for the user to rely on the gray box to spot new info depends on the usage pattern, so in this case an option would make sense to me. But I am biased of course, because I also like the old style better. The old style resulted in the same pattern in the two programs which is handy for me.

> That's the thing: any change is going to feel weird at first, because you're not used to it... and after a while it just starts feeling normal. Give it a few weeks. I've had that happen to me multiple times over the years when people would make changes to theming engines and I would think "this is so wrong" and after a while I just got used to them, to my own surprise.
>

Humans adapt eventually, that's true, but if I can take a well known shortcut, and that doesn't bother others *too much* (I am referring to the relative cost of adding **this** option) I'd prefer so.

if there is interest I can send a screenshot of my typical usage to show how the bold text makes things easier for me.

> But then if Lars et al. want to add another option for this, that's up to them, I don't control the project, I merely give feedback and advice.

We appreciate it @nekohayo I know your name from pitivi and the effort in simplifying it shows.

Anyways, at the end of the day it's just a bold text, maybe we are spending too much time on it, if @lwindolf is not interested in an option I can always patch my local copy if I find out that I really can't live with the new behavior.

Thanks,
   Antonio

**Comment by GreenLunar** [comment]
Would a dconf switch be feasible?  Would it be possible to add the old behavior with a plugin?

**Comment by ao2** [comment]
@GreenLunar I like the idea of having only the `dconf` setting, without the corresponding UI, I think it's good enough for us old farts and can be passed as a "backward compatibility" mechanism.

See https://github.com/ao2/liferea/commit/dcded9f73379c0c31c123e07b88c55ea6f97edde

If that's acceptable I will send a pull request.

You can test the patch with a local build of liferea by building it like this:

```
$ ./autogen.sh --prefix=$PWD/build
$ make
$ make install
$ LD_LIBRARY_PATH=$PWD/build/lib \
  GSETTINGS_SCHEMA_DIR=$PWD/build/share/glib-2.0/schemas \
  ./build/bin/liferea
```
The old behavior can be enabled in another terminal with this command:

```
$ cd .../liferea
$ GSETTINGS_SCHEMA_DIR=$PWD/build/share/glib-2.0/schemas \
  gsettings set net.sf.liferea feedlist-unread-items-bold true
```

Ciao ciao,
   Antonio

**Comment by shartge** [comment]
> I like the idea of having only the dconf setting, without the corresponding UI, I think it's good enough for us old farts and can be passed as a "backward compatibility" mechanism.

I would be more than fine with this option as well.
