### ISSUE TITLE
[make] Incorrect permissions when running make with umask 0077

### ISSUE THREAD

**Issue by genodeftest** [lwindolf/liferea#290]
Steps to reproduce:
```
$ umask 077
$ make
# umask 077
# make install
```
What should happen:
liferea should set its permissions not relying on any user-set umask prefernces.

What happens:
Files are created with wrong permissions: only readable by owner, after installation this owner is root. Liferea cannot be started. It crashes with this error message:
```
$ liferea

GLib-GIO-ERROR **: Settings schema 'net.sf.liferea' is not installed

Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Comment by genodeftest** [comment]
Workaround: manually set umask to 022 in both user (with compile) and root (for installation).

**Comment by lwindolf** [comment]
I do not know how to fix this really :-(

**Comment by genodeftest** [comment]
With ordinary makefiles (not generated by Automake), you would use the `install -m 555` command. It seems like you are shipping your own `install-sh` file. May I ask why? Is this a "feature" of Automake?

Anyway, it looks like a bug in GNU Automake: https://sourceforge.net/p/curl/bugs/723/ (with patch for automake, which hasn't been applied)
