### ISSUE TITLE
URL links with ? is highlighting wrong.

### ISSUE THREAD

**Issue by brainrom** [lwindolf/liferea#291]
On screenshot
![2015-11-22 11-05-14](https://cloud.githubusercontent.com/assets/15963835/11322357/75997180-9109-11e5-9575-8d4a3dbcde9d.png)

**Comment by lwindolf** [comment]
I believe this is not a problem in Liferea.

But to 100% verify this I'd need the original feed content. Do you have a copy of the original feed XML?

**Comment by lwindolf** [comment]
Closing old ticket.
