### ISSUE TITLE
Updated Swedish translation

### ISSUE THREAD

**Issue by gusnan** [lwindolf/liferea#294]
Hi!

As a part of translationproject I try to update the Swedish translation
of Liferea, getting my work reviewed I send it according to
translationproject workflow, and I get the following reply from the
translation robot:

>***> You submitted a PO file for which the Translation Project does    
>not have a template -- liferea-1.11.6.pot.  If appropriate, please
>urge the package maintainer to send this POT file, or the URL of the
>corresponding tarball, to the TP coordinators.  

So I don't really know what I can/need to do.
Anyway, I have made my translation work available here:

http://gusnan.se/translations/liferea/sv.po

and I would really appreciate if you included it in Liferea.

**Comment by GreenLunar** [comment]
@lwindolf, I suggest to add a template of Liferea unstable, too, to http://translationproject.org/

**Comment by lwindolf** [comment]
The translation was merged recently.
