### ISSUE TITLE
RSS feed description QName error?

### ISSUE THREAD

**Issue by daurnimator** [lwindolf/liferea#299]
I'm having trouble with this RSS feed: http://cube-drone.com/rss.xml
liferea seems to fail if the description field contains anything with a ":" in it.
It's interpreting it as a QName for some reason, e.g.:

> This page contains the following errors:
> error on line 27 at column 319: Failed to parse QName 'drone:'
> Below is a rendering of the page up to the first error.

Reported here: https://twitter.com/classam/status/680239748540022784

**Comment by lwindolf** [comment]
With the current feed content this is not reproducible. Can you retest?

**Comment by daurnimator** [comment]
> With the current feed content this is not reproducible. Can you retest?

Yeah the issue isn't present at the moment, none of the current descriptions in the feed have a colon in them.
Should be easy to reproduce though: just put a colon in a feed.

**Comment by Leiaz** [comment]
I can't reproduce by just adding a colon in a description field.
I can reproduce with : 
```
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Test</title>
    <description>test</description>
    <item>
      <title>Test</title>
      <description>Test:  &amp;lt;thisworks:&amp;gt; &lt;thisisanerror:&gt;</description>
    </item>
  </channel>
</rss>
```
The description field contains entity-encoded HTML. The first will be decoded as `&lt;` and `&gt;` and renders `<` and `>` as characters. The second is seen as a tag with just a prefix. That would be an error in the feed.

**Comment by daurnimator** [comment]
I think I tracked this one down.
A sample of what I think was causing it:
```xml
<?xml version="1.0" encoding="utf-8"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>Test</title>
    <description>test</description>
    <item>
      <title>Test</title>
      <description>some img: &lt;img alt='
test1: doesn&#39;t work.
test2: bar'/&gt;</description>
    </item>
  </channel>
</rss>
```

Which would be caused by the feed generator not escaping the `&#39;`.
