### ISSUE TITLE
liferea 1.10.17 fails to build from source when --disable-libnotify is specified as configure option

### ISSUE THREAD

**Issue by vostorga** [lwindolf/liferea#302]
Attached is build log
[build.txt](https://github.com/lwindolf/liferea/files/72779/build.txt)

Error happens when linking:
libtool: link: x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -Wl,-O1 -o liferea auth.o auth_activatable.o browser.o browser_history.o comments.o common.o conf.o date.o db.o dbus.o debug.o e-date.o enclosure.o export.o favicon.o feed.o feed_parser.o feedlist.o folder.o html.o htmlview.o item.o item_history.o item_loader.o item_state.o itemset.o itemlist.o json.o metadata.o migrate.o net.o net_monitor.o newsbin.o node.o node_type.o plugins_engine.o render.o rule.o social.o subscription.o update.o main.o vfolder.o vfolder_loader.o xml.o -pthread -Wl,--export-dynamic -pthread  -Wl,--as-needed parsers/libliparsers.a fl_sources/libliflsources.a ui/libliui.a webkit/libwebkit.a -lxslt -lz -ldl -lm -lxml2 -lsqlite3 -lgthread-2.0 -lwebkitgtk-3.0 -lsoup-2.4 -ljavascriptcoregtk-3.0 -ljson-glib-1.0 -lpeas-gtk-1.0 -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lpeas-1.0 -lgmodule-2.0 -lgio-2.0 -lgirepository-1.0 -lgobject-2.0 -lglib-2.0 -pthread
feed.o: In function `feed_process_update_result':
feed.c:(.text+0x137): undefined reference to `notification_node_has_new_items'
fl_sources/libliflsources.a(libliflsources_a-ttrss_source_feed.o): In function `ttrss_feed_subscription_process_update_result':
ttrss_source_feed.c:(.text+0x377): undefined reference to `notification_node_has_new_items'
collect2: error: ld returned 1 exit status

**Comment by efferre79** [comment]
Looking at the code it seems that the libnotify support was removed with commit 6b9a24b7ea07ae34e4d83c72fa326e6e9f3b3b2a. I don't understand why there is no trace of this work also in the log history of src/fl_sources/ttrss_source_feed.c, anyway also from this file the notification_node_has_new_items function call disappeared

**Comment by lwindolf** [comment]
@vostorga notification_node_has_new_items is not referenced in recent code anymore. This should not happen. Can you try to "make clean" first?

**Comment by Calmarius** [comment]
Same here... On Ubuntu 14.04 64 bit. The default ./configure; make; make install just fails with the error above.

**Comment by lwindolf** [comment]
Reproduced.

**Comment by lwindolf** [comment]
I believe I fixed the issue. If someone could re-test that would be awesome!
