### ISSUE TITLE
Implement rss-bridge

### ISSUE THREAD

**Issue by pizzamaker** [lwindolf/liferea#305]
rss-bridge can create RSS from various types of websites that don't support it. It would be nice to see some integration with Liferea, so that Liferea can automatically turn these problematic websites into RSS feeds.

rss-bridge repo: https://github.com/sebsauvage/rss-bridge

**Comment by asl97** [comment]
http://lzone.de/liferea/faq.htm#feature-x

**Comment by GreenLunar** [comment]
@pizzamaker, what do you think of issue #165?
