### ISSUE TITLE
[i18n] Untranslatable strings 2

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#306]
* Remove

See dialog Search Folder Properties.

----

* Developers:
* Contributers: Code, Patches, Debugging
* and many more...

See dialog About.

----

P.S. Contributers > Contributors

See https://github.com/lwindolf/liferea/issues/216#issuecomment-156096599

**Comment by lwindolf** [comment]
I do not plan to fix the translation of "Developers, Contributors..." for simplicity.
