### ISSUE TITLE
Handling issues of Feature Request

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#314]
@lwindolf, I request you to grant me with privileges to label issues of this repository.

I think, it is not good to have feature requests labeled as [invalid](https://github.com/lwindolf/liferea/labels/invalid) and closed; alternatively, I suggest to label feature requests as feature-request and if one does not want to see feature requests when browsing in the [Issues](https://github.com/lwindolf/liferea/issues) section, s/he can filter it with the issue filter.

**Comment by GreenLunar** [comment]
bump

**Comment by lwindolf** [comment]
It would only work for me when also tagging them as feature request and closing them. This is probably not what you want...

**Comment by GreenLunar** [comment]
It would be better than nothing. I am still interested.

**Comment by GreenLunar** [comment]
Bump!

**Comment by GreenLunar** [comment]
Thank you!

**Comment by GreenLunar** [comment]
There is no "feature-request" label.  May I set such label?

**Comment by lwindolf** [comment]
Please do so!

**Comment by GreenLunar** [comment]
@Leiaz please create a new label. I do not know where is the page to set it.

**Comment by lwindolf** [comment]
@GreenLunar Check out https://github.com/lwindolf/liferea/labels
