### ISSUE TITLE
liferea keeps animating images even when the window is docked

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#320]
Relayed bug 817249 from Debian¹ (Please let me know if I made the wrong assumption that this is not Debian specific)

steps to reproduce:

1. show a post that contains an animated image. Say,
   http://devopsreactions.tumblr.com/post/137275323038/reviewing-the-interns-commits
2. check top; liferea uses CPU
3. close the liferea window
4. check top; liferea uses CPU just like before
5. show a post that does not contain an animated image, say:
   http://www.enricozini.org/blog/2016/debian/simple-one-liner-to-save-battery-life-and-reduce-system-latency/
6. close the liferea window
7. check top; liferea is not using CPU

Given that I occasionally need to run my laptop on battery for a long
time, and that its CPU fan is approaching end of life and I would like
it not to spin unless it's really needed, this issue currently means
that I need to take care of clicking somewhere that empties the current
post view in liferea when I'm done reading feeds.

When the window is closed, liferea should really be doing nothing else
than waiting for the next update timers to trigger.

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=817249

**Comment by lwindolf** [comment]
Sadly this cannot be fixed as rendering is 100% in the hand of Webkit and there is not disabling of animated GIFs in Webkit. The same effect should be reproducable in Epiphany.

**Comment by paulgevers** [comment]
The original reported  (a Debian dev) had the following remark:

My personal workaround for this is currently to ensure that I do not
have a feed item currently open before I close the liferea window.

This suggests me a potential hack for working around the webkit
limitation: when the window hide signal is received, the webkit widget
contents are cleared. When the window is shown again, the entry that was
displayed on hide gets reloaded.

**Comment by Leiaz** [comment]
This appears to be fixed by #311 using WebKit 2. Both Liferea and the WebKitWebProcess show 0 CPU usage in top when the window is hidden.
