### ISSUE TITLE
The date column goes before the title column

### ISSUE THREAD

**Issue by birdie-github** [lwindolf/liferea#321]
This is a bug unless your native language is Arabic.

Every other Westerner reads from left to right which means your eyes always stumble on the article date which is plain wrong because a feed reader is meant to give you NEW information so date is of the least importance.

If this reasoning is not enough then consider the fact that most other RSS clients show the title column first (on the left).

This is not a feature request. This is a bug report.

**Comment by lwindolf** [comment]
Good idea. We should do this for 1.13+
