### ISSUE TITLE
New articles counter resets and disappears whenever the user opens Liferea's main window

### ISSUE THREAD

**Issue by birdie-github** [lwindolf/liferea#323]
This is absolutely wrong.

I can open its main window and not read or mark read any articles. Then why does the counter of new articles disappear from the tray icon?

It's a bug.

**Comment by lwindolf** [comment]
It is implemented behaviour and similar to other tray icon using applications. Thererfore it is not a functional bug, and I also do not consider it a usability bug.

**Comment by birdie-github** [comment]
I don't know any other systray application which behaves the same way. The most used RSS application in Linux which is Akregator certainly does NOT reset unread articles count.

I'm sorry but your "everyone's opinion except mine doesn't count/sucks" stance won't earn you new users or co-developers. But I guess you don't care.
