### ISSUE TITLE
Liferea allows tracking/spying on the user

### ISSUE THREAD

**Issue by birdie-github** [lwindolf/liferea#324]
Again this is a huge privacy problem - not a feature request.

Liferea has no settings in regard to 1) **cookies** 2) **web cache** 3) **user agent**.

That means websites are free to spy on you using cookies, infinite cookies (images with no/infinite expiration date), web browser user agent.

**Comment by lwindolf** [comment]
Liferea does not allow spying per se. Using ever cookies they are able to do this all the same with all of the suggested options implemented. The goal of Liferea is not a maximum of privacy. So this boils down to a privacy feature request.

I understand the wish for privacy options though.

**Comment by GreenLunar** [comment]
Related to #270
