### ISSUE TITLE
Search is case sensitive for everything uppercase

### ISSUE THREAD

**Issue by hphde** [lwindolf/liferea#332]
Hi,

I was searching a string and wrote the word lower case and it wasn't found. Obviously it was there and then I saw it was written all uppercase.

I tried some tests and it seems words starting with a single starting uppercase character are not affected.

Kind regards,
HP

**Comment by nekohayo** [comment]
That's interesting, from my testing I was under the impression that everything was case sensitive all the time... and I would love to have a checkbox in the search conditions somewhere to be able to set a particular condition to be case (in)sensitive. Currently, I have to deduplicate 3-4 times my search folders to account for "most" possible scenarios, but I'd rather really have the ability to have case insensitive searches.
