### ISSUE TITLE
Feedbin integration

### ISSUE THREAD

**Issue by brendan-r** [lwindolf/liferea#338]
Hello,

Firstly, thank you for Liferea!

I've been looking to use a server to synch feeds recently, and [feedbin](https://feedbin.com/) stood out as being [FOSS](https://github.com/feedbin/feedbin), under active development, user respecting, and rather nice to look at. It's also well integrated with mobile clients. It has a [simple API](https://github.com/feedbin/feedbin-api) which uses basic auth.

If I had any experience with C, I'd be sending a pull request, but unfortunately I'm pretty clueless :confused: 

Is feedbin integration possible?

Brendan

**Comment by lwindolf** [comment]
Judging from the API implementing it wouldn't be hard. The problem I see is the user base. The use case being someone using both FeedBin (e.g. on Mac or Windows) and Liferea on Linux just seems not very widely distributed.

Future plan for Liferea is to move all online source subscription support into Python plugins that can be easily copied/adapted to other online services.

**Comment by lwindolf** [comment]
For now closing this as a feature request.

**Comment by brendan-r** [comment]
Makes sense, thanks! ::+1::
