### ISSUE TITLE
Disable smooth scrolling for feeds and items entirely

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#340]
For feeds and items only.

Always scroll per item(s). Never scroll smoothly (per pixel) when using a touch pad/screen.

---

Realization from SMPlayer playlist

When scrolling, next entries are being entirely displayed, **step-by-step**, and not in between.  See attached animations.

Scrolling with UI scroll bar
![smplayer_playlist_scrollbar](https://cloud.githubusercontent.com/assets/2053884/14496203/1be1a65a-019b-11e6-8706-985b7fee0139.gif)

Scrolling with a laptop touch pad
![smplayer_playlist_touchpad](https://cloud.githubusercontent.com/assets/2053884/14496218/25ab0852-019b-11e6-853c-314fcbade4ec.gif)

**Comment by lwindolf** [comment]
I believe this is entirely a toolkit issue. This should be a issue against GTK not a specific GTK using application. AFAIK there are some guys working on improving widgets for touchpads.

**Comment by GreenLunar** [comment]
Would you reopen this issue if we find that there is an option to choose scrolling type?

See https://github.com/QupZilla/qupzilla/issues/1907 (Qt toolkit) `QAbstractItemView::ScrollPerItem` against `QAbstractItemView::ScrollPerPixel`

**Comment by GreenLunar** [comment]
Gnumeric (GTK+3) is able to scroll per items (column and row).
