### ISSUE TITLE
please migrate liferea to use python3 (libpeas loader)

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#346]
In Debian (and thus Ubuntu) work is in progress to get rid of python2 as upstream support for that is going to finish before the end of support of the next Debian release. liferea currently uses the python2 libpeas loader. Could you please migrate to the python3 loader?

Debian bug that triggered this: https://bugs.debian.org/817852

**Comment by lwindolf** [comment]
With Jessie now being stable I believe it makes sense to switch to Python 3 entirely. The only thing I would wish for would be a libpeas Python 3 migration guide...

Will try to include this in 1.12-RC's

**Comment by lwindolf** [comment]
Fixed thans to @picsel2
