### ISSUE TITLE
Liferea does not show any errors or prompts when clicking on some types of content. (Debian Bug # 660597) 

### ISSUE THREAD

**Issue by Sidicas** [lwindolf/liferea#348]
Liferea does not show any errors or prompts when clicking on some types of content.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=660597

Comments in the bug say that you need to "Register a prompt service"

There is also some example code in the bug report.

Is this something that can be fixed on the liferea side? Or perhaps a message that it juts can't be opened.

Currently, if you click on something that can't be opened, there is no feedback to the user at all.  So the user doesn't understand why their .pdf link doesn't open.

Found in:
Package: liferea
Version: 1.10.12
Version: 1.10.19

**Comment by lwindolf** [comment]
That's true. I know of this behaviour for example when clicking PDF links, FTP links or Javascript links.

At least different protocols should be fixable in the Webkit view.

**Comment by Leiaz** [comment]
What should be done with the files ? Should they be downloaded like enclosures, like the "Save Link As" menu item, or by asking for a filename and using WebKitDownload ?

**Comment by lwindolf** [comment]
I do not have a preference here. Using "Save Link As" would have the advantages of having only one code path to support.
