### ISSUE TITLE
Space to skim through articles is not working. (Debian Bug# 706056)

### ISSUE THREAD

**Issue by Sidicas** [lwindolf/liferea#349]
Space to skim through articles is not working.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=706056

It seems this issue was previously fixed.
https://sourceforge.net/p/liferea/mailman/message/9639687/

However, it is not currently working in the following versions:

Package: liferea
Version: 1.10.12
Version: 1.10.19

Let me know if you need any more info.

**Comment by lwindolf** [comment]
Merged PR from @mozbugbox. Should be fixed now. Please retest!
