### ISSUE TITLE
Tray icon does not display properly on all desktops (Debian Bug# 436348)

### ISSUE THREAD

**Issue by Sidicas** [lwindolf/liferea#350]
Tray icon does not display properly on all desktops

I was thinking this was just a resolution issue, but no matter how much I adjust the tray size or liferea icon size, it does not seem to display properly on LXDE (and reportedly, other DEs too).

![lxdeiconissue](https://cloud.githubusercontent.com/assets/845776/15277360/42e75b42-1ac7-11e6-8343-aca4db749abd.png)

![lxdeiconissue2](https://cloud.githubusercontent.com/assets/845776/15277362/4633f026-1ac7-11e6-8997-9bb31ddc11a0.png)

Liferea
1.10.19

Debian Sid / Unstable

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=436348
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=667885

**Comment by Leiaz** [comment]
It looks similar to issue #177.

**Comment by mozbugbox** [comment]
The trayicon just need to response to the `size-changed` event and scale the pixbuf of the icon.

I guess it's a bug in Gtk+. The Gtk+ doc said it will auto resize pixbuf to fit statusicon, but didn't.

see 2306fadb1a719f651d986f909ee622dd820c2239 @mozbugbox

**Comment by lwindolf** [comment]
Please retest!

**Comment by hugomg** [comment]
Is there a way to test the updated liferea binary *without* installing it? I tried running `./src/liferea` after `./configure` and `make` but it crashes complaining that it wanted to have been installed to /usr/local

    ** (liferea:15128): ERROR **: Loading /usr/local/share/liferea/liferea.ui failed

**Comment by lwindolf** [comment]
No, there isn't because those .ui ressource need to reside in a well known path that is passed on configure time.

You might want to do this:

    ./configure --prefix=$HOME/liferea-test 
    make
    make install

and run

   $HOME/liferea-test/bin/liferea

Later on just remove $HOME/liferea-test

**Comment by hugomg** [comment]
Good news! I can now confirm that the annoying tray icon bug is gone, at least for me (XFCE on Debian Testing).

-----------

However, changing the prefix as you suggested was still not enough to install liferea in a nonstandard directory. When I tried doing `./configure --prefix=/tmp/liferea-test`liferea ended up crashing with a gsettings-related error:

    (liferea:25208): GLib-GIO-ERROR **: Settings schema 'net.sf.liferea' does not contain a key named 'do-not-track'
    fish: “/tmp/lifereatest/bin/liferea” terminated by signal SIGTRAP (Trace or breakpoint trap)

The workaround I found for this was to change the `XDG_DATA_DIRS` environment variable:

    env XDG_DATA_DIRS="/tmp/liferea-test/share:$XDG_DATA_DIRS" /tmp/liferea-test/bin/liferea

This feels like a bug for me. Either there is a way to change the ./configure script so that liferea can find the `net.sf.liferea.gschema.xml` file (like it could do with `liferea.ui`) or this is something that should be documented somewhere in the readme... Should we open a new issue for this?

**Comment by lwindolf** [comment]
@hugomg Thank you for retesting. I am glad to hear it works.

About the configure issue: yes, please open a ticket for this.

**Comment by GeneralFailer** [comment]
The icon is still bugged for me on 1.12-rc2.
![screenshot_2017-02-11_02-58-22](https://cloud.githubusercontent.com/assets/9321788/22848532/4bb9a058-f006-11e6-92c7-60fc89e95b4a.png)

I'm using Arch Linux w/ Xfce.

**Comment by lwindolf** [comment]
@GeneralFailer Can you explain the buggy rendering you see in the screenshot? While it is not perfect I do not see any obvious sizing issue.

**Comment by GeneralFailer** [comment]
Never mind I guess. It's been a huge pain in the ass to determine whether the unread item counter works since you've implemented #323.

**Comment by GeneralFailer** [comment]
Oh right, it actually doesn't work most of the time.
