### ISSUE TITLE
Store and refer to feed icon by domain/sub-domain name

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#352]
From #344

Liferea should not store an icon per feed. If user is subscribed to feeds http://lzone.de/taxonomy/weather and http://lzone.de/taxonomy/traffic, there should be a single icon for both under the name `lzone.de.png`, and http://liferea.lzone.de/ would use `liferea.lzone.de.png`.

It would be more sensible, and there would be less clutter and duplicated files under `~/.cache/liferea/favicons`.

**Comment by da2x** [comment]
Invalid. Feeds and web documents from the same domain can have different icons. It’s stored in $XDG_HOMER_CACHE anyway, so no need to be super tidy.

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
