### ISSUE TITLE
dark theme option - too bright

### ISSUE THREAD

**Issue by tecan** [lwindolf/liferea#354]
would be nice to have a dark theme option for those nightreaders (something easier on the eyes). gtk themes dont seem to work properly.

**Comment by lwindolf** [comment]
There are 3 solutions:

- Liferea follows the dark theme hinting and pre-defined colors from GTK. So if you configure a dark theme globally Liferea will use it.
- If you want to run a light theme you can enable the dark theme for Liferea only: http://unix.stackexchange.com/questions/14129/gtk-enable-set-dark-theme-on-a-per-application-basis
- Finally there is a plugin based solution by @mozbugbox https://github.com/mozbugbox/liferea-plugin-studio

If you are already running with a dark theme I suspect the third option can help you. Please let me know if it works!

**Comment by lwindolf** [comment]
Also added hints to FAQ https://lzone.de/liferea/faq.htm#dark-theme

**Comment by tecan** [comment]
there is still an issue when launching the application from another user into an existing xsession with those methods though.

**Comment by tecan** [comment]
figured it out, turns out it was my current theme. thanks

**Comment by lwindolf** [comment]
Awesome.

**Comment by whizse** [comment]
Apologies for bumping old (closed) bugs!

I started writing  a simple dark theme plugin available here: https://github.com/whizse/liferea-plugins/tree/master/dark-mode

It's a little bit easier than setting an environment variable (and sets the window border dark too). In addition it uses a custom dark CSS that seems to work ok for most sites.

Caveat: I don't really use it everyday so it's a bit "how ya goin"  overall, and will probably not see many updates.

**Comment by lwindolf** [comment]
@whizse Feel free to reference it in plugins/plugin-list.json so it becomes visible in the plugin installer!
