### ISSUE TITLE
Export all feeds to other computers

### ISSUE THREAD

**Issue by aleandrodasilva** [lwindolf/liferea#356]
I would like to export the database of all feeds to other computers in order to preserve them and not only the feedlist in the format opml. Maybe I'm wrong but I didn't find this option.

**Comment by lwindolf** [comment]
As Liferea follows the XDG directory standard it is just copying the relevant XDG directories to the other computer. The following bash command shows you all non-cache files locations Liferea uses on a typical setup:

    find $HOME/{.config,.local/share}

If you transfer all of them to another computer it should be fine.

**Comment by lwindolf** [comment]
I added this to the FAQ https://lzone.de/liferea/faq.htm#how-to-copy-remote
