### ISSUE TITLE
comments cause compile fails

### ISSUE THREAD

**Issue by heynnema** [lwindolf/liferea#357]
Comments are starting with /**. Should be /*.

Ubuntu 16.04

Cheers, Al

**Comment by lwindolf** [comment]
Can you post the exact compiler output? I'm really confused so far because that is C and comments do start with // or /*

**Comment by heynnema** [comment]
Lars,

Sorry for the confusion, some *'s got lost. It was supposed to say
"replaced comment start /** with /*".

Cheers, Al

Al Heynneman
heynnema@gmail.com

**Comment by Leiaz** [comment]
That can't cause compilation to fail. The second `*` is part of the comment. It is used to mark the comment for doc generation tools.

What is the actual error message ?

**Comment by heynnema** [comment]
On 06/25/2016 12:33 AM, Leiaz wrote:
>
> That can't cause compilation to fail. The second |*| is part of the 
> comment. It is used to mark the comment for doc generation tools.
>
> What is the actual error message ?
>

I changed one instance in auth.c, and did a make (did not do a make 
clean first), and I got this...

$ make
Making all in parsers
make[1]: Entering directory '/home/alheynneman/src/liferea/src/parsers'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alheynneman/src/liferea/src/parsers'
Making all in ui
make[1]: Entering directory '/home/alheynneman/src/liferea/src/ui'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alheynneman/src/liferea/src/ui'
Making all in fl_sources
make[1]: Entering directory '/home/alheynneman/src/liferea/src/fl_sources'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alheynneman/src/liferea/src/fl_sources'
Making all in webkit
make[1]: Entering directory '/home/alheynneman/src/liferea/src/webkit'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alheynneman/src/liferea/src/webkit'
Making all in tests
make[1]: Entering directory '/home/alheynneman/src/liferea/src/tests'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/alheynneman/src/liferea/src/tests'
Making all in .
make[1]: Entering directory '/home/alheynneman/src/liferea/src'
   CC       auth.o
   CCLD     liferea
   GISCAN   Liferea-3.0.gir
auth.c:2: Error: Liferea: identifier not found on the first line:
  * @file auth.c  authentication helpers
    ^

(liferea:30301): GLib-GIO-CRITICAL **: g_settings_get_value: assertion 
'G_IS_SETTINGS (settings)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_get_string: assertion 
'value != NULL' failed

(liferea:30301): GLib-CRITICAL **: g_variant_unref: assertion 'value != 
NULL' failed

(liferea:30301): GLib-GIO-CRITICAL **: g_settings_get_value: assertion 
'G_IS_SETTINGS (settings)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_get_type: assertion 'value 
!= NULL' failed

(liferea:30301): GLib-CRITICAL **: g_variant_type_is_subtype_of: 
assertion 'g_variant_type_check (type)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_get_boolean: assertion 
'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_unref: assertion 'value != 
NULL' failed

(liferea:30301): GLib-GIO-CRITICAL **: g_settings_get_value: assertion 
'G_IS_SETTINGS (settings)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_get_type: assertion 'value 
!= NULL' failed

(liferea:30301): GLib-CRITICAL **: g_variant_type_is_subtype_of: 
assertion 'g_variant_type_check (type)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_get_boolean: assertion 
'g_variant_is_of_type (value, G_VARIANT_TYPE_BOOLEAN)' failed

(liferea:30301): GLib-CRITICAL **: g_variant_unref: assertion 'value != 
NULL' failed

(liferea:30301): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(liferea:30301): GLib-GObject-CRITICAL **: g_signal_connect_data: 
assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed

(liferea:30301): GLib-GObject-WARNING **: invalid (NULL) pointer instance

(liferea:30301): GLib-GObject-CRITICAL **: g_signal_connect_data: 
assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
enclosure.h:50: Warning: Liferea: enclosure_from_string: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
enclosure.h:113: Warning: Liferea: enclosure_mime_types_get: return 
value: Missing (element-type) annotation
item.h:84: Warning: Liferea: item_new: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
item.h:95: Warning: Liferea: item_load: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
item.h:102: Warning: Liferea: item_copy: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
itemset.h:52: Warning: Liferea: itemset_foreach: argument callback: 
Missing (scope) annotation for callback without GDestroyNotify (valid: 
call, async)
itemset.h:65: Warning: Liferea: itemset_merge_items: argument items: 
Missing (element-type) annotation
node.h:84: Warning: Liferea: node_new: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:93: Warning: Liferea: node_is_used_id: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:103: Warning: Liferea: node_from_id: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:233: Warning: Liferea: node_get_icon: return value: Missing 
(transfer) annotation
node.h:241: Warning: Liferea: node_get_large_icon: return value: Missing 
(transfer) annotation
node.h:311: Warning: Liferea: node_get_itemset: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
ui/icons.h:73: Warning: Liferea: icon_create_from_file: return value: 
Missing (transfer) annotation
ui/media_player.h:35: Warning: Liferea: liferea_media_player_load: 
argument enclosures: Missing (element-type) annotation
fl_sources/node_source.h:241: Warning: Liferea: 
node_source_root_from_node: return value: Invalid non-constant return of 
bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:249: Warning: Liferea: node_source_setup_root: 
return value: Invalid non-constant return of bare structure or union; 
register as boxed type or (skip)
fl_sources/node_source.h:309: Warning: Liferea: 
node_source_add_subscription: return value: Invalid non-constant return 
of bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:327: Warning: Liferea: node_source_add_folder: 
return value: Invalid non-constant return of bare structure or union; 
register as boxed type or (skip)
fl_sources/node_source.h:352: Warning: Liferea: 
node_source_find_or_create_folder: return value: Invalid non-constant 
return of bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:395: Warning: Liferea: 
node_source_get_node_type: return value: Unresolved type: 'nodeTypePtr'
enclosure.h:50: Warning: Liferea: enclosure_from_string: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
enclosure.h:113: Warning: Liferea: enclosure_mime_types_get: return 
value: Missing (element-type) annotation
node.h:84: Warning: Liferea: node_new: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:93: Warning: Liferea: node_is_used_id: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:103: Warning: Liferea: node_from_id: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
node.h:233: Warning: Liferea: node_get_icon: return value: Missing 
(transfer) annotation
node.h:241: Warning: Liferea: node_get_large_icon: return value: Missing 
(transfer) annotation
node.h:311: Warning: Liferea: node_get_itemset: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
item.h:84: Warning: Liferea: item_new: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
item.h:95: Warning: Liferea: item_load: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
item.h:102: Warning: Liferea: item_copy: return value: Invalid 
non-constant return of bare structure or union; register as boxed type 
or (skip)
fl_sources/node_source.h:241: Warning: Liferea: 
node_source_root_from_node: return value: Invalid non-constant return of 
bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:249: Warning: Liferea: node_source_setup_root: 
return value: Invalid non-constant return of bare structure or union; 
register as boxed type or (skip)
fl_sources/node_source.h:309: Warning: Liferea: 
node_source_add_subscription: return value: Invalid non-constant return 
of bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:327: Warning: Liferea: node_source_add_folder: 
return value: Invalid non-constant return of bare structure or union; 
register as boxed type or (skip)
fl_sources/node_source.h:352: Warning: Liferea: 
node_source_find_or_create_folder: return value: Invalid non-constant 
return of bare structure or union; register as boxed type or (skip)
fl_sources/node_source.h:395: Warning: Liferea: 
node_source_get_node_type: return value: Unresolved type: 'nodeTypePtr'
feedlist.h:64: Warning: Liferea: feedlist_create: return value: Missing 
(transfer) annotation
feedlist.h:71: Warning: Liferea: feedlist_get_selected: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
feedlist.h:111: Warning: Liferea: feedlist_get_root: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
feedlist.h:131: Warning: Liferea: feedlist_find_node: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
feedlist.h:141: Warning: Liferea: feedlist_add_subscription: argument 
options: Unresolved type: 'updateOptionsPtr'
feedlist.h:257: Warning: Liferea: feedlist_find_unread_feed: return 
value: Invalid non-constant return of bare structure or union; register 
as boxed type or (skip)
itemlist.h:64: Warning: Liferea: itemlist_create: return value: Missing 
(transfer) annotation
itemlist.h:71: Warning: Liferea: itemlist_get_displayed_node: return 
value: Missing (transfer) annotation
itemlist.h:78: Warning: Liferea: itemlist_get_selected: return value: 
Invalid non-constant return of bare structure or union; register as 
boxed type or (skip)
itemlist.h:172: Warning: Liferea: itemlist_remove_items: argument items: 
Missing (element-type) annotation
itemlist.h:217: Warning: Liferea: itemlist_add_search_result: argument 
loader: Unresolved type: 'ItemLoader*'
ui/liferea_htmlview.h:83: Warning: Liferea: liferea_htmlview_get_widget: 
return value: Missing (transfer) annotation
ui/liferea_htmlview.h:227: Warning: Liferea: htmlview_get_impl: return 
value: Invalid non-constant return of bare structure or union; register 
as boxed type or (skip)
ui/browser_tabs.h:63: Warning: Liferea: browser_tabs_create: return 
value: Missing (transfer) annotation
ui/browser_tabs.h:88: Warning: Liferea: 
browser_tabs_get_active_htmlview: return value: Missing (transfer) 
annotation
ui/itemview.h:198: Warning: Liferea: itemview_find_unread_item: return 
value: Invalid non-constant return of bare structure or union; register 
as boxed type or (skip)
ui/itemview.h:242: Warning: Liferea: itemview_create: return value: 
Missing (transfer) annotation
ui/item_list_view.h:82: Warning: Liferea: item_list_view_get_widget: 
return value: Missing (transfer) annotation
ui/item_list_view.h:222: Warning: Liferea: 
item_list_view_find_unread_item: return value: Invalid non-constant 
return of bare structure or union; register as boxed type or (skip)
ui/item_list_view.h:73: Warning: Liferea: item_list_view_create: return 
value: Missing (transfer) annotation
ui/liferea_shell.h:78: Warning: Liferea: liferea_shell_lookup: return 
value: Missing (transfer) annotation
ui/liferea_shell.h:208: Warning: Liferea: liferea_shell_get_window: 
return value: Missing (transfer) annotation
ui/media_player_activatable.h:61: Warning: Liferea: 
liferea_media_player_activatable_load: argument enclosures: Missing 
(element-type) annotation
   GICOMP   Liferea-3.0.gir
make[1]: Leaving directory '/home/alheynneman/src/liferea/src'

> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/lwindolf/liferea/issues/357#issuecomment-228519682>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABUsXgziTe1qDPPujDuCXS26bNIs2j1Eks5qPNm5gaJpZM4I9_bo>.
>


-- 
*Al Heynneman*
heynnema@gmail.com

**Comment by Leiaz** [comment]
This is a GObject Introspection / GTK-Doc error, not a compile error. You added a `*` to the comment at the top of auth.c, so GTK-Doc tried to interpret it, but can't because [it doesn't start with an identifier]( https://developer.gnome.org/gtk-doc-manual/stable/documenting_syntax.html.en).

Not all files are formatted properly for GTK-Doc but that doesn't stop Liferea from compiling.

**Comment by heynnema** [comment]
On 06/25/2016 09:35 AM, Leiaz wrote:
>
> This is a GObject Introspection / GTK-Doc error, not a compile error. 
> You added a |*| to the comment at the top of auth.c, so GTK-Doc tried 
> to interpret it, but can't because it doesn't start with an identifier 
> <https://developer.gnome.org/gtk-doc-manual/stable/documenting_syntax.html.en>.
>

You requested what the error message(s) were, so I changed one instance 
of the first comment that I found in auth.c, back to the original way 
that I found it, that is "/**", and that is what fails. Changing all of 
the original instances of /** to /* fixes all of the compilation noise. 
Changing the /** to "/* *" probably would have worked too. Does that 
make any sense?

Cheers, Al

> Not all files are formatted properly for GTK-Doc but that doesn't stop 
> Liferea from compiling.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/lwindolf/liferea/issues/357#issuecomment-228555100>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ABUsXhcmoaZhmM-gRVAuOawNdGqTbBIVks5qPVjTgaJpZM4I9_bo>.
>


-- 
*Al Heynneman*
heynnema@gmail.com

**Comment by lwindolf** [comment]
Ah, I see now. You are worried about the GIR scanner warnings.

I do promise to further improve them file by file, but working through all of them now is not worth the effort. I hope you understand.
