### ISSUE TITLE
Liferea icon in task bar

### ISSUE THREAD

**Issue by Surfoo** [lwindolf/liferea#359]
Hello,

I'm using Manjaro Gnome 16.06 (Gnome 3.20)  and here the top icon in the task bar : 
![liferea](https://cloud.githubusercontent.com/assets/553659/16585640/3a36adea-42c2-11e6-93ee-942dd55dd85d.png)

The image is repeated...

**Comment by Leiaz** [comment]
This is identical to issue #177. There is a fix in git master branch.

**Comment by lwindolf** [comment]
I believe this to be fixed with 1.12-RC1
