### ISSUE TITLE
UI can lock up (freeze) during refresh operations - not fully asynchronous

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#36]
It happens quite often than when I click a folder or feed, while Liferea is refreshing, the click is completely ignored. I wait a couple seconds, realize it has been ignored, click again and it works.

That alone sounds a bit tricky to debug, but there's an easier way: trigger a global refresh and use the mousewheel to quickly and repeatedly scroll up/down in the listview widget of a feed's items... and you will get something that freezes/hiccups.

In theory the whole thing should be async and never block the gtk main loop.

**Comment by lwindolf** [comment]
Closing old ticket, as there have been no more recent reports on this.
