### ISSUE TITLE
Missing some spacing above the internal browser's address bar

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#363]
The internal browser has a navigation/address bar, but the spacing around it is not uniform, it only has some spacing on the bottom:

![liferea tabs look](https://cloud.githubusercontent.com/assets/479401/16901932/049c0df4-4c1f-11e6-9801-97a925aada4e.png)

Instead, it should the same 3px spacing ("border") all around the area, on the four sides.

**Comment by mikelolasagasti** [comment]
![liferea-363](https://cloud.githubusercontent.com/assets/773148/20862546/fa65d43a-b9ad-11e6-9ee2-65876cfab3de.png)

Added 5px margin in my pull request
