### ISSUE TITLE
Search folders show permanent "unread" counters even when items are marked as read

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#365]
I use a ton of search folders to filter out things, or to find specific things cross-feeds that would require my attention. In the latter case, the problem is that the visual counters for search folders are never cleared, they represent the number of matching items instead of the number of matching _unread_ items. The 1st statistic is useless to me, while the 2nd one is the one I'd need.

**Comment by HNJAMeindersma** [comment]
Same problem

**Comment by lwindolf** [comment]
I believe we have fixed this with the search folder counter redesign. Should not be an issue anymore.
