### ISSUE TITLE
Segfault on start (fixed by removing nodes and items)

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#366]
This bug¹ report was filed against the Debian package (1.10.19-2).

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=827894

The reported "fixed" the issue by removing nodes and items from his non-corrupt database, which is available to reproduce the crash (58MB and confidential).

Original report:
============
liferea does not start: it shows the main window, and then segfaults:

  $ liferea
  
  (liferea:11306): libnotify-WARNING **: Failed to connect to proxy
  
  (liferea:11306): Gtk-WARNING **: Theme parsing error: gtk.css:10:17: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
  openjdk version "1.8.0_91"
  OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-2-b14)
  OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
  Segmentation fault
  
  (I wonder why a JDK output shows up)

This is the same under gdb:

  (gdb) run
  Starting program: /usr/bin/liferea 
  [Thread debugging using libthread_db enabled]
  Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
  [New Thread 0x7fffe1e6a700 (LWP 11510)]
  [New Thread 0x7fffe1669700 (LWP 11511)]
  [New Thread 0x7fffe0e68700 (LWP 11512)]
  
  (liferea:11505): libnotify-WARNING **: Failed to connect to proxy
  [New Thread 0x7fffd3fff700 (LWP 11513)]
  
  (liferea:11505): Gtk-WARNING **: Theme parsing error: gtk.css:10:17: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
  [New Thread 0x7fffcb9d5700 (LWP 11514)]
  [New Thread 0x7fff8b0d0700 (LWP 11515)]
  [New Thread 0x7fff890bc700 (LWP 11518)]
  [New Thread 0x7fff888bb700 (LWP 11519)]
  [New Thread 0x7fff83fff700 (LWP 11520)]
  [New Thread 0x7fff837fe700 (LWP 11522)]
  [New Thread 0x7fff82ffd700 (LWP 11530)]
  [New Thread 0x7fff827fc700 (LWP 11531)]
  [New Thread 0x7fff81ffb700 (LWP 11532)]
  [New Thread 0x7fff817fa700 (LWP 11533)]
  openjdk version "1.8.0_91"
  OpenJDK Runtime Environment (build 1.8.0_91-8u91-b14-2-b14)
  OpenJDK 64-Bit Server VM (build 25.91-b14, mixed mode)
  
  Program received signal SIGSEGV, Segmentation fault.
  0x00007ffff3a722a7 in gdk_pixbuf_get_from_surface () from /usr/lib/x86_64-linux-gnu/libgdk-3.so.0

I also tried purging all java packages from my system, and it still
segfaults.

If I remove ~/.local/share/liferea/liferea.db it doesn't segfault
anymore, but then I lose all my feeds.

The databse itself is not corrupted:

  $ sqlite3 liferea.db.backup .dump > /dev/null
  $ echo $?
  0

I removed nodes and items in the database, and liferea works again:

 sqlite3 ~/.local/share/liferea/liferea.db
 sqlite> delete from node
 sqlite> delete from items;

I'll keep the original database around just in case.

**Comment by Leiaz** [comment]
Without a gdb backtrace (with debug symbols) it is difficult to know where the crash is happening as Liferea doesn't directly call `gdk_pixbuf_get_from_surface`.

**Comment by paulgevers** [comment]
@Leiaz would you rather have a gdb backtrace than the database to reproduce yourself?

**Comment by Leiaz** [comment]
The backtrace have the advantage that it can be posted publicly (with some strings redacted if necessary) if they want to keep the database private, and it may be sufficient to find the problem.

**Comment by paulgevers** [comment]
@Leiaz: the original reported can't reproduce anymore because he doesn't have the 1.8 version of liferea anymore that he had when it crashed. liferea 1.10 that he has now has a different layout. Do you think this bug should be closed, or do you find it still valuable to get his database?

**Comment by Leiaz** [comment]
No, unless someone else wants it. There are enough things to fix while waiting to see if it happens again :)

**Comment by paulgevers** [comment]
Ok, closing then, just like I did with the Debian bug.
