### ISSUE TITLE
liferea-add-feed segfaults on specific feed

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#368]
This is a copy of bug 831997 reported in Debian¹ which I can reproduce on my system as well:

I can reproducibly crash liferea-add-feed (not being able to add any feeds) via:

$ liferea-add-feed http://googleresearch.blogspot.com/atom.xml
Segmentation fault (core dumped).

 The backtrace is:

#0  0x00007fb7dca3a651 in g_application_impl_open (impl=0x0, files=<optimized out>, n_files=<optimized out>, hint=0x45f7f5 "feed-add", platform_data=0x23a1f30)
    at /build/glib2.0-vjfO_h/glib2.0-2.48.1/./gio/gapplicationimpl-dbus.c:631
631	/build/glib2.0-vjfO_h/glib2.0-2.48.1/./gio/gapplicationimpl-dbus.c: No such file or directory.
[Current thread is 1 (Thread 0x7fb7e1b95ac0 (LWP 5652))]
(gdb) bt
#0  0x00007fb7dca3a651 in g_application_impl_open (impl=0x0, files=<optimized out>, n_files=<optimized out>, hint=0x45f7f5 "feed-add", platform_data=0x23a1f30)
    at /build/glib2.0-vjfO_h/glib2.0-2.48.1/./gio/gapplicationimpl-dbus.c:631
#1  0x000000000041b44d in main ()

¹ https://bugs.debian.org/831997

**Comment by beroal** [comment]
Could you please include this in the version 1.10?
