### ISSUE TITLE
Share/publish feature

### ISSUE THREAD

**Issue by goodevilgenius** [lwindolf/liferea#369]
3/4 services that liferea synch with (viz. InoReader, TOR, tt-rss) offer some sort of share/publish feature, allowing  the user to share an article with other users on the service.

It would be great if this was supported directly from Liferea.

N.B., this is very different from #136, which was a request to share with *other* services, rather than the same service.

**Comment by lwindolf** [comment]
Closing this as it is a feature request.

**Comment by goodevilgenius** [comment]
Where would you like feature requests sent?

**Comment by lwindolf** [comment]
Sorry, the project has a "No feature request" policy (check https://lzone.de/liferea/faq.htm#feature-x). This is due to missing time and developers!

**Comment by goodevilgenius** [comment]
Ok. I guess I'll see if I can do it myself as a plugin.

**Comment by lwindolf** [comment]
Let me know if you need help!
