### ISSUE TITLE
Liferea tips not showing up on docs page

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#373]
On this page http://lzone.de/liferea/docs.htm there are 10 links to useful links.
If you click on any of them, like http://lzone.de/Liferea-Trick-1-Middle-Mouse-Button, it takes you 
to a different looking page 'powered by discus''  which has the title of the trick, some ad-looking stuff, a place for comments, but no comments, and no content.  

I thought I went through these tricks sometime in the past and I think I remember something quite different.   

Is anybody else seeing the same thing?

**Comment by lwindolf** [comment]
Thanks a lot for the hint. I fixed all the URIs to point at the proper places.

**Comment by rich-coe** [comment]
Working much better!  Thanks.
