### ISSUE TITLE
Number of Headlines annoyance

### ISSUE THREAD

**Issue by RealVegOs** [lwindolf/liferea#374]
Enough is enough! I want an option to set the default number of headlines permanently. I don't want to drag the upper window part higher each morning. BTW, the separation line to do this (see pointers below), is way to thin! There should be a better handle.

![lifera_24-08-16](https://cloud.githubusercontent.com/assets/7726676/17917333/af153846-69bb-11e6-9f7c-41453991286a.png)

I wonder, if you all really use Liferea or why I am the only one who is annoyed by this GUI glitch.

**Comment by lwindolf** [comment]
I agree that the resize panes handles are much to small in your screenshot.

These handles are rendered by GTK which is themed using a theme you choose. There is nothing any application can do about it :-(

**Comment by RealVegOs** [comment]
It's not quite fair to close this issue and mark it invalid. It's much easier in other programs to change the hight of the upper window part, e.g. in Sylpheed. The other thing is, you did not answer about the my feature request to set the default number of Headline in the options. That means, setting the default hight of the window part. It's always reset to about 70 pixels when I start the program. I want 200 at least, for more headlines. That's the biggest annoyance witch devaluates Liferea for me! Cheers, you made it great, make life hard for an old man (born 1954).

**Comment by lwindolf** [comment]
About the height of the headline pane: the idea here is for Liferea to just remember what it was last, so it always stays the same for you.

Which version of Liferea are you currently using?

**Comment by RealVegOs** [comment]
I use 1.10.12 from Debian stable.

**Comment by lwindolf** [comment]
Sorry for the late response. The headline pane issue you experience was fixed in 1.10.16. From the ChangeLog:

        * Fixes Github #140, #158: Vertical pane placement is forgotten.
          (patch by foresto)

Can you please retest with latest 1.10.19 release? Of course it is not in Debian yet :-(

**Comment by paulgevers** [comment]
I plan to backport 1.12 if there is demand once we have the issues ironed out.

@RealVegOs normally you should report issues you encounter in Debian packages to the Debian bug tracker (with "reportbug package-name"), especially if you are running stable. Of course you can report upstream (like you did), but there is always a reasonable chance that the bug you experience is already resolved (like here).
