### ISSUE TITLE
Cannot manually update a feed

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#377]
When a feed subscription has issues (poor date formatting in feed xml) and you are trying to develop a script to fix the issue, lifrea (1) caches the feed content and (2) records the date of feed.  If you want to manually update the feed subscription,  the only way to fetch a new copy of the feed for processing is to invalidate the recorded date in the db record for the subscription.  The other option is to wait for the feed content to update.

I think that a manual 'update this feed' from the subscription of the feed in the UI should force the update, perhaps by changing the date?   Another option would be to offer a force option only on the feed's subscription menu.   The menu for either option is the one that is invoked from right clicking on the subscription in the left sidebar.

**Comment by GreenLunar** [comment]
Another way is to restart Liferea.

For these cases, I am downloading the source URL, loading it locally, and once I am done processing, I am replacing the source to the original URL.

**Comment by da2x** [comment]
Reload the feed twice to bypass caching. (That is a bug, by the by.)

**Comment by lwindolf** [comment]
Should be fixed since #580 was released with 1.13.3
