### ISSUE TITLE
Cannot add feed http://www.thebookoflife.org/feed/

### ISSUE THREAD

**Issue by alexandru-calinoiu** [lwindolf/liferea#379]
Trying to add http://www.thebookoflife.org/feed/ I get the following error 

'The URL you want Liferea to subscribe to points to a webpage and the auto discovery found no feeds on this page. Maybe this webpage just does not support feed auto discovery.Could not determine the feed type.'

**Comment by Leiaz** [comment]
The parsing of the feed fails with error "CData section not finished" on line 1010. There is an invalid character on that line.

It fails in `xml_parse` but Liferea then attempts auto-discovery and the previous parse errors are discarded and not displayed.

**Comment by lwindolf** [comment]
@Leiaz Thanks for triaging.

@alexandru-calinoiu Please contact the feed author / webmaster about this!
