### ISSUE TITLE
Liferea process HTTP redirect code 307 incorrectly

### ISSUE THREAD

**Issue by jekhor** [lwindolf/liferea#38]
When my internet provider returns HTTP redirect 307 as answer to any request (there are no money at account, redirection to billing page), then Liferea automatically updates all feed URLs to feed of internet provider.

HTTP code 307 'Temporary Redirect' is temporary issue and must not cause feed URL updating.

**Comment by da2x** [comment]
I believe this was fixed by commit 323a1ee09829cf71b708adb0036f438e8f030a56 and can be closed.
