### ISSUE TITLE
add windows 10 support

### ISSUE THREAD

**Issue by midpoint** [lwindolf/liferea#385]
Hi,Is it possable to add windows 10 support ?
tks.

**Comment by midpoint** [comment]
I can't found a tiny tiny rss desktop client for windows 10.
welcome any ideas.

**Comment by midpoint** [comment]
I need a support TTS (tiny tiny RSS) RSS desktop client.Do you have any good recommendations?

**Comment by GreenLunar** [comment]
+1
Liferea on Windows is a good thing to have.

What does tks mean?

There is RSS Guard which can be run from a USB stick.
http://www.portablefreeware.com/index.php?id=2639
https://github.com/martinrotter/rssguard

**Comment by midpoint** [comment]
Thanks. I tried a little, RSS Guard is slow.
FeedDemon is the best I have ever used RSS client, but unfortunately it does not support the tiny tiny RSS. I Can't use my own server.

**Comment by lwindolf** [comment]
Work on Windows support is in progress. To complete the work I need to merge 4 additional patches...

**Comment by lwindolf** [comment]
Closing this as a duplicate to #339

**Comment by midpoint** [comment]
Thank lwindolf .
