### ISSUE TITLE
miss liferea_web_extension.h while building the 1.12 rc1.

### ISSUE THREAD

**Issue by PandaJim** [lwindolf/liferea#394]
I/usr/include/webkitgtk-4.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -c liferea_web_extension.c  -fPIC -DPIC -o .libs/liblifereawebextension_la-liferea_web_extension.o
liferea_web_extension.c:25:35: fatal error: liferea_web_extension.h: No such file or directory
compilation terminated.
web_extension_main.c:23:35: fatal error: liferea_web_extension.h: No such file or directory
compilation terminated.
Makefile:490: recipe for target 'liblifereawebextension_la-liferea_web_extension.lo' failed
make[5]: *** [liblifereawebextension_la-liferea_web_extension.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
Makefile:483: recipe for target 'liblifereawebextension_la-web_extension_main.lo' failed
make[5]: *** [liblifereawebextension_la-web_extension_main.lo] Error 1
make[5]: Leaving directory '/«PKGBUILDDIR»/src/webkit/web_extension'
Makefile:502: recipe for target 'all-recursive' failed
make[4]: *** [all-recursive] Error 1
make[4]: Leaving directory '/«PKGBUILDDIR»/src/webkit'
Makefile:822: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
make[3]: Leaving directory '/«PKGBUILDDIR»/src'
Makefile:653: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/«PKGBUILDDIR»'
Makefile:457: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/«PKGBUILDDIR»'
dh_auto_build: make -j4 returned exit code 2
debian/rules:12: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

https://launchpadlibrarian.net/285466553/buildlog_ubuntu-xenial-amd64.liferea_1.12~rc1-0build2+ubuntu16.04_BUILDING.txt.gz

**Comment by PandaJim** [comment]
Never mind, I've redownloaded the source (tar.gz) package instead of liferea-1.12-RC1.tar.bz2 package that seems work with the above issue, though there are still too many GObject Introspection / GTK-Doc error

**Comment by lwindolf** [comment]
I've fixed the sources (adding the missing .h to the Makefile.am) and attached a new tarball to the release.

Thanks for reporting!

**Comment by Leiaz** [comment]
Sorry, that's my clumsy use of the autotools. I didn't realize I had to put the headers there.

**Comment by lwindolf** [comment]
@Leiaz Don't worry. No problem at all. It's just me being to lazy to run "make dist-check"
