### ISSUE TITLE
1.12-RC1: http://www.openlayers.org/api/openlayers.js mentioned in xslt/item.xml

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#403]
The Changelog of 1.12-RC1 suggests that the calls to http://www.openlayers.org/api/openlayers.js are removed. However, xslt/item.xml.in contains another instance of the block that was removed in commit 5f92f23.

Note: I haven't verified that this code is used anywhere, I was triggered by a Lintian (Debian package checker) error.

**Comment by lwindolf** [comment]
Should be fine now.
