### ISSUE TITLE
All feeds diseapear time to time

### ISSUE THREAD

**Issue by M5oul** [lwindolf/liferea#405]
- Liferea 1.10.19
- Fedora 24

**Comment by GreenLunar** [comment]
Did you mean to the title count of each feed?

Please post a screenshot.

**Comment by M5oul** [comment]
I mean all unread feeds.

**Comment by M5oul** [comment]
Sometimes alll feeds disapear before 1 000 feeds at almost 100 feeds.
I don't know why.
It annoying to loose all feeds.
It great for cleaning, but I could do it manually 🐱

**Comment by M5oul** [comment]
Ok, I had to change the number of caching rss feeds kept in memory.
