### ISSUE TITLE
1.12-RC1: ctrl-space marks two articles as unread

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#406]
Locally I already run the 1.12-RC1 Debian package (the same that is available in Debian experimental, but build with gobject-introspection).

I love the functionality that was blogged about a while ago to jump to the next unread article. However, with 1.12-RC1, it doesn't jump to the next article, but to the one after that and marks the next one as unread as well.

Any tips on how to debug this?

**Comment by Leiaz** [comment]
You mean mark as read ? Already in #395.

**Comment by paulgevers** [comment]
@Leiaz,

On 07-10-16 12:50, Leiaz wrote:
> You mean mark as read ? Already in #395.

You are right, I meant "read". And sorry for not understanding that that bug was about this feature.

Paul
