### ISSUE TITLE
New Subscription button grey'd out.

### ISSUE THREAD

**Issue by Sidicas** [lwindolf/liferea#41]
Step 1: Set up a "News Source" such as TTRSS. Import your feeds.

Note: When you click on a TTRSS feed, your "New Subscription", "New Folder", "New Source", etc. is all grey'd out.

Step 2: Delete your "unread" and "important" folders.

Now all you have are your TTRSS feeds and your "New Subscription" button is still grey'd out.  No matter which feed you click on, your new subscription button is still grey'd out.  

Problem: No way to add feeds at this point without deleting ~/.config/liferea and starting over from scratch.

See attached screenshot:
http://imgur.com/Vf72uWm

**Comment by lwindolf** [comment]
I believe the behaviour in git master has now improved mostly because subscribing into TinyTinyRSS is possible. So the button doesn't get disabled. All currently supported online sources allow subscribing. So I think the issue is solved.

Please retest with git master or 1.11.3
