### ISSUE TITLE
No possibility to download non-media enclosures

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#413]
Liferea indicates, by icon, that a non-media (i.e. audio, video) attachment (such as ODT, ODS, PNG) is available, but it does not display an expand/collapse dialog at bottom of entry view, and so it cannot be reached using Liferea.

**Comment by Leiaz** [comment]
Which version are you using ? It should be fixed in 1.12  #361.

**Comment by GreenLunar** [comment]
I am using Liferea 1.11.7
