### ISSUE TITLE
[BiDi] Direction should be set by self content

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#414]
Current state:

Direction of entry content should **not** be determined by entry title.
Direction of feed description should **not** be determined by feed title.

Desired state:

Direction of entry content should be determined by entry content.
Direction of feed description should be determined by feed description.

~~I will attach an example feed later.~~

ATTACHMENT [xfce_mousepad.zip](https://github.com/lwindolf/liferea/files/552832/xfce_mousepad.zip)

**Comment by GreenLunar** [comment]
Three files attached https://github.com/lwindolf/liferea/files/552832/xfce_mousepad.zip

Content is in English.  Characters that interrupt proper direction are of RTL.

* xfce_mousepad_testing_feed.atom
* `</subtitle>` is displayed from a wrong direction
 - `</title> of `</feed >` has RTL character א (U+05D0).

* xfce_mousepad_testing_entry.atom
* `</<content>` is displayed from a wrong direction
 - `</title> of first `</entry >` has RTL character א (U+05D0);
 - `</title> of second `</entry>` has (an invisible) RTL character RLM (U+200F);
 - Third `</entry> remains untouched.

* xfce_mousepad.atom
* Original file from [git.xfce.org](https://git.xfce.org/apps/mousepad/atom/?h=master)

**Comment by GreenLunar** [comment]
@RealVegOs I think this issue also concerns you. Please subscribe to this thread.

**Comment by UsernamesAreFuckedUp** [comment]
Are there any updates on this? There are plenty of Persian, Arab, etc. guys using Liferea, and it's kind of disturbing to see this bug unfixed after 6 years.
