### ISSUE TITLE
Subscriptions of type Command are not asynchronous

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#415]
Command subscriptions appear to be running on main thread, so the UI of freezes each period a subscription of type command is being executed.

This problem is perceivable mostly when commands are downloading content remotely (e.g. from HTTP).

**Comment by rich-coe** [comment]
I'm suffer from this issue as well.

**Comment by rich-coe** [comment]
@GreenLunar Did you have any ideas on how to solve this?
I'm guessing that the update code happens on the main thread because all UI updates have to occur there.  I'm thinking that if there is a command option, then the command should run off the main thread and signal the main thread like it does now when complete.

**Comment by GreenLunar** [comment]
> Did you have any ideas on how to solve this?

Yes, I have set the subscription type to URL and retrieved page content via `STDIN` (see #428), and I have reserved only the processing operations to the script, which is used in Liferea as a filter.

It appears that regardless to Command type, there are other non-asynchronous operations, but I did not confirm this yet, as I still have a few Command subscriptions that interact with HTTP.

**Comment by GreenLunar** [comment]
The more I observe, the more it seems that neither downloading nor processing of of feeds is asynchronous, but I am using a "toaster" laptop (very old and very weak machine), so I could be wrong.

**Comment by rich-coe** [comment]
I have a fix for this that turned out to be rather simple.
I'll let it run for a few hours before issuing a pull request.

**Comment by GreenLunar** [comment]
Thank you, @rich-coe.
Pull request #463 has tremendously improved the performance of Liferea.

Yet, there are websites that I "scrape" information from in order to be readable with Liferea.
The websites with which I have problem with are those that require Javascript in order from information to be loaded; I think PhantomJS freezes Liferea.

Here is a subscription of _Command_ Source Type to load content from a webpage:
`phantomjs .local/share/liferea/scripts/content.js https://example.org/`

```
cat .local/share/liferea/scripts/content.js
/*
content
http://phantomjs.org/api/webpage/property/content.html
content {string}
This property stores the content of the web page (main 
frame), enclosed in an HTML/XML element. Setting the 
property will effectively reload the web page with the 
new content.
*/

var webPage = require('webpage'),
  page = webPage.create(),
  system = require('system'),
  address = system.args[1];

if (system.args.length === 1) {
  console.log('Usage: content.js <URL>');
  phantom.exit();
}

page.open(address, function (status) {
  var content = page.content;
  console.log(content);
  phantom.exit();
});
```

**Comment by rich-coe** [comment]
@greenlunar I've noticed liferea hanging as well.  I first looked at your script and there's nothing obvious to me to be causing a problem.
What I've noticed is that some pages, either in a feed or loaded on a tab have extensive javascript that causes the WebKitWebProcess to get hung.  As a work-around, I kill this process and liferea comes back.

ps -ef | egrep WebKit
// find pid of WebKitWebProcess, call it WEBPID
killl WEBPID

I currently under the assumption that something is causing a WebKit issue and when I upgrade next to an new WebKit version, the issue may be fixed.  My current webkit version is 4_0-37-2.16.0, which doesn't mean much to me.

**Comment by GreenLunar** [comment]
> What I've noticed is that some pages, either in a feed or loaded on a tab have extensive javascript that causes the WebKitWebProcess to get hung. As a work-around, I kill this process and liferea comes back.

Even so, I don't think that Liferea should be hanging.

**Comment by rich-coe** [comment]
I agree it should not be hanging.  I've been ignoring the issue for now.  I'll see what I can do to track down the issue.

**Comment by rich-coe** [comment]
I got a traceback during a 'hang'
```
#0  0x00007f282bcbcbaf in JSC::Interpreter::getStackTrace(WTF::Vector<JSC::StackFrame, 0ul, WTF::CrashOnOverflow, 16ul>&, unsigned long, unsigned long) () at /usr/lib64/libjavascriptcoregtk-4.0.so.18
#1  0x00007f282bf005e2 in JSC::Exception::finishCreation(JSC::VM&, JSC::JSValue, JSC::Exception::StackCaptureAction) () at /usr/lib64/libjavascriptcoregtk-4.0.so.18
#2  0x00007f282bf00669 in JSC::Exception::create(JSC::VM&, JSC::JSValue, JSC::Exception::StackCaptureAction) ()
    at /usr/lib64/libjavascriptcoregtk-4.0.so.18
#3  0x00007f282c0c8f0b in JSC::VM::throwException(JSC::ExecState*, JSC::JSValue) ()
    at /usr/lib64/libjavascriptcoregtk-4.0.so.18
#4  0x00007f282bd245cf in  () at /usr/lib64/libjavascriptcoregtk-4.0.so.18
[...]
#9998 0x00007f2818ed7000 in  ()
#9999 0x00007f26ce41cd00 in  ()
#10000 0x000000000000000a in  ()
#10001 0x00007f27364fc820 in  ()
#10002 0x00007f27364fc820 in  ()
[ ... and it keeps going ]
```
