### ISSUE TITLE
Image will not be displayed, unless its URL string is complete

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#419]
Assume a feed is located at `https://lzone.de/`

If a link is incomplete (eg. `/liferea/blog/Liferea+Trick+%235%3A+Privacy+with+a+SOCKS+Proxy`), Liferea automatically adds to it `https://lzone.de/`, which results in https://lzone.de/liferea/blog/Liferea+Trick+%235%3A+Privacy+with+a+SOCKS+Proxy

However, when it is so in images (ie. `</img>`), Liferea does not complete it, even though Liferea allows copying the full location of such image.

In order not to promote the following website (not posted yet), and not to spam your mailboxes, I will post example feed, after I done writing this post.

**Comment by Leiaz** [comment]
Which image is not being displayed in that feed ? Currently all items contain a `noimage_thumb.jpg` image that Liferea displays.

**Comment by GreenLunar** [comment]
Yes, that is the image. I am using Liferea 1.11.17.

I have posted a new link to an ATOM feed; please try it.

**Comment by Leiaz** [comment]
The broken images are those with relative urls and a relative path : `dir/image.jpg`. The relative urls with full path (`/dir/image.jpg`) appear to work.

**Comment by GreenLunar** [comment]
Thank you for checking. I have deleted the example link

**Comment by GreenLunar** [comment]
By the way, the URLs with full path are advertisements.

**Comment by Leiaz** [comment]
This was fixed by #457.
