### ISSUE TITLE
Crashes with various feed list treeview operations

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#42]
With 1.10.8, I experienced this randomly when reordering/moving feeds around across folders in the feeds list treeview. Just move them all around the place until you eventually get a crash.

The automated Fedora crash/stack catcher told me this was already caught and reported downstream, here, so it should have the relevant traces:

https://bugzilla.redhat.com/show_bug.cgi?id=1062807
https://retrace.fedoraproject.org/faf/reports/318270/

**Comment by lwindolf** [comment]
I can sometimes reproduce this. But found nothing conclusive yet.

**Comment by nekohayo** [comment]
Hm, the trace in the downstream reports isn't sufficient to identify the cause?

**Comment by lwindolf** [comment]
Another report in #611 

Sadly I can't reliably reproduce it  :-(
