### ISSUE TITLE
1.12-RC1 Internal browser shows files system on backup

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#423]
This report is taken straight from the Debian bug 841318¹, as I don't believe this is Debian specific.

¹ https://bugs.debian.org/841318

Became alarmed this morning when using the Liferea internal browser to
view a page from it's feed. When on the webpage, I clicked on an image
included in the page to enlarge it. When finished, I clicked the back
arrow in Liferea viewing area to go back to main page, and was taken
to the root of my file system, allowing me to view each file/directory as a hyperlink.
The desired outcome would be to take me to the original webpage, after
viewing enlarged thumbnail from said webpage.

![selection_10-19-1611-08-32001](https://cloud.githubusercontent.com/assets/3652166/19533817/a2fd97a8-9641-11e6-85d0-857a1e699a24.png)

**Comment by Leiaz** [comment]
I couldn't find thumbnails that reproduced this but the `file:///` url could end up in the navigation history and cause this. So this is likely fixed by #432 if they want to test.
