### ISSUE TITLE
Access to Web Inspector

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#426]
Allow users to access WebKit web inspector with content menu.
I suggest to make this a hidden GSettings option; or, alternatively, web inspector can be activated by key shortcut.

It would be more convenient than having to open an external web browser.

Even though, I think, this is an Enhancement, I am marking this as Feature Request because I sense that it could affect stability.

**Comment by lwindolf** [comment]
Did you check out @mozbugbox  plugin that does this already?

See: https://github.com/mozbugbox/liferea-plugin-studio

**Comment by GreenLunar** [comment]
I forgot about that plugin, even though I have it installed.

I have never managed to activate that plugin, as it returns `AttributeError`
