### ISSUE TITLE
Webkit2 support

### ISSUE THREAD

**Issue by vcunat** [lwindolf/liferea#430]
Hello! A quick question: do you expect to **soon** release some version that:
- supports building against webkitgtk-2.12, and
- is considered stable for being a default in a distro? (I'm not sure about RC-1.)

Thanks! The reasoning is security: I don't believe trying to patch up 2.4.x versions is really reliable. Downstream link:

**Comment by lwindolf** [comment]
In the next few days there will be an RC2 and there surely will be probably some more.

But after 5 releases or so there will be a new stable 1.12.0

Guessing from the bug reports so far the problems with 1.12-RC1 are more with users not liking changes than functional bugs.
