### ISSUE TITLE
Move from GnomeKeyring to libsecret

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#436]
libsecret works for both GNOME and KDE (and maybe other desktop environments). It is also API compatible (just renaming classes).

Therefore the gnome-keyring plugin should be ported to libsecret.

https://wiki.gnome.org/Projects/Libsecret
https://wiki.gnome.org/GnomeGoals/LibsecretMigration

**Comment by stephenbhope** [comment]
I'd like to work on this.

**Comment by paulgevers** [comment]
Please be aware that the libgnome-keyring library is deprecated and its usage is strongly
discouraged.

Today I received the following bug against the Debian package¹:
+++++++++++++++
Hi,

The libgnome-keyring library is deprecated and its usage is strongly
discouraged [1].

Your package liferea recommends or suggests gir1.2-gnomekeyring-1.0.

Please update your application to use libsecret/gir1.2-secret-1 instead [2].
Such a port should ideally happen with upstream being involved.

On behalf of the Debian GNOME team,
Michael Biebl

[1] https://git.gnome.org/browse/libgnome-keyring/commit/?id=6a5adea4aec93
[2] https://wiki.gnome.org/Projects/Libsecret
+++++++++++++++

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=867951

**Comment by lwindolf** [comment]
@stephenbhope Hey, so far no one has worked on this. Are you still interested in porting the GnomeKeyring plugin to libsecret?

**Comment by da2x** [comment]
@stephenbhope, still interested in this?
https://developer.gnome.org/libsecret/0.16/py-examples.html
https://github.com/lwindolf/liferea/blob/master/plugins/gnome-keyring.py

**Comment by bgermann** [comment]
I guess, this can be closed.
