### ISSUE TITLE
1.12-RC1: Tray icon is blur

### ISSUE THREAD

**Issue by Surfoo** [lwindolf/liferea#440]
Hello,

I just installed Liferea 1.12-RC1 on my manjaro (with Gnome 3.22.1) and the tray icon is not at the right size, and it's blur: 

![1 12-rc1](https://cloud.githubusercontent.com/assets/553659/19839673/49b0e4b8-9ee6-11e6-8e84-4842d424f8d8.png)

**Comment by mhoran** [comment]
I'm experiencing this as well, on MATE Desktop. The old icon looked great, but the new one is all blurry. It seems to remain blurry no matter what size I make the panel.

**Comment by mhoran** [comment]
I just noticed that the unread items icon looks fine, so it's just the 0 unread icon that is blurry.

**Comment by glaubersm** [comment]
Same problem on KDE Plasma desktop environment.
Even unread items icon looks blurry.

liferea 1.12.6
Arch Linux
KDE Plasma 5.15.4 desktop environment

**Comment by lwindolf** [comment]
I've updated the icon with an SVG version. This should solve the issue. To be released with 1.13.4

**Comment by mhoran** [comment]
The new icon looks great! In comparison to other icons, though, it's quite small:
![Screenshot at 2020-12-16 13-03-56](https://user-images.githubusercontent.com/5330/102388146-5ac2d500-3f9f-11eb-839a-a2a48ae0428b.png)

Dropbox seems to have this issue as well but other SVG icons look fine. No matter what size I make the panel this persists.

The unread icon looks fine:
![Screenshot at 2020-12-16 13-06-45](https://user-images.githubusercontent.com/5330/102388402-b1301380-3f9f-11eb-80d4-01d1bc63cfa4.png)

Any thoughts? This is on MATE Desktop.

**Comment by mhoran** [comment]
Ah, it's only small after launch when there are no new items. Once the icon flips back it is larger. How odd!

**Comment by lwindolf** [comment]
Hmm... you are right, I did not notice the size change. I can reproduce this.

**Comment by lwindolf** [comment]
@mhoran I believe I have fixed this issue. Please retest!

**Comment by mhoran** [comment]
Looks great, thanks!
