### ISSUE TITLE
Multi language atom feeds

### ISSUE THREAD

**Issue by Cj-Malone** [lwindolf/liferea#442]
Liferea doesn't support multi language feeds correctly, ignoring the hreflang attribute on links and xml:lang on other elements.

I created an [example feed](https://feeds.betterfeeds.org/examples/multilingual.atom) so you can see [feed title](https://github.com/lwindolf/liferea/blob/master/src/parsers/atom10.c#L704), [entry title](https://github.com/lwindolf/liferea/blob/master/src/parsers/atom10.c#L456) and links just uses the last element the parser encounters but content however adds the [longest](https://github.com/lwindolf/liferea/blob/master/src/item.c#L101).

**Comment by Cj-Malone** [comment]
Sorry, its just the links that are the issue. So [link](https://github.com/lwindolf/liferea/blob/master/src/parsers/atom10.c#L266) needs to take into account ```hreflang```

**Comment by lwindolf** [comment]
@Cj-Malone Can you retest the fixes of #457 (included in 1.12.0)?

**Comment by Leiaz** [comment]
I haven't fixed this, Liferea still uses the last link encountered. `atom10_parse_link` just returns a link, no language information. That link is directly set as the item or feed link in `atom10_parse_entry_link` and `atom10_parse_feed_link`. We would need to check if an alternative link is more appropriate according to locale or display alternative links in some way.

**Comment by lwindolf** [comment]
@Cj-Malone Reopening

@Leiaz thanks for clarifying!
