### ISSUE TITLE
New Tray Icon Plugin an Liferea behavior differs from early one

### ISSUE THREAD

**Issue by jEsuSdA** [lwindolf/liferea#443]
Hi!

The new Tray Icon plugin does not provides the same behavior than the previous one.

In previous version you can "Don't show counter for feeds unreaded" but now the counter is always activated and there is no configuration option for disallow this.

The Liferea itself bolds the name of feeds with unread articles, and now, all the feeds are showed at the same manner. 

Are you planning to add this lost features?

Thanks and congratulations for your work! great feed reader! ;)

**Comment by lwindolf** [comment]
The new solution is now a plugin and I try to motivate contributions based on the plugin. It is a reasonable task to add configuration options to the tray plugin to add configuration switches.
