### ISSUE TITLE
Blue urls with dark theme

### ISSUE THREAD

**Issue by zaari** [lwindolf/liferea#444]
Activating Global Dark Theme in Gnome Tweak Tool makes Liferea urls look too dark on the dark gray background. Please, can you make them lighter when the dark theme is activated?

**Comment by M5oul** [comment]
Same problem here.

**Comment by lwindolf** [comment]
Possible solution is to pass a flag from the dark theme detection and color calculation to the XSLT/CSS handling, so link colours can be changed.

**Comment by lwindolf** [comment]
We found a bug in the CSS style extracting from GTK themes. This was fixed with 1.12.2
