### ISSUE TITLE
1.12-RC1: liferea doesn't honor "-w hidden" or "--mainwindow-state=iconified" anymore

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#447]
This is a copy of bug 844262¹ reported in Debian:

++
Dear Maintainer,
to run liferea I use an application autostart entry in Xfce. Command: 'liferea -w hidden'. This used to start liferea with just the tray icon visible. But the current version starts with
visible main window. 

Same effect when launching from command line:

```
wolfgang@pitr:~$ liferea -w hidden
(liferea:8810): Gtk-WARNING **: Failed to get the GNOME session proxy: The name org.gnome.SessionManager is not owned
(liferea:8810): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1214:18: Not using units is deprecated. Assuming 'px'.
(WebKitWebProcess:8824): Gtk-WARNING **: Theme parsing error: gtk-widgets.css:1214:18: Not using units is deprecated. Assuming 'px'.
```
Using the option --mainwindow-state=iconified instead of hidden also has no effect.

++

After a minor check I can add the following on my own KDE system:
Interesting, on my system, the hidden option is honored when I have the Tray Icon disabled (which means I can't see liferea anywhere). Once I enable the plugin, liferea shows as you describe.

¹ https://bugs.debian.org/844262

**Comment by Leiaz** [comment]
From the [comment in it](https://github.com/lwindolf/liferea/blob/ab914a91d9881fec62bd73716486e867310c0576/plugins/trayicon.py#L116) : 
```
        # show the window if it is hidden when starting liferea
        self.window.deiconify()
        self.window.show()
```

The plugin is doing this on purpose. Perhaps related to [this](https://github.com/lwindolf/liferea/issues/410#issuecomment-256813970).

**Comment by mase76** [comment]
Same behaviour here under Debian Stretch with XFCE4.

**Comment by City-busz** [comment]
My PR fixes the problem: https://github.com/lwindolf/liferea/pull/523

**Comment by lwindolf** [comment]
I'm planning to remove the safety from the plugin once there is a --no-plugins option.

Still if there are too many users having problems with it again, there might be no way to have it remain there.

**Comment by DocHifi** [comment]
The fix from City-busz works for me (Ubuntu Mate 16.04 / Liferea 1.12.1)
Thanx

**Comment by antoyo** [comment]
While waiting for a fix, one can use:
```
liferea & xdotool search --onlyvisible --classname --sync Liferea windowminimize
```

**Comment by raniesantos** [comment]
any update on this?

**Comment by zero77** [comment]
> liferea & xdotool search --onlyvisible --classname --sync Liferea windowminimize

this no longer seems to be working, at least in debian.

**Comment by pixelplanetdev** [comment]
I get it that we have to be aggressive about showing the window when environments without systray exist, but couldn't the plugin check if we launch with --mainwindow-state=hidden and if it is, don't show it.

Whoever uses that argument knows what he wants and he can always recover.

**Comment by lwindolf** [comment]
@pixelplanetdev Not 100%. If a session manager remembers the command with which you started it will start the same way again. So not each start with --mainwindow-state=hidden is intentional.

Additionally due to loose coupling the plugins do not have access to CLI arguments :-(
