### ISSUE TITLE
Sorting items by flagged/read state

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#448]
Currently it stops working after items have changed state. The GtkTreeStore IS_STATE column isn't updated.

But I'm not sure if this is a bug or a feature : when it works clicking on an unread item makes it move down the list ... The jump can be annoying.

**Comment by lwindolf** [comment]
@Leiaz is this still an issue?

**Comment by Leiaz** [comment]
This wasn't really an issue. I don't remember why I was looking at that part of the code, but I noticed other columns where updated (and items reordered) but not this one. I was wondering whether to "fix" it or not, but it is probably better that way. I don't really use that sorting order, I just click on the column when some new item have a really old date and is buried under many read items.
