### ISSUE TITLE
rss url with "special" characters ('@')

### ISSUE THREAD

**Issue by C138** [lwindolf/liferea#453]
Hi
Feeds like the following one, note de '@', are not valid for liferea (right?)

http://osmose.openstreetmap.fr/fr/byuser/HainautCart@.rss

Have to check it with rssowl and it works out of the box ... :-P 

Cheers

**Comment by GreenLunar** [comment]
It works with Liferea, only the source url is not displayed properly.

**Comment by mikelolasagasti** [comment]
Works on master:

![liferea-453-1](https://cloud.githubusercontent.com/assets/773148/20635699/d115608a-b360-11e6-9d00-d3cc14a8355a.png)
![liferea-453-2](https://cloud.githubusercontent.com/assets/773148/20635700/d1158510-b360-11e6-878e-aac23d2a21b3.png)

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
