### ISSUE TITLE
Render feeds using XSLT

### ISSUE THREAD

**Issue by sjehuda** [lwindolf/liferea#455]
I am almost done working on a prototype that transforms feeds into HTML pages, which will be published at [syndication4humans-qupzilla](https://github.com/sjehuda/syndication4humans-qupzilla) ([issue tracker](https://github.com/sjehuda/syndication4humans/issues)).

**Comment by sjehuda** [comment]
It is ready for testing.

**Comment by lwindolf** [comment]
Thanks for linking your project. I still do not understand what you want to achieve with this ticket.

Right now what Liferea is doing is normalizing tag soup and broken XML using libxml2 and treating everything as XML parsing it using feed standard specific parsers that all produce a common intermediate format (stored in the DB). On rendering time Liferea serializes the DB content of one or multiple items into an XML document and renders them document into XHTML using XSLT.

So we have the following data flow

input => fixed XML => parsable DOM tree => DB stored new items => internal XML => XLST rendered XHTML

**Comment by sjehuda** [comment]
> I still do not understand what you want to achieve with this ticket.

I want this XSLT stylesheet to be integrated in Liferea; eventually, I want this stylesheet to be part of WebKit and any other layout engine software component that renders web pages.

There is also a [live demo](https://sjehuda.github.io/blog.qupzilla.com.atom).

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
