### ISSUE TITLE
Deleted news marked as unread

### ISSUE THREAD

**Issue by ghost** [lwindolf/liferea#458]
Liferea marks feeds as unread, when I read a feed, delete it, and restart Liferea. TheOldReader synchronized feeds aren't marked as unread, after I delete them, and restart Liferea, but displayed as read, altought they are deleted. I think the feeds are correct, because the RSSGuard works correctly with the same feeds. 
I use Arch Linux, and Liferea 1.12.
I think it can be fixed with a filter, which is filtering feeds by their name, and remember the status of each feed.

**Comment by genodeftest** [comment]
How about creating a hash and/or remembering the feed id + last update time? Remembering all the feeds will bloat the database, but having news come back again after being deleted is probably worke.

**Comment by tagirb** [comment]
Same here. After cleaning up all the read news and restarting Liferea, they are fetched and shown as unread again. Seems like Liferea does not remember the last position in the feeds.

**Comment by tagirb** [comment]
Ok, according to [this old bug report](https://bugs.launchpad.net/ubuntu/+source/liferea/+bug/659914), this is actually desired. Is it possible to add an option for e-mail like feed processing, whereby Liferea would remember its current position in each feed?
