### ISSUE TITLE
Sometimes content loaded in embedded browser cannot be scrolled

### ISSUE THREAD

**Issue by mhoran** [lwindolf/liferea#471]
I've noticed since upgrading to 1.12-rc2 that at sometimes content loaded via the embedded browser cannot be scrolled. I haven't been able to nail down when/why this happens, and I've seen it on a few feeds that I've configured to load through the embedded browser. Grabbing the scroll bar simply does nothing, and the space bar does nothing as well.

Relatedly, some other feeds I subscribe to can be scrolled via scrollbar or spacebar when the frame is focused, but spacebar from the headline view does nothing. I haven't been able to narrow down a reason for this either. Maybe it's related?

**Comment by mcatanzaro** [comment]
This is https://bugs.webkit.org/show_bug.cgi?id=165056

**Comment by mhoran** [comment]
Thanks @mcatanzaro. It looks like that's the source of the second issue, as when I set `GTK_OVERLAY_SCROLLING=0` the scrollbar does not lock up.

The first issue looks to be related to content that is displayed in a modal. I typically see this on twitter feeds that are loaded via an RSS proxy. If I exit the modal, and focus back on the item list, the space bar does work as expected. The `GTK_OVERLAY_SCROLLING=0` fix does nothing to help this.

**Comment by lwindolf** [comment]
As I understand it this is not a Liferea, but a Webkit issue.

Will keep this open a while to see if other users see it too...

**Comment by mcatanzaro** [comment]
This was fixed in WebKit last week. If you're still seeing it in WebKitGTK+ 2.14.4 or later, then you can open a new WebKit bug.

**Comment by mcatanzaro** [comment]
Reference: http://trac.webkit.org/changeset/211775

**Comment by mcatanzaro** [comment]
Actually it looks like @mhoran noticed two different scrollbar problems. @mhoran, if anything is still broken, please do consider filing a bug report against WebKit.

**Comment by mhoran** [comment]
OK. I'm on Debian jessie so I'll have to wait for a backport of 2.14.4. I just realized I was on a quite old version from jessie so I upgraded to the 2.14.3 backport. I'm still experiencing the modal issue, and obviously the fix for the second issue is not in 2.14.3. Setting `GTK_OVERLAY_SCROLLING=0` does fix the second issue (as identified by @mcatanzaro) so I can live with most things for the moment.

I've not had a good history of opening WebKit bug reports. I maintain [capybara-webkit](https://github.com/thoughtbot/capybara-webkit), a headless [Capybara](https://github.com/teamcapybara/capybara/) browser that uses WebKit via Qt. Maybe I'll have more luck with GTK bugs, but all my Qt bugs [were](https://bugs.webkit.org/show_bug.cgi?id=82995) [ignored](https://bugs.webkit.org/show_bug.cgi?id=93237) for [years](https://bugs.webkit.org/show_bug.cgi?id=32723) with no action (and then closed).

Thanks!

**Comment by mhoran** [comment]
Interestingly, upgrading to 2.14.3 breaks article skimming, which works fine with 2.6.2.

**Comment by mhoran** [comment]
OK, looks like all but the "modal scrolling" issue are fixed with the latest WebKitGTK+ on Debian, so I'm closing this out since it doesn't seem to be a liferea issue. Thanks!
