### ISSUE TITLE
I can't sincronize feeds with inoreader

### ISSUE THREAD

**Issue by jccall80** [lwindolf/liferea#472]
I can't sync feeds with Inoreader. I use the correct username and password...

I obtain next error:

Entity: line 1: parser error : Start tag expected, '<' not found
AppId required! Contact app developer. See http://www.inoreader.com/developers

I use the version 1.12 in Debian Testing

Rgds

**Comment by lwindolf** [comment]
It seems InoReader has changed its API to add a per-user API token.

**Comment by lwindolf** [comment]
We need to extend InoReader settings with a API token input field and persist it and send it on each request.

**Comment by lwindolf** [comment]
I've decided to drop inoreader support as I have no capacity to fix it.

On the long term there will be a plugin API to extend Liferea with support for external online sources. I hope using some good plugin examples people will create new integrations and maintain them.
