### ISSUE TITLE
Git (1.11.x) version ignores the fact that the tray icon feature is disabled

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#48]
With current git master, if I start liferea and close it with ctrl+W or alt+F4 or the window manager's close button, next time I start it, nothing will happen... the thing is that I need to start it twice simultaneously before it shows the window. This does not affect 1.10; I suspect this is a bug introduced by the fact that in 1.11, there is no more option in the preferences governing the use of the "tray icon" (notification area), it seems to have been turned into a plugin instead (I looked in the plugins and the tray icon one was disabled).

Note that even when the "missing window" issue occurs, there is no tray icon. The window just fails to appear.

Furthermore, when you launch the 2nd liferea instance to "force" the window to be shown, the feed item preview pane (where you see the contents) will reset its position to the top (if you're using the horizontal layout) instead of staying at its previous position.

**Comment by lwindolf** [comment]
Finally isolated the two overlapping causes. Code got simpler...
