### ISSUE TITLE
white text on light grey background - add colour controls

### ISSUE THREAD

**Issue by tripkin** [lwindolf/liferea#485]
Liferea v 1.10.17 on Ubuntu 16.04 w/Gnome

I have had this pop up a number of times, which was fixable in the past by tweaking the themes: switch to and from Adwaita to a dark theme of my choosing,  and by disabling and enabling the global dark theme. I have also tried manipulating the css directly, to no avail.

Would it be possible to add colour controls to the preferences dialogue?

![screenshot from 2017-02-22 08-20-55](https://cloud.githubusercontent.com/assets/14840341/23218647/fd9b9bc4-f8d9-11e6-8133-80cf8814b7b5.png)

**Comment by lwindolf** [comment]
1.12 has dark theme handling. Please upgrade!
