### ISSUE TITLE
Showing comments and other info from other feed

### ISSUE THREAD

**Issue by pyostrike** [lwindolf/liferea#488]
Hello.
Some feeds shows me comments, author, published in and attachment, but there is no such data in feed. The other data is from escapepod.org, but I have no such feed.
1.10.18

UPD. Probably removing local/share/liferea/opml is workaround of this

**Comment by lwindolf** [comment]
You need to provide more details for this. Example screen shots and expected behaviour are usually helpful for debugging.

**Comment by pyostrike** [comment]
I have no issue now. Using 1.12-rc3
Probably fixed or gone away.
/usr/local/share/liferea/opml recreted by update, but liferea works as it should, i.e. no data from other feed is shown in other one.
