### ISSUE TITLE
Liferea entry titles appears to drop plain text that is (properly escaped) HTML markup

### ISSUE THREAD

**Issue by siebenmann** [lwindolf/liferea#492]
I read my own blog's feed in Liferea to make sure that everything is fine with it, and today I found an anomaly in how Liferea displays the titles of entries with ordinary text that is HTML markup. At the moment the top entry in my feed is [this blog entry](https://utcc.utoronto.ca/~cks/space/blog/web/CSSPreLayoutTrailingWhitespace); it has the title of `CSS, <pre>, and trailing whitespace lead to browser layout weirdness`. In my Atom feed, the relevant entry has a <title> attribute of:

```
<title type="html">CSS, &amp;lt;pre&gt;, and trailing whitespace lead to browser layout weirdness</title>
```

This marks the title as containing HTML (which is correct), but escapes the `<pre>` because it is intended to be plain text, not HTML markup. In Firefox's view of Atom feeds and other feed readers I have convenient access to, this is represented properly in the eventual title. In Liferea, in both the entry view itself and the Headline box, the title is instead rendered as `CSS, , and trailing whitespace lead to browser layout weirdness`. The `<pre>` text has just vanished. I ran liferea with `--debug-html` and the relevant HTML snippet comes out as:

```
<a href="https://utcc.utoronto.ca/~cks/space/blog/web/CSSPreLayoutTrailingWhitespace" class="itemhead">CSS, , and trailing whitespace lead to browser layout weirdness</a>
```

This is all with the latest Liferea git tip, although it was happening with a somewhat earlier version of the (development) tree as well. I updated to git tip when I saw this in order to make sure that it was still there in the very latest version.

**Comment by lwindolf** [comment]
Hi Chris, thank you for reporting the issue.

The problem is quite complex and hard for a GTK application to do right. According to the Atom spec a title can contain HTML, as used by your feed. The problem is that then the application has to expect all the mad possible HTML tags. As it is inpossible to render this in Pango (GTK markup) our decision was to not support HTML and to extract all text only (which breaks your use case).

If your content would be

     <title type="text">CSS, &amp;lt;pre&gt;, and trailing whitespace 

it would work perfectly :-)

Actual HTML titles IMO are quite rare with Atom feeds as they probably break a lot of renderers. Even when one is a Javascript client rendering into DOM one wouldn't like some arbitrary HTML to break the own layout and strip it down first...

**Comment by siebenmann** [comment]
The thing is, though, that my title doesn't contain any HTML markup. Or at least it's not supposed to, when properly decoded. Decoded, it would be `CSS, &lt;pre>, and trailing whitespace lead to browser layout weirdness`, with the `&lt;` keeping the plain text `<pre>` from being interpreted as HTML markup by escaping the leading `<`. If Liferea is seeing the `<pre>` as actual HTML markup, it feels like there is one too many levels of HTML entity decoding going on somewhere.

(I do use actual HTML markup in the titles of some of my entries, most recently [this one](https://utcc.utoronto.ca/~cks/space/blog/web/PupFixingTwitterMess), and Liferea seems to quietly strip it out without problems. So do other things, for example the Firefox rendering of the raw Atom feed.)

**Comment by siebenmann** [comment]
I looked at the code and I think, tentatively, that I may have spotted where Liferea is doing one level too many of escaping of HTML `title` Atom feed attributes. I put debugging into atom10.c's `atom10_parse_text_construct()` function, and it reported the following for two cases.

To start with, a case of actual HTML in the title. Well, it always has HTML in the title, but:

```PARSING: title HTML extract start: <div xmlns="http://www.w3.org/1999/xhtml" xml:base="https://utcc.utoronto.ca/~cks/space/blog/"><p>Using <code>pup</code> to deal with Twitter's increasing demand for Javascript</p></div>
PARSING: title HTML extract unxmlize: Using pup to deal with Twitter's increasing demand for Javascript
PARSING: title HTML extract unhtmlize: Using pup to deal with Twitter's increasing demand for Javascript
```

The first line is the results from `xhtml_extract()`, the second line is the results from `unxmlize()` on that, and the third line is the results from then running `unhtmlize()` on top of that. The XHTML extraction process has already entity-decoded the raw Atom `title` contents and thus materialized the actual HTML tags such as the `<code>` set here; they are all stripped off by `unxmlize()`, and then `unhtmlize()` doesn't change anything.

Next is the case with the non-markup `<pre>` text:
```
PARSING: title HTML extract start: <div xmlns="http://www.w3.org/1999/xhtml" xml:base="https://utcc.utoronto.ca/~cks/space/blog/"><p>CSS, &lt;pre&gt;, and trailing whitespace lead to browser layout weirdness</p></div>
PARSING: title HTML extract unxmlize: CSS, <pre>, and trailing whitespace lead to browser layout weirdness
PARSING: title HTML extract unhtmlize: CSS, , and trailing whitespace lead to browser layout weirdness
```

Here `unxmlize()` both strips HTML tags and decodes entities like the `&lt;` and `&gt;` to `<` and `>`. This materializes a `<pre>` that `unhtmlize()` will then strip out again.

Since eg `item_to_xml()` uses `xmlNewTextChild()` for the title (among other things), which appears to escape reserved XML characters, I think titles could be left with `<` and `>` in their straight text. However `atom10_parse_text_construct()` is a general function and I don't know if all uses of all values returned from it are safe this way once they've shuffled through all of the fields.

**Comment by siebenmann** [comment]
Nngh. Github preview *and* comment editing is broken for me at the moment, so I accidentally dropped a crucial newline from my comment. The first block of `PARSING` stuff should have three lines but is missing the first one in the rendered version:

```
PARSING: title HTML extract start: <div xmlns="http://www.w3.org/1999/xhtml" xml:base="https://utcc.utoronto.ca/~cks/space/blog/"><p>Using <code>pup</code> to deal with Twitter's increasing demand for Javascript</p></div>
PARSING: title HTML extract unxmlize: Using pup to deal with Twitter's increasing demand for Javascript
PARSING: title HTML extract unhtmlize: Using pup to deal with Twitter's increasing demand for Javascript
```

**Comment by Leiaz** [comment]
@lwindolf  I think this is a bug in the atom parser. The example [HTML atomTextConstruct]( https://tools.ietf.org/html/rfc4287#section-3.1.1) isn't parsed properly. With `type="text"` the parser works, the entities are decoded once, so your example displays `CSS, &lt;pre>, and trailing whitespace`.

I think one `unhtmlize` should be enough ? 

```diff
diff --git a/src/parsers/atom10.c b/src/parsers/atom10.c
index ef1569ca..ad6f9900 100644
--- a/src/parsers/atom10.c
+++ b/src/parsers/atom10.c
@@ -187,7 +187,7 @@ atom10_parse_text_construct (xmlNodePtr cur, gboolean htmlified)
        } else if (!strcmp(type, "html")) {
                ret = xhtml_extract (cur, 0, NULL);
                if (!htmlified)
-                       ret = unhtmlize (unxmlize (ret));
+                       ret = unhtmlize (ret);
        } else if (!strcmp (type, "xhtml")) {
                /* The spec says to show the contents of the div tag that MUST be present */
                ret = xhtml_extract (cur, 2, NULL);
```
