### ISSUE TITLE
auto scrol up!!!

### ISSUE THREAD

**Issue by k9team3** [lwindolf/liferea#493]
i tested liferea for a while now. I got different RSS feeds in different directories, but all are coming in the map unread. I'm monitoring the news but when my field is fulled with 30 messages, i don t see the newest message at my screen, i m scroll up manual to look at the newest messages. Is it possible to make a auto scroll up, so the newest message is standing at the top of you're screen?

**Comment by lwindolf** [comment]
This is not possible. A suitable solution might be to use reverse date order.
