### ISSUE TITLE
Try add copyq as external browser, but get error.

### ISSUE THREAD

**Issue by Spacewalker2** [lwindolf/liferea#500]
Hello,

I try to add '/usr/bin/copyq add %s' as manual external browser because I want to collect urls for later reading.  "Item->Open in External Browser" shows the message "Failed to execute child process 'mozilla' (No such file or directory)" but the path is correct I checked it. It would be cool if this works :-)

bye

**Comment by Leiaz** [comment]
It is supposed to work. I broke the text box when updating the ui file some time ago. Sorry.

Thanks for the report !
