### ISSUE TITLE
Liferea deanonymize Tor

### ISSUE THREAD

**Issue by user1508** [lwindolf/liferea#503]
I use liferea with tor for more privacy. I connect liferea to polipo (http-proxy) on localhost and polipo sends the data to tor-socks-proxy. I'm interested in what's going on so I check the established connections with iftop and I discover a behavier of liferea that deanonymize me. Liferea seems to update the feeds through tor but if I click on any item which include a picture or something else liferea create a new direct connection and ignores the proxy-settings. I rockon that the proxy-setting don't pass to the webkit component. **This is very disappointing** because liferea is an fast and useful program!

By the way javascript should be disabled by default and the cookie file should be read only or removed everytime if the user don't want any cookies.

**Comment by GreenLunar** [comment]
> By the way javascript should be disabled by default and the cookie file should be read only or removed everytime if the user don't want any cookies.

### Cookies
Issues: #108 #270 #324
I set file ./.config/liferea/cookies.txt, which is empty, to read-only.

### Javascript
[Why is NoScript configured to allow JavaScript by default in Tor Browser? Isn't that unsafe?](https://www.torproject.org/docs/faq.html.en#TBBJavaScriptEnabled)
Perhaps Javascript should be disabled by default.

**Comment by Leiaz** [comment]
Yes, unless you are using WebkitGTK+ version 2.15.3 or more, the only proxy setting that works as people would expect is "automatic" (system wide settings). 

@lwindolf Perhaps we could grey out other choices and change the setting to automatic for people with older WebKit version, with a warning dialog ? I don't see a case where people would want to download a feed through a specific proxy but download the external elements in items differently.

**Comment by lwindolf** [comment]
@user1508 @GreenLunar what do you guys think about the solution in #526 (included in recent release 1.12.0)?
