### ISSUE TITLE
Liferea window opens below each other

### ISSUE THREAD

**Issue by xahon** [lwindolf/liferea#505]
When i click on feed line in tray 
![image](https://cloud.githubusercontent.com/assets/18731681/25608725/7f8d6688-2f5f-11e7-8149-e60ffd970220.png)
liferea opens below other opened programs instead of on top of them.

Issue disappears if i select "Always on top" button in ubuntu window context menu

**Comment by lwindolf** [comment]
Which Liferea version are you using?
Which window manager do you use?
Which window focus setting? (Focus follows mouse, or click to focus)
Which desktop environment do you run?

**Comment by xahon** [comment]
I am not using liferea anymore, using gnome-mail instead. It has bridge to liferea

**Comment by xahon** [comment]
That can notify any change

**Comment by lwindolf** [comment]
Thank you for the feedback.
