### ISSUE TITLE
Feature request. Regex patterns

### ISSUE THREAD

**Issue by xahon** [lwindolf/liferea#506]
Can you add regex pattern to format rss items output.

F.e. if item contents `....price: 100$` i could add pattern `/price:\s(\d*\$)/<b>$1</b>/g` or such like that

**Comment by GreenLunar** [comment]
You should do this using a "conversion filter" command/script.  See Subscription Properties -> Source.
https://lzone.de/liferea/blog/Liferea+Trick+%236%3A+Website+Scraping
https://lzone.de/liferea/scraping.htm
https://kiza.eu/software/snownews/snowscripts/extensions/

P.S. How can you utilize the above content/pattern with one-lined command?
