### ISSUE TITLE
Add highlighting on tray icon

### ISSUE THREAD

**Issue by xahon** [lwindolf/liferea#507]
I cannot understand if new feed comes without clicking the icon. It better to be if icon became another when new feed downloads

**Comment by jcubic** [comment]
+1

**Comment by xahon** [comment]
It looks like maintainers have abandoned this project :(

**Comment by xahon** [comment]
@jcubic use unity-mail instead. It can listen your mail and push notification. Also it have integration with liferea and thunderbird

**Comment by jcubic** [comment]
I use Fedora/Xfce unity-mail will probably don't work for me. But tray icon is just a python plugin maybe I can came up with better icons and also make it themable, right now you can change that icons.

**Comment by lwindolf** [comment]
As the Liferea maintainer I can say that the project isn't abandoned. The project is slowely approaching year 15 of it's existance. When things go slow it is time to contribute more! One man can only achieve so much.

The idea of changing the icon after updates with new items is good. A possible implementation would be

- on init save current unread count
- on init register to be notified when feeds do update
- on feed update: check if unread count went up, if yes switch icon
- on tray click: reset icon

or something similar. It should be doable in the python plugin. If you guys need pointers I'll gladly help. Please contribute and make Liferea better.

**Comment by Leiaz** [comment]
Which icon is this about ? The systray icon from the plugin already changes and displays the number of new items (capped at 99).

**Comment by jcubic** [comment]
yes there is counter, maybe the issue was when there are unread because when you focus or read first news the counter disappear

**Comment by lwindolf** [comment]
That's intentional. Because once you start reading there is no reasonable way anymore to know which of the unread items you have seen and which not. This is why we reset the counter so you are at least informed when the next batch of new items appears.

**Comment by jcubic** [comment]
I think you can close this issue as `won't fix`, you will have one less issue open.
