### ISSUE TITLE
Entry title as Email subject

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#509]
Allow user to send an Email to entry author with entry title as a subject.

1) User follows a feed or a git repository.
2) User wants to send an email to the author, of which their email is published under entry _Author_.

I did not yet figure out the appropriate UX.

**Comment by lwindolf** [comment]
Maybe an optional (only if author email present) extra menu option in the item context menu and trigger the systems mail program by launching "xdg-email"

**Comment by poetsmeniet** [comment]
Hi @lwindolf I would like to work on this feature-request. Is it still current?

**Comment by poetsmeniet** [comment]
@lwindolf ok cool, i might have time tomorrow to go through the code

**Comment by lwindolf** [comment]
Take all the time you need! No haste needed :-)

**Comment by Leiaz** [comment]
Fixed by #680.
