### ISSUE TITLE
Implement sliding window of message header items in GTK scoll list

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#510]
The existing message header list loads all available items into the GTK scroll list. 
This makes scrolling the list box slow, as there are a lot of items, and it makes switching to another selection slow as the current list box has to be discarded and a new list box has to be constructed.

This is a common technique used for efficiently showing large list of items in a scrollable list box.

**Comment by lwindolf** [comment]
Sorry, won't work as we (and GTK enforces this) implement sorting using GtkTreeView/GtkTreeModel which requires all items to be loaded before sorting. Async loading works only by offsett-loading against a sort aware backend.

While we have sqlite as a sortable backend we could query, but we'd have to discard GtkTreeView to properly view stuff.

Won't fix. Actually using GtkTreeView is a hard limit hurting power user use cases.

**Comment by rich-coe** [comment]
That's funny.  I found sample GTK tutorials on the GTK site that show how to implement the sliding window.

**Comment by lwindolf** [comment]
Do you still have links to those? I'd interested to learn more on it.

**Comment by rich-coe** [comment]
https://en.wikibooks.org/wiki/GTK%2B_By_Example/Tree_View/Custom_Models

I've started some work on this, but got buried in other work.  When I get some results, I'll post my work.

**Comment by rich-coe** [comment]
I tried a different approach.  I created a background task to read the db data from itemset_foreach() and populate the batch_itemstore.  It works well to not lockup the ui.   I'd like to make it quicker to partially update the UI in batches.  I also need to handle cancelling the current db fetch if the user switches selections.

**Comment by rich-coe** [comment]
In https://wiki.gnome.org/Projects/GTK/GtkTreeView/Ideas
I found some of this information, not sure how current this is .... 

    TreeModel improvements : TreeModel batch API
    Every modification made to a GtkTreeModel has to be signaled to anybody observing this GtkTreeModel instance.  [ ... ]
    An elegant solution to this problem is to introduce the possibility of batching together notifications of changes to a GtkTreeModel. [ ... ]

    TreeModel improvements : TreeModel lazy loading
    For very large data sets, or data sets that are expensive to retrieve, one wants to avoid loading rows from such data sets as long as possible: that is, until a row is to be displayed on the screen. With very large data sets, most of the contents will never be viewed, so there is no use in fetching all data from the source. 
    The current implementation of the internal data structure in GtkTreeView makes such lazy loading very hard to implement. Once a model is registered with the GtkTreeView, the tree view will build the root level of its internal Red-Black Tree. [ ... ]
