### ISSUE TITLE
Feature request - support for JSON feeds

### ISSUE THREAD

**Issue by tripkin** [lwindolf/liferea#513]
JSON feeds are now starting to be made available, and it would be nice to see this included in liferea. See https://jsonfeed.org/ for more info...

**Comment by whizse** [comment]
I'm guessing that a good start for this would be a conversion filter that takes a json.feed and spits out atom?

I was struggling to find some good in the wild examples of json feed usage, but at least NPR is one example of a mainstream site with support: https://www.npr.org/feeds/1001/feed.json

(Also, out of scope for Liferea, but it would be nice to have a WebExtension for Firefox/Chrome to detect and add these feeds to a reader application.)

**Comment by sjehuda** [comment]
I have created an XSLT 1.0 script which transforms JSON Feed 1.0, as transformed by XSLT 3.0 function "json-to-xml", to Atom 1.0.

https://git.xmpp-it.net/sch/Focus/src/branch/main/templates/json-feed-1.0.xslt

https://github.com/lwindolf/liferea/discussions/1474

**Comment by lwindolf** [comment]
@sjehuda When I want to test this script with xsltproc how would I call it?

**Comment by sjehuda** [comment]
On Fri, 21 Nov 2025 15:35:01 -0800
Lars Windolf ***@***.***> wrote:

> lwindolf left a comment (lwindolf/liferea#513)
> 
> @sjehuda When I want to test this script with xsltproc how would I
> call it?
> 

Fist, I should create a software (e.g. Python script) to convert JSON
to XML, as SaxonJS does.

If you deem this as an urgent concern, then I will create a script
durin the next couple of days.

After feed.json is converted to XML, XSLT script execution is done as:

xsltproc json-feed-1.1.xslt json-as-xml.xml > result.atom

**Comment by sjehuda** [comment]
I have made a script to convert JSON to XML as done by XPath 3.1 function `json-to-xml`.

https://github.com/BaseMax/json-to-xml-converter/issues/1

I think that it should be good for most cases; and, I sense, that there should be a few more improvements.

**Comment by sjehuda** [comment]
Yes. That script is ready.

It requires execution of that script and also of xslproc, or any other
XSLT processor.

I am intending to incorporate it with my project, starting with JSON
files (Activity Streams and JSON Feed).

https://git.xmpp-it.net/sch/Slixfeed

However, I advise to incorporate that script in another section,
because project "The Focus" is *not* intended nor even designed for
"scraping".

https://git.xmpp-it.net/sch/Focus

The stated purpose, is to uniform syndicated documents.

**Comment by sjehuda** [comment]
Good evening.

Command "focuscript" (part of project Slixfeed) should work.

Automated.
```
focuscript auto https://mirhamasala.com/rss/feed.json
```

Manual.
```
focuscript /path/to/json-1.0.focus https://mirhamasala.com/rss/feed.json
```

Install.
```
python3 -m venv .venv
source .venv/bin/activate
pip install git+https://git.xmpp-it.net/sch/Slixfeed
```

I should create a package "release", so that it be more accessible with the filter interface of Liferea.

**Comment by lwindolf** [comment]
Done.
