### ISSUE TITLE
Integration with FeedHQ?

### ISSUE THREAD

**Issue by sgtpep** [lwindolf/liferea#515]
FeedHQ https://feedhq.org/
It's open-source. It provides an API similar to Google Reader. Newsbeuter supports it and it works perfectly well. Would be happy to see more feed readers supporting it.

**Comment by GreenLunar** [comment]
Once support is added, don't forget to ask to mention Liferea at https://feedhq.org/apps/

**Comment by sgtpep** [comment]
Absolutely. Thank you very much for consideration!

**Comment by lwindolf** [comment]
Please test the generic google reader support added with #962 !
