### ISSUE TITLE
Default browser not honoured.

### ISSUE THREAD

**Issue by bjarkih1977** [lwindolf/liferea#516]
I've been using Manjaro/Cinnamon for some time and Liferea worked perfectly.  When I switched to KDE (clean install) it started opening links in chrome even thoug firefox is set as default browser.  When trying to sett "mozzile%s" as external browser nothing happened, no browser opened.  And now when clicking the liferea app icon in taskbar nothing happens.

**Comment by lwindolf** [comment]
You wrote "mozille%s" without a space before the %s. This cannot work. Please try with "mozille %s"

**Comment by Leiaz** [comment]
This could also have been due to #511.

**Comment by lwindolf** [comment]
Please retest with 1.12.1 or git master!
