### ISSUE TITLE
Improve time to switch folders

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#519]
Switching folders can take a long time.
I got poor results trying to identify the issue being called from itemset_foreach().

I see two different approaches that could fix this
(1)  Load as many items as possible into the displayed folder as can be done in 250ms.  Display the folder and load the rest as a background task.
(2)  Create a custom GTK Tree Model to load items.  Initially it loads ~100 (?) items and loads new items as the user scrolls through the list.

**Comment by rich-coe** [comment]
The count per millisecond (cpms) goes down the more items there are.
It implies that insertion time is O(n^2)?

    loading item list with node "apple" : = itemset_foreach took 0,011s : count= 53  cpms= 4.8182 : = itemlist merge took 0,015s
    loading item list with node "ac" : = itemset_foreach took 0,013s : count= 122  cpms= 9.3846 : = itemlist merge took 0,027s
    loading item list with node "business" : = itemset_foreach took 0,770s : count= 4097  cpms= 5.321 : = itemlist merge took 0,781s
    loading item list with node "books" : = itemset_foreach took 1,664s : count= 7207  cpms= 4.3311 : = itemlist merge took 1,684s
    loading item list with node "code" : = itemset_foreach took 6,625s : count= 17482  cpms= 2.6388 : = itemlist merge took 6,685s
    loading item list with node "commentary" : = itemset_foreach took 99,354s : count= 61418  cpms= 0.6182 : = itemlist merge took 99,598s
    loading item list with node "ac" : = itemset_foreach took 0,013s : count= 122  cpms= 9.384615 : = itemlist merge took 0,036s
    loading item list with node "apple" : = itemset_foreach took 0,013s : count= 53  cpms= 4.076923 : = itemlist merge took 0,017s
    loading item list with node "books" : = itemset_foreach took 1,704s : count= 7207  cpms= 4.229460 : = itemlist merge took 1,725s
    loading item list with node "business" : = itemset_foreach took 0,797s : count= 4097  cpms= 5.140527 : = itemlist merge took 0,808s
    loading item list with node "code" : = itemset_foreach took 6,680s : count= 17482  cpms= 2.617066 : = itemlist merge took 6,739s
    loading item list with node "commentary" : = itemset_foreach took 96,796s : count= 61418  cpms= 0.634510 : = itemlist merge took 97,039s
    loading item list with node "healthTech" : = itemset_foreach took 0,029s : count= 197  cpms= 6.793103 : = itemlist merge took 0,030s
    loading item list with node "i18n" : = itemset_foreach took 0,010s : count= 60  cpms= 6.000000 : = itemlist merge took 0,011s
    loading item list with node "fun" : = itemset_foreach took 16,772s : count= 26754  cpms= 1.595159 : = itemlist merge took 16,882s
    loading item list with node "music" : = itemset_foreach took 0,121s : count= 950  cpms= 7.851240 : = itemlist merge took 0,124s
    loading item list with node "news" : = itemset_foreach took 5,154s : count= 12194  cpms= 2.365929 : = itemlist merge took 5,208s

**Comment by lwindolf** [comment]
Batched loading itself isn't a problem, batched loading in sorted lists is... as it means mapping the sorting logic into the DB layer.
