### ISSUE TITLE
Syncing with Feedly

### ISSUE THREAD

**Issue by Bishopst** [lwindolf/liferea#52]
Is there a way to sync liferea with feedly. So that if I add content to feedly, I can then update liferea directly without having to manually add these urls to liferea everytime? I can't seem to find a way to do so. I think this would really be great given that feedly does not have a desktop or app version for ubuntu or linux!

**Comment by GreenLunar** [comment]
Future plan for Liferea is to move all online source subscription support into Python plugins that can be easily copied/adapted to other online services. See https://github.com/lwindolf/liferea/issues/338#issuecomment-218602690

**Comment by baybal** [comment]
@GreenLunar I want to try making this one. Any cues on what to start from? Docs, samples?

**Comment by lwindolf** [comment]
@baybal Sorry for the late reply. First we'd need to make sure all necessary subscription handling interfaces are exposed to Python using GIR. It might be that it is cumbersome to do so and maybe use an intermediate format. So feel free to suggest an API Python plugins could use to provide updates.

To verify if the C API can be used you could try to register a node source provider using the interface in src/fl_sources/node_source.h

Please do not invest to much in it. If it gets to complicated it might be more reasonable to provide an easier API feasible for GIR/Python plugins.

**Comment by lwindolf** [comment]
Some update here. Actually it is not possible to build useful Feedly support. The reason being that Feedly refuses to provide new application secrets, they will only grant exceptions for "innovative new applications".

The developer sandbox keys that everyone can use work only for 30days.

Given this it is not really possible to implement support. Feedly just doesn't want to.

**Comment by baybal** [comment]
Well, just use somebody's else key, and the problem is solved. It's not like they can really filter clients by anything other than HTTP useragents.

**Comment by lwindolf** [comment]
@baybal I'd find this highly unethical. If Liferea does accidentily DoS or otherwise misuse the account and Feedly closes it, then the original key owner would be held responsible and loose the key. Sorry, that's just not an option. I would not want this to happen for an app key I register.
