### ISSUE TITLE
Internal browser scrolling locks up with certain feeds when JS is enabled

### ISSUE THREAD

**Issue by mhoran** [lwindolf/liferea#524]
Running liferea 1.12-rc3 and libwebkit2gtk 2.16.3 (from Debian stretch), the internal browser locks up shortly after loading items from the [Dilbert](http://dilbert.com/feed) feed. Interestingly, when I click in the frame, the screen just goes white. Disabling JavaScript resolves the issue, but causes issues with other feeds (notably, Twitter.)

I've tried this with Epiphany on the same system, and the Dilbert page does not lock up in the same way. So it would seem that there's some interaction between liferea and WebKit, but I'm not sure.

**Comment by mhoran** [comment]
Note that this doesn't seem to be a duplicate of #471. Notably, setting `GTK_OVERLAY_SCROLLING=0` does not help. Even clicking the scrollbar causes the frame to go blank (white).

**Comment by Leiaz** [comment]
Here it crashed both Liferea and Epiphany with WebKitGTK+ 2.16.2 but it doesn't crash any more with 2.16.5 (Arch Linux). [Some crashes and security issues were fixed in 2.16.4](https://webkitgtk.org/2017/06/20/webkitgtk2.16.4-released.html). I think this should go to Debian, they backport patches for serious issues.

**Comment by mhoran** [comment]
Yup, that was it. Not sure why I didn't see the crash in Epiphany, but I updated to libwebkit2gtk-4.0-37 (2.16.5-1~bpo9+1) from Debian backports and it resolved the issue.

Thanks!

**Comment by rich-coe** [comment]
I was running 2.16.3 webkit and had periodic issues with WebKitWebProcess crashing.
I upgraded to 2.16.5 and hadn't had any of the issues (yet) with items displayed in feeds, but the new version reliably crashes certain web pages when loading an item in a tab with using the internal browser.
