### ISSUE TITLE
tiny tiny rss, login problem since 1.12.rc2 (and rc3 too)

### ISSUE THREAD

**Issue by jajaxor** [lwindolf/liferea#525]
Hi (sorry for my bad english)

I use Liferea since few month without any problem.

until 1.12rc1, I can use Liferea ttss plugins.

since rc2 (and rc3), I have got a login problem =>

mycomputer:~$ liferea
cannot open "/home/jaja/.cache/liferea/plugins/rdgnmag.opml"TinyTinyRSS login failed: error 'Login request failed with HTTP error 0'!
TinyTinyRSS login failed: error 'Login request failed with HTTP error 0'!
TinyTinyRSS login failed: error 'Login request failed with HTTP error 0'!

**Comment by lwindolf** [comment]
Can you please provide the relevant snippets from a debug run with "--debug-net"? Please ensure to strip any credentials from the ouput!

For me running 1.12-rc3 against TTRSS works fine.

**Comment by jajaxor** [comment]
Hi,

ok, it's my certificat who have got a problem :+1: 

< HTTP/1.1 6 Certificat TLS inacceptable

how solve that ?

**Comment by lwindolf** [comment]
Hard to say. I'd suggest to test it with https://www.ssllabs.com/ssltest/ they usually detect the problem. Liferea itself has no special requirements on certificates it uses libsoup for HTTP(S) connections.
