### ISSUE TITLE
Cannot sort headlines by date any more, since 1.12-rc3

### ISSUE THREAD

**Issue by liquidnight2** [lwindolf/liferea#527]
That new version has a headline area with only one column which combines title and date into one item.
So you removed the date header, and did not provide a sorting right-mouse menu on the feed.

![no-time-entry](https://raw.githubusercontent.com/liquidnight2/westalpen/master/no-time-entry.jpg)

Some of my installed packages on gentoo-amd64:
net-news/liferea-1.12_rc3-r1
net-libs/webkit-gtk-2.16.5
net-libs/webkit-gtk-2.4.11-r1
x11-libs/gtk+-3.22.16
x11-libs/gtk+-2.24.31
x11-libs/gtksourceview-3.20.4
dev-util/gtk-doc-am-1.25-r1
dev-util/gtk-update-icon-cache-3.20.9
dev-python/pygtk-2.24.0-r4

_How do I add a screenshot here ? "Something went really wrong, and we can’t process that file. " 
It is a jpg._

**Comment by lwindolf** [comment]
Yep, this is a problem I'm still working on that is blocking 1.12.0. Current idea is that the headline column is now sorting per date asc/desc. So the possibility to sort lexicographically would be gone instead.

From an implementation perspective this is a problem with the limited searching possibilities of GtkTreeView which only allows to have one sorting criteria for each column.

BTW if you have time please try the branch "wide_view_test" for the recent experiment on solving this issue. Feedback would be awesome!

**Comment by liquidnight2** [comment]
I am using liferea in productive mode and have downgraded to 1.10.17 which is the last version that works for me. 

On the sorting issue: I saw that I could not switch to sort-by-date any more. 
The previous implementation with the 2 rows and  one per entry line worked well in my view. And I prefer the one line layout more than the 2 line layout.  I am a user that uses 50 or more entries on each feed on the same view. 

Since gentoo compiles liferea anyway, I guess I would be able to build that "wide_view_test" branch, too.  Would you get me a hint where I can access that branch ? Then I would try to build that branch and run it for testing.

**Comment by lwindolf** [comment]
@liquidnight2 You can access the git branches from the "Code" page left top corner above the files listing.

You can also directly download the branch as

     https://github.com/lwindolf/liferea/archive/wide_view_test.zip

**Comment by Leiaz** [comment]
@lwindolf I'm getting some `Gtk-WARNING **: Attempting to sort on invalid type gpointer` when clicking on the favicon column header in wide view and changing to normal view.

**Comment by lwindolf** [comment]
@Leiaz I can reproduce this.

**Comment by lwindolf** [comment]
Fixed with b199a9d8e9991a0ab40467201c85c75168401e45

**Comment by lwindolf** [comment]
@liquidnight2 I decided to merge the solution in wide_view_test to master. I believe this fixes your issue. Please retest!

**Comment by liquidnight2** [comment]
I have cloned the git repo, and ran  ./autogen.sh  and make. 
How do I start that local liferea ? 
I don't like to run 'make install' becauese that would trash my productive liferea.

**Comment by lwindolf** [comment]
You need to build and run with something like

    mkdir ~/build
    autogen.sh --prefix=~/build
    make && make install
    ~/build/bin/liferea

**Comment by liquidnight2** [comment]
thanks, now I need to cope  the "can't open display" problem - what is not specific to liferea. I need to look up some more hints about that issue.

**Comment by lwindolf** [comment]
As I understand it with X11 you can do either

    xhost +si:localuser:<name>       # with <name> being the user name

or

    xhost +local:

the first command only allows a single user, while the other command allows all local users to connect to your display. Now to run a command from the other user you need to tell him first where you display is. So determine it first with

    echo $DISPLAY

and with the other user set exactly the same DISPLAY env var, for example

    export DISPLAY=:1

No you should be able to start X client

**Comment by liquidnight2** [comment]
$ build/bin/liferea   --debug-all

`

(liferea:13946): GLib-GIO-CRITICAL **: g_dbus_proxy_new_sync: assertion 'G_IS_DBUS_CONNECTION (connection)' failed

(liferea:13946): GLib-GIO-CRITICAL **: g_dbus_proxy_get_name_owner: assertion 'G_IS_DBUS_PROXY (proxy)' failed

(liferea:13946): dconf-CRITICAL **: unable to create directory '/var/run/user/1003/dconf': Keine Berechtigung.  dconf will not work properly.

(liferea:13946): dconf-CRITICAL **: unable to create directory '/var/run/user/1003/dconf': Keine Berechtigung.  dconf will not work properly.

(liferea:13946): dconf-CRITICAL **: unable to create directory '/var/run/user/1003/dconf': Keine Berechtigung.  dconf will not work properly.

(liferea:13946): dconf-CRITICAL **: unable to create directory '/var/run/user/1003/dconf': Keine Berechtigung.  dconf will not work properly.

(liferea:13946): dconf-CRITICAL **: unable to create directory '/var/run/user/1003/dconf': Keine Berechtigung.  dconf will not work properly.
CONF   : proxy auto detect is configured
CONF   : Manual proxy settings are now NULL:0 NULL:NULL
NET    : proxy set to http://(null):(null)@(null):0
DB     : Opening DB file /home/test/.local/share/liferea/liferea.db...
DB     : executing SQL: PRAGMA journal_mode=WAL
DB     :  -> result: 0 (success)
DB     : executing SQL: PRAGMA page_size=32768
DB     :  -> result: 0 (success)
DB     : executing SQL: PRAGMA synchronous=NORMAL
DB     :  -> result: 0 (success)
DB     : current DB schema version: 10
DB     : No VACUUM as freelist count/page count ratio 0,00 <= 10
DB     : executing SQL: CREATE TABLE items (   item_id		INTEGER,   parent_item_id     INTEGER,   node_id		TEXT,   parent_node_id     TEXT,   title		TEXT,   read		INTEGER,   updated		INTEGER,   popupINTEGER,   marked		INTEGER,   source		TEXT,   source_id		TEXT,   valid_guid		INTEGER,   description	TEXT,   date		INTEGER,   comment_feed_id	TEXT,   comment            INTEGER,   PRIMARY KEY (item_id));
DB     :  -> result: 1 (table items already exists)
DB     : executing SQL: CREATE INDEX items_idx ON items (source_id);
DB     :  -> result: 1 (index items_idx already exists)

`

**Comment by lwindolf** [comment]
Liferea does auto-schema-upgrades so it might upgrade an older sqlite schema version. So to be 100% safe you should backup ~/.cache/liferea first.

**Comment by liquidnight2** [comment]
Ok, now I ran  a custom built liferea from the current git master on my regular user:

```
HTML   : HTML view: adding "Denunziation ? Wikipedia, Psiram und Co."
DB     : loading item 486438
HTML   : HTML view: adding "ZDF-Theveßen verhöhnt 7 Millionen Deutsche!"
HTML   : XSLT localisation: setlocale(LC_MESSAGES, NULL) reports 'de_DE'
HTML   : XSLT localisation: lang='de_DE' shortlang='de'
HTML   : writing 2351 bytes to HTML view
GUI    : = itemlist merge took 0,144s
PERF   : = itemlist_merge_itemset took 0,144s
PERF   : = itemlist_load took 0,144s
PERF   : = feedlist_selection_changed took 0,144s
PERF   : = liferea_shell_create took 1,177s
PERF   : function "liferea_shell_create" is slow! Took 1177ms.
NET    : network manager: connecting to StateChanged signal
NET    : network manager: connected to StateChanged signal: yes
GUI    : Acquired the name org.gnome.feed.Reader on the session bus

CONF   : Setting last-window-state to 0

(liferea:2575): Gtk-WARNING **: Allocating size to GtkWindow 0x1014270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(WebKitWebProcess:2589): GLib-GIO-ERROR **: Settings schema 'net.sf.liferea' does not contain a key named 'do-not-track'

(liferea:2575): Gtk-WARNING **: Allocating size to GtkWindow 0x1014270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(liferea:2575): Gtk-WARNING **: Allocating size to GtkWindow 0x1014270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(liferea:2575): Gtk-WARNING **: Allocating size to GtkWindow 0x1014270 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
UPDATE : processing request (http://feeds.feedburner.com/blogspot/cwWR)
NET    : downloading http://feeds.feedburner.com/blogspot/cwWR

(liferea:2575): GLib-GIO-ERROR **: Settings schema 'net.sf.liferea' does not contain a key named 'do-not-track'
```

**Comment by Leiaz** [comment]
If you installed it in a user dir, you need to add it to `XDG_DATA_DIRS` or the schema won't be found : 
```
XDG_DATA_DIRS=~/your_dir/share:$XDG_DATA_DIRS ~/your_dir/bin/liferea
```

**Comment by liquidnight2** [comment]
Ok, now I was able to run the git master version, that comes up with   Version  1.12-rc3.

The issue is not solved,  since I still cannot sort by date.  --> (seeing the most recent items on top is a must-have for me).

**Comment by lwindolf** [comment]
@liquidnight2 Great that you got it working! So when you click the "Schlagzeile" (headline) column it doesn't sort by date?

**Comment by liquidnight2** [comment]
I just started the git version again, it hangs while loading many   html view items.   The debug log tells continually all the items and the gui hangs with 100% cpu load since minutes.

**Comment by sideeffffect** [comment]
I solved this by editing `~/.cache/liferea/plugins/*.opml` -- changing the `sortColumn="title"` to `sortColumn="time"`
