### ISSUE TITLE
This Tumblr may contain sensitive media problem

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#529]
If a blog in Tumblr is tagged as containing sensitive content, only after login, this content can be displayed, I think this is different from blogs that require autentication, so the feeds from this blog are not available until login and we have a error.

**Comment by lwindolf** [comment]
I understand and can reproduce the problem. This is a long-standing limitation in the internal browser which has advantages (security) and disadvantages.

To fix this one would have to implement a persistant Webkit session shared among all non-internal HTML rendering widget instances. It is possible, just no time to do it :-(
