### ISSUE TITLE
Themeable tray icons

### ISSUE THREAD

**Issue by jcubic** [lwindolf/liferea#531]
Any reason why not to use status icons from theme instead of the fixed onces?

You can take a look how to create themeable icons in this repo [linuxmint/blueberry](https://github.com/linuxmint/blueberry)

the python script is using:
```python
        self.icon = Gtk.StatusIcon()
...
        if self.rfkill.hard_block or self.rfkill.soft_block:
            self.icon.set_from_icon_name("blueberry-tray-disabled")
            self.icon.set_tooltip_text(_("Bluetooth is disabled"))
        else:
            self.icon.set_from_icon_name("blueberry-tray")
            self.update_connected_state()
```
https://github.com/linuxmint/blueberry/blob/master/usr/lib/blueberry/blueberry-tray.py

and they copy icons to [/usr/share/icons/hicolor/.../status](https://github.com/linuxmint/blueberry/tree/master/usr/share/icons/hicolor)

**Comment by lwindolf** [comment]
No reason. Just needs to be fixed. The current tray icon plugin is a user contribution after the static code was removed. It is a compromise to help users that really need a tray icon.

Please consider contributing a patched plugin!

There is some plugin writing help in
https://lzone.de/liferea/blog/Writing+Liferea+Plugins+Tutorial+Part+1
https://lzone.de/liferea/blog/Writing+Liferea+Plugins+Tutorial+Part+2

**Comment by jcubic** [comment]
There is project [Hardcode-Tray](https://github.com/bil-elmoussaoui/Hardcode-Tray) and they add support for liferea, so I'm fine with this.

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
