### ISSUE TITLE
"Important" status marker symbol icon does not show in its column in 1.12 release candidate

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#533]
There used to be a dedicated gtk listview column in Liferea to show icons marking "important" items inside the feed, where you could click to toggle that (!) icon's state.

In the release candidate, that icon does not show up but you can still click anywhere to the left of the feed item's title in the listview—whether on the icon representing the feed, or in the blank space—and it toggles the marker on and off. A bit confusing, and I can't imagine this being something else than an oversight given how weird it looks like :)

**Comment by nekohayo** [comment]
This contains a screencast video illustrating the issue.

[Screencast_2017-08-26.zip](https://github.com/lwindolf/liferea/files/1253993/Screencast_2017-08-26.zip)

**Comment by lwindolf** [comment]
Known issue to be solved before 1.12. I have no idea where to put it. I actually need GUI design help on this (or I would have to revert the wide pane rendering change entirely). 

What looks absolutely silly is having a heart or star symbol in front of the large favicon.

@nekohayo Do you have any ideas? I know you do a lot of UX stuff on Pitivi.

**Comment by lwindolf** [comment]
Actually I see now 3 possibilities

1. Reverting to before
2. Switching to NNW style ![image](https://user-images.githubusercontent.com/3315368/30077650-cc58077c-927c-11e7-9fe5-6c312b6a21b7.png) with the image sitting at the right. So in mutti feed mode only items with images would have their real image shown to the right. And it would be visually ok to have a star column to the left again.
3. Giving up the idea to apply the star in the list view. Why shouldn't it be exclusively be added in the item view?

**Comment by nekohayo** [comment]
The NNW style is pretty, though I see it more as an alternate display mode rather than the one-and-only listview display mode, as it doesn't really scale when you have hundreds (or thousands) of items to sift through... so while I find that look sexy, I would still like to somehow have the old "compact" items list mode for power users like me (I don't want to be discouraging/stop-energy though... just stating that for my particular usage patterns I am most efficient with the tight listview most of the time)

As for having the "important" status flag toggle be available only within the item's preview pane itself, I could understand the reasoning for it, though you do lose some flexibility/efficiency feature for power users again. My usecase is typically to sift through hundreds of items quickly to do a first pass at identifying those I actually want to read "when I have more time"; I do that by:

* quickly reading the titles and directly clicking their (!) icon column's cell,
* ...which lets me toggle the status without even touching the read/unread status or entering the preview mode. The advantage is that it would let me do that with only one click.
  * In comparison, having the toggle inside the previewer would mean you would need multiple clicks: selecting the item, setting the toggle, marking unread, then selecting another item...

Why do I set this "Important" status instead of just marking those items as unread? Because I don't want them to be auto-pruned from the feed whenever it exceeds item cache limits or old-age limits... it's mostly the only trick I found for my usage pattern when I "batch flag, then batch read later" once every few weeks/months...

In reaction to your question above, my hunch is that having the "important/flagged" interactive icons be on the opposite side as the favicons would be a reasonably useful approach, with these considerations:

* Ideally with the favicons forced to a strict standard width/height, even if it happens to be very small (particularly in compact listview) to avoid weird height variations like issue #534
* I _think_ the order wouldn't be terribly important, it could be status icon on the left edge and favicon on the right edge, or vice versa... but I haven't thought about this terribly deeply so far, and I guess it's the kind of thing that we might end up seeing "in practice"...
 * Alternatively, if you strongly prefer something less "highly visible" as the red (!) icon (especially if you're considering having the flagged status icon be near the favicon again), you could also use the standard "non-starred-symbolic" and "starred-symbolic" (or the colorful variants: "starred" and "non-starred") GTK/Adwaita status icons. This _might_ alleviate the issue of the status flag icons feeling "too close to the favicons"?

**Comment by lwindolf** [comment]
Thank you for this great input! I did several experiments. It turned out the one about having favicons to the right doesn't work at all. They are visually too noisy and put to much weigth and contrast to the right. Actually with high contrast icons on the left and on the right the text becomes somewhat invisible.

This is why I further focussed on the restoration of the old behaviour. After thinking a while: why not use the favicon column as click target? And if it is not present simply show the normal state column (with somewhat larger icons) instead. So in wide pane there is always a icon column in front which one can use to toggle the flag.

I've uploaded the experiment in the branch "wide_view_test". Would be great if you can test it.

The branch also has teaser texts as shown in the NNW screenshot. While they use up even more vertical space I still believe they add a lot of value especially for power users skimming a lot of content. For me it reduces the click-through on feeds with bad titles significantly. How is this for you?

**Comment by lwindolf** [comment]
The wide_view_test branch is now merged with master. With the new solution the icon for status important is visible again.
