### ISSUE TITLE
Date and time indicators in the new feed items listview don't need parentheses

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#535]
In 1.12 RC3, feed items show themselves like this in the listview:

> <b>Blah blah blah this is a blog post title</b> — (date_and_time)

But it should probably be:

> <b>Blah blah blah this is a blog post title</b> — date_and_time

...because the former is just adding extra visual noise for nothing, considering there is already an emdash with spacing on each side of the emdash.

**Comment by lwindolf** [comment]
Agreed.
