### ISSUE TITLE
Text is rendered over other text

### ISSUE THREAD

**Issue by jNullj** [lwindolf/liferea#537]
# issue
Text is rendered over other text, making it impossible to read and click links.
![problem](http://i.imgur.com/XJMhZoX.png)

# About the system
OS: Archlinux x64 up to date
Liferea version 1.12-rc3
DE: KDE plasma 5.10.5

**Comment by rich-coe** [comment]
web page url?
feed url?

**Comment by jNullj** [comment]
Happens with all of my feeds, but its only with some of the text/links
this image is from https://www.reddit.com/r/FreeGamesOnSteam/.rss
another example would be http://feeds.feedburner.com/Explosm
Or any of my github feeds (reporisotry url .atom )
some text does show up currectly, like the commit itself, but the information around it is all at the same position, on each other, and _outside of the actual web frame_
