### ISSUE TITLE
Main window won't show up from the tray icon menu

### ISSUE THREAD

**Issue by City-busz** [lwindolf/liferea#538]
Steps to reproduce:
1. Enable the Tray Icon plugin.
2. Minimize the main window.
3. Right click on the tray icon, and select "Show / Hide" item.
Expected behaviour: the main window become visible again.
Actual behaviour: the main window won't show up even if I click multiple times on the menu item.

My PR fixes the problem: #523

**Comment by lwindolf** [comment]
That's exactly the problem I was trying to explain: there are so many desktop environment combinations that I cannot reproduce it. The plugin says it support only GNOME classic.

Are you using GNOME classic? If yes, which version? And which window manager?

**Comment by lwindolf** [comment]
@City-busz Just for fun: have a look at #505. It's impossible to support the feature.

**Comment by City-busz** [comment]
I'm using gnome-flashback 3.24.0 and metacity 3.24.1. I can test this problem with and without my changes in different desktop environments if you consider to accept my PR. The solution is really simple: we have to deiconify() the window before showing it again.

**Comment by lwindolf** [comment]
I could reproduce the issue on Ubuntu 17.04 GNOME Flashback (Metacity)

**Comment by lwindolf** [comment]
Please retest! Fix was done in liferea_shell_toggle_visibility()
