### ISSUE TITLE
Keep Headline-Preview Ratio

### ISSUE THREAD

**Issue by Euren** [lwindolf/liferea#540]
When the window is resized, the various panes do not resize appropriately. That is, when I make the window vertically smaller, the preview pane below rises up but when I make the window larger again, the preview pane stays large. 

I would like to suggest we keep a fixed ratio between the headlines the preview pane. 

It's a bit frustrating to have to resize the separation line every time I resize the window. Especially when using a tiling window manager which resizes.

Version: 1.12-rc2

Somewhat in line to #374

**Comment by lwindolf** [comment]
Please retest with recent releases!
