### ISSUE TITLE
Potential problem with the enrich items feature

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#542]
It is enabled by default and it clogs the job queue.

I discovered that when trying to reproduce a segfault, which looked like it happened at update.

First "update all" appeared to work, but next update was stuck in the pending jobs queue. The queue containing about 15000 items ... 

Maybe I'm keeping a bit too many feeds and too many items that I barely read, but maybe it is not a good idea to try to download *every* article at once like that :D 
Some websites may also dislike the big number of automated requests.

**Comment by lwindolf** [comment]
You are 100% right. Shouldn't be on per-default. It needs a per-feed option to extract extra content. So you consciously decide for which feeds you want deep crawling.

**Comment by lwindolf** [comment]
Code has no a per-default off feed property. The only sad thing is: nobody will find it...
