### ISSUE TITLE
linux reddit feed broke since couple days

### ISSUE THREAD

**Issue by WhatsThePlan** [lwindolf/liferea#547]
hi. following feed broken since a couple of days, gives error that feed could not be parsed:

https://www.reddit.com/r/linux/.rss?limit=200

since feed change before bug is maybe solved i create gist of current broken version for you here:

https://gist.github.com/WhatsThePlan/1ec173720bf51a46ff5641793a930b33

**Comment by Leiaz** [comment]
The error is in the feed, it contains an invalid (for xml documents) character : `PCDATA invalid Char value 27`

The parser is set to not be tolerant of errors.
