### ISSUE TITLE
Tray Icon Ubuntu 16.04 still not showing in v1.12-rc3

### ISSUE THREAD

**Issue by 2SI3NX** [lwindolf/liferea#550]
Even the latest stable version, it will not show the tray icon.

Firstly let me say that i have looked into many rss feed readers and none of them compare to Liferea and the simplicity and necessities it offers!
I used to use quiterss before this, and i have many reasons why I changed. Firstly their dev team does not respond to any requests and have updates once a year. Secondly one of the options to bypass proxy in Liferea does not even exist as an option in quiterss which is awesome. And many more reasons!

The main point of this issue is that im sure many of us using Ubuntu would like tray icon to finally work.  Ive seen many of the same issues being opened on here but will it be fixed?

1. In the plugins menu, none of the plugins preferences work. ie. the preferences button is greyed out in all plugins AND the tray icon.

2. Will we be able to set Liferea to startup in the tray at startup?  You could put a setting in the plugin menu's preferences. 

3.
If I can also suggest 2 other Enhancements that quieterss has which was quite convenient.

3.1. Instead of having inotify notifications that a certain feed was just "updated" doesnt offer much of a notification. can you make it rather that it pops up from any position on the screen the user wishes to configure it? such as the bottom right or the bottom left.

3.2. Relating to 3.1, To show the news headlines of new updated feeds in that popup notification, just like in quiterss. Instead of just saying "updated CNN feed" which is a bit pointless.

Thanks for your time and an awesome rss feeder!

**Comment by lwindolf** [comment]
Which desktop are you using in Ubuntu? And which Ubuntu version?

**Comment by 2SI3NX** [comment]
Normal Ubuntu 16.04 gnome with Unity.

**Comment by lwindolf** [comment]
@2SI3NX I could reproduce this with Unity. Unity explicitely doesn't want trayicon und uses libindicate instead. Sadly this means it will never work with Unity. The good news: with Ubuntu 17.10 Unity is permanently gone.

This means we will all be on GNOME again soon. And in GNOME there is a good GNOME shell extension named "topicons" which brings the trayicon features back again. 

As for your question as wether Liferea will be able to start to the tray again: yes

**Comment by 2SI3NX** [comment]
Thanks, however i dont think i understand..how do other apps do it and dont have a problem with the tray icon?  Deluge for example..

**Comment by lwindolf** [comment]
In Unity the "tray" isn't a real tray, but a special so called indicator widget implemented using libindicate. The Ubuntu maintained Liferea package is compiled with support for libindicate. If you compile the latest 1.10.x you can compile with libindicate support by running

    ./configure --enable-libindicate

As Ubuntu dropped Unity and libindicate 1.12 doesn't contain support anymore.
