### ISSUE TITLE
Nextcloud synchronization

### ISSUE THREAD

**Issue by towo** [lwindolf/liferea#551]
Since Liferea is syncing with a few external sources, and nextcloud-news with a lot of clients, maybe one could unite those two?

**Comment by mase76** [comment]
+1

**Comment by griseus** [comment]
+1

**Comment by jajaxor** [comment]
+1

**Comment by logos88** [comment]
+1

**Comment by sbaconnais** [comment]
That would be awesome

**Comment by qazip** [comment]
I'm also looking forward to this.

**Comment by qazip** [comment]
I'm also looking forward to this. Are you planning to support this anytime soon @lwindolf?

**Comment by petre2dor** [comment]
+1

**Comment by veloute** [comment]
+1

**Comment by operat** [comment]
+1

**Comment by puresick** [comment]
+1

**Comment by Valdaer** [comment]
+1

**Comment by kujaw** [comment]
Just wondering if anything has changed related to this topic.

**Comment by lwindolf** [comment]
No changes. No one is working on it. Contributions are essential here :-)

**Comment by zero77** [comment]
Nextcloud news API documentation:
https://github.com/nextcloud/news/blob/master/docs/externalapi/External-Api.md
https://github.com/nextcloud/news/issues/102
