### ISSUE TITLE
Unread items count not updated when items are read by another TT RSS client

### ISSUE THREAD

**Issue by openhs** [lwindolf/liferea#557]
When using Tiny Tiny RSS items can be read by another client besides Liferea (for example in web interface).  If so Liferea does not update unread items count.

Let's say Liferea shows 2 unread items for a feed Foo in Feed List.  Then these two items are read in the Tiny Tiny RSS web interface.  Going back to Liferea it still shows 2 unread items for Foo.  Refresh nor Mark All As Read does not help.

When Liferea is in this inconsistent state Ctrl + N (Next Unread Item) does not work properly.  It wants to jump to a non existing unread item and refuses to go further to the proper (actually existing) unread items.

This is for version 1.12-rc3.

**Comment by lwindolf** [comment]
That's not good. It should catch up the read state from the TinyTinyRSS instance and mark the items as read on next fetch.
