### ISSUE TITLE
how to configure tt-rss with basic auth

### ISSUE THREAD

**Issue by pcause** [lwindolf/liferea#564]
My tt-rss server is configured to use basic auth.  When I configure a new news source there is the user/password, but I don't see a field for basic auth credentials.  When I create the source it never loads anything.  I suspect this is because of the basic auth.   I've also tried entering the user name and password for tt-rss in the new source dialog and the http auth credential in the URL:

https://user;paw@server.com:port/ttrss

and that doesn't work either.  on a console window I can see errors that say login failed with http error 0.  I note that for regular subscriptions there is a property page for entering http auth information.

**Comment by lwindolf** [comment]
Yes, the subscription properties dialog for remote sources doesn't expose basic auth support.

As a workaround and depending how sensible the password is you could add to ~/.config/liferea/feedlist.opml. You could add it to the xmlUrl attribute directly:

    <outline title="Tiny Tiny RSS" type="source" id="jbwipcd" sourceType="fl_ttrss" xmlUrl="http://user:password@myserver.com/tt-rss/" htmlUrl="" updateInterval="-1" expanded="true"/>

**Comment by pcause** [comment]
tried this on latest and can't login.  just says login request failed with error 0.

**Comment by ocdtrekkie** [comment]
This is what I'd need to be able to use this with my TTRSS instance as well, since it is on Sandstorm.
