### ISSUE TITLE
in-app customizable keyboard shortcuts

### ISSUE THREAD

**Issue by ghettoparazite** [lwindolf/liferea#565]
Please add the ability to add/remove/modify in-app keyboard shortcuts.

**Comment by lwindolf** [comment]
This is already possible. Check out https://lzone.de/liferea/blog/Liferea+Trick+%238%3A+Change+Menu+Accelerators

**Comment by lwindolf** [comment]
I see. Well Liferea use GTK as widget toolkit. And the toolkit sets some constraints and standards on applications implemented in this toolkit. For GTK/GNOME shortcut handling is more or less universally handled using the techniques in the blog post.

1000 GTK applications building 1000 different accelerator config dialogs doesn't make sense.
