### ISSUE TITLE
Updated italian translation

### ISSUE THREAD

**Issue by Janvitus** [lwindolf/liferea#566]
...is here! :)

Cheers

BTW, the items in the Preferences/Plugin tab are not translatable.

[liferea.it.zip](https://github.com/lwindolf/liferea/files/1544745/liferea.it.zip)

**Comment by lwindolf** [comment]
Thank you for the contribution. I already added the it.po.

About the OPML update: you remove some music feeds that still work fine. Why?

Finally about the plugins. You can translate those only via the *.plugin files in the plugins/ subdirectory. Here is an example:

    $ cat ../plugins/gnome-keyring.plugin 
    [Plugin]
    ...
    Name=GNOME Keyring Support
    Name[de]=Unterstützung für GNOME Keyring
    Name[he]=תמיכה עבור GNOME Keyring
    Description=Allow Liferea to use GNOME Keyring as password store
    Description[de]=Erlaubt Liferea Passwörter im GNOME Keyring zu speichern
    Description[he]=אפשר ליישום Liferea להשתמש בתוכנה GNOME Keyring כמחסן סיסמאות

**Comment by Janvitus** [comment]
OPML: i've changed/added some feeds from "Italian feed examples", i haven't touched the "english default feeds".

BTW: I'm Gianvito (@gmx.it), the last Liferea (and GNOME) italian translator ;)

For the plugin,

trayicon.plugin:
Name[it]=Icona di vassoio (GNOME Classic)
Description[it]=Mostra una piccola icona nel vassoio di sistema per visualizzare o nascondere l'applicazione.

media-player.plugin:
Name[it]=Riproduttore multimediale
Description[it]=Riproduce musica e video direttamente nell'applicazione.

libnotify.plugin:
Name[it]=Notifiche popup
Description[it]=Mostra dei popup che informano sui nuovi aggiornamenti.

gnome-keyring.plugin:
Name[it]=Supporto al portachiavi di GNOME
Description[it]=Consente all'applicazione di usare come archivio delle password il portachiavi di GNOME.

bold-unread.plugin:
Name[it]=Non letti in grassetto
Description[it]=Testo in grassetto per gli abbonamenti con articoli non letti nell'elenco dei notiziari

Regards.

**Comment by lwindolf** [comment]
@Janvitus: Thanks for the plugin updates and the OPML clarification, I misread the comment!

Thanks a lot for the long time contribution! Happy new year!

**Comment by Janvitus** [comment]
@lwindolf i've updated the translation :)

[liferea_it.zip](https://github.com/lwindolf/liferea/files/9903180/liferea_it.zip)

**Comment by lwindolf** [comment]
@Janvitus I've added your translation to the code.
