### ISSUE TITLE
Disable smooth scroll in news' window

### ISSUE THREAD

**Issue by qazip** [lwindolf/liferea#568]
Hello,

The scroll speed is perfect both in feed's list and news' list. However, in the news window (where the actual content is), the scroll is way too slow, seems like it has smooth scroll, which I hate. It would be good to either disable for everyone or give us an option in the settings to toggle it on/off.

**Comment by lwindolf** [comment]
Good point.

From a technical perspective the difference is caused by feed/item lists being GtkTreeViews following GTK defaults, while the HTML pane is Webkit which is probably influenced by Chromium scrolling behaviour and defaults to smooth-scrolling.

**Comment by Leiaz** [comment]
It is available as a setting for the WebKit view, but according to [the doc](https://webkitgtk.org/reference/webkit2gtk/stable/WebKitSettings.html#WebKitSettings--enable-smooth-scrolling) it is already off by default.

**Comment by liskin** [comment]
Do note that the "too slow" behaviour doesn't happen everywhere. On my Debian, it scrolls just as fast as everywhere else, with the additional "feature" that both smooth and non-smooth scrolling happens at the same time, so as I'm moving my fingers, it scrolls smoothly for a bit, then jumps, then scrolls smoothly, jumps, ... :-)

**Comment by Leiaz** [comment]
If you want to try explicitly setting it on or off, to see if it fixes this, you can add : 

```diff
diff --git a/src/webkit/webkit.c b/src/webkit/webkit.c
index c77fb01c..a10ffd89 100644
--- a/src/webkit/webkit.c
+++ b/src/webkit/webkit.c
@@ -402,6 +402,8 @@ liferea_webkit_impl_init (LifereaWebKitImpl *self)
                self->settings,
                "minimum-font-size",
                normalize_font_size (7),
+               "enable-smooth-scrolling",
+               FALSE,
                NULL
        );
        conf_get_bool_value (DISABLE_JAVASCRIPT, &disable_javascript);
```

You can also check if it happens with other WebKit based apps, like the Epiphany web browser. If you are using touchpads, [scrolling may be handled differently](https://bugs.webkit.org/show_bug.cgi?id=155750).

**Comment by sulfurcatwalk** [comment]
hello,
do you plan to add this? is there an easy workaround to disable it? smooth scrolling makes me dizzy.
