### ISSUE TITLE
Option to dim read news items

### ISSUE THREAD

**Issue by ghettoparazite** [lwindolf/liferea#569]
Please add a option to dim the read news items with something like 30-40% to make it easier to find new news items at a glance.

**Comment by lwindolf** [comment]
What do you mean exactly? Like have a lighter color shade for the text color? Or do you refer to the font size?

**Comment by ghettoparazite** [comment]
I mean darken the font to a grey shade.

**Comment by lwindolf** [comment]
I see. Thank you for clearifying.

When a GTK application has the goal to work with all existing GTK themes this is really hard. There is only a single font color. There is no other color the theme gives you to brighten stuff. Especially not when reusing a widget (as the GtkTreeView) which already reuses other theme colors of lighter shades for different purposes.

Given the theme related color bug reports Liferea got over the last 15 years this is not a good idea.

We are actually doing a similar thing in the HTML pane, where we use up to 3 shades of theme colors. The difference there is that we do control all colors used and can ensure contrast. Sadly this is not possible  in the tree views.
