### ISSUE TITLE
Liferea doesn't remember the feeds' custom settings

### ISSUE THREAD

**Issue by geplus** [lwindolf/liferea#572]
Hi
OS: Manjaro Linux
Liferea's version: 1.12.0

Liferea doesn't remember the custom order of the news and the custom colum's width, ot only when I close and reopen the program, but even when I click on anotehr feed and then I return on the feed that have the custom settings.
The 1.12-rc3 version of Liferea works well, no problems with it.

**Comment by lwindolf** [comment]
Reproduced.
