### ISSUE TITLE
Allow additional enclosure download tools

### ISSUE THREAD

**Issue by DirkSchmitt** [lwindolf/liferea#575]
Problem in short
----------------
The supported *download* applications are hardcoded and limited.
This results is inpossible extensibility without „hijacking“ on of the hardcoded command.

My use case
-----------
I want to download enclosures with a custom and special postprocessing done by a script I written for myself.
Let for the moment reference this script as *myDownloadScript*.

Currently I'm force to add *myDownloadScript* as a link in with a name like *kget* or *uget-gtk* to a location
recognized by my `PATH` statement.

This is an awfull hack → 😱

Surely the hack can be encapsulated in a custom wrapper script for *liferea* – but is still an awfull hack.

Proposal
--------

In *./src/ui/preferences_dialog.c* I see the following code:

```
/** download tool commands need to take an URI as %s */
static const gchar * enclosure_download_commands[] = {
"steadyflow add %s",
"dbus-send --session --print-reply --dest=org.gnome.gwget.ApplicationService /org/gnome/gwget/Gwget org.gnome.gwget.Application.OpenU
RI string:%s uint32:0",
"kget %s",
"uget-gtk %s"
};

/** order must match enclosure_download_commands[] */
static const gchar *enclosure_download_tool_options[] = { "steadyflow", "gwget", "kget", "uget", NULL };
```

My proposal is to add an additional method:
```liferea-user-script %s```

This would allow to install *myDownloadScript* under a name, which would not hide a tool used in other places.
Also it introduce an extension point.
If the script *liferea-user-script* is not existing on the local system it behaves like e.g. for *steadyflow* also
not available on many installation.

**Comment by da2x** [comment]
Issue #583 added more tools to the list and expanded protocol support.

We shouldn’t add a magical liferea-user-script option, but rather let user’s select their own script or executables  with a file chooser widget.

**Comment by lwindolf** [comment]
So the typical radio button with the select box after the first option and a file dialog behind the other. Sounds like a good idea.

**Comment by Leiaz** [comment]
@da2x Did you want to write this ?
