### ISSUE TITLE
Date column positioning

### ISSUE THREAD

**Issue by flyingOwl** [lwindolf/liferea#579]
I just got updated to version 1.12.0 on my Fedora machine. And I really don't like the change that was described here: #321 and done here: #399 . For me the date column is very important so I never wanted it anywhere else.

I have a few news feeds which I rarely read (say: marking items as read) but I sometimes visit the website. So whenever I open that feed I only want to scroll down to an item I have already seen (while visiting the website the previous day e.g.). While scrolling, I heavily depend on the date column. It's easier to remember the time of the last visit than the last headline I've seen. And now the date column is so far away from the headline that it's really unpleasant to keep an eye on it. It's also not easy to see which date belongs to which headline. I know you can change to width of the headline column, but this messes with long titles and would create a lot whitespace to the right.

I also sometimes open (very active) feeds and want to check the time of the last item. Now my eyes have to pan over the whole screen instead of just a few centimeters.

I would propose to either make the columns draggable, so everyone can change the columns on their own. Or at least add a switch to the settings to toggle the date placement (before the title or after the title).

**Comment by sitaramc** [comment]
I second this.  In many of my feeds, I want to wait 2-3 days before I open the link, because the comments are often more interesting/important than the main article (which I would have probably seen elsewhere anyway).

I definitely do not like this change that forcibly moved the date to the far right.  Please make it draggable.

Speaking for myself, even a simple format spec in the preferences that specifies what column goes where would be fine.  So, for example, the default might be "%F %H %A %D", and people like me and flyingOwl could change it to "%F %D %A %H".  You could also allow strftime format specs for the "%D" part.

**Comment by yaneti** [comment]
Technically a plugin approach similar to the bold-unread plugin would work eg:
```
from gi.repository import GObject, Peas, PeasGtk, Gtk, Liferea, Gdk, Pango

class NrDateFirstPlugin (GObject.Object, Liferea.ShellActivatable):
    __gtype_name__ = 'NrDateFirstPlugin'

    shell = GObject.Property (type=Liferea.Shell)

    def do_activate (self):
        normalviewitems = self.shell.lookup ("normalViewItems")
        self.itemlist = normalviewitems.get_child().get_child()
        self.columns = self.itemlist.get_columns()
        self.itemlist.move_column_after(self.columns[4], self.columns[1])


    def do_deactivate (self):
        self.itemlist.move_column_after(self.columns[4], self.columns[3])
```
But not in this simplistic form because that would be very fragile  wrt columns order and view mode changes

**Comment by lwindolf** [comment]
While moving a column is easy we must not forget that GTK forces us to do pixel-calculations to determine which column was clicked. Any volatile column ordering absurdely increases complexity there.

There is a reason why there is no common column reodering library/solution/dialog in GTK apps :-)

**Comment by yaneti** [comment]
wrt to the pixel calculations I see two options
- prevent draging the date column to position 0 , with GtkTreeViewColumnDropFunc
- find a way to avoid the hacks in on_item_list_view_button_press_event . I don't know how, I just have the gut feeling this shouldn't be this hard

**Comment by yaneti** [comment]
Added an additional commit to the #587 branch that avoids pixel calculations on click and allows the date column to be  ordered at any place

**Comment by lwindolf** [comment]
Closing this a the DnD PR was merged.
