### ISSUE TITLE
Numeric feed entry titles are right-aligned

### ISSUE THREAD

**Issue by Gert-dev** [lwindolf/liferea#582]
Usually feed entry titles are aligned left in the column (or right in RTL languages). It seems that this changes whenever the feed entry title only contains a number, such as `1.2.3`, which often happens for GitHub release feeds for projects following semantic versioning:

![test](https://user-images.githubusercontent.com/24809863/34463006-1baad3ca-ee50-11e7-8cff-f4171ae48f7b.png)

**Comment by lwindolf** [comment]
Argh, to properly support RTL languages there is an auto-sensing on feed titles which injects a direction marker. For some reason "1.1.20" seems to be detected as an RTL direction string.

The thing is Liferea uses GTK RTL detection methods. So there is no way we can influence the result...

**Comment by Gert-dev** [comment]
Thanks for your response. Do I understand correctly that this is in fact a GTK bug? In that case I'll look into reporting an issue to GTK instead.
