### ISSUE TITLE
Plugin installer plugin issues

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#593]
The filter by category combo is lacking an "All" option, so it is not possible to go back to showing all without closing the window.
It would be nice to see the source/author, maybe with a link, from the GUI.

Trying to install plugins results in : `Failed to enable plugin (<class 'NameError'>) !` and on next attempt `Failed to copy plugin directory (<class 'FileExistsError'>) !` The plugins are available in preferences > plugins as they have been copied to the plugins directory.

Installing dependencies fails because of lack of permissions to install. Maybe pip should be called with the `--user` option, as the plugins themselves are also installed in the user's home ?

Also [GtkUIManager has been deprecated since Gtk 3.10](https://developer.gnome.org/gtk3/stable/GtkUIManager.html#gtk-ui-manager-new). Any plugin that uses it will need to be rewritten, although likely not before Gtk 4 as it still works in 3.22 which is the last Gtk 3 release.

**Comment by lwindolf** [comment]
Thanks for the feedback. I'll address the issues. GUI is for from reasonably well done :-)

**Comment by lwindolf** [comment]
As for GtkUIManager you are right, still the GTK Docs are unhelpful as for the alternative (probably GtkBuilder but a per-method replacement suggestion would be really helpful).

**Comment by lwindolf** [comment]
Plugin activation is fixed now (schema id was missing).

Plugin reinstallation is somehow prevented now (new 'Install' button is insensitive, although row activation is still possible and should be disable also).

**Comment by lwindolf** [comment]
Should be much better now.
