### ISSUE TITLE
Polish default feeds

### ISSUE THREAD

**Issue by wmyrda** [lwindolf/liferea#594]
Feeds present in Liferea for polish users have been broken or outdated for years. I recommend remove them from https://github.com/lwindolf/liferea/blob/master/opml/feedlist_pl.opml

    <outline text="Przykładowe Subskrypcje">
      <outline text="polskie">
        <outline text="7thGuard.net" htmlUrl="http://www.7thguard.net/" xmlUrl="http://rss.7thguard.net/7thguard.xml" />
        <outline text="Linux.pl" htmlUrl="http://linux.pl/" xmlUrl="http://www.linux.pl/rss.php" />
      <outline text="Hacking.pl" htmlUrl="http://hacking.pl/" xmlUrl="http://rss.hacking.pl/" />
      </outline>

and replacing with

    <outline text="Przykładowe Subskrypcje">
      <outline text="Wiadomości IT">
        <outline text="Benchmark.pl" htmlUrl="http://www.benchmark.pl/" xmlUrl="http://www.benchmark.pl/rss/aktualnosci-pliki.xml" />
        <outline text="dobreprogramy" htmlUrl="https://www.dobreprogramy.pl/" xmlUrl="http://feeds.feedburner.com/dobreprogramy/Aktualnosci?format=xml" />
        <outline text="Dziennik Internautów" htmlUrl="http://di.com.pl/" xmlUrl="http://feeds.feedburner.com/glowny-di?format=xml" />
        <outline text="TwojePC.pl" htmlUrl="https://twojepc.pl/" xmlUrl="https://twojepc.pl/news_rss.php" />
      <outline text="Bezpieczeństwo IT"> 
        <outline text="Sekurak" htmlUrl="https://sekurak.pl/" xmlUrl="http://feeds.feedburner.com/Sekurak?format=xml" />
        <outline text="Niebezpiecznik.pl" htmlUrl="https://niebezpiecznik.pl/" xmlUrl="http://feeds.feedburner.com/niebezpiecznik?format=xml" />
      </outline>

In case you wonder "Wiadomości" means news while "Bezpieczeństwo" means security

thanks!

**Comment by wmyrda** [comment]
Something broke links visibility. I placed 6 different feeds there, but for some reason there are not visible clearly in html while I can see them all. Hopefully I will spot what has been broken

**Comment by lwindolf** [comment]
Thanks for the update. Next time please directly edit it using github, it is really easy!
