### ISSUE TITLE
slatestarcodex's rss feed is not recognized

### ISSUE THREAD

**Issue by UnkindPartition** [lwindolf/liferea#595]
[slatestarcodex's rss feed](http://slatestarcodex.com/feed/) stopped working recently. 

> There were errors while parsing this feed!
> Details
> Could not detect the type of this feed! Please check if the source really points to a resource provided in one of the supported syndication formats!
> 
> XML Parser Output:
> The URL you want Liferea to subscribe to points to a webpage and the auto discovery found no feeds on this page. Maybe this webpage just does not support feed auto discovery.Could not determine the feed type.
> 
> You may want to contact the author/webmaster of the feed about this!

The thing is, this is the feed, not a webpage, but liferea doesn't seem to recognize it. 

```
% curl -D -  -s http://slatestarcodex.com/feed/ | head -30
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 25 Jan 2018 15:16:32 GMT
Content-Type: application/rss+xml; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Keep-Alive: timeout=20
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Pragma: no-cache
Last-Modified: Thu, 25 Jan 2018 08:32:39 GMT
ETag: "e36b7b49b34e24ec112bb4f46fcd8ae7-gzip"
Link: <http://slatestarcodex.com/wp-json/>; rel="https://api.w.org/"
X-Cacheable: CacheAlways: feed
Cache-Control: max-age=600, must-revalidate
X-Cache: HIT: 2
X-Pass-Why:
X-Cache-Group:
X-Type: feed

<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>

<channel>
	<title>Slate Star Codex</title>
```

The RSS validator does find an [obscure xml entity error](https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fslatestarcodex.com%2Ffeed%2F#l146), but it doesn't seem severe enough not to recognize the url as an rss feed.

Tested with the current master (a0a7464).

**Comment by feuerbach** [comment]
I think the fact that the feed was invalid was causing this. As of now, the feed seems to be fixed.

It would still be nice to give a better error message. Liferea doesn't distinguish between a broken rss feed and a webpage without a feed.

**Comment by rfc1036** [comment]
The same currently happens for Boing Boing's feed, which has a badly escaped URL: https://boingboing.net/feed/atom .

**Comment by rfc1036** [comment]
I also had to "fix" http://blog.urbanfile.org/category/milano/feed/ with a script because it has a newline character at the beginning of the stream.

**Comment by rich-coe** [comment]
I use this script to skip those feeds that have whitespace at the beginning of their feeds.

--- skipwhitespace.pl ----

    : # use perl                            -*- mode: Perl; -*-
          eval 'exec perl -S $0 "$@"'
            if $running_under_some_shell;

    $first = 1;

    while (<>) {
        if ($first && m/^\s+/) {
            s/^\s+//;
            next if (/^$/);
        }
        $first = 0;
        print $_;
    }

**Comment by lwindolf** [comment]
Closing old issue
