### ISSUE TITLE
CSS stylesheet not picking #GTK-COLOR-NORMAL-LINK from GTK theme

### ISSUE THREAD

**Issue by pupyc** [lwindolf/liferea#602]
I'm using liferea with gnome 3.26, adapta-gtk-theme and Wide view.

I found that the article view does not follow my gtk theme (I only noticed the link colors), and I don't know if it is only in the article view, but here is a screenshot 
![omg](https://user-images.githubusercontent.com/31791780/35841454-f6fcadb2-0af3-11e8-8a6b-0844591fcc84.png)

another UI thing is favicons, most people use 8x8 or 16x16 favicons for their website, but liferea scales them to fit the area and that pixelates the images
![list](https://user-images.githubusercontent.com/31791780/35841657-0f9844d4-0af5-11e8-8d54-f836565ebcfd.png)
I suggest viewing an image from the article not the website favicon is a good idea but I don't know if it is possible, but I have seen other feed readers doing that.

another feature I miss is mark as read by scroll over news items.

thank you for your great work!

**Comment by lwindolf** [comment]
The link color is definitively an issue. It's the only thing currently not styled. The default blue usually works fine with brighter themes, but fails in terms of contrast on all dark themes. And let's not speak about blue themes.

We could use the dark theme detection for switching the link color to a light blueish color.

The favicons are not nice I agree. The favicon link extraction code is something from around 2006 and needs to be redone. Actually it is easy as nowadays most commercial sites have up to 20 icon sizes and we just have to choose the right one. Of course it will not help with all icons...

**Comment by pupyc** [comment]
When I try `liferea --debug-html` it show the color for 

`HTML   : theme color "GTK-COLOR-FG" is CFD8DC`
`HTML   : theme color "GTK-COLOR-BG" is 263238`
`HTML   : theme color "GTK-COLOR-LIGHT" is 2E424C`
`HTML   : theme color "GTK-COLOR-DARK" is 1C2225`
`HTML   : theme color "GTK-COLOR-MID" is 253239`
`HTML   : theme color "GTK-COLOR-BASE" is 263238`
`HTML   : theme color "GTK-COLOR-TEXT" is CFD8DC`
`HTML   : Dark GTK theme detected.`
`HTML   : theme color "FEEDLIST_UNREAD_BG" is CFD8DC`
`HTML   : theme color "FEEDLIST_UNREAD_FG" is 263238`
`HTML   : Feed list unread CSS: foreground='#263238' background='#CFD8DC'`

But there is no nothing about `#GTK-COLOR-NORMAL-LINK`, `#GTK-COLOR-VISITED-LINK`, maybe something from gtk side has changed

**Comment by lwindolf** [comment]
@pupyc Ah...  it seems since we implemented the theme coloring more recent GTK versions added link color constants. I'll add them asap, as this is a great improvement! Thanks for hinting on this!

**Comment by lwindolf** [comment]
Ah... it's more complicated. Even though the code dates back to 2013 we already handle the link colors. But we do so conditionally:

	color = NULL;
	gtk_widget_style_get (widget, "link-color", &color, NULL);
	if (color) {
		themeColors = g_slist_append (themeColors, render_calculate_theme_color ("GTK-COLOR-NORMAL-LINK", *color));
		debug0 (DEBUG_HTML, "successfully set the color for links");
		gdk_color_free (color);
	}

So if the widget from whose theme we extract the colors has the "link-color" style, then we extract the color. If it works a debug message "succesfully set the color for links" should appear.

**Comment by lwindolf** [comment]
After checking the GTK docs I found finally doing the migration from GtkStyle (which is deprecated) to GtkStyleContext seems to be the solution as in GtkStyleContext there are more GTK_STATE_FLAG_* variants including some for the link colors.

**Comment by lwindolf** [comment]
Above PR fixes the problem.
