### ISSUE TITLE
Liferea installed with show a popup window with new headlines default ON

### ISSUE THREAD

**Issue by pktehgm** [lwindolf/liferea#605]
How can I install Liferea with Preferences\GUI\Notification Settings\Show a popup window with new headlines turned/marked ON by default?
Is there a configuration file I can change somewhere?

**Comment by Leiaz** [comment]
Liferea uses GSettings, the gschema is [net.sf.liferea.gschema.xml.in](https://github.com/lwindolf/liferea/blob/master/net.sf.liferea.gschema.xml.in). GSettings have a way to override the default values when packaging, see the [vendor overrides section on GSettings doc](https://developer.gnome.org/gio/stable/GSettings.html#GSettings.description).

The settings key for this was `show-popup-windows`, but it is no longer used in recent Liferea versions. The notifications are done with the libnotify plugin instead. The setting for the list of enabled plugins is `active-plugins`.

**Comment by pktehgm** [comment]
I found that changing the /usr/share/liferea/prefs.ui changes that toggle
