### ISSUE TITLE
Main windows doesn't show up on Linux Mint

### ISSUE THREAD

**Issue by DavidB87** [lwindolf/liferea#606]
I'm currently on latest Linux Mint 18.3 64-bit.
Cinnamon 3.6.6

Liferea version 1.10.17-1ubuntu2

In the task manager I can see the app, it uses 18,5 MiB in memory, but the window never pops up.
I reinstalled it, rebooted system. Nothing helps.

**Comment by Leiaz** [comment]
Try launching Liferea with `liferea -w shown`. If you used the tray icon in the past, Liferea may start with the window minimized.

**Comment by DavidB87** [comment]
It works only via Terminal. Starting from shortcut, or autostart does not help.

**Comment by Leiaz** [comment]
After you close it it should restart in the same state. But if it doesn't you can try changing the `last-window-state` setting to zero with GConf editor.

You are also using a very old version of Liferea.

**Comment by lwindolf** [comment]
Closing old ticket
