### ISSUE TITLE
'Mark all items read' is misleading

### ISSUE THREAD

**Issue by headsign** [lwindolf/liferea#607]
I've read of someone complaining about this before and here I am, after making the same mistake twice in two months: while wanting to update the feeds, I erroneously clicked on 'Mark all items read', which can't be undone.

The issue: the button is in a much too prominent place and its tooltip suggests (me at least) that it updates all items. But most of all, an option to undo the last action would be helpful. Or maybe add a silly dialog like "Are you sure..."

Also, I don't think marking all items read is such an important action that it should be a tooltip but that's just my opinion :)

**Comment by lwindolf** [comment]
The plan is to add a confirmation dialog. See #591 

Closing this as a duplicate.
