### ISSUE TITLE
Option to force HTTPS

### ISSUE THREAD

**Issue by ghost** [lwindolf/liferea#609]
Please add an option to only use HTTPS for fetching feeds.

**Comment by superkuh** [comment]
Does this mean that your copy of liferea actually works with HTTPs feeds? I'm using 1.10.3 from the Ubuntu 14.04 repos and it fails with, "HTTP error code 0: A network error occurred, or the other end closed the connection unexpectedly" on all HTTPS feeds.

**Comment by da2x** [comment]
No. Just no. This will break as there is no guarantee that the server will serve the same content from HTTPS as it does on HTTP.

Liferea updates feeds that permanently redirect from HTTP to HTTPS and sends future requests directly to HTTP.

Lifeea could implement HTTP Strict Transport Security. However, this belong down in libsoup and not Liferea.
