### ISSUE TITLE
SIGSEGV in gtk_tree_model_filter_build_level when dragging feed out of folder

### ISSUE THREAD

**Issue by nbeaver** [lwindolf/liferea#611]
Steps to reproduce:
1. Drag a feed out of a folder into the top-level, leaving the folder empty.
1. Drag the feed into another folder, this one with a feed.
1. Observe the segfault.

Backtrace attached; I have two more just like it.

I also have a short video screen capture showing the steps I took to reproduce the crash if that would be helpful.

[liferea_sig11_uid1000_time1516130207.coredump.txt](https://github.com/lwindolf/liferea/files/1777019/liferea_sig11_uid1000_time1516130207.coredump.txt)

**Comment by Leiaz** [comment]
I can reproduce. Thank you for the report !

**Comment by lwindolf** [comment]
For all 15 years of Liferea the GtkTreeView DnD crashes never stop. This entire GtkTreeIter/Path madness is unusable from a developer perspective.

**Comment by nbeaver** [comment]
For what it's worth, here's a screencast showing the bug:

https://www.youtube.com/watch?v=RR2_Mp6FS2c

**Comment by nekohayo** [comment]
This particular issue has happened to me for years too.
In case it can help somehow, here's [a screencast](https://www.youtube.com/watch?v=rdSxCz1owUA) of how I trigger it reliably (with some appropriate music :)

...and here's the backtrace [output of gdb's "bt full"](https://github.com/lwindolf/liferea/files/4424070/liferea-github-611.-.backtrace.of.crash.on.moving.a.feed.to.a.folder.txt).

One of the situations that often trigger it is when dealing with empty folders, I think?

**Comment by nekohayo** [comment]
OK, I think I've nailed down at least one clear reproducibility case here. Let's say we have something like this:

```
Folder A
  Feed 1
  Feed 2
  Feed 3
Folder B (with various items in it)
Folder C (with various items in it)
Feed 4
Folder D
  (empty)
Folder E
Feed 5
Feed 6
```

Reproducibility:

1. If I drag "Feed 4" to "Folder D" (when it's empty), I get a crash.
1. If I drag "Feed 2" (or something like that) to "Folder D", no crash.
1. If I then drag "Feed 4" to "Folder D" (that now has "Feed 2" in it), it still crashes.
1. If I drag "Feed 4" to be between Feed 5 and 6 (or anywhere, for that matter), it crashes.
1. If instead I drag "Feed 5" to be just next (after) to "Feed 4", and THEN drag "Feed 4" elsewhere, such as "Folder D", it does NOT crash. To be clear, at that point it now looks like this:

```
Folder A
  Feed 1
  Feed 2
  Feed 3
Folder B (with various items in it)
Folder C (with various items in it)
Feed 5
Folder D
  Feed 4
Folder E
Feed 6
```
...and then, if I try to drag the now-solitary "Feed 5" elsewhere (such as into "Folder D"), it crashes too.

CONCLUSION: presuming there's no race condition / heisenbug here, it seems that Liferea crashes when you try to drag a solitary feed that was "sandwiched" between two folders.

**Comment by lwindolf** [comment]
Awesome analysis!!! Still it doesn't crash for me when I try to reproduce it :-(
