### ISSUE TITLE
1.2.2 compile issue on 32-bit system

### ISSUE THREAD

**Issue by PandaJim** [lwindolf/liferea#616]
The new Liferea 1.12.2 has an issue building on 32-bit Ubuntu. 

> date.c:178:1: error: conflicting types for ‘date_format’
>  date_format (gint64 date, const gchar *date_format)
>  ^~~~~~~~~~~
> In file included from date.c:35:0:
> date.h:37:9: note: previous declaration of ‘date_format’ was here
>  gchar * date_format (time_t date, const gchar *date_format);
>          ^~~~~~~~~~~
> Makefile:754: recipe for target 'date.o' failed
> make[4]: *** [date.o] Error 1

**Comment by paulgevers** [comment]
I confirm this issue. This is blocking for inclusion of 1.2.2 in Debian and Ubuntu.

**Comment by Leiaz** [comment]
Thank you for the report. This was fixed by #615.

@lwindolf Sorry, I broke a release again.

**Comment by PandaJim** [comment]
Fixed. Thanks
