### ISSUE TITLE
Hide read items only after I leave the folder

### ISSUE THREAD

**Issue by headsign** [lwindolf/liferea#617]
I've been using NetNewsWire for the longest time and there's one thing I really miss in Liferea: when I have 'Hid read items' selected, the headlines for each item disappear as soon as I scrolled through them within a folder, but sometime, I have a moment when I realize there was something interesting and I want to go back up one line, but the line is gone. What I miss is an option to only flush read items when I leave the folder, so that I can still freely navigate the headlines in a particular session and then, once I end the session, they are flushed.

**Comment by rich-coe** [comment]
The branch local/webkit2 in rich-coe/liferea provides this feature.
I haven't updated to the latest master that was published yesterday yet.

**Comment by headsign** [comment]
Thanks for pointing out. I'll have a look at it.

**Comment by lwindolf** [comment]
It's hard to change the behaviour without knowing what is used out there.

A solution for your use case might be the item history feature to navigate to the previously selected item. There is a toolbar button and a menu option.

**Comment by lwindolf** [comment]
The feature from @rich-coe was merged with #778 and release with 1.13.8
