### ISSUE TITLE
favor request: please carry the Ubuntu addition to the desktop file

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#618]
For a long time, Ubuntu has been patching the desktop file shipped with the Ubuntu version of liferea. However, adding it in your desktop file is harmless.

Could you do the Debian/Ubuntu maintainers a favor and are you willing to apply the attached patch? Don't get me wrong, I can fully understand you say no, but I want to ask nevertheless.

[add_X-Ubuntu-Gettext-Domain.patch.txt](https://github.com/lwindolf/liferea/files/1796052/add_X-Ubuntu-Gettext-Domain.patch.txt)

**Comment by lwindolf** [comment]
Sure. Hereby added!

**Comment by paulgevers** [comment]
@lwindolf thanks.
