### ISSUE TITLE
Use .desktop files for Enclosures

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#622]
Use .desktop files to manage the list of download managers.
```
[Desktop Entry]
Type=Application
Version=1.0
Name=Transmission
GenericName=BitTorrent Client
Exec= transmission-gtk %u
Icon=transmission
Terminal=false
Type=Application
MimeType=x-scheme-handler/magnet;
```
When there are two software of same type (i.e. same `GenericName`), use entry `Name`.
Referring to #575 #583

**Comment by lwindolf** [comment]
Sorry, I don't get it. How would this work in detail?

**Comment by GreenLunar** [comment]
These files will be located under `/usr/share/liferea/handlers/` and `.local/share/liferea/handlers/` and will be looked upon on startup, only if modification date of directory `handlers/` has changed.

Similar to `/usr/share/xfce4/helpers/` of Xfce4.

**Comment by Leiaz** [comment]
How would this be better than the "custom" option with a file chooser proposed by da2x in #575 ?

The applications would still be hard coded in a different format and users who want to use a custom script or command would need to write a whole desktop file for it. And of course we would need to parse those desktop files ...

**Comment by GreenLunar** [comment]
It would not be better than a file chooser proposed by da2x in #575, unless Liferea would not offer a preset list of commands.
