### ISSUE TITLE
Build from git master broken on Ubuntu 16.04 after 'Fix deprecation of gtk_show_uri()'

### ISSUE THREAD

**Issue by glitsj16** [lwindolf/liferea#628]
Hi, very pleasantly surprised by the 'headerbar' plugin, thanks to all involved devs on that :+1:.
On Arch everything builds & runs just fine. On Ubuntu 16.04 I noticed that building from git master throws a few make errors and these look related to [Fix deprecation of gtk_show_uri()](https://github.com/lwindolf/liferea/commit/9a2fea4617235897544b1bb17c3a6f5c1307a186).

Reverting that commit produces a working build and at first glance liferea (incl. the new shiny 'headerbar' plugin) seems to work just fine. I do realize Ubuntu 16.04 might be too dated, just wanted to throw this in as a FYI. Full [build log](https://ptpb.pw/C4dP.log) available, here's what I think is the relevant part:

```
--- cut for brevity ---
make[3]: Entering directory '/tmp/liferea-git/src'
  CC       auth.o
  CC       auth_activatable.o
  CC       browser.o
browser.c: In function ‘browser_launch_URL_external’:
browser.c:125:10: warning: implicit declaration of function ‘gtk_show_uri_on_window’; did you mean ‘gtk_gesture_set_window’? [-Wimplicit-function-declaration]
   done = gtk_show_uri_on_window (GTK_WINDOW (liferea_shell_get_window ()), uri, GDK_CURRENT_TIME, NULL);
          ^~~~~~~~~~~~~~~~~~~~~~
          gtk_gesture_set_window
...

  CCLD     liferea
browser.o: In function `browser_launch_URL_external':
/tmp/liferea-git/src/browser.c:125: undefined reference to `gtk_show_uri_on_window'
collect2: error: ld returned 1 exit status
Makefile:643: recipe for target 'liferea' failed
make[3]: *** [liferea] Error 1
make[3]: Leaving directory '/tmp/liferea-git/src'
Makefile:824: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/liferea-git/src'
Makefile:683: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/liferea-git'
Makefile:466: recipe for target 'all' failed
make: *** [all] Error 2
```

Regards

**Comment by lwindolf** [comment]
I'll check the gtk_show_uri_on_window() version requirements. Of course it doesn't make sense to up the GTK version to soon. This can wait for 1.14

**Comment by Leiaz** [comment]
Gtk 3.22, see #454, there are also others we should wait a bit to fix.
