### ISSUE TITLE
GISCAN build error on Debian 9

### ISSUE THREAD

**Issue by oddhack** [lwindolf/liferea#631]
Building from current HEAD (d093494052379852f6afaf219fa1383bf0c7b951) on an up-to-date Debian 9 (jessie) system, the build fails in or after the GISCAN step with a variety of GLib assertion failures followed by an error

> ui/icons.c:29: Error: Liferea: Skipping invalid GTK-Doc comment block:
> /**<< list of icon assignments */".

See attached log.

[errs.txt](https://github.com/lwindolf/liferea/files/1919432/errs.txt)

Is there additional system configuration information that would be helpful in debugging this?

**Comment by lwindolf** [comment]
I get the same error message, but no build fail. Are you sure this is the cause of the build break?

**Comment by Leiaz** [comment]
I removed the errors in 8b56afc1e72824febc7 (but they shouldn't prevent Liferea from building).

**Comment by oddhack** [comment]
Thanks - sorry for no previous reply, I was travelling. I do seem to be able to build and run successfully from the latest commit, and it overcame the problem I was having with left-clicking on titles of RSS articles not opening in a browser (which, to digress, seemed to recur out of nowhere after a long period of not being a problem). I appreciate the fixes, though I never did pin down what was causing the build issues.
