### ISSUE TITLE
Inoreader sync broken

### ISSUE THREAD

**Issue by sirredbeard** [lwindolf/liferea#632]
Liferea never seems to update with my feeds after adding Inoreader as a source.

There is also no indication of updating occurring in the update monitor.

I have exited and restarted Liferea, uninstalled and reinstalled, removed ~/.config/liferea and tried again.

To no avail.

![2018-04-21_15-16-42_000](https://user-images.githubusercontent.com/33820650/39088071-e1cd48a0-4579-11e8-949b-ea4e0e7ee601.jpeg)

![2018-04-21_15-25-09_000](https://user-images.githubusercontent.com/33820650/39088133-c1d5cf4e-457a-11e8-919b-e7bb3146ccf1.jpeg)

![screenshot from 2018-04-21 16-10-19](https://user-images.githubusercontent.com/33820650/39088361-a176cc2c-457e-11e8-86e5-9ab189667689.png)

![screenshot from 2018-04-21 16-11-54](https://user-images.githubusercontent.com/33820650/39088374-bc682bf2-457e-11e8-936c-fa541a05ff2e.png)

**Comment by Leiaz** [comment]
Inoreader changed their API, see #472.

**Comment by lwindolf** [comment]
I've decided to drop inoreader support as I have no capacity to fix it.

On the long term there will be a plugin API to extend Liferea with support for external online sources. I hope using some good plugin examples people will create new integrations and maintain them.
