### ISSUE TITLE
https feeds are broken with squid ssl_bump

### ISSUE THREAD

**Issue by wmyrda** [lwindolf/liferea#638]
I started using squid to cache SSL sites. It does not go without trouble as some sites do not work and do not accept self issued squid SSL certificates which are needed to decrypt traffic for caching it and crypt it back again. 

Sites that do not work are listed in `acl broken_sites ssl::server_name` which makes them work again as caching for them is disabled.

Relevant part of squid config
```
http_port 192.168.101.1:8080 intercept
https_port 192.168.101.1:8090 intercept ssl-bump \
  cert=/etc/squid/ssl_cert/squid.pem \
  generate-host-certificates=on dynamic_cert_mem_cache_size=4MB
sslcrtd_program /usr/libexec/squid/ssl_crtd -s /var/lib/ssl_db -M 4MB

acl broken_sites ssl::server_name .wikipedia.org .nsatc.net .microsoft.com
ssl_bump splice broken_sites
ssl_bump peek all
ssl_bump bump all
```
However at the same time there problem using ssl feeds in Liferea appeared. SSL sites which work just fine browsing them in Firefox do not work as feeds in Liferea. Examples are:
- https://www.phoronix.com/rss.php
- https://www.naturalnews.com/rss.xml

Hence ssl caching is only thing I have changed it is obvious the problem has to do with certificates acceptance. On one hand one could argue that Liferea is not prone to MITM attacks which is fine by default, but for those which are fine with it there could be an option to accept more certificates, perhaps the same way Firefox does it.

Actual error I got in Liferea is
```
Ostatnia aktualizacja tej subskrypcji nie powiodła się!
Kod błędu HTTP 0: Wystąpił błąd sieci lub z innego powodu połączenie zostało niespodziewanie przerwane
```
which one could translate into: `the last actualization did not work. HTTP error code 0: Network error or other cause resulted in connection terminatation`.

Please take a look if fixing it is possible.

**Comment by wmyrda** [comment]
Just a quick fought. Extending global proxy settings to be able to have different proxy for HTTP and HTTPS should take care of this at least in some situations.
Being able to set different proxy for each feed would could also help and be useful just like other per feed options are ex. number of kept headers in archive.

**Comment by lwindolf** [comment]
This should already work when you use the GNOME proxy settings, which allow you to differentiate.

I fear the behaviour you describe cannot be debugged.

**Comment by wmyrda** [comment]
I actually use XFCE so gnome settings are not much of a help for me as in my case other than using command line network settings can be set with `networkmanager` or  `wicd`. As the workaround I did set in liferea proxy server to my privoxy server to skip squid completely which does the caching prior to privoxy so it is all back and working.

As for debugging the behavior I understand it my be very hard or next to impossible to do hence the proposition to somehow extend proxy settings in the application which more of feature request than a bug, but would allow me and maybe others like me  to keep the caching of feeds for http sites.
