### ISSUE TITLE
Right clicking on article no longer selects it

### ISSUE THREAD

**Issue by bruceg** [lwindolf/liferea#639]
Prior to version 1.12.3 (including 1.12.2), right clicking on an article in the list pane to bring up a context menu (Open in Tab, etc) selects the article and so marks it as read. As of version 1.12.3 this is no longer the case. The new behavior is different from other applications that allow right clicking of list items (file browser, etc) and is incorrect.

**Comment by yaneti** [comment]
Hey @Leiaz . I was afraid I might've caused this with the column patches so I did a bisect.
Led to abf2dd975dd13e3510bc458275e0931af8d9157e , so.. it probably wasn't me :)

**Comment by Leiaz** [comment]
Yes, I [proposed that change](https://github.com/lwindolf/liferea/pull/608#issuecomment-375390868). To me the previous behavior was incorrect : Claws mail and Thunderbird don't open emails or mark them as read when using the right-click popup menu. "Losing" the item I was looking at when right-clicking on another to put in a news bin or open in an external browser felt wrong to me. Although marking as read when using an "open" action would make sense ...

**Comment by bruceg** [comment]
Hmmm, if Claws and Thunderbird both do it this way, I guess there is some merit, though the behavior change was surprising to me. As far as I can recall, the old behavior existed from the beginning of Liferea having a right-click menu. I frequently use right-click plus either open in tab or in browser to "read" the item outside of the main window, so this now requires an extra click on each item to accomplish that.

Would there be any possible compromise where some of the actions like "Open in Tab" would mark an item as read? That might be undesirable though as the item would then just disappear from lists like "All Unread".

**Comment by lwindolf** [comment]
@bruceg You are right, right click was selecting since earliest Liferea version. Still for a long time there were user bug reports complaining about being unable to interact with a headline without marking it as read.

BTW you are probably missing the middle click as the fastest way to open a headline in a tab (while also marking it as read).

For now I'd also suggest we wait for some more feedback, to see if many people are affected by the behaviour change.

**Comment by lwindolf** [comment]
@bruceg You are right, I totally confused middle clicking links with middle clicking headlines.

Do you mind going for @Leiaz solution?

**Comment by bruceg** [comment]
The solution in issue #640 would work for my use case, yes.

**Comment by lwindolf** [comment]
Merged!
