### ISSUE TITLE
Allow changing user agent for downloading feeds

### ISSUE THREAD

**Issue by dperelman** [lwindolf/liferea#642]
While the [webkit-setting](https://github.com/lwindolf/liferea-plugin-studio/tree/master/webkit-setting) plugin has options for setting the User Agent for the internal browser, this is separate from the `SoupSession` that is used to actually download the feeds. Looking at that plugin, there are commented out lines referencing changing settings in the `SoupSession`. As far as I can tell in my fiddling, those are commented out because Liferea's plugin API does not actually offer access to that object. Would it be possible to expose that object to the plugin API, so I could write a plugin that changes that setting? This specific use-case seems niche enough that leaving it to a plugin would make sense.

(My specific use-case is that Twitter recently changed their User Agent sniffing to send the mobile site to Liferea and the mobile site does not actually contain timestamps for tweets, so there's no way to modify [the conversion filter I'm using](https://github.com/dperelman/twitrssme/blob/feature/streaming/fcgi/twitter_stream_to_rss.pl) to actually output useful RSS. Additionally, Twitter redirects to HTTPS, so changing the user agent with a proxy would be non-trivial. The workaround would be to just go back to having the external program do the download as well as processing, but Liferea pretty much freezes while it's waiting on the output from external commands, so that's not a good solution.)

**Comment by rich-coe** [comment]
As of Issue#415, liferea no longer hangs when processing an external command for a feed.

**Comment by dperelman** [comment]
@rich-coe Thanks. It does seem to still freeze the GUI a bit while updating those feeds, but not as long as it used to (I'm using Liferea 1.12.2 on Debian Sid). That's a usable workaround.
