### ISSUE TITLE
Header Bar plugin

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#644]
When the Header Bar plugin is active, liferea doesn't remember the size of the window of liferea after restart.

**Comment by lwindolf** [comment]
Reproduced.

**Comment by lwindolf** [comment]
Seems like the gtk_window_set_titlebar() causes the entire window to be reinitialized.

**Comment by lwindolf** [comment]
Additionally the window get smaller each launch time.

**Comment by nekohayo** [comment]
I don't experience this issue on 1.12.7, should this ticket be closed?

**Comment by ndias** [comment]
No, I have liferea-1.12.7 and I still have this issue.

**Comment by lwindolf** [comment]
Still present in 1.13.1

I do not consider it super critical as it is an optional plugin.

At the same time I have no idea how to get rid of this nasty effect. Maybe it will be gone when the switching from normal menu to headerbar during startup is gone...

**Comment by lwindolf** [comment]
@nekohayo Good idea. Closing as duplicate of #909
