### ISSUE TITLE
WebKit-less liferea as possible privacy measure?

### ISSUE THREAD

**Issue by Gert-dev** [lwindolf/liferea#650]
There are some existing issue reports requesting features such as an ad blocker (#476) to mitigate possible snooping via requests performed inside the content pane of a feed result.

As Liferea is, as mentioned in #476, a feed reader and does not have the resources to start building things such as ad blocking and perhaps other privacy-improving measures - in any case, one could say it would always have to play catch-up anyway -, I was wondering if it would be viable to provide a Liferea that simply does no content rendering at all?

A privacy-minded user usually configures his browser to his liking anyway (uBlock, uMatrix, NoScript, cookie destruction, containerization and whatnot), and this way Liferea only has to concern itself with showing the flat list of feed items and their summary (and, optionally, perhaps a completely stripped version of the HTML).

This would reduce the surface for these things quite a bit.

The implementation could be as simple as not showing the content pane and always opening items in the user's local browser.

Another option may be to, as mentioned above, add a checkbox that strips all HTML before display. It would basically render the use of WebKit useless for those using it, but it would also solve the issue in a rather drastic way until, perhaps in the future, a better solution can be provided.

On a side note, the ad blocker plugin seems to be broken here; it complains about not being able to find the WebKit module, which I presume is because it seems to be using WebKit 1, which is now retired due to larger security concerns - though I may just be doing it wrong.

**Comment by criztovyl** [comment]
Isn't the catch-up is mainly done in the filter lists?
If so, I think if a request filter is implemented one could leverage the existing filter lists or let the user do whitelisting. (Maybe that's even what the ad-blocker plugin is doing.)

**Comment by criztovyl** [comment]
Ignore my comment, one might still want to disable WebKit all-together and I think the request is so far okay.

**Comment by Gert-dev** [comment]
@criztovyl Catch-up is indeed partially done in the filter lists, but a filter list only does so much; users may desire additional functionality to do more finely grained control of what is allowed and what not (i.e. uMatrix, NoScript, HTTPS Everywhere). (In other words, things a standard ad blocker with only filter lists usually doesn't or can't do.)

Admittedly, some of the things I mentioned may not be relevant if you use the standard RSS feed content view, since it is usually fairly limited, though they may be relevant if you're using Liferea itself to open the actual article.

**Comment by glitsj16** [comment]
> The implementation could be as simple as not showing the content pane and always opening items in the user's local browser.

Having considered WebKit-less anything on occasion, I looked at Liferea's code-base a few times in similar vein. Learned a lot, but the goal never really panned out. Mostly because I am not a programmer by trade and I already had Liferea configured to use my preferred browser from the moment that option was available. Together with **only** checking the 'Disable Javascript' box in Liferea's 'Internal Browser Settings' pane, my feed-consuming self was satisfied.

Perusing the issues here today on another matter, I noticed this thread and came up with the last piece of the minimalistic puzzle, at least for me. I wouldn't want to see options limited to a non-WebKit/non-internal browser experience when using Liferea, no matter what the privacy/security issues. Hence this simplest of patches **merely** hides both WebKit-related context menus: 'Open in Browser' and 'Open in Tab'. Just throwing it out here.

```
--- a/glade/liferea_menu.ui
+++ b/glade/liferea_menu.ui
@@ -115,14 +115,14 @@
         </item>
       </section>
       <section>
-        <item>
+        <!--<item>
           <attribute name="action">app.launch-selected-item-in-tab</attribute>
           <attribute name="label" translatable="yes">Open In _Tab</attribute>
         </item>
         <item>
           <attribute name="action">app.launch-selected-item-in-browser</attribute>
           <attribute name="label" translatable="yes">_Open In Browser</attribute>
-        </item>
+        </item>-->
         <item>
           <attribute name="action">app.launch-selected-item-in-external-browser</attribute>
           <attribute name="label" translatable="yes">Open In _External Browser</attribute>

--- a/src/ui/popup_menu.c
+++ b/src/ui/popup_menu.c
@@ -104,6 +104,7 @@
 	menu_item = g_menu_item_new (NULL, NULL);
 
 	section = g_menu_new ();
+	/*
 	g_menu_item_set_label (menu_item, _("Open In _Tab"));
 	g_menu_item_set_action_and_target (menu_item, "app.open-link-in-tab", "s", item_link);
 	g_menu_append_item (section, menu_item);
@@ -111,6 +112,7 @@
 	g_menu_item_set_label (menu_item, _("_Open In Browser"));
 	g_menu_item_set_action_and_target (menu_item, "app.open-link-in-browser", "s", item_link);
 	g_menu_append_item (section, menu_item);
+	*/
 
 	g_menu_item_set_label (menu_item, _("Open In _External Browser"));
 	g_menu_item_set_action_and_target (menu_item, "app.open-link-in-external-browser", "s", item_link);
@@ -144,11 +146,13 @@
 
 	section = g_menu_new ();
 
+	/*
 	text = g_strdup_printf (_("_Bookmark at %s"), social_get_bookmark_site ());
 	g_menu_item_set_label (menu_item, text);
 	g_menu_item_set_action_and_target (menu_item, "app.social-bookmark-link", "(ss)", item_link, item_get_title (item));
 	g_menu_append_item (section, menu_item);
 	g_free (text);
+	*/
 
 	g_menu_item_set_label (menu_item, _("Copy Item _Location"));
 	g_menu_item_set_action_and_target (menu_item, "app.copy-link-to-clipboard", "s", item_link);
 
```

The patch works against current git master, and should be easy enough to adapt to future code-changes.

Regards

**Comment by nekohayo** [comment]
I run Liferea with Javascript disabled. If Liferea's webkit does not execute javascript, and ignores cookies (which I _presume_ it does), and is essentially just serving oldschool HTML and images (and CSS if opening something in an internal browser tab, but then if you do, that's your own conscious action), then what attack is there to be had?

**Comment by Gert-dev** [comment]
> then what attack is there to be had?

IIRC, serving an image URL in an RSS feed (or HTML in general) causes typical clients to load that image from an URL when the article is viewed. The server hosting that image could be a tracking domain that reads the IP address and other headers sent by the client when that happens, which allows deducing that the user has opened/read/is reading the feed article in question.

**Comment by 400thecat** [comment]
Hello,
has there been any progress in this direction?
d
Can liferea be compiled without the internal browser entirely?

It seems to me very unfortunate, that liferea even tries to have internal browser. Why not use your default browser which you have alredy? Eric Raymond used to say long time ago, that every program will continue adding features until it can read email. I guess nowadays every application is trying to be a browser.

Anyways, could somebody please advise if liferea can be build without webkit?

**Comment by 400thecat** [comment]
sorry, how is this completed?
could you please provide details how I can compile liferea without webkit ?

**Comment by lwindolf** [comment]
@400thecat The ticket is not complete. I just closed it because it was very old and currently had no chance to be implemented.

Sorry about overlooking your comment from August!!! It might be hard to implement an alternative HTML renderer in the current code base as it relies on using Javascript to implement Reader Mode.

If you want to look at the code there is first a class `LifereaBrowser` which encapsulates all HTML widget logic and then a class `LifereaWebkit` which does the necessary setup of WebkitGtk. In principle you could dynamicall switch the HTML renderer in `LifereaBrowser`.

BTW in Liferea 1.4 we had multiple HTML backends: we hade support for GtkMozEmbed and GtkHtml2.

**Comment by nekohayo** [comment]
For those of you who somehow need to block ads and other stuff, short of writing and maintaining an adblocker plugin for Liferea, my suggestion would be that you set up [Pi-Hole](https://pi-hole.net/) on some spare server/laptop/RaspberryPi sitting in your wardrobe, and configure your computer's network settings to use that as the DNS server. You'll be able to enjoy the benefits without having to touch a single line of Liferea's code (and so will other apps and devices on your network), and Lars won't have to have some unmaintainably divergent codebase for a minority of users.
