### ISSUE TITLE
Free Music Archive RSS feed URL ships broken

### ISSUE THREAD

**Issue by benjbrandall** [lwindolf/liferea#651]
Liferea 1.12.2 on Ubuntu 18.04 LTS

On first run, the Free Music Archive RSS link is broken, pointing to https://freemusicarchiveorg/recent.atom rather than https://freemusicarchive.org/recent.atom

![orgrecent](https://user-images.githubusercontent.com/15836153/40900865-521cb446-67d6-11e8-9221-54b426f3b4f0.png)

Similarly, Gorilla vs. Bear just underneath also isn't connecting. Clicking it, it seems to be going through a GDPR redirect which might be the issue (http://www.gorillavsbear.net/gdpr/consent/?redirect=/category/mp3/feed/)

**Comment by lwindolf** [comment]
Gorilla vs Bear is the only site so far protecting feeds by GDPR prompt. I really like them. No feed reader can handle this... If they care about their RSS feed I believe they will fix it. 

I fixed the missing / in the FMA link.

**Comment by Leiaz** [comment]
There are others, see #641.

**Comment by lwindolf** [comment]
FMA feed is now removed from default feeds.
