### ISSUE TITLE
Segmentation Fault adding frozentux atom

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [lwindolf/liferea#654]
+New Subscription -> Feed Source: ```https://www.frozentux.net/feed/atom/```

Affected versions: git and 1.12.3

**Comment by Leiaz** [comment]
This feed contains a very weird date : `-0001-11-30T00:00:00Z` but Glib's [`g_time_val_from_iso8601`](https://developer.gnome.org/glib/unstable/glib-Date-and-Time-Functions.html#g-time-val-from-iso8601) reports success in parsing it ... The date is outside the range covered by GDateTime ...
