### ISSUE TITLE
zoom per feed feature request

### ISSUE THREAD

**Issue by c-e-p-x-u-o** [lwindolf/liferea#656]
It will be cool to remember zoom for each feed. As not I need to Ctrl-+ / Ctrl--  from feed to feed

**Comment by lwindolf** [comment]
I do not really understand the request. Why is this necessary when all article contents are presented with the same font size?

**Comment by c-e-p-x-u-o** [comment]
I mean feeds with "Auto-load item link in configured browser when selection articles"

**Comment by lwindolf** [comment]
I understand the wish. So you mean zoom level per website domain. Because actual feeds articles can point to multiple domains (think social network feeds).

I think this level of customization is out-of-scope for Liferea. I fear not even major webbrowser do support this.

**Comment by c-e-p-x-u-o** [comment]
Firefox support this. Chromium support this. What major webbrowsers you talking about?

**Comment by lwindolf** [comment]
You are right on this. Firefox for example does store and persist zoom level per website.

**Comment by c-e-p-x-u-o** [comment]
Exactly! Could liferea does this same way as firefox?
