### ISSUE TITLE
set font for Headline

### ISSUE THREAD

**Issue by 532910** [lwindolf/liferea#657]
It will be cool to be able to set Headline font for Normal view.

**Comment by lwindolf** [comment]
Could this be of help: https://lzone.de/liferea/blog/Liferea+Trick+%2310%3A+Custom+CSS+for+Article+Rendering ?

**Comment by c-e-p-x-u-o** [comment]
No. I mean this font:

![liferea](https://user-images.githubusercontent.com/14617699/49327995-fb412a80-f579-11e8-8d5f-cde09cc60841.png)

**Comment by lwindolf** [comment]
I see. All widgets in GTK applications can be style using GTK CSS definitions. Have a look at this blog post that gives help on how to do this (although on scope for plugins, still it applies to theming the application itself -> section "Trying GTK CSS styles")

https://lzone.de/liferea/blog/Writing+Liferea+Plugins+Tutorial+Part+4

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
