### ISSUE TITLE
Avoid duplication of subscription

### ISSUE THREAD

**Issue by rgaiacs** [lwindolf/liferea#658]
From my experience, liferea will add another subscription even if I already subscribed to a given address. Would be great to allow this.

**Comment by Leiaz** [comment]
@murnux No, this is about not creating another subscription when you already have one for that address.
So if you add Ars Technica a second time, no new subscription should be created.

But maybe something should still happen, like selecting that subscription and/or updating it ? If nothing happens, users might think it is a bug.

**Comment by murnux** [comment]
I understand now. It would make sense that something should happen here, perhaps give the user a choice to overwrite (delete the previous one, then add new one) or to cancel?

**Comment by lwindolf** [comment]
I agree. Adding a standard GTK confirmation dialog asking "Do you really want to add this subscription a second time?" sounds great.

**Comment by murnux** [comment]
Here's my approach, and would like input as a new contributor to Liferea:

- I presume the best way is to check if the source is already in the liferea.db in the user's local directory?

- Should the check happen in the `db_subscription_update` function in `db.c` or elsewhere?

**Comment by lwindolf** [comment]
@murnux I'd advise against using or modifying the DB interface.

The approach should be more like this: you want to check the entire feed list for a given criteria (if nodes have the same URI) so you should use the feedlist_foreach_data() method. Using it you can pass a check function that it applied to each node and can pass a list of e.g. node titles using a GSList as userdata parameter.

**Comment by cauimsouza** [comment]
@murnux  Are you still working on this? If not, I'd like to work on it.

**Comment by murnux** [comment]
@cauimsouza Yes, feel free, things have come up and haven't had the opportunity to take time into this. Thanks for asking.

**Comment by sinodko** [comment]
Do anyone still works on this? If not, I would try.

**Comment by sinodko** [comment]
Is anyone working on this one or I can try?

**Comment by blueray453** [comment]
I am using Liferea 1.12.2

I added the source from an existing feed (Ex. https://1stwebdesigner.com/feed/ ) again.

No warning.

The feature seems to be not working.

**Comment by lwindolf** [comment]
@blueray453 This feature was release with 1.12.6 (see the milestone tag some lines above your comment). Please upgrade.

**Comment by Leiaz** [comment]
With Firefox removing the button showing the feeds, now I just try adding to Liferea "plain" website urls as there may be a feed not listed on the page. For the posted example link it works, but if the added subscription url is not the feed's actual url, there won't be a warning. For instance if you try to add https://blog.mozilla.org twice.
So maybe this could to be improved.

**Comment by lwindolf** [comment]
I see so we'd need to check for the effective URL only.
