### ISSUE TITLE
Please add the "Mark All As Read" to the GTK HeaderBar.

### ISSUE THREAD

**Issue by rolandixor** [lwindolf/liferea#664]

**Comment by lwindolf** [comment]
For anyone wanting to solve it: simply extend the headerbar.py plugin with another GAction that calls feedlist_scan_unread()

**Comment by Leiaz** [comment]
There should already be a "mark all as read" GAction (see in src/ui/liferea_shell.c), so this is just adding a button that activates it.

**Comment by lwindolf** [comment]
Closing as this is solved by above PR
