### ISSUE TITLE
Preview pane disappears, unable to restore

### ISSUE THREAD

**Issue by Malvineous** [lwindolf/liferea#666]
I've just moved my Liferea config to a new machine, and the preview pane has disappeared.  I can't find a way to restore it either, through the menus, preferences, or command line options.

I used to have a list of feeds, a list of news items, and then a preview which would show the content of each item as I was clicking through them all.  Now the preview pane has disappeared so I only see the list of feeds and the list of items in each feed.

There doesn't seem to be any way of getting the preview pane to reappear.  Have I missed something or does an option need to be added for this?

**Comment by Leiaz** [comment]
It is likely reduced to the point of being invisible. You can restore it by grabing the separator at the bottom. If you can't, you can try changing the `last-hpane-pos` value with gsettings.

**Comment by Malvineous** [comment]
Oh wow that's embarrassing, that's all it was, I was able to grab the separator and bring it back up...  Sorry for the noise!
