### ISSUE TITLE
Blank plugins preferences in git master

### ISSUE THREAD

**Issue by glitsj16** [lwindolf/liferea#667]
By coincidence I wanted to check **Liferea's plugins preferences**, only to notice the view is empty (in Liferea compiled from current git master). Plugins still work though, only the `plugins preferences pane` is affected.

After some rebuilds and more testing it looks like [this recent plugin-related commit](https://github.com/lwindolf/liferea/commit/14ef64f31114de13256f7a5a43b824148a136058) is causing the issue for me (on both Arch Linux and Ubuntu 16.04 LTS). At least the issue disappears when reverting the aforementioned commit. I hoped to offer some kind of debug log, yet running with `--debug-all` didn't produce anything helpful (or I missed it). If anyone has pointers on how to debug this further, I would be more than happy to do so.

Regards

**Comment by Leiaz** [comment]
But the plugin installer is itself a plugin. If it replaces the plugins preference tab, maybe it should be made part of the app first.

**Comment by sillyslux** [comment]
Now i have neither Tools->Preferences->Plugins nor Tools->Plugins. Am i missing some python dependency?

**Comment by lwindolf** [comment]
@sillyslux  @glitsj16  Above commit ensures the plugin installer cannot be disabled. I hope this helps.

**Comment by glitsj16** [comment]
@lwindolf Thanks for looking in to this. There seems to be some confusion though. As sillyslux mentioned above, the issue is not that plugins aren't loaded/unloaded or accidentally disabled somehow. Current git master simply does not show a GUI menu item 'Tools > Plugins' (not even when including your latest commit).

Looking at https://github.com/lwindolf/liferea/blob/master/plugins/plugin-installer.py now to figure out why that menu item is still missing.

**Comment by Leiaz** [comment]
@lwindolf You made the plugin installer plugin `Builtin`, but according to [the doc](https://developer.gnome.org/libpeas/stable/PeasPluginInfo.html#peas-plugin-info-is-builtin) it means it is Liferea's responsibility to load it, and currently I don't see anything ensuring it is loaded, regardless of user's settings (for users who didn't enable it previously).

**Comment by lwindolf** [comment]
@Leiaz @glitsj16 I think now I understand.

A partial fix (adding the plugin installer as installed per default in the DConf schema) was added with the commit above. There needs to be additional mandatory enabling in the code itself...

**Comment by Leiaz** [comment]
I think it should be loaded in `liferea_plugins_engine_init` at the end after the `g_settings_bind`.

**Comment by lwindolf** [comment]
Agreed
