### ISSUE TITLE
Inoreader clean up in 1.12.5

### ISSUE THREAD

**Issue by PandaJim** [lwindolf/liferea#669]
Hi, it seems that the Inoreader is not cleaned up in source because I got following error while building the 1.12.5 release:

make[2]: *** No rule to make target '../glade/inoreader_source.ui', needed by 'liferea.pot'.  Stop.

And here's the link to buildlog:

https://launchpadlibrarian.net/387441181/buildlog_ubuntu-xenial-amd64.liferea_1.12.5-0ubuntu2~ubuntu16.04_BUILDING.txt.gz

**Comment by lwindolf** [comment]
Argh... will fix the release tarball

**Comment by lwindolf** [comment]
New tarball 1.12.5.a is now available. Thank you for reporting this!!!
