### ISSUE TITLE
any existing-or-planned outbox/out-feed/follow-through/federation ? e.g. for p2p sorting/aggregation, peer-filtering, multi-person workflows, "chaining" lifereas together...

### ISSUE THREAD

**Issue by Osndok** [lwindolf/liferea#673]
This might totally be the wrong place for this, but in testing liferea I notice that it seems almost exclusively geared towards a terminal consumption of content, and could not find any sort of continuation (such as where the items that are 'marked' get stored).

I was wondering if someone "in the know" could just give me a quick indication if there are any existing or planned outfeed paths (short of just reading the database out from under liferea, which is an option!).

Ultimately, I have in mind to re-publish a curated RSS feed from liferea, and wanted to get an idea of if this is beyond the scope of liferea (that the maintainer would not want such plugins are pull requests), or if there is a similar existing plugin to serve as a 'jumping off point' or an alternative RSS reader that is already geared towards this end.

Thanks for your time reading this, and for developing what is (AFAICT) the best Linux RSS reader.

**Comment by lwindolf** [comment]
Liferea is primarily a feed consumption application with only occasional archiving.

The supported archiving mechanisms are:

- Flagging articles -> all flagged articles are not dropped from cache
- Adding "news bins" which can be used to store articles by using "Copy to News Bin" item view option
- Setting per-subscription or global article count to unlimited so nothing is dropped anymore

Currently there are no plans for out-feed support. Although it sounds intriguing...
