### ISSUE TITLE
Inoreader sync support mentioned on the website

### ISSUE THREAD

**Issue by dmytrokyrychuk** [lwindolf/liferea#674]
Sorry if this is not the right place to report this. As as stated in #472, Inoreader sync support does not work due to Inoreader API changes, but the page at https://lzone.de/liferea/ still claims Inoreader sync support.

**Comment by lwindolf** [comment]
I finally got to fix this. Thank you for reporting this.

On a side note (as you probably were interested in Inoreader support) I'm currently investigating reusing the FeedReader backend plugins (https://github.com/jangernert/FeedReader/tree/master/plugins/backend) to support a wide variety of online services (including Inoreader).

**Comment by dmytrokyrychuk** [comment]
Thanks for letting me know. I have since moved to The Old Reader. All I needed is a way to sync read articles between my phone and laptop. The Old Reader works great with Liferea. I would consider switching back to Inoreader once/if Liferea support of it is restored because I liked the Inoreader Android app better than the News+ app that I am using now. But at the moment I am satisfied with The Old Reader. Thank you for all the effort you put in Liferea!

**Comment by ForlornWongraven** [comment]
I really would like to see Inoreader support (again). I kept my subs for Inoreader running since both the Android and the IOs app are great. Just to read RSS on the desktop is not so good with their webpage.

**Comment by lwindolf** [comment]
I'm currently investigating how feasible implementing the Feedreader plugin API would be to reuse their plugins (https://github.com/jangernert/FeedReader)... No promises though :-)
