### ISSUE TITLE
Add better Reddit via AMP

### ISSUE THREAD

**Issue by NamedKitten** [lwindolf/liferea#676]
If you change the site from www.reddit.com to amp.reddit.com you will get a AMP version of the post that might work better with content extraction.

**Comment by NamedKitten** [comment]
If you where to have a option that gets the reddit post content and comments via the AMP page which is easier to read then that would result in a better viewing experience and images correctly sized.

E.G: https://amp.reddit.com/r/ProgrammerHumor/comments/9lu8ef/bsod_world_record_in_rome_termini_station/ vs https://www.reddit.com/r/ProgrammerHumor/comments/9lu8ef/bsod_world_record_in_rome_termini_station/
for reddit RSS posts on https://www.reddit.com/r/ProgrammerHumor.rss
The "Extract full content from HTML5 and AMP" option should fetch it from the amp. subdomain rather then www.

**Comment by lwindolf** [comment]
@NamedKitten I like the idea, yet I do not know have it could work in a general way.

There is no safe way to guess an AMP domain and the feed path there.

It's different with the AMP article lookup which is standardized by the AMP <link> tag.

**Comment by NamedKitten** [comment]
Parse the `<link rel="amphtml" href="https://amp.reddit.com/r/ProgrammerHumor/comments/9bu7yc/meta_new_rules_and_mod_applications/"/>`
 from the item url page and then use that to get the AMP content.

**Comment by Leiaz** [comment]
@NamedKitten Have you checked the "get amp data" option in the advanced tab of the feed options?  It is a bit buggy right now, but it should do this.
