### ISSUE TITLE
Cannot make: jsc/jsc.h: No such file or directory error from latest libjavascriptcoregtk-4.0-dev

### ISSUE THREAD

**Issue by fossterer** [lwindolf/liferea#677]
As of this day, on Ubuntu 18.04.1 LTS, I can't 'make' this project due to error below:

<pre>Making all in ui
make[3]: Entering directory &apos;/liferea/src/ui&apos;
  CC       libliui_a-preferences_dialog.o
In file included from <b>/usr/include/webkitgtk-4.0/webkit2/webkit2.h:54:0</b>,
                 from <b>preferences_dialog.c:29</b>:
<b>/usr/include/webkitgtk-4.0/webkit2/WebKitJavascriptResult.h:28:10:</b> <font color="#EF2929"><b>fatal error: </b></font>jsc/jsc.h: No such file or directory
 #include <font color="#EF2929"><b>&lt;jsc/jsc.h&gt;</b></font>
          <font color="#EF2929"><b>^~~~~~~~~~~</b></font>
compilation terminated.
Makefile:717: recipe for target &apos;libliui_a-preferences_dialog.o&apos; failed
make[3]: *** [libliui_a-preferences_dialog.o] Error 1
</pre>

I found that a related patch was submitted and is currently in discussion here: https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/wTae6hNw8qk

As described at https://github.com/lwindolf/liferea/pull/675#issuecomment-427879699, I attempted installing a lower version package but am seeing the below errors:

<pre>$ sudo apt install libwebkit2gtk-4.0-dev=2.20.1-1
[sudo] password for shashank: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libwebkit2gtk-4.0-dev : Depends: libwebkit2gtk-4.0-37 (= 2.20.1-1) but 2.22.2-0ubuntu0.18.04.1 is to be installed
                         Depends: gir1.2-webkit2-4.0 (= 2.20.1-1) but 2.22.2-0ubuntu0.18.04.1 is to be installed
                         Depends: libjavascriptcoregtk-4.0-dev (= 2.20.1-1) but 2.22.2-0ubuntu0.18.04.1 is to be installed
E: Unable to correct problems, you have held broken packages.
</pre>

Any tips?

**Comment by lwindolf** [comment]
Yes, absolutely use the resolver of aptitude! :-)

**Comment by fossterer** [comment]
Hi @lwindolf I installed aptitude and ran the command. I didn't see any such 3rd resolver choice but the magic worked.

For the curious, the packages have to be installed (of whatever version) and the aptitude resolver then goes on to modify them as requested.

In my initial trials, I uninstalled the packages before using aptitude and as a result, the aptitude said 'Nothing to install'
