### ISSUE TITLE
Missing plugin installer

### ISSUE THREAD

**Issue by taxman10m** [lwindolf/liferea#682]
Just installed 1.12.5-2 and I'm not seeing anything in the program about plugins or a plugin installer.

Has this feature been removed?

**Comment by yaneti** [comment]
See #667 .
You can get back the plugins menu (and reset your plugins choices) by
```$ gsettingset  net.sf.liferea.plugins active-plugins  "['plugin-installer']"```

**Comment by taxman10m** [comment]
That doesn't work. It seems to also remove active plugins and replace it with just the plugin-installer.

This is before:

gsettings get net.sf.liferea.plugins active-plugins
['gnome-keyring', 'media-player', 'trayicon']

This is after running your command

gsettings set net.sf.liferea.plugins active-plugins "['plugin-installer']"
gsettings get net.sf.liferea.plugins active-plugins
['plugin-installer']

**Comment by taxman10m** [comment]
I only had a small window of time to test things this morning, but what I
was experiencing was that after doing your fix Liferea would hang and not
start. Maybe this was because the key ring plugin gets disabled and this
interfers with the refresh of feeds on start. I'll look at things
thoroughly tonight. Thanks for your quick and helpful feedback on this
issue.

**Comment by yaneti** [comment]
Sorry it broke that bad for you.

By the sound of it the gnome-keyring pugin sounds like something that should maybe get the same treatment as the plugin-installer and be there unconditionally.

I've never used user/password protected fees so I wouldn't have noticed.

**Comment by Leiaz** [comment]
The gnome keyring plugin is not mandatory. 

@taxman10m If you are not seeing Liferea's window try starting it with `liferea -w shown`

**Comment by taxman10m** [comment]
You are right, I think it was just starting hidden. So these would be the full steps to fix my issue:

1) gsettings set net.sf.liferea.plugins active-plugins "['plugin-installer']"
2) liferea -w shown
3) Enable whatever plugins you want.

**Comment by lwindolf** [comment]
Closing this as I believe it is fixed. Sorry for the inconvenience with the introduction of the plugin change!

**Comment by macias** [comment]
openSUSE really gets worse and worse as Liferare packaging goes. As writing this the fix for openSUSE 15.3  is to install manually package libpeas-loader-python3 (just reported it here: https://bugzilla.opensuse.org/show_bug.cgi?id=1203314).
