### ISSUE TITLE
Compile for Ubuntu 16.04.5 LTS - Help?

### ISSUE THREAD

**Issue by cement-head** [lwindolf/liferea#683]
Hi,

  I'd like to compile the latest tarball for use on Ubuntu 16.04.5 LTS (10/22/2018), specifically with the:

./configure --enable-libindicate

option to enable the tray icon for UNITY.  Does anyone have a list of the Ubuntu specific dependencies? (I could dig through everything, but if someone has a cross-listing, that'd be helpful)

Installing the dependencies gives me this:

$ sudo apt install gtk3 libxml2 libxslt1-dev libsqlite3-dev libwebkit2gtk-4.0-dev libjson-glib-dev libgirepository1.0 libpeas-dev gsettings-desktop-schemas-dev python3
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'libgirepository1.0-dev' for regex 'libgirepository1.0'
Note, selecting 'libgirepository1.0-doc' for regex 'libgirepository1.0'
E: Unable to locate package gtk3

Alternatively, if someone has a <*.deb> already built with this configure option, I would appreciate the share.

Thanks,
Andor

**Comment by cement-head** [comment]
Compiled; installed with <sudo checkinstall>; no tray icon.  What happened?

**Comment by lwindolf** [comment]
Do you have the trayicon plugin enabled?

**Comment by cement-head** [comment]
How do I enable the trayicon plugin?  Simply download the plugins and install them into ~./local/share/liferea/plugins ?

**Comment by cement-head** [comment]
Using Issue #682 got the Plugins back. Enbaling TRAYICON gives this error:

Traceback (most recent call last):
  File "/usr/local/lib/liferea/plugins/trayicon.py", line 114, in do_activate
    self.delete_signal_id, 0, None, None, None)
TypeError: Argument 5 does not allow None as a value

**Comment by lwindolf** [comment]
@cement-head Can you provide your GTK version? In recent GTK docs like this https://lazka.github.io/pgi-docs/GObject-2.0/functions.html#GObject.signal_handlers_block_matched all None parameters are listed as optional. Still this might have been different in older GTK releases...

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old tickets.
