### ISSUE TITLE
option show picture or not

### ISSUE THREAD

**Issue by cmdtstof** [lwindolf/liferea#684]
i can't find an option for NOT showing the pictures in items.
is there something? it would be very great for me to have it since using lowband and netbook.
thanks

**Comment by lwindolf** [comment]
You might want to disable <img> tags using the user CSS. Have a look at this blog post:

https://lzone.de/liferea/blog/Liferea+Trick+%2310%3A+Custom+CSS+for+Article+Rendering

More or less

     div.content img { display: none }

should help.
I think there should be no special preference to reduce complexity in Liferea.

**Comment by cmdtstof** [comment]
works perfect. thanks a lot!
