### ISSUE TITLE
file name "net.sourceforge.liferea.desktop" trigers minor bug in MATE

### ISSUE THREAD

**Issue by pirate486743186** [lwindolf/liferea#690]
This is strictly speaking a bug in MATE.
EDIT: It's a bug in caja....

I'm in MATE. I created a small wrapper script in ~/bin to do stuff.
When the menu item of liferea is in the menu or panel, it works fine.
When moved to the desktop however, it seams that it's ignoring my script,.

Renaming "net.sourceforge.liferea.desktop" to "liferea.desktop" bypasses the issue.

**Comment by lwindolf** [comment]
I'd expect only a handful of users knowing about it. At the same time I think it doesn't matter as the .desktop file isn't really an interface for every day end users.

I'm sorry to disappoint you, I do believe adding a 2nd .desktop file isn't of any benefit for the majority of users. Also cannot even estimate the support efforts of this .desktop / DBUS startup complexity. So I'm being honest with you: we cannot these types of problem upstream :-(

I do hope Liferea is still useful for you.
