### ISSUE TITLE
How to not minimize to tray?

### ISSUE THREAD

**Issue by qazip** [lwindolf/liferea#693]
I don't like the default behaviour of liferea, which is to minimize to tray when closing. Is there a way to close it instead of minimizing it?

**Comment by lwindolf** [comment]
The tray minimizing is a behaviour of the trayicon plugin which doesn't provide a setting for choosing the behaviour as we had previously in the preferences when the tray icon was a core functionality.

So I see 3 choices

- disable the tray icon
- always close using the "Subscription" menu
- extend the trayicon plugin with a setting to choose the behaviour
