### ISSUE TITLE
Open video-feeds with mpv

### ISSUE THREAD

**Issue by qazip** [lwindolf/liferea#695]
It would be cool to support opening video-feeds (youtube videos for example) with mpv. Not sure if this is in the scope of what you want for liferea.

**Comment by lwindolf** [comment]
Do you have an example feed for which you want this?

I'm trying to understand wether you want to pass along embedded links, <video> tags or enclosures to an external application

**Comment by qazip** [comment]
Well, any youtube and/or podcast feed. For example https://www.youtube.com/feeds/videos.xml?user=Kurzgesagt.

**Comment by lwindolf** [comment]
I see. This sounds like a filter script use case to me. You can add "filter" commands to subscriptions which can transform the subscription anyway you like. Using this you might want to convert the video link to a enclosure and/or a youtube player embed.

**Comment by qazip** [comment]
How can I add filter commands to subscriptions? Is there any documentation regarding that?

**Comment by lwindolf** [comment]
Of course :-)

    https://lzone.de/liferea/help110/subscriptions_en.html

On another thought it might be time to extend the media player with video support.

**Comment by qazip** [comment]
Ok, so it seems that it's pretty straightforward to open an enclosure (youtube video) with vlc (I can't make it work with mpv for some reason). However, I don't like having to use the mouse to do it. Would it be possible to create a shortcut to the command "Open enclosure..."?
