### ISSUE TITLE
Extend mediaplayer plugin to play videos too

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#696]
Currently the core plugin mediaplayer.py only plays audio. It is based on GStreamer, so it can also play video. "All" that's missing is the widget magic to setup a reasonable video widget.

**Comment by Leiaz** [comment]
I had looked at the media plugin code some time ago in this branch : https://github.com/Leiaz/liferea/commits/enclosure-list-view with the idea that there could be multiple media plugins handling different types of media. I don't know if it is a good idea, I also wanted to make the media plugin less dependent on the implementation of EnclosureListView.
