### ISSUE TITLE
Fix plugin installer UX

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#697]
Spacing, wording and layout might need some improvements.

Other possible improvements

- [ ] provide link to 3rd party repos
- [ ] show installation command log (at least on errors)
- [ ] hide already installed plugins from

**Comment by MetalDent** [comment]
Hi, is anyone working on this issue?

**Comment by lwindolf** [comment]
Nope.

**Comment by MetalDent** [comment]
great! I can work on it if that's alright

**Comment by lwindolf** [comment]
@MetalDent That would be awesome. If you need any help let me know!

**Comment by MetalDent** [comment]
@lwindolf yes, if you can explain the issue a bit?

**Comment by lwindolf** [comment]
![image](https://user-image.githubusercontent.com/3315368/95001084-f3fc6500-05c6-11eb-9b81-14e762bc3484.png)

@MetalDent Sure. Given the screenshot above you can see the padding issues in the "Filter by category" area.

Also note the problem of having "Installed" plugins on a tab called "Download Plugins"
