### ISSUE TITLE
Fix mediaplayer UX when continuing to play when selecting other headlines

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#698]
The problem here is when you start playing audio (e.g. music) and continue reading articles, the playback is interrupted once you view an article with another audio attachement (with the re-initialization of the other media player widget).

**Comment by Shriya721** [comment]
I can help out with this one!!

**Comment by lwindolf** [comment]
@Shriya721 That would be great! When you need advise on the code or debugging help please let me know!
