### ISSUE TITLE
Using @import in Liferea CSS

### ISSUE THREAD

**Issue by bberberov** [lwindolf/liferea#703]
I tried using `@import url("file:///<filename>")` in the `~/.config/liferea/liferea.css` file and it does not appear to work.  Is this something that should work?  Nothing was mentioned in the file's comments.  Thanks.

**Comment by lwindolf** [comment]
It is not intentionally prevented. This might be same security default of Webkit.

May I ask about your intended use case?

**Comment by jaklt** [comment]
I simply wanted to use custom fonts, for example, from https://fonts.google.com/

**Comment by bberberov** [comment]
I want to share the same style with other applications, [ReText](https://github.com/retext-project/retext) for example.  Also, possibly loading original page styles when it makes sense, local copies of course.

**Comment by lwindolf** [comment]
Thanks for explaining the use case. Makes a lot of sense.

I could reproduce that it does not work. Neither with "\@import url()" nor with "\@import <filename>"
