### ISSUE TITLE
Versions of dependencies and supported distros

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#706]
In the commits to simplify GObject boilerplate, macros new from Glib 2.44 are used. In `configure.ac` the version listed is still 2.28, that is the version shipped with Debian 8. There are other parts of the code we could update (deprecated functions we could replace) if we increased the required versions of dependencies. Should we aim to be compatible with Debian 9, Ubuntu 16.04 (used in travis-ci test) or other ?

Anyway we should update the `configure.ac` to list the correct versions.

**Comment by lwindolf** [comment]
I'd say yes, as Debian 9 is "stable".

**Comment by Leiaz** [comment]
I updated configure.ac. Gtk version is 3.22, Glib is 2.50.
