### ISSUE TITLE
Can't synchronize with theoldreader more than once.

### ISSUE THREAD

**Issue by dmusican** [lwindolf/liferea#708]
I've had great success adding a new source into Liferea, logging into my account at theoldreader. Works great. However, when I shut down Liferea and start it up again, it prompts me for my Liferea username and password... but this doesn't work, and I can't ever login again without blowing away my theoldreader source and starting over.

**Comment by lwindolf** [comment]
I sometimes experience this too. While I know that this is not a solution I found that deleting the credentials in the GNOME keyring manager seahorse does get me out of this situation.

The most recent releases had a fix about startup update of subscriptions: https://github.com/lwindolf/liferea/pull/742/files (current git master) 
Can you retest please with this fix?

**Comment by R-L-T-Y** [comment]
KDE with kwalletd. Don't have a clue how to fix this issue.

**Comment by lwindolf** [comment]
Closing this old ticket.
