### ISSUE TITLE
New feed added via Liferea to source TinyTinyRSS always enables Authentication

### ISSUE THREAD

**Issue by Perflyst** [lwindolf/liferea#709]
I just noticed that if you add a feed via Liferea which has TinyTinyRSS as source it always enables "Feed Authentication" in tt-rss. Your username and password from the tt-rss account is used for that.

This looks like a huge security and privacy issue because your credentials are transmitted to the feeds webserver even if not needed. The feed's webserver can identify you via username and also gets your password.

How to reproduce:
Install tt-rss on a server.
Add tt-rss in liferea as source.
Add a feed via liferea to tt-rss.
Log in into tt-rss and go to "Preferences" -> "Feeds", click on the newly added feed and scroll down to "Authentication".

-> There is "This feed requires authentication." enabled and your tt-rss username/password entered.

**Comment by lwindolf** [comment]
I think this is an HTML issue in tt-rss, the form elements in the "Feeds" preferences are made in a way if you have auto-fill credentials enabled (in your browser) it will always fill out the credential of your current login. While this might seem like Liferea did supply it this is not the case.

You can verify this by disabling password auto-fill in your browser and revisit the feed preferences of your tt-rss setup. The "password" will be gone then.

I believe this is worth raising as an issue with tt-rss. I think this was introduced only recently. I remember not seeing this in versions like 1.10 and earlier.

**Comment by Perflyst** [comment]
You are right. I was testing it in a new clean browser profile on which password autofill is enabled by default.
