### ISSUE TITLE
Unsubscribe from the Update Monitor

### ISSUE THREAD

**Issue by stuartlangridge** [lwindolf/liferea#713]
I've just started using Liferea and I've imported an OPML file that I've been moving from reader to reader for about fifteen years now, and some of the feeds in it are long dead. What this has meant is that those feeds get "stuck" in the update monitor, and I can immediately see that those are feeds which have been dead for a long time and so I'd like to unsubscribe from them. However, finding those feeds in my list is hard -- I don't know which folder they're in, and I can't search for them because there aren't any actual items. It might be useful to add a "delete this feed" button in the Update Monitor when a specific feed in "Downloading now" is selected?

**Comment by lwindolf** [comment]
I see your use case. Other feed readers implement this via a "Search Broken Feeds" menu item. It then presents you with all discontinued/unreachable feeds and allows you to unsubscribe. Might be good for Liferea to have that too.
