### ISSUE TITLE
Add an option to remove the previous pane

### ISSUE THREAD

**Issue by alexarnaud** [lwindolf/liferea#716]
Hello,

I'm visual-impaired and I'm using the Orca screen reader and a screen magnifier software to use Liferea with many only keyboard shortcuts.

I'd like to be able to remove the previous pane to prevent the load time resulting to it with the screen reader that load it on each article.

I'd liek to help to figure out this but I'm not familiar with the Liferea and GTK programming for now.

Thanks in advance for your amazing software.

Best regards,
Alex.

**Comment by lwindolf** [comment]
@alexarnaud I'd like to help with this, but sadly I lack experience and time on digging into Orca... Sorry!
