### ISSUE TITLE
Add a way to clear the cache

### ISSUE THREAD

**Issue by ao2** [lwindolf/liferea#717]
Hi,

every now and then I find myself removing `~/.cache/liferea/WebKitCache/`.

Can we have a function in liferea to do that? Maybe a button in `Tools -> Preferences -> Privacy` or something like that.

I don't think there is a feature request for that already.

Thanks, Antonio

**Comment by lwindolf** [comment]
I would suggest to use Bleachbit for that purpose. The current Liferea support in Bleachbit is IMO optimal. I'd say it doesn't make sense to build this into applications as privacy/security aware users want to clean all there apps, which is where Bleachbit excels at.

**Comment by ao2** [comment]
Ah, I didn't even know about Bleachbit,

I thought about adding an option in Liferea because web browsers usually have the option built-in, but using an external tool also works for me.

Thanks for commenting, closing the issue.
