### ISSUE TITLE
Crashes while playing some YouTube flash videos

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#72]
While playing a YouTube video embedded into a feed item's contents, Liferea crashed. Fedora's ABRT caught the crash and told me the issue was already reported downstream here: https://bugzilla.redhat.com/show_bug.cgi?id=1033959

**Comment by lwindolf** [comment]
The last WebkitGtk release has flash crash fixes. Might help... http://webkitgtk.org/2015/01/07/webkitgtk2.4.8-released.html
