### ISSUE TITLE
Mark all as read doesn't clear Unread folder if one entry is selected

### ISSUE THREAD

**Issue by anonymous133** [lwindolf/liferea#720]
How to reproduce:

1. Select 'Unread' folder (Have at least 2 unread entries)
2. Select a Headline in it.
3. Click menu 'Subscriptions' > 'Mark all as read' 
4. The list gets cleared except for that selected entry

**Comment by Leiaz** [comment]
The selected item have special treatment by design, but it is not really in the search folder anymore, and after it is unselected the folder item list should be empty.

**Comment by anonymous133** [comment]
Yes you are right. But from my understanding if you click "Mark all as read" the selected entry should be automatically deselected and then "Mark all read" should be called. 

If you think this is not how it is supposed to be than you can close this ticket.

Thank you for this nice and useful project!

**Comment by lwindolf** [comment]
@anonymous133 Fixed. Now for all search folders items are unselected before marking all read. For feeds items do stay selected.
