### ISSUE TITLE
Error downloading feeds from cbc.ca

### ISSUE THREAD

**Issue by bruceg** [lwindolf/liferea#721]
Since April 2nd, I have been unable to directly download RSS feeds advertised on cbc.ca. When they are added to the subscriptions, they show as updating for about two minutes, and then report "HTTP error code 0: There was an internal error in the update process"

If I change the source to a command containing `wget --output-document=- --quiet URL` it updates and parses just fine, so I do have a work around.

The link I am currently trying to fetch is https://rss.cbc.ca/lineup/canada-saskatchewan.xml but I have tried others as well. I suspect this is either a redirect issue or CBC is doing something with the content based on the user agent.

**Comment by tripkin** [comment]
I can confirm this with multiple feeds (every feed I have tried including the two I was following prior to April 22). @bruceg, thanks for the (temporary, I hope!) fix!

**Comment by bruceg** [comment]
@tripkin What is the URL you are using? This is still working for me as-is with the URL listed in the original post.

**Comment by tripkin** [comment]
@bruceg, I am using the following command:
`wget --output-document=- --quiet https://rss.cbc.ca/lineup/canada-calgary.xml`

**Comment by tripkin** [comment]
@bruce, if it helps, I am using Liferea 1.12-rc3 as provided by the Debian 9.9 repos...

**Comment by bruceg** [comment]
@tripkin I just pasted that into a new feed as a command source, and it works for me.

**Comment by tripkin** [comment]
@bruceg, that is very interesting. Maybe I should try wiping my settings and reinstall liferea then. Are you using the same version?

**Comment by bruceg** [comment]
@tripkin Looking at the change log, it appears that the command downloader was only introduced in 1.12.3, which is several releases newer than -rc3. That may be your issue.

**Comment by tripkin** [comment]
@bruceg, that would most likely be it. I will try the newer version. Thanks a lot for your help!

**Comment by tripkin** [comment]
Okay, I have just removed the Debian version and compiled and installed 1.12.6 from git, and it is working fine with @bruceg's fix. Thanks!
