### ISSUE TITLE
Effectively impossible to download podcasts

### ISSUE THREAD

**Issue by WaterSibilantFalling** [lwindolf/liferea#722]
For all intents and purposes, it is impossible to download podcasts. 

A warning that this is not a podcast application should be prominently added. 

If there is any way to download podcasts, then this is some of the worse interface design this millennium.

**Comment by rich-coe** [comment]
Can you describe what you are doing and what feed URL you are complaining about?

**Comment by annoying258** [comment]
yep. it is horrible. although if you are really dedicated to using `liferea`  for all your rss/atom feeds, you can do it.

**Comment by rich-coe** [comment]
When I click on a download link, it brings up a kget dialogue to download the object.
I don't understand this complaint.
