### ISSUE TITLE
LJ and rel="alternate" type="text/html"

### ISSUE THREAD

**Issue by zaitcev** [lwindolf/liferea#723]
Somewhere around April 3, 2018 - yes, it's more than 1 year ago - it became impossible to open LiveJournal articles in a browser. This is the action that happens by default if one clicks once into the title of the selected article.

I did not capture the old Atom, but current one looks like this:

    <entry>
        <id>urn:lj:livejournal.com:atom1:zaitcev:256230</id>
        <link rel="alternate" type="text/html" href="https://zaitcev.livejournal.com/256230.html"/>
        <link rel="self" type="text/xml" href="https://zaitcev.livejournal.com/data/atom/?itemid=256230"/>

It appears that Liferea ignores the type of the link, and uses it (maybe as long as it refers to "self"). The result is not usable in a browser.

Liferea release is 1.12.6.

P.S. This continues to works perfectly in any other Atom feed, so it's likely that LJ publishes a bad feed. Still, it's a problem. I'll investigate what the spec says and update this report.

**Comment by zaitcev** [comment]
So, the RFC 4237 says:

" o  atom:entry elements that contain no child atom:content element
    MUST contain at least one atom:link element with a rel attribute
    value of "alternate".
o  atom:entry elements MUST NOT contain more than one atom:link
    element with a rel attribute value of "alternate" that has the
    same combination of type and hreflang attribute values.
o  atom:entry elements MAY contain additional atom:link elements
    beyond those described above."

but then

"The "atom:link" element defines a reference from an entry or feed to a Web resource.  This specification assigns no meaning to the content (if any) of this element."

So, we're hung out at the mercy of feed publishers.

**Comment by lwindolf** [comment]
The problem here seems to be our stateless parsing of links. While both types are detected...

                if (!xmlHasNsProp (cur, BAD_CAST"rel", NULL) || !relation || g_str_equal (relation, BAD_CAST"alternate")) {
                        alternate = g_strdup (url);
                } else if (g_str_equal (relation, "self")) {
                        alternate = g_strdup (url);
                }

...order of the links will determine who wins. To solve this situation we would need some awareness on choosing the HTML link over the XML link. Currently the code does not check the type on "self".

**Comment by timmc** [comment]
For people landing here, I recommend the following workaround:

1. Install the [Redirector](https://einaregilsson.com/redirector/) browser extension
2. Add a redirect that changes `^https://([^.]+)\.dreamwidth\.org/data/atom/\?itemid=([0-9]+)$` to `https://$1.dreamwidth.org/$2.html`

**Comment by lwindolf** [comment]
@zaitcev Sorry about this taking so long to fix.

The code now only uses "self" tags of type "text/html".
