### ISSUE TITLE
[1.12.6]  does not remember its position/size when the HeaderBar plugin is enable

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#724]
This is a [forwarded Debian bug report](https://bugs.debian.org/929444).

Liferea never starts-up with the last known position and size when the HeaderBar plugin is enable. All is fine without the plugin.

**Comment by nekohayo** [comment]
Hi Paul, I'm not encountering this issue on 1.12.7 (which is nearly the same thing as 1.12.6 as far as I understand) on Fedora, with the headerbar plugin activated. You should probably ask your bug reporter to come here to debug, and maybe test with the 1.12.7 version just in case...

**Comment by lwindolf** [comment]
Finally fixed in master.
