### ISSUE TITLE
Connecting to CloudFlare-based websites gets stuck on recaptcha

### ISSUE THREAD

**Issue by Gert-dev** [lwindolf/liferea#726]
It seems that sites using CloudFlare, such as [Phoronix](https://www.phoronix.com/rss.php) as well as the [DuckDuckGo blog](https://spreadprivacy.com/rss/), sometimes cause problems for Liferea when attempting to fetch feed content or opening the internal browser; they want to show the user a recaptcha due to "suspicious traffic", which cannot be fulfilled when refreshing feeds.

This is almost constantly noticeable when using Tor, but this problem can also present itself to users not using Tor.

What is very strange is that, whilst testing using Tor to aggravate the issue, I noticed the following things:

* Opening the feeds using something like cURL also bounces on the recaptcha verification.
* Opening the feeds and sites in plain Firefox does not show the recaptcha; it seems that CloudFlare must have some additional logic for Firefox - I tried reusing the same user agent and other headers, but this did not appear to help.
* Opening articles from the feed in the Liferea browser also shows the recaptcha, which I can solve there and I will get access to the article (temporarily), but this unfortunately does not "leak over" into refreshing the feed, which will then still get a 403 error with the recaptcha.

I have several feeds that don't work this way, and the common denominator everywhere seems to be CloudFlare - CloudFlare is notorious for causing problems for Tor users among others; they claim that most of Tor's traffic is malicious, which I cannot confirm nor deny.

It may also be worth noting that there is the [PrivacyPass](https://privacypass.github.io/) project which seems to try to mitigate this issue somewhat and is supported by at least CloudFlare, but I don't know if this is a permanent solution for other sites which may have the same problem.

**Comment by Gert-dev** [comment]
I thought I'd mention this for completeness, but it turns out that I am now getting the same recaptcha in Firefox most of the time.

Strangely enough, it seems that setting the tor browser user agent `Mozilla/5.0 (Windows NT 6.1; rv:60.0) Gecko/20100101 Firefox/60.0` in `general.useragent.override` solves the problem there.

I'm not sure if this will also fix it for Liferea, as it also doesn't seem to suffice for tools such as cURL, but it may be worth a shot. Currently, however, it seems impossible to override the user agent used for fetching (you can only override the internal browser user agent).

**Comment by lwindolf** [comment]
This is probably heavily dependant on Cloudflares dynamic blocking rules.

You are right, that you currently can only override the user agent for Webkit (the internal browser) but not the feed download functionality. This might be worth extending.

**Comment by lwindolf** [comment]
Recent Liferea release allow overriding the user agent via environment variable. See `man liferea` on how to do it.

Also problem does not appear often. No other user reports so far.

Closing this as a workaround exists.
