### ISSUE TITLE
Integrate With Firefox

### ISSUE THREAD

**Issue by blueray453** [lwindolf/liferea#727]
The documentation says -

> If you want to subscribe from within Firefox you can configure it to add subscriptions to Liferea directly. To do so click the feed icon in the location entry. 

However, I am using Firefox 67.0 and it does not have any feed icon in the location entry.

Am I missing any firefox addon or something?

**Comment by TomaszGasior** [comment]
Firefox removed RSS support.

**Comment by lwindolf** [comment]
Documentation needs fixing...

**Comment by lwindolf** [comment]
Fixed by removing the doc section. It seems to me there is no possibility of integration anymore.
