### ISSUE TITLE
option to disable all updates for a feed

### ISSUE THREAD

**Issue by pabs3** [lwindolf/liferea#729]
I have some feeds where I'd like to keep a copy of all the posts (so I don't want to delete the feed), but the feed domain has been taken over by spammers and when the feed gets updated in liferea, I receive spam posts.

I can disable automatic updates to the spam feeds but when I want to refresh my feeds and do a manual refresh using "Update All", then the spam feeds get updated too.

It would be nice to have an option to disable all updates for a feed.

**Comment by micressor** [comment]
I would like to have this feature as well.
It is possible to set a single feed to "No automatic update".
But this is ignored when you click on "Update all" in the toolbar.

**Comment by pabs3** [comment]
I am not seeing a commit for this, was it accidentally closed?

-- 
bye,
pabs

https://bonedaddy.net/pabs3/

**Comment by lwindolf** [comment]
This request was not implement and will not be. The close was due to a ticket tracker cleanup.

**Comment by rich-coe** [comment]
I want this feature as well.  'Never update this feed.'  so that 'Update all' would ignore the subscription.
Especially for feeds that are 'archived'.
