### ISSUE TITLE
`error` favicon problems

### ISSUE THREAD

**Issue by asl97** [lwindolf/liferea#73]
1. when the feed error (404, parse error, etc etc), it doesn't change into the error favicon shown below like in the past
2. if i go offline (disconnect from the internet) then force update the favicon, it all change into the error favicon which is  **expected** but if i try to force update it again after reconnecting to the internet or click the `update all` button,  it doesn't **change back to the site favicon** even if it successfully update it without any problem, i would need to restart liferea to change it back

![selection_023](https://cloud.githubusercontent.com/assets/4752645/3823067/19ff8e80-1d34-11e4-824d-4767cd7a894a.jpg)

ps: sorry for bad title, change it if you want

**Comment by lwindolf** [comment]
Reproduced

**Comment by Leiaz** [comment]
Closing this as it was fixed by the above commits some time ago.
