### ISSUE TITLE
Copy Link Location is not active

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#731]
I'm almost sure this may be unique to my installation.
'Copy Link Location' has been broken for a long time.  I've been working around the problem by clicking one of the other 'browser' options.
I found issue #560, but I don't have the issue fixed in that report.
I'm looking for what I need to do to fix the UI element and what is missing?

**Comment by lwindolf** [comment]
Cannot reproduce 'Copy Link Location' not working. What happens we you use it? How do you use the copied text after triggering the menu option.

**Comment by rich-coe** [comment]
![liferea-copy](https://user-images.githubusercontent.com/6563203/59957039-4bba9f80-945a-11e9-8a25-762d120573c5.png)
I don't know why the link is not active.
Right click brings up menu, copy link is not available.

**Comment by Leiaz** [comment]
I can't reproduce either. Does this happen with all links, all the time ? Which version of Liferea ? Are you using any plugin ?

**Comment by rich-coe** [comment]
This appears to be a problem with a bad merge, something I did wrong somewhere.
I've pulled from master and re-compiled and don't have the issue anymore.
@lwindolf and @leiaz I appreciate you looking into this.
