### ISSUE TITLE
Set  debounce.

### ISSUE THREAD

**Issue by kukvs666** [lwindolf/liferea#733]
Hello!

I have a problem with liferea.

I have lot of Medium flux. But Medium's server answer very lot of error 429, "too many requests".

There he a debounce function i can set for solve this problem?

Thanks for your answer!

**Comment by lwindolf** [comment]
I believe you have to lower the update frequency to solve this.

Please check both the global update frequency (Tools / Preferences) and the medium feed specific update frequencies (if you set specific update frequencies) in the feed properties.

In the worst case I'd say have a update once per-day should be ok.
