### ISSUE TITLE
Automatically update article as read on Tiny Tiny RSS server

### ISSUE THREAD

**Issue by nikolas-n** [lwindolf/liferea#736]
I'm using Tiny Tiny RSS as a feed source on my liferea. The problem I've been having for some time is that to update a feed as "read" on my server I have two options:

1. Set the timespan of Update All to a short period of time (I now have it 30 minutes)
2. After I've marked some items as read, go to the feed, right click on it and click on Update

The first approach has the problem that if (for any reason) i finish reading an article before the 30 minutes and i close the application, the item won't be updated as read on the ttrss server.
The second approach (which I'm now using) has the problem that you have to be alert to Update each feed separately (I have around 50 feeds), which is something time consuming and not very convenient.

The reason I want the items to be updated as read is that i'm using also other clients (android app, browser when i'm not on my computer, etc.)

I'd like to ask if the following suggestion is (or could be) considered. Whenever an item is either opened (read) or marked as read, liferea will automatically hit the specific endpoint and update the ttrss installation that the item is read.

Sorry if this has been brought up in the past. Also, I don't know if many people use this combination (i.e. Liferea+ttrss), so I don't know how important this is :-)

Thanks!

```
Liferea: 1.12.6
TTRSS: 18.12
```

**Comment by lwindolf** [comment]
Actually the current implementation should immediately (within like 5s delay) update TinyTinyRSS endpoints. Only when there is no network connectivity Liferea will queue actions to be performed at TinyTinyRSS at a later time.

**Comment by lwindolf** [comment]
Closing old ticket. Also works for me.
