### ISSUE TITLE
Improve error visibility in (unexpanded) feed list folders

### ISSUE THREAD

**Issue by glitsj16** [lwindolf/liferea#748]
When a feed errors during an update this is mostly visible in the feed list tree by way of its changed icon. At least that's how I usually `spot errors` (without having to activate the relevant item). The feed's native/custom icon in such cases changes to a generic one, which can be visually spotted quite easily on a glance. So far so good. When the errored feed item happens to be inside an unexpanded folder, this **visual** error checking is impossible. You'd have to expand folders first to notice items which have (network) errors. It would be nice if liferea could improve on this somehow.

I'm thinking of **showing an (exclamation mark) icon** next to the folder name, or **changing its color**. Something simple, yet (subtly) effectively indicating that a folder contains an errored feed item (or several). I'm willing to work on this, but could need some pointers. Would this be possible via a `plugin`?

**Comment by rich-coe** [comment]
I would support this effort.
One issue I noticed is that one my feeds reports "(null) updated" in the bottom left status area.  I have no idea what feed this or how to find out.
One idea is to have a 'status log' that has some maximum that records the status of feeds that had errors that is accessible from the UI.

**Comment by lwindolf** [comment]
@glitsj16 @rich-coe I see the usability problem. One simple idea that comes to mind is to force all faulty feeds to simply be visible in this mode. What do you think about this?

Alternatively the "Update Monitor" dialog could present feeds that were not downloaded.

**Comment by glitsj16** [comment]
@lwindolf Thanks for your response. I'm not quite sure I get what you mean by "**forcing all faulty feeds to simply be visible in this mode**". Does this mean folders that carry such feeds will be expanded automatically? How exactly are they visible? Even so, for me that sounds like the better way to handle this. Not that I dislike the "Update Monitor" dialog idea, but it's an extra window users would have to keep open to catch things like this in the first place. It might be better suited for @rich-coe though...

I do realize asking for something visible **at a glance** is complicated and rather personal. After using liferea for years on a daily basis I guess my way of using it got very specific indeed. I even use custom (monochrome) icons for all feeds. Having hundreds of differently shaped/colored favicons made staring at the liferea window all day a bit intense on the aging brain. That's the context for posting the original question: the less clutter I can have the better :)

**Comment by glitsj16** [comment]
Still trying to come up with implementable ideas on this issue. I'm wondering how hard it would be to show the number of feeds with errors in the `lower right corner` of the status bar (cfr. the number of unread feeds)? I'll be looking at the code in more detail in a few days but I'd be happy with any feed-back on whether this would be worthwhile.

**Comment by lwindolf** [comment]
Sorry for not responding so long here. I've checked NetNewsWire screenshots a while ago and remember those having a "Broken Feeds" menu item in the "Tools" menu, which would present you with a list of all problematic feeds.

Another idea: when you click a folder the first click renders a folder description, which currently is useless because there is not info inside except for the folder name that should be known already. This view could be improved to render a list of all broken feeds.

**Comment by glitsj16** [comment]
No need to apologize. It's not that Liferea is broken without it. And I really appreciate all the work you and others put in. I still regard it to be my go-to application for RSS, keep up with git commits and use it on a daily basis.

Personally I'd be more than happy to try whatever idea you deem appropriate / integrates better with maintaining Liferea's code-base. It does still happen that feeds break, but after some long overdue maintenance of feed URLs on my part it improved a lot. I wonder if the relevant RFC specs provide a mechanism to announce 'our feed moved from A to B' so RSS programs could simply account for this and adjust he source address based on such info. That's actually the main reason why 'feed-rot' seems to happen. And my lazyness/forget-fulness to do regular checks ;) I'll have some free time during the end-of-year period coming up to dig into this some more. Thanks for your response.

**Comment by lwindolf** [comment]
@glitsj16: I really appreciate you looking into this. From my point of view the lowest impact/complexity solution would be to extend `node_to_xml()` with infos about broken childs and to add some HTML rendering using the XSLT stylesheets.
