### ISSUE TITLE
Liferea is always hidden and inaccessible

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#75]
1. Enable plugin Tray Icon.
2. Minimize Liferea (by the way, Liferea is not shown in task-bar).
3. Click on Liferea tray icon.
4. Liferea would show up and vanish instantly.

Maybe you need to do these steps between steps 1 and 2.
* Restart Liferea.
* Click on Liferea tray icon.

Version: 1.11.0-git.

**Comment by lwindolf** [comment]
I believe right now git master has a stable reproducible behaviour (especially after the fix for #48). 

I think this issue (even when using the trayicon plugin) is fixed now. Please retest!

**Comment by GreenLunar** [comment]
Better, but not good yet.

Bug:
* Minimize to taskbat
* Click on tray icon (appear)
* Click on tray icon (appear, still)

Note:
* Minimize to taskbat
* Restore from taskbat
* Click on tray icon (appear)
* Click on tray icon (hidden, good)

**Comment by lwindolf** [comment]
Thanks for retesting. I would leave it at this for now. The plugin is usable, even if it is not perfect.

The idea of switching to plugins is to engage users in extending/improving Liferea. Maybe someone will improve the trayicon plugin?
