### ISSUE TITLE
Display unread item count in window title

### ISSUE THREAD

**Issue by mgorny** [lwindolf/liferea#753]
Something I've noticed in Evolution and would find as useful in Liferea: the window title could include the number of unread items, e.g. `Liferea (2 unread)`.

**Comment by lwindolf** [comment]
Recent Liferea versions do exactly this. Which version do you use?

**Comment by mgorny** [comment]
1.12.7. I don't recall ever seeing such a thing. Could it be DE-dependent somehow? I'm using Xfce4.

**Comment by lwindolf** [comment]
Could be. Not sure. Using GNOME Shell it works. It doesn't work though when you use the headerbar plugin.

**Comment by lwindolf** [comment]
Ticket cleanup. Closing old ticket.
