### ISSUE TITLE
Question: Access the Blobs

### ISSUE THREAD

**Issue by nobicycle** [lwindolf/liferea#755]
Hello,

I use the following query when I need to extract an article, say for printing:

> SELECT s.node_id, s."source",n.title,i.title, i.description, i.item_id
> FROM subscription s, node n, items i 
> WHERE n.node_id=s.node_id AND  i.node_id=s.node_id AND ( n.type='rss' OR n.type='atom' ) 
> AND s."source"='\<source\>'
> ORDER BY i.date DESC
> 
> 

\<source\> is the Liferea source value in the gui.  The html is in the description field.

The images in the html is already fetched and stored in :
$HOME/.cache/liferea/WebKitCache/Version 14/Blobs/

Files in this folder have names such as 3EED57A57C7AF0E201F1F917CB981AABE54D9915

How can I relate the i.item_id 's to these long file names?

**Comment by lwindolf** [comment]
Sorry, I fear this is probably impossible. This image cache is internal to the webkit library Liferea uses and there is no direct relationship.

**Comment by nobicycle** [comment]
OK Thanks.
