### ISSUE TITLE
Can't sort items by date in Wide View on Fedora 31

### ISSUE THREAD

**Issue by sethgoldin** [lwindolf/liferea#757]
I am unable to sort items by date in Wide View.

I'm running:

- Fedora release 31 (Thirty One)
- Kernel 5.3.7-301.fc31.x86_64
- GNOME Version 3.34.1
- Liferea 1:1.12.7-3.fc31

I am not sure if it's related to https://github.com/lwindolf/liferea/issues/527 but that issue was closed back in 2017.

**Comment by lwindolf** [comment]
You can actually though it is a bit non-obvious. Try clicking the headline column. As there is not much use of sorting alphabetically it will sort by date.

**Comment by sethgoldin** [comment]
Thanks. It might be helpful if a column for date and time were exposed in that panel to make it a bit more obvious.

**Comment by lwindolf** [comment]
@sethgoldin Especially in the 3-pane mode used in non-fullscreen horizontal screen real estate is scarce. Which is why both columns where merged in the first place. Of course in full-screen it is quite the opposite. The current code is a balance of usability and code-complexity.
