### ISSUE TITLE
[Feature Request] feed specific "external browser" setting

### ISSUE THREAD

**Issue by SFort** [lwindolf/liferea#758]
it would be usefull if feeds could have a setting to specify what should be used to open it.

Feed | "External browser"
----------- | ------------------------
video/youtube | mpv %s
news/updates | firefox %s
twitch | streamlink %s
comics | geeqie %s

**Comment by lwindolf** [comment]
I understand the wish. At the same time I think the feature would add to much complexity GUI wise.

**Comment by muhlinux** [comment]
@SFort I agree. This would be nice. 

Alternatively try this for now:
I'm not sure how the enclosures are for twitch and comics, but for Youtube you can double click the attachment and add "mpv %s" to the enclosure prompt. Then tick "Do this automatically from now on" Now you can click the attachment and it'll open in mpv or simply hit `ctrl`+`o`
