### ISSUE TITLE
Tiny fonts in Plasma, not obeying system wide font DPI setting

### ISSUE THREAD

**Issue by Futureknows** [lwindolf/liferea#759]
On a HiDPI KDE Plasma desktop. Scaling is 100 and font DPI is 160 which works great on all other apps. Liferea however is tiny, unreadable, basically not inheriting system font DPI setting.

Any ideas?

**Comment by Futureknows** [comment]
Solved it by appending GDK_DPI_SCALE=2 at start of command line

`GDK_DPI_SCALE=2 liferea`

**Comment by lwindolf** [comment]
Thanks for posting the solution!
