### ISSUE TITLE
"show numbers of new items in the tray icon" missing in GUI preferences

### ISSUE THREAD

**Issue by Ottaviocr** [lwindolf/liferea#760]
Admittedly, I'm using an old version of Liferea (1.12-rc3) on Debian old-stable (stretch). I'm struggling to build Liferea from sources as I have tons of unmet dependencies.

In the previous version for Debian Jessie (1.10.12-1), I used to have the option "show numbers of new items in the tray icon" in Tools > Preferences > GUI. This now seems to be enabled by default and not switchable.

Has this option been removed or has Debian done it for me? I can see this is still showing up in the online docs: https://lzone.de/liferea/help110/preferences_en.html

**Comment by lwindolf** [comment]
The trayicon implementation has been removed with 1.12 and was moved to a plugin. The plugin based implementation is a bit simpler and misses any configuration options.

The idea of the Python plugins is that everyone with basic scripting skills can add such features :-)

**Comment by lwindolf** [comment]
Oh actually someone is doing this already: https://github.com/lwindolf/liferea/pull/752 you might want to download the plugin from this PR and try it :-)

**Comment by Ottaviocr** [comment]
Not sure if I did the right thing, but I replaced the original trayicon.py with the one from #752 and restarted liferea. I now have this crash:

``$ liferea
Traceback (most recent call last):
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/trayicon.py", line 107, in do_activate
    min_enabled = self.get_config()
  File "/usr/lib/x86_64-linux-gnu/liferea/plugins/trayicon.py", line 162, in get_config
    with open(config_path, "r") as f:
TypeError: invalid file: PosixPath('/home/oc/.local/share/liferea/plugins/trayicon/trayicon.txt')

**Comment by lwindolf** [comment]
Sorry, for the late reply. If the above error happens please remove the file causing it.

As we have the new trayicon plugin (with unread count) release for quite some while I'll close the ticket.
