### ISSUE TITLE
MediaRSS support

### ISSUE THREAD

**Issue by azmeuk** [lwindolf/liferea#761]
Looking at a feed like [this one](https://www.youtube.com/feeds/videos.xml?channel_id=UC7_gcs09iThXybpVgjHZ_7g) for example, we can see that there is a `<media:group>` tag containing information such as the video thumbnail, the video description and the video link. The `<media:group>` and variants appears to be part of the [Media RSS](http://www.rssboard.org/media-rss#media-group) specification.

```xml
  <media:group>
   <media:title>Is Time Travel Impossible?</media:title>
   <media:content url="https://www.youtube.com/v/pGnMiGrYmPE?version=3" type="application/x-shockwave-flash" width="640" height="390"/>
   <media:thumbnail url="https://i1.ytimg.com/vi/pGnMiGrYmPE/hqdefault.jpg" width="480" height="360"/>
   <media:description>Sign Up on Patreon to get access to the Space Time Discord! 
https://www.patreon.com/pbsspacetime

Check out the Space Time Merch Store
https://pbsspacetime.com/

Time travel stories are cool because both the past and future are somehow more interesting that the present and because everyone wants a redo.  But so far it appears we’re doomed to live consumed by regret in the eternal, boring present. Time marches on, inexorably and only forward. Or so we thought until Einstein came along. His special and general theories of relativity changed the way we think about time forever, and believe it or not, their raw equations permit time travel. They even tell us how to do it. So let’s review the possibilities, and decide how possible they really are. [...]</media:description>
   <media:community>
    <media:starRating count="14205" average="4.93" min="1" max="5"/>
    <media:statistics views="349292"/>
   </media:community>
  </media:group>
```

Currently, Liferea does not display a lot of thing. I think displaying the thumbnail and the description would be great. Displaying the player would be amazing.

With a youtube feed:
![Capture d’écran du 2019-11-16 15-25-21](https://user-images.githubusercontent.com/60163/68994625-5f412980-0885-11ea-9b6a-b998964ca4fd.png)

With a peertube feed:
![liferea-peertube](https://user-images.githubusercontent.com/60163/69147822-3a41f600-0ad3-11ea-8f7e-296da4f28a18.png)

What do you think?

**Comment by lwindolf** [comment]
Great idea. Some simple extra parsing could add those features.

**Comment by rich-coe** [comment]
I use a filter to display youtube media.  It mostly works.
Some youtube videos have higher playback requirements and will only play in the 
embedded browser.  You get an error: 'Video Unavailable.'  For that you have to open 
the link in a new tab anyway.
I suspect there is some browser variables that are only supplied in the browser tab, and not
in the liferea item browse window.

    : # use perl				-*- mode: Perl; -*-
            eval 'exec perl -S $0 "$@"'
            if $running_under_some_shell;

    $item = 0;
    $desc = 0;

    @entry = ();
    @descr = ();

    while (<>) {
        print $_;
        if (m/<media:group>/) {
            push @entry, "<content type=\"html\"><![CDATA[";
            $item = 1;
            next;
        }
        if ($item && m/<.media:group>/) {
            print join('', @entry);
            print join('', @descr);
            print "]]>\n</content>\n";
            @entry = ();
            @descr = ();
            $item = 0;
            next;
        }
        if ($item && m/<media:title>([^<]*)/) {
            push @entry, "<p>Title: $1</p>\n";
            next;
        }
        if ($item && m/<media:content url="([^"]*)" .*width="([^"]*)" height="([^"]*)"/) {
            $url = $1;
            $wid = $2;
            $hei = $3;
            $url =~ s#/v/#/embed/#;
            push @entry, "<p>\n";
            # <iframe width="640" height="480" src="https://www.youtube.com/embed/4Agdgn7GCJ8" frameborder="0" allowfullscreen></iframe>
            push @entry, "<iframe width=\"$wid\" height=\"$hei\" src=\"$url\" frameborder=\"0\" allowfullscreen></iframe>";
            push @entry, "<\p>\n";
            next;
        }
        if ($item && m/<media:starRating ([^<]*).>/) {
            @vals = split(/ /, $1);
            push @entry, "<p> Rating: "; 
            while (@vals) {
                ($k, $v) = split(/=/, shift @vals);
                $v =~ s/"//g;
                push @entry, "$k : $v  "; 
            }
            # push @entry, "</p>\n";
            next;
        }
        if ($item && m/<media:statistics views="([^"]*)/) {
            push @entry, "  Views  $1</p>\n";
            push @entry, "<p> </p>\n";
            next;
        }
        if ($item && m/<media:description>([^<]*)/) {
            $desc = 1;
            push @descr, "<p>";
            push @descr, $1;
            next;
        }
        if ($desc && m/(.*)<.media:description>/) {
            $desc = 0;
            push @descr, "<br/>";
            push @descr, $1;
            push @descr, "</p>\n";
            next;
        }
        if ($desc) {
            push @descr, "<br/>";
            push @descr, $_;
        }

    }

**Comment by mikelolasagasti** [comment]
I created PR #764 to show description and thumbnail based on the Youtube example. It could be extended to read more tags.

Current status:
![image](https://user-images.githubusercontent.com/773148/70912094-840af700-2013-11ea-9355-59d98c75e3f8.png)

PR:
![image](https://user-images.githubusercontent.com/773148/70912013-58880c80-2013-11ea-9aff-77af78d36990.png)

**Comment by mikelolasagasti** [comment]
With a CSS change (maybe I could just use the gravatar one?) and some XSLT magic, the new result would be:

![image](https://user-images.githubusercontent.com/773148/71025624-b433c200-2107-11ea-90da-644111e59b59.png)

**Comment by lwindolf** [comment]
@mikelolasagasti Thanks for implementing this. Will review soon!

**Comment by lwindolf** [comment]
#764 was merged

**Comment by lwindolf** [comment]
@azmeuk please try out recent master

**Comment by azmeuk** [comment]
This is perfect! Thank you very much.
