### ISSUE TITLE
doesn't keep frames size and position after exit.

### ISSUE THREAD

**Issue by repu1sion** [lwindolf/liferea#762]
Every time when I start liferea all frames (feeds, headline, browser) aligned from left to right and are in unreadable state (see screenshot). When I resize frames liferea doesn't save it size and position and after exit they are all in default state again. 1.12.2 and I don't see it fixed in latest versions.

![2019-11-22-153943_1920x1080_scrot](https://user-images.githubusercontent.com/968971/69430462-572e3180-0d3e-11ea-8ea6-e270daceb4ca.png)

**Comment by Leiaz** [comment]
This is similar to #570 #590

**Comment by nekohayo** [comment]
This should be closed as a duplicate of 590 and 590 should be renamed/retitled for clarity...

**Comment by Leiaz** [comment]
Duplicate of #901
