### ISSUE TITLE
Feature Request - set custom fonts in feed content

### ISSUE THREAD

**Issue by yerbestpal** [lwindolf/liferea#766]
The issue is that currently there is no settings that I am aware of for a user to set a font for their subscription content, be it the initial Headline view or any web pages that are loaded from them.

The use case for this is pretty strong; different fonts have different functions. In my case, I wanted to apply the [Sans Forgetica](https://sansforgetica.rmit/) font in an effort to better retain what I read. Some people just have an easier time reading certain fonts, and other might just be shooting for a tighter looking desktop.
It would probably be worthwhile arguing the case for font settings in general, like being able to set font sizes, and I might even make a separate issue for this.

I have very little programming skills and I doubt there is anything I could do to help, but I would do my best.

**Comment by lwindolf** [comment]
This is already possible with custom CSS. Check out "Liferea Trick #10" on the doc page https://lzone.de/liferea/docs.htm

**Comment by rich-coe** [comment]
The link on that page
https://lzone.de/liferea/blog/Liferea+Trick+%2310%3A+Custom+CSS+for+Article+Rendering
gives me a 'Not Found' result page.
If I go to https://lzone.de/liferea/blog/
there's a link to 
https://lzone.de/liferea/blog/2016/08/23/Liferea-Trick-10-Custom-CSS-for-Article-Rendering.html
which does work.

**Comment by lwindolf** [comment]
@rich-coe Thanks for pointing out the broken link. I fixed the direct link from the documentation page. But there are some other issues where links might be broken. I hope to fix them soon.
