### ISSUE TITLE
Title bar shows Wayland generic icon on KDE Plasma Wayland session

### ISSUE THREAD

**Issue by glaubersm** [lwindolf/liferea#768]
I use Liferea 1.12.7 on Arch linux.

Title bar of Liferea shows a Wayland generic icon when running on Wayland session of KDE Plasma DE.

![liferea](https://user-images.githubusercontent.com/15967631/71820906-6576a980-306f-11ea-89b4-b28c41df75d6.png)

**Comment by glaubersm** [comment]
This bug persists with 1.14 RC3. Could anyone reopen this bug please?

**Comment by lwindolf** [comment]
Reopened. Sorry about the accidental close.

Can you check if on your setup `find /usr/local/share/ -name net.sourceforge.liferea.png` finds installed Liferea icons?

**Comment by glaubersm** [comment]
Your command does not find anything on my system.

**Comment by lwindolf** [comment]
It should find files like those: 

      $ find /usr/local/share/ -name net.sourceforge.liferea.png
      /usr/local/share/icons/hicolor/16x16/apps/net.sourceforge.liferea.png
      /usr/local/share/icons/hicolor/48x48/apps/net.sourceforge.liferea.png
      /usr/local/share/icons/hicolor/24x24/apps/net.sourceforge.liferea.png
      /usr/local/share/icons/hicolor/22x22/apps/net.sourceforge.liferea.png
      /usr/local/share/icons/hicolor/32x32/apps/net.sourceforge.liferea.png

Did you properly run `sudo make install`?

**Comment by glaubersm** [comment]
I have instaled this package from AUR
https://aur.archlinux.org/packages/liferea-git

**Comment by lwindolf** [comment]
Ah... I see. When using distro "packages" you need to report bugs with the distro. Here in the upstream project we can only support the build instructions as given in the README.md.

**Comment by glaubersm** [comment]
I know here is the upstream It's not a packing issue.
I have just built the master branch from git and the icon is still incorrect.
Here is the output of your command now:
```
$ find /usr/local/share/ -name net.sourceforge.liferea.png
/usr/local/share/icons/hicolor/16x16/apps/net.sourceforge.liferea.png
/usr/local/share/icons/hicolor/32x32/apps/net.sourceforge.liferea.png
/usr/local/share/icons/hicolor/24x24/apps/net.sourceforge.liferea.png
/usr/local/share/icons/hicolor/22x22/apps/net.sourceforge.liferea.png
/usr/local/share/icons/hicolor/48x48/apps/net.sourceforge.liferea.png

```
Possibly this link is helpful to fix the icon

https://community.kde.org/Guidelines_and_HOWTOs/Wayland_Porting_Notes#Application_Icon

**Comment by lwindolf** [comment]
We do fullfill both conditions for Wayland icon discovery.

The desktop file properly specifies a reverse domain icon name

    $ grep Icon net.sourceforge.liferea.desktop.in
    Icon=net.sourceforge.liferea

and the icon is placed as such.
