### ISSUE TITLE
Feature Request - Remove Duplicate Articles

### ISSUE THREAD

**Issue by blueray453** [lwindolf/liferea#769]
It would be greate to have the option to remove duplicate articles (URIs) from the feed.

**Comment by lwindolf** [comment]
Such a feature based on identical item GUIDs is implemented. Removing based on URIs is not a good idea as user might be very confused when out of several blogs linking to the same source one of them looses posts.

This is especially the case for non-commerical blogs where posts don't point to an article page to gather traffic, but rather directly to external content.

**Comment by blueray453** [comment]
@lwindolf  How to remove duplicate usinf GUID?

**Comment by Ottaviocr** [comment]
Yes, i too would like to understand how this is implemented.
