### ISSUE TITLE
SIGUSR1 causes Segmentation fault

### ISSUE THREAD

**Issue by sillyslux** [lwindolf/liferea#774]
Also SIGUSR2 makes liferea shutdown. Exit codes are 139 and 140.
128+n Fatal error signal "n"
that's 128 +11 and +12
After some googling, it seems that this has something to do with threading.

**Comment by lwindolf** [comment]
Closing this. Not really a problem in my opinion.

**Comment by rich-coe** [comment]
I don't agree the SIGUSR1 is causing a segmentation fault. 
SIGUSR1 is used by the memory management 'usage' function to call a signal handler.
