### ISSUE TITLE
vscode configuration files

### ISSUE THREAD

**Issue by sillyslux** [lwindolf/liferea#775]
Personally i use vscode for programming and debugging liferea.
For debugging, i have gdb configured in .vscode/launch.json
Currently, i have it locally ignored via .git/info/exclude
Can i add .vscode/ to the repository? If not, can i add it to .gitignore?

**Comment by lwindolf** [comment]
As long as you maintain the .vscode/ folder feel free to include it :-)

Having a line in .gitignore IMO doesn't hurt at all.
