### ISSUE TITLE
Shaky text

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#78]
Ever since I have upgraded to Liferea GTK+3 I see dynamic shaky text while updating subscriptions which is annoying and is causing to higher usage in CPU.

![liferea_shaky_writings](https://cloud.githubusercontent.com/assets/2053884/3941024/2f559a1a-2507-11e4-8265-d553b190fe8d.gif)

**Comment by mozbugbox** [comment]
in [src/ui/feed_list_view.c, line 277](https://github.com/lwindolf/liferea/blob/master/src/ui/feed_list_view.c#L276-L277), try change the value `GTK_TREE_VIEW_COLUMN_AUTOSIZE` to `GTK_TREE_VIEW_COLUMN_GROW_ONLY`. That might help.

```c

gtk_tree_view_column_add_attribute (column, iconRenderer, "pixbuf", FS_ICON);
gtk_tree_view_column_add_attribute (column, titleRenderer, "markup", FS_LABEL);
gtk_tree_view_column_add_attribute (column2, countRenderer, "markup", FS_COUNT);

gtk_tree_view_column_set_expand (column, TRUE);
gtk_tree_view_column_set_sizing (column, GTK_TREE_VIEW_COLUMN_AUTOSIZE);
gtk_tree_view_column_set_sizing (column2, GTK_TREE_VIEW_COLUMN_AUTOSIZE);
gtk_tree_view_append_column (treeview, column);
gtk_tree_view_append_column (treeview, column2);
```
Use grow only instead of auto sizing for count column width.

**Comment by lwindolf** [comment]
@GreenLunar Could you test the suggestion from @mozbugbox ?

**Comment by GreenLunar** [comment]
Yes.  Please, post here a patch and I will test it with latest git master.

**Comment by mozbugbox** [comment]
Patch: https://gist.github.com/mozbugbox/4e38cb57f28aac801706

**Comment by GreenLunar** [comment]
```
libtool: link: cannot find the library `/usr/lib/libsecret-1.la' or unhandled argument `/usr/lib/libsecret-1.la'
make[3]: *** [html_auto] Error 1
```

II will try this patch against Liferea Unstable 1.11.4

**Comment by GreenLunar** [comment]
This patch appears to be working as stated. I will finally confirm whether it does, within several hours or tomorrow.

Thank you, @mozbugbox.

**Comment by GreenLunar** [comment]
It appears to be working as expected.

@mozbugbox, please push this change.

**Comment by asl97** [comment]
@GreenLunar you are `@mention`-ing the wrong person.
iirc only @lwindolf has push access.

**Comment by GreenLunar** [comment]
I am sorry.  I meant to send pull request.

**Comment by GreenLunar** [comment]
BUMP!

**Comment by lwindolf** [comment]
@asl97 @GreenLunar No need for a PR. I'll test this for a while and merge it if there are no obvious issues.

**Comment by lwindolf** [comment]
Seems ok. Merged.
