### ISSUE TITLE
connection failure reported

### ISSUE THREAD

**Issue by geoffleach1** [lwindolf/liferea#781]
Most (if not all) pages end with the message: A network error occurred, or the other end closed the connection unexpectedly.

The displayed text appears to be complete, so I believe that there is a (new) message termination code being sent.  An example feed would be Instapundit: http://feeds.feedburner.com/pjmedia/instapundit?format=xml

**Comment by nekohayo** [comment]
The feed works fine here for testing purposes (not that I would read it; I would suggest a more neutral site, I do not recommend anyone here to test this link further). You will have to be more specific (or provide another example that actually triggers the problem with the latest version of Liferea), or maybe you have encountered issue #1121.

In any case, my recommendation to maintainers would be to close this ticket, as it is not actionable as it is.

**Comment by lwindolf** [comment]
Closing this.
