### ISSUE TITLE
Does Liferea support "threaded" posts?

### ISSUE THREAD

**Issue by fsantanna** [lwindolf/liferea#782]
Atom Threading Extensions:
https://tools.ietf.org/html/rfc4685

**Comment by lwindolf** [comment]
Nope. The current code does not support this.

Do you know how relevant this extension is with real world feeds?

**Comment by fsantanna** [comment]
I believe it would be relevant for forums, mailing lists, news with comments, etc. Any content with hierarchy.
In my particular case, I'm using Liferea as a reader for an application that generates atom files (I use the | command as the feed source).

**Comment by rich-coe** [comment]
@fsantanna I don't about @lwindolf, but I translated '_relevant with real world feeds'_ as at least one example feed (several in fact would booster this request) that implements the provided data and at least one existing implementation (or detailed description of one proposed) as an example of how it might work as a User experience?

**Comment by nekohayo** [comment]
In my opinion, mailing lists are best read in an email client, and forum comment threads are best read in a web browser; using Liferea to grab the headlines to pick which topic to read is fine, but expecting it to basically reimplement reddit/discourse/etc. is probably out of scope, and it might be hell to manage treeview widgets. In my humble opinion, I'd say this is out of the intended usecase for a feed reader, especially one that does not have many code maintainers.

**Comment by lwindolf** [comment]
Closing this.
