### ISSUE TITLE
"Disable mark all read" plugin incompatible with the Headerbar plugin

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#784]
This is a minor issue, but thought I'd report it nonetheless: if using the headerbar plugin, "markallreadinactive" doesn't hide the "Mark all as read" button from the headerbar.

**Comment by lwindolf** [comment]
This is a 3rd party plugin that can be found here https://github.com/whizse/liferea-plugins.

Cannot be fixed within the scope of this github project.

**Comment by nekohayo** [comment]
Oh, I hadn't realized the markallreadinactive plugin was third-party unlike the headerbar one... the reason I mentioned that plugin was only because it existed, but since it doesn't exist anymore... I would like to request that this be reconsidered for the Headerbar plugin itself, instead.

In my view, that button is _way_ too dangerous to sit there as a primary action, and should never have been present on the headerbar to begin with, I'm not sure the risk warrants the proximity of that (unlabelled!) button next to the other inoffensive ones, especially since that action can also be accessed through two different menus (the global menu's Feed submenu, and the contextual/right-click menu in the feed list).

I would rather imagine other inoffensive (and probably more commonly used) buttons for the headerbar instead:

* New subscription
* Update all

**Comment by nekohayo** [comment]
(Issue #811 has a much more audacious/comprehensive headerbar/UI proposal, but the issue here in 784 is an worthwhile one-to-three-liner diff to consider in the meantime)

**Comment by lwindolf** [comment]
Given this preconditions

- toolbar has Mark-All-Read button
- headerbar is not favored according to recent user feedback 
- Mark-All-Read is "protected" by the confirmation dialog

For the sake of maintainability and consistency I decide that both toolbar and headerbar shall have the Mark-All-Read button.

IMO the perfect solution is still to ask @whizse to extend the plugin.
