### ISSUE TITLE
RFC: feature request: deferred marking of read items 

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#788]
I am currently using a feature where in the Unread list, after reading an item, it does not immediately delete the item from the unread list when moving to the next item, but marks the item as 'deferred read' as a transient state.   This allows me to go back to a previously read item if I mistakenly skip one (fat finger a key), or want to go back a re-read a previously read item in more detail.  I currently flush the deferred read items by switching to another item feed, but there could be a menu item that 'executes' this action.

Please let me know if you would find this feature useful.
Would this feature need to be optional to keep the current behaviour or should it always be there?

**Comment by rich-coe** [comment]
Note this is a request for comments in preparation for a pull request to @lwidolf.

**Comment by lwindolf** [comment]
Do you use the "Previous Item" feature to go back to the previous item?

This feature is currently only accessible via mouse or menu.

The probably should be a corresponding hotkey like Ctrl-P that matches Ctrl-N for "Next headline".

What do you think about a hotkey solution to this problem?

**Comment by lwindolf** [comment]
@rich-coe ping

**Comment by rich-coe** [comment]
@lwindolf  I'll make a PR this week.

**Comment by lwindolf** [comment]
Awesome!

**Comment by rich-coe** [comment]
Add UI preference 'Defer removing read items from Search Folder'.
Don't delete items from folder, like 'Unread', until leaving the folder.

Uses transient 'isHidden' flag on the item to set the font.

When reading items from a Search Folder, like 'Unread', defer removing the items from the UI until you leave the folder.  This allows re-reading read items or marking them unread.  Read items appear in light-weight font.

**Comment by lwindolf** [comment]
Added with merge of #997
