### ISSUE TITLE
[RTL] Back/Forward icons are misplaced

### ISSUE THREAD

**Issue by GreenLunar** [lwindolf/liferea#79]
Buttons are in their proper positions, but icons are not.

![liferea_back-and-forward](https://cloud.githubusercontent.com/assets/2053884/3941042/558d4d08-2508-11e4-861d-9926eb08c84a.png)

**Comment by lwindolf** [comment]
Fixed. Please test the implementation in git master.

**Comment by GreenLunar** [comment]
Not good.  Placement is incorrect.

> Buttons are in their proper positions, but icons are not.

Buttons are not RTL adaptable. See File Roller, Midori etc.

**Even better, instead of using left/right arrows, use up/down (see Evince or Qupzilla search bar).**

**Comment by lwindolf** [comment]
@GreenLunar Thanks for the hint on Roller/Midori. I'll have a look at them.

**Comment by GreenLunar** [comment]
I thought you were headed towards examining applications like these, when I read this "But I saw other GNOME applications do it, so it is probably common to implement it.".

**Comment by lwindolf** [comment]
Yeah I actually was checking code rather than inspecting GUIs and searching for text direction switching and found examples doing it. Maybe I misunderstood them.

**Comment by GreenLunar** [comment]
While keeping button labels the same (i.e. Next/Previous Item), you might prefer to set the icons to `Up` and `Down`.  QupZilla (a Qt based web browser) is using `Up` and` Down` in it search bar (Ctrl+F).  In that way, you would not need to be bothered with RTL UI issues, in this concern.

**Comment by GreenLunar** [comment]
Oops, I have already mentioned it!

I forgot to delete a note on my end to post this comment.

THIS AND PREVIOUS MESSAGES WILL BE DELETED.

**Comment by GreenLunar** [comment]
> Thanks for the hint on Roller/Midori/Evince.

Evince is an example for a workaround to be applied with Up and Down icons.

**Comment by Leiaz** [comment]
@GreenLunar Are you using a theme that contains the localized rtl icons "go-next-rtl" and "go-previous-rtl" ? Here on Archlinux the default Gnome theme gnome-icon-theme have them, but the Tangerine icon theme doesn't, so it falls back on "go-next" and "go-previous" of the same theme, [according to the standard](http://standards.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).

**Comment by GreenLunar** [comment]
> Are you using a theme that contains the localized rtl icons "go-next-rtl" and "go-previous-rtl" ?

Yes, gnome-icon-theme-3.8.3-i486-1

```
$ ls /usr/share/icons/gnome/32x32/* | grep rtl
document-revert-rtl.png
edit-redo-rtl.png
edit-undo-rtl.png
format-indent-less-rtl.png
format-indent-more-rtl.png
format-text-direction-rtl.png
go-first-rtl.png
go-last-rtl.png
go-next-rtl.png
go-previous-rtl.png
gtk-go-back-rtl.png
gtk-go-forward-rtl.png
gtk-goto-first-rtl.png
gtk-goto-last-rtl.png
gtk-indent-rtl.png
gtk-jump-to-rtl.png
gtk-media-forward-rtl.png
gtk-media-next-rtl.png
gtk-media-previous-rtl.png
gtk-media-rewind-rtl.png
gtk-revert-to-saved-rtl.png
gtk-unindent-rtl.png
media-playback-start-rtl.png
media-seek-backward-rtl.png
media-seek-forward-rtl.png
media-skip-backward-rtl.png
media-skip-forward-rtl.png
```

> You don't actually need the buttons reversed, right ? Just the icons, and the previous button should be on the right ?

I am not sure, because it might be inconsistent with Back/Previous icons of the [embedded web browser](#issuecomment-68110822).

**Comment by Leiaz** [comment]
It is currently inconsistent in master because the buttons are reversed in the application toolbar (previous is on the left), but not in the browser toolbar (previous is on the right). 

I used the `he_IL.utf8` locale for testing (but I can't read hebrew, or anything right to left). With Gnome icon theme 3.12 and Gtk+ 3.18.1, and the above commit reversed, the previous button is on the right for both toolbars, and the arrows are pointing away from each other (<- ->).

**Comment by GreenLunar** [comment]
Please submit a fix and I will test it.

**Comment by Leiaz** [comment]
For testing you can do a `git revert -n 26dd75e`. There is a conflict in the changelog, but as it is just for testing, you can ignore it. Then you can use `git reset --hard` to discard the changes.

**Comment by GreenLunar** [comment]
This is too complicated to me.  Please fork this repository and I will perform tests.

**Comment by lwindolf** [comment]
Closing this very old bug.
