### ISSUE TITLE
How to make backups

### ISSUE THREAD

**Issue by elcortegano** [lwindolf/liferea#798]
Hi recently was trying to backup liferea from its configuration files, but this has lead to the following error, that makes me impossible to open the program:

```
(liferea:8413): Gtk-WARNING **: 20:27:36.015: Failed to parse /home/xiao_ou/.config/gtk-3.0/settings.ini: El archivo de claves no tiene el grupo «Settings»

** (liferea:8413): WARNING **: 20:27:36.047: Unexpected status on SQL execution: 14 (unable to open database file)

** (liferea:8413): WARNING **: 20:27:36.047: Unexpected status on SQL execution: 14 (unable to open database file)

** (liferea:8413): ERROR **: 20:27:36.047: Failure while preparing statement, (error=14, unable to open database file) SQL: "SELECT COUNT(type) FROM sqlite_master WHERE type = 'table' AND name = 'info';"
`trap' para punto de parada/seguimiento (`core' generado)

```
The files I was copying for backup were `feedlist.opml*` to `.config/liferea/`, `liferea.css` to the same folder, and `liferea.db*` to `.local/share/liferea/`.

If I reinstall the program the error persists. It is not until I delete these files that I can open liferea, but of course this way does not allow to recover the feeds I have listed in my backup files.

How to properly restore feeds in liferea?

**Comment by Leiaz** [comment]
It says "unable to open database file". Did you check that the file was restored with the proper permissions ?

**Comment by lwindolf** [comment]
Also copying the DB file while Liferea is running might lead to corruption. If you do not care about the headline archive removing the .db file will solve your issue.

**Comment by lwindolf** [comment]
But then again: sqlite error code 14 seems to be about file permissions.

**Comment by elcortegano** [comment]
I get a different error now. I am using chmod +x to make sure that files have permissions to be executed.

The new error is:

```
** (liferea:29826): WARNING **: 09:47:11.890: Unexpected status on SQL execution: 11 (database disk image is malformed)

** (liferea:29826): WARNING **: 09:47:11.891: Unexpected status on SQL execution: 11 (database disk image is malformed)
**
ERROR:db.c:729:db_init: assertion failed: (sqlite3_get_autocommit (db))
Bail out! ERROR:db.c:729:db_init: assertion failed: (sqlite3_get_autocommit (db))
Aborted (core dumped)
```

**Comment by lwindolf** [comment]
@elcortegano The "database disk image is malformed" indicates unrecoverable database corruption.
