### ISSUE TITLE
[1.13.0] plugins/headerbar.py not mentioned in either POTFILES.in or POTFILES.skip

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#799]
Hi,

I am trying to build liferea 1.13.0 for Debian, but my build fails with the following message:
```
The following files contain translations and are currently not in use. Please
consider adding these to the POTFILES.in file, located in the po/ directory.

plugins/headerbar.py

If some of these files are left out on purpose then please add them to
POTFILES.skip instead of POTFILES.in. A file 'missing' containing this list
of left out files has been written in the current directory.
Please report to liferea-devel@lists.sourceforge.net
```
I can imagine that the file is not translated on purpose, but I'm not sure. I'll work around it for now by creating the POTFILES.skip as suggested, but wanted you to be aware of the issue.

**Comment by lwindolf** [comment]
No, this was unintendet. The plugin contains gettext wrapped literals that are already translated and should be used. Therefore I added the plugin file to POTFILES.in
