### ISSUE TITLE
Log / debug settings

### ISSUE THREAD

**Issue by BillDietrich** [lwindolf/liferea#801]
I'm using Liferea 1.12.2 on Linux Mint 19.3 Cinnamon.  Liferea seems to do a LOT of logging into the system journal.  Please document the log / debug settings, and provide a way to control them from the GUI.  And maybe the default settings should be to do less logging.  Thanks.

**Comment by lwindolf** [comment]
The logging options are documented
```
$ LANG=C src/liferea --help-debug
Usage:
  liferea [OPTION?]

Print debugging messages for the given topic
  --debug-all                      Print debugging messages of all types
  --debug-cache                    Print debugging messages for the cache handling
  --debug-conf                     Print debugging messages for the configuration handling
  --debug-db                       Print debugging messages of the database handling
  --debug-gui                      Print debugging messages of all GUI functions
  --debug-html                     Enables HTML rendering debugging. Each time Liferea renders HTML output it will also dump the generated HTML into ~/.cache/liferea/output.xhtml
  --debug-net                      Print debugging messages of all network activity
  --debug-parsing                  Print debugging messages of all parsing functions
  --debug-performance              Print debugging messages when a function takes too long to process
  --debug-trace                    Print debugging messages when entering/leaving functions
  --debug-update                   Print debugging messages of the feed update processing
  --debug-vfolder                  Print debugging messages of the search folder matching
  --debug-verbose                  Print verbose debugging messages
```

And they are not active by default. I'd guess the logs you see are GTK assertions. Can you post examples?

**Comment by BillDietrich** [comment]
There are some assertions, but also plenty of HTTP stuff.  File attached.  
[temp.txt](https://github.com/lwindolf/liferea/files/4320892/temp.txt)

**Comment by lwindolf** [comment]
This looks like debugging for libsoup (which Liferea uses) is active. This can cause this type of output.

When you run liferea with --debug-net you'd get this output.

Can you check the CLI parameters with which liferea was invoked? E.g.

      ps -ef |  grep liferea

**Comment by BillDietrich** [comment]
user1     8875  4926  5 09:34 ?        00:01:20 /usr/bin/liferea --gapplication-service

By the way, I am using uGet 2.2.0  But the logging in system journal says "liferea", so I assume the problem is on the Liferea side.

**Comment by rich-coe** [comment]
I wonder if Linux Mint added a patch to their liferea build that's enabling debug and logging.

**Comment by lwindolf** [comment]
@BillDietrich I've just reproduced the issue with uGet v2.2 and it is uGet writing those logs. Please file a bug against uget!

**Comment by BillDietrich** [comment]
Okay, I have filed a report with uGet, but their bug-tracking system is called something like "Questions and Answers" and does not inspire confidence.  A report of a simple broken link in their app's Help menu has been unfixed for over a year, for example.

**Comment by BillDietrich** [comment]
Same issue still happens with Liferea 1.13.7 and uGet 2.2.3 on Endeavour 2021.12.17 LXQt.  Tons of HTTP activity logging in system journal.  Some default value is set wrong at compile time, I guess.

**Comment by BillDietrich** [comment]
https://ugetdm.com/qa/1421/logging-level-set-far-too-high

**Comment by BillDietrich** [comment]
I just tried about 8 different downloaders, and they all have similar behavior: dumping lots of output into the system journal.  I think Liferea must be connecting the downloader's stdout to the system journal.  Please provide an option (in the Liferea GUI) to turn this off.  Thanks.
