### ISSUE TITLE
Broken links in documentation site

### ISSUE THREAD

**Issue by BillDietrich** [lwindolf/liferea#802]
On web page https://lzone.de/liferea/docs.htm at the bottom:

The link https://lzone.de/security+advisory+feeds is broken.

The site https://ctrlq.org/rss/ was last updated in 2013 and seems to not work; no search I do returns any results.

The link https://gdata.youtube.com/demo/index.html gives a 404 error.

**Comment by lwindolf** [comment]
Thank you for pointing this out. I simply removed the section. After all we have default example feeds.
