### ISSUE TITLE
Error while parsing Moneysense feed

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#808]
If you try to subscibe to https://www.moneysense.ca/feed/ using Liferea, it refuses to work, Liferea then just says "There were errors while parsing this feed!"

Attaching it here for reproduceability (since maybe it's a transient problem): 
[moneysense feed 2020-03-29.zip](https://github.com/lwindolf/liferea/files/4399779/moneysense.feed.2020-03-29.zip)

Is there nothing that can be done about feeds like this one? For what it's worth, that same feed URL works in FeedReader. Unfortunately since Liferea provides no debug log or debugging window for feeds, I don't know what was wrong with it. Tested on Liferea 1.12.7.

**Comment by lwindolf** [comment]
I fear with libxml2 which Liferea uses it is not possible. While libxml2 has a generic error reporting method it often provides binary garbage as an error string. Not sure if github will render it: This is the actuall error message from the libxml2 SAX parser �ǥ��U

**Comment by lwindolf** [comment]
Aside from this I agree that the parser error reporting is awful. Even if we cannot indicate what failed we can indicate when it failed. Having a feed parsing stage mapping (e.g. stage 1 authentication, stage 2 parsing document, stage 3 extracting content...) it might be more useful to show what of those failed and point users into a direction. Let's track this in #809

**Comment by lwindolf** [comment]
BTW I have no clue why libxml2 doesn't like this totally valid feed.
