### ISSUE TITLE
Use a real infobar and allow showing details/logs for feed parsing errors

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#809]
When a feed parsing error occurs, this yellow banner is shown:

![2020-03-29 17-07-27](https://user-images.githubusercontent.com/479401/77860910-d85f6e80-71df-11ea-964a-4de6ed32eeea.png)

However, as illustrated in #808, this isn't really helpful for users to either report bugs on Liferea or to notify the website owners. I mean sure, I know there were errors... but Liferea is not telling me what they are and why it can't cope with them.

Ideally, this yellow banner should be replaced by a standard GtkInfobar widget, with an action button to "Show details..." that could display the errors in a scrollable (and copy-able) textview in a separate window.

Ideally, that window should be [auto-sized](https://fortintam.com/blog/dont-make-me-scroll/) to avoid the need for scrolling, but anything is better than nothing for now.

Heck, it could simply dump a .txt (or .xml, or something with the proper file extension) error log file into /tmp/ (or something in the user XDG cache directory where liferea stores its cache) and open it with the user's default text editor using xdg-open and voilà, you get syntax highlighting for free, and no need to create an additional UI dialog in Liferea ;) it could even prepend the log with some notes about reporting it in Liferea or pre-written text to make it easy for users to include in an email to website owners with broken feeds (in the cases where it's really broken beyond any hope of Liferea being able to parse it).

**Comment by medeotl** [comment]
Could be useful to provide a link to https://validator.w3.org/feed/check.cgi?url=mysite.feed in the infobar to give user more info about the error?

**Comment by lwindolf** [comment]
@medeotl Had this in the past, then the validator went malware and we had the URL hint to a malware site out there with the users. Won't fall for this again :-)

**Comment by lwindolf** [comment]
To solve this issue here I have the following concept / idea:

- do not give technical reasons anymore, as our parsing library libxml2 almost never provides those
- instead provide an overview of processing phases to help the user determine the cause
- suggest generic solution for the failed phase

Example phases rendering:

     [OK] authentication
     [OK] download
     [OK] parsing XML
     [FAILED] determining feed type
     [   ] extracting content

     ---> Suggestion: please validate the feed using an online validator

Or another 

     [OK] authentication
     [FAILED] download
     [   ] parsing XML
     [   ] determining feed type
     [   ] extracting content

     ---> Suggestion: Check your internet connectivity and try to manually fetch the feed source URL

or 

     [OK] authentication
     [OK] download
     [FAILED] parsing XML
     [   ] determining feed type
     [   ] extracting content

     ---> Suggestion: sorry Liferea relies on well-formed XML. Please contact author to fix this...

What do you think?

**Comment by Leiaz** [comment]
This is in answer to posts in #808 but to continue the discussion here : it is actually possible to get an error message from the parser. For the given feed I get "XML declaration allowed only at the start of the document". Here is how (ugly, debug printf in code, example) : 

```diff
diff --git a/src/xml.c b/src/xml.c
index cb2d2986..b9fd6c94 100644
--- a/src/xml.c
+++ b/src/xml.c
@@ -511,6 +511,14 @@ xml_get_ns_attribute (xmlNodePtr node, const gchar *name, const gchar *namespace
 	return xmlGetNsProp (node, BAD_CAST name, BAD_CAST namespace);
 }
 
+static void liferea_errorSAXFunc (void * ctx, const char * msg,...)
+{
+  va_list valist;
+  va_start(valist,msg);
+  g_vprintf (msg, valist);
+  va_end(valist);
+}
+
 xmlDocPtr
 xml_parse (gchar *data, size_t length, errorCtxtPtr errCtx)
 {
@@ -521,6 +529,7 @@ xml_parse (gchar *data, size_t length, errorCtxtPtr errCtx)
 
 	ctxt = xmlNewParserCtxt ();
 	ctxt->sax->getEntity = xml_process_entities;
+	ctxt->sax->error = liferea_errorSAXFunc;
 	
 	if (errCtx)
 		xmlSetGenericErrorFunc (errCtx, (xmlGenericErrorFunc)xml_buffer_parse_error);
```
It is also possible to put the parser in a more tolerant ["recovery mode"](http://xmlsoft.org/html/libxml-parser.html#xmlSAXParseMemory) by passing 1 instead of 0 to xmlSAXParseMemory. For feeds that are not too malformed, like the example feed, it works. But if the feed is too broken, it could replace the previous feed items with a ton of new garbage items.

**Comment by lwindolf** [comment]
@Leiaz In all cases we should hook the SAX error callback as you illustrated.

**Comment by nekohayo** [comment]
These all sound like good ideas to me, or at least, more useful for users wanting to know why the feed is encountering errors ;) though for network-related errors, wouldn't Liferea be able to know when the network is not available anyway (through NetworkManager for example) and thus not even attempt to download feed updates while the system's network connection doesn't provide full Internet connectivity anyway?

**Comment by lwindolf** [comment]
@nekohayo The typical network manager hook to know about online/offline status is implemented. Still this doesn't cover all network issues. There is some latency until NetworkManager detects a downtime and what to do with a feed that was already in download... But the basic handling is there.

**Comment by lwindolf** [comment]
@nekohayo Please have a look at the screencast in #938 what do you think?

**Comment by nekohayo** [comment]
I think it's pretty nice, definitely an improvement over the previous lack of information!

If I can nitpick, I'd say it might not be immediately obvious (when looking at a single failing feed, rather than the plethora of failing feeds like in your screencast) that the list is actually a linear "process" from top to bottom. So, short of making it a numbered list, maybe you could be a little bit more explicit in the intro text above it, saying:

> There was a problem when fetching this subscription! _This is where the fetching process halted for "$feed_name":_
>
> [the list]
> etc.

**Comment by lwindolf** [comment]
Thanks for the feedback. I decided to go for the numbered list as I believe having less "filler" sentences is better.

For now I consider this issue solved.
