### ISSUE TITLE
Give a progress indication when updating all feeds

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#810]
To help users be patient when there are more than 20 feeds to update, it would be helpful to have a rough estimation of feed update progress.

I could imagine a progressbar widget in various places (the headerbar, under the headerbar, or at the bottom of the feeds list) but if you prefer something much simpler, unobtrusive and compatible with both the headerbar and traditional UI, it could be shown as a simple text string in the (floating) statusbar, simply by appending the "updating" and "updated" status messages with:

>  (checking feed %d of %d)

**Comment by rich-coe** [comment]
Is Tools>Update Montor  not sufficient?

**Comment by nekohayo** [comment]
No, it does not provide progress indication and has no items count nor time estimates, refreshes only once per second unlike the realtime statusbar updates, and requires you to actually go digging two levels deep to spawn a new separate window for it. It is clearly meant to be more of a debugging tool than something built-in that would indicate to the casual user that the app is busy and progressing, and roughly how long it will be busy for.

**Comment by nekohayo** [comment]
To give some more context for this, from a "cognitive science" human-computer-interaction design point of view: the presence of a progress counter or progressbar makes users more patient—it's totally a mind trick, but when humans have a rough visual indication of how long a process is taking, the wait becomes much more tolerable. Having this directly in the headerbar would be great for user experience (the update monitor feels more like a debugging tool than a UX enhancement).

Various studies and articles have been written on the topic, but here's one of them from a fairly known HCI/usability group: https://www.nngroup.com/articles/progress-indicators/

**Comment by lwindolf** [comment]
Was implemented a while ago, by having "Updating x/y ..." status bar message. While it is not graphical I think it improves UX significantly.
