### ISSUE TITLE
Convert twitter account URL into RSS feed

### ISSUE THREAD

**Issue by antistress** [lwindolf/liferea#814]
Hi,

Similarly to YouTube (#813), another website which doesn't provide RSS feed for commercial reasons regardless user interests, it would be cool to allow Liferea users to follow Twitter accounts  since not everybody has – or want to have – a Twitter account.

There are different possibilties using kind of proxies like this service https://rssbox.herokuapp.com/ | https://github.com/stefansundin/rssbox under AGPL or, maybe better, nitter.net also under AGPL which directly provides an RSS feed.

We could imagine that, if I want to follow https://twitter.com/firefox for instance, and that I copy/paste this URL into Liferea, Liferea could warn :

Hi, we're sorry but Twitter.com doesn't support RSS feeds. However it's still possible to follow Twitter accounts using another service, Nitter.net, which acts like a mirror site that does provide RSS feeds. Do you want to add this feed through Nitter.net ? YES | GIVE UP | Show me Nitter's [About page](https://nitter.net/about) first 

Thanks

**Comment by lwindolf** [comment]
I do not believe hard-coding such hints works well with long-lived downstream distribution packaged (e.g. Debian).

BTW if you are looking for a working converter there is twitrss.me with which you can add twitter feeds:

    http://twitrss.me/twitter_user_to_rss/?user=larswindolf

I extended the FAQ (https://lzone.de/liferea/faq.htm#subscribe-twitter)
 with a hint on twitter feeds. I think this is a good compromise.

Thank you for bringing this up!

**Comment by antistress** [comment]
Agree.
Thanks for your answer and the tip
BTW, besides https://twitrss.me that I didn't know, https://queryfeed.net/ seems to do the job also.
Cheers

**Comment by ao2** [comment]
@antistress if you prefer a local converter you can use Tweeper:
https://ao2.it/en/blog/2020/07/09/tweeper-142-released-twitter-rss-conversion-back
https://git.ao2.it/tweeper.git/blob/HEAD:/README

Once it's installed and reachable from `PATH` you can use it as a filter in liferea:
```
$ liferea-add-feed  "|tweeper https://twitter.com/NSAcareers"
```
or use it in a "command" when adding a source.
