### ISSUE TITLE
with reduced feed list, I cannot read last unread item

### ISSUE THREAD

**Issue by jpritikin** [lwindolf/liferea#82]
As soon as I try to read the last unread item in a folder then the whole folder disappears and the item disappears along with it. Liferea 1.10.3-1ubuntu1

**Comment by lwindolf** [comment]
I cannot reproduce it with git master. Can you recheck with recent 1.10 releases / git master?

**Comment by jpritikin** [comment]
Sorry, I switch to elfeed (emacs extension)
