### ISSUE TITLE
create menu item to view item source

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#824]
Create a menu item to view an item's source.
Useful for debugging to see the item's source 'html' from the db.
When displaying the item, the option could be available on the item UI, or in the item list.
'View Source'

Upon selection, display a pop-up window in which displays the item in a text window.

Optionally hide item selection in preference menu to not present 'View Source' as a menu option for novice users.  Possibly in a section or tab under 'Advanced' or 'Debugging'.

**Comment by lwindolf** [comment]
We have a great debugging feature in place using Webkit inspector: it is described here https://lzone.de/liferea/blog/Writing+Liferea+Plugins+Tutorial+Part+4

#773 has added a menu option to help launch inspector when run with --debug-html

I believe this addresses you idea quite well.

**Comment by rich-coe** [comment]
I'll try it out.
