### ISSUE TITLE
Sorting feeds in a Folder, "Program received signal SIGSEGV, Segmentation fault"

### ISSUE THREAD

**Issue by ndias** [lwindolf/liferea#83]
Liferea crashes when sorting feeds in a Folder, with "Program received signal SIGSEGV, Segmentation fault"

The gdb output 

Program received signal SIGSEGV, Segmentation fault.
gtk_tree_store_iter_n_children (tree_model=0xcd8da0, iter=0x7fffffffc450)
    at gtktreestore.c:767
767	      node = node->next;
(gdb) bt
#0  gtk_tree_store_iter_n_children (tree_model=0xcd8da0, iter=0x7fffffffc450)
    at gtktreestore.c:767
#1  0x0000003b390a7f6d in gtk_tree_model_filter_build_level (
    filter=filter@entry=0xce7ce0, parent_level=parent_level@entry=0xdaf260, 
    parent_elt=parent_elt@entry=0x15818c0, emit_inserted=emit_inserted@entry=0)
    at gtktreemodelfilter.c:792
#2  0x0000003b390a8088 in gtk_tree_model_filter_update_children (
    filter=filter@entry=0xce7ce0, level=level@entry=0xdaf260, 
    elt=elt@entry=0x15818c0) at gtktreemodelfilter.c:1837
#3  0x0000003b390ab00e in gtk_tree_model_filter_update_children (
    elt=0x15818c0, level=0xdaf260, filter=0xce7ce0)
    at gtktreemodelfilter.c:1824
#4  gtk_tree_model_filter_row_changed (c_model=0xcd8da0, c_path=0x17fba30, 
    c_iter=<optimized out>, data=0xce7ce0) at gtktreemodelfilter.c:2086
#5  0x0000003b390ab139 in gtk_tree_model_filter_refilter_helper (
    model=<optimized out>, path=<optimized out>, iter=<optimized out>, 
    data=<optimized out>) at gtktreemodelfilter.c:4253
#6  0x0000003b390a3fc8 in gtk_tree_model_foreach_helper (
    model=model@entry=0xcd8da0, iter=iter@entry=0x7fffffffc690, 
    path=path@entry=0x17fba30, func=func@entry=
    0x3b390ab130 <gtk_tree_model_filter_refilter_helper>, 
    user_data=user_data@entry=0xce7ce0) at gtktreemodel.c:1946
#7  0x0000003b390a532e in gtk_tree_model_foreach (model=0xcd8da0, 
    func=func@entry=0x3b390ab130 <gtk_tree_model_filter_refilter_helper>, 
    user_data=0xce7ce0) at gtktreemodel.c:1993
#8  0x0000003b390a9c3f in gtk_tree_model_filter_refilter (
    filter=<optimized out>) at gtktreemodelfilter.c:4273
#9  0x000000000043febc in feed_list_view_selection_changed_cb (
    selection=<optimized out>, data=<optimized out>) at feed_list_view.c:78
#10 0x0000003b8cc104c7 in _g_closure_invoke_va (
    closure=closure@entry=0x75df90, return_value=return_value@entry=0x0, 
    instance=instance@entry=0x7fffe4003920, args=args@entry=0x7fffffffc910, 
    n_params=0, param_types=0x0) at gclosure.c:840
#11 0x0000003b8cc29749 in g_signal_emit_valist (instance=0x7fffe4003920, 
    signal_id=<optimized out>, detail=0, 
    var_args=var_args@entry=0x7fffffffc910) at gsignal.c:3238
#12 0x0000003b8cc2a3af in g_signal_emit (instance=<optimized out>, 
    signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3386
#13 0x00007fff91bf547c in _gtk_tree_selection_internal_select_node (
    selection=<optimized out>, node=<optimized out>, tree=<optimized out>, 
    path=path@entry=0x156d100, mode=<optimized out>, 
    override_browse_mode=override_browse_mode@entry=0)
    at gtktreeselection.c:1427
#14 0x0000003b390c5ac4 in gtk_tree_view_real_set_cursor (
    tree_view=tree_view@entry=0xbc85d0, path=path@entry=0x156d100, 
    flags=flags@entry=(CLEAR_AND_SELECT | CURSOR_INVALID))
    at gtktreeview.c:13160
#15 0x0000003b390c7ab3 in gtk_tree_view_row_deleted (model=<optimized out>, 
    path=<optimized out>, data=0xbc85d0) at gtktreeview.c:9167
#16 0x0000003b8cc10298 in g_closure_invoke (closure=0xcd9cb0, 
    return_value=return_value@entry=0x0, n_param_values=2, 
    param_values=param_values@entry=0x7fffffffcc60, 
    invocation_hint=invocation_hint@entry=0x7fffffffcc00) at gclosure.c:777
#17 0x0000003b8cc2235d in signal_emit_unlocked_R (node=node@entry=0xcd9600, 
    detail=detail@entry=0, instance=instance@entry=0xcd8da0, 
    emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fffffffcc60)
    at gsignal.c:3586
#18 0x0000003b8cc2a0f2 in g_signal_emit_valist (instance=<optimized out>, 
    signal_id=<optimized out>, detail=<optimized out>, 
    var_args=var_args@entry=0x7fffffffcdf0) at gsignal.c:3330
#19 0x0000003b8cc2a3af in g_signal_emit (instance=instance@entry=0xcd8da0, 
    signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3386
#20 0x0000003b390a5108 in gtk_tree_model_row_deleted (
    tree_model=tree_model@entry=0xcd8da0, path=path@entry=0x1586290)
    at gtktreemodel.c:1867
#21 0x0000003b390b5321 in gtk_tree_store_remove (
    tree_store=tree_store@entry=0xcd8da0, iter=iter@entry=0x7fffffffcf40)
    at gtktreestore.c:1230
#22 0x0000003b390b5489 in gtk_tree_store_clear_traverse (node=0x157d560, 
    store=store@entry=0xcd8da0) at gtktreestore.c:1856
#23 0x0000003b390b545f in gtk_tree_store_clear_traverse (node=0xce8a00, 
    store=store@entry=0xcd8da0) at gtktreestore.c:1839
#24 0x0000003b390b6808 in gtk_tree_store_clear (tree_store=0xcd8da0)
    at gtktreestore.c:1884
#25 0x0000000000441430 in feed_list_node_clear_feedlist ()
    at feed_list_node.c:246
#26 feed_list_node_reload_feedlist () at feed_list_node.c:253
#27 0x00000000004402db in feed_list_view_sort_folder (folder=0x15679a0)
    at feed_list_view.c:221
#28 0x0000003b8cc10298 in g_closure_invoke (closure=0xd77f00, 
    return_value=return_value@entry=0x0, n_param_values=1, 
    param_values=param_values@entry=0x7fffffffd1a0, 
    invocation_hint=invocation_hint@entry=0x7fffffffd140) at gclosure.c:777
#29 0x0000003b8cc2235d in signal_emit_unlocked_R (node=node@entry=0x6e1ee0, 
    detail=detail@entry=0, instance=instance@entry=0xcd6790, 
    emission_return=emission_return@entry=0x0, 
    instance_and_params=instance_and_params@entry=0x7fffffffd1a0)
    at gsignal.c:3586
#30 0x0000003b8cc2a0f2 in g_signal_emit_valist (instance=<optimized out>, 
    signal_id=<optimized out>, detail=<optimized out>, 
    var_args=var_args@entry=0x7fffffffd320) at gsignal.c:3330
#31 0x0000003b8cc2a3af in g_signal_emit (instance=instance@entry=0xcd6790, 
    signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3386
#32 0x0000003b390dc3ac in gtk_widget_activate (widget=widget@entry=0xcd6790)
    at gtkwidget.c:7199
#33 0x0000003b38fc82de in gtk_menu_shell_activate_item (menu_shell=0xcb5380, 
    menu_item=0xcd6790, force_deactivate=<optimized out>)
    at gtkmenushell.c:1391
#34 0x0000003b38fc862d in gtk_menu_shell_button_release (widget=0xcb5380, 
    event=<optimized out>) at gtkmenushell.c:805
#35 0x0000003b38fab62e in _gtk_marshal_BOOLEAN__BOXEDv (closure=0x6d8a40, 
    return_value=0x7fffffffd5e0, instance=<optimized out>, 
    args=<optimized out>, marshal_data=<optimized out>, 
    n_params=<optimized out>, param_types=0x6d8a70) at gtkmarshalers.c:130
#36 0x0000003b8cc104c7 in _g_closure_invoke_va (
    closure=closure@entry=0x6d8a40, 
    return_value=return_value@entry=0x7fffffffd5e0, 
    instance=instance@entry=0xcb5380, args=args@entry=0x7fffffffd6e0, 
    n_params=1, param_types=0x6d8a70) at gclosure.c:840
#37 0x0000003b8cc29749 in g_signal_emit_valist (instance=0xcb5380, 
    signal_id=<optimized out>, detail=0, 
    var_args=var_args@entry=0x7fffffffd6e0) at gsignal.c:3238
#38 0x0000003b8cc2a3af in g_signal_emit (instance=instance@entry=0xcb5380, 
    signal_id=<optimized out>, detail=detail@entry=0) at gsignal.c:3386
#39 0x0000003b390dd37c in gtk_widget_event_internal (
    widget=widget@entry=0xcb5380, event=event@entry=0x8936a0)
    at gtkwidget.c:7168
#40 0x0000003b390dd659 in gtk_widget_event (widget=widget@entry=0xcb5380, 
    event=event@entry=0x8936a0) at gtkwidget.c:6830
#41 0x0000003b38fa990c in propagate_event_up (topmost=<optimized out>, 
    event=<optimized out>, widget=0xcb5380) at gtkmain.c:2391
#42 propagate_event (widget=<optimized out>, event=0x8936a0, 
    captured=<optimized out>, topmost=0x0) at gtkmain.c:2499
#43 0x0000003b38fab1ea in gtk_main_do_event (event=0x8936a0) at gtkmain.c:1714
#44 0x0000003b3864ef62 in gdk_event_source_dispatch (
    source=source@entry=0x728c30, callback=<optimized out>, 
    user_data=<optimized out>) at gdkeventsource.c:364
#45 0x0000003b8b8492a6 in g_main_dispatch (context=0x6f6070) at gmain.c:3066
#46 g_main_context_dispatch (context=context@entry=0x6f6070) at gmain.c:3642
#47 0x0000003b8b849628 in g_main_context_iterate (
    context=context@entry=0x6f6070, block=block@entry=1, 
    dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3713
#48 0x0000003b8b8496dc in g_main_context_iteration (context=0x6f6070, 
    context@entry=0x0, may_block=may_block@entry=1) at gmain.c:3774
#49 0x000000392469c954 in g_application_run (application=0x8a50d0, 
    argc=argc@entry=0, argv=argv@entry=0x0) at gapplication.c:1635
#50 0x000000000041aea0 in main (argc=1, argv=0x7fffffffdef8) at main.c:262

**Comment by lwindolf** [comment]
Reproduced
