### ISSUE TITLE
Line item highlights under mouse pointer

### ISSUE THREAD

**Issue by heynnema** [lwindolf/liferea#830]
When reviewing the items in a news feed, moving the mouse pointer up/down the item list, it highlights the current item under the mouse pointer, without the item having been clicked/selected.

**Comment by lwindolf** [comment]
You didn't specify wether you consider this a bug, a feature request or something else.
If you consider this strange, I'm with you. This suddenly started happening for me after upgrading to Ubuntu 20.04.

Seems to be a new GTK theme gimmick. There is not a single line of code in Liferea causing this :-)

You might want to reproduce this with Nautilus. Try navigating the file list with arrow keys and you get the same effect.
