### ISSUE TITLE
update compile instructions for ubuntu 20.04

### ISSUE THREAD

**Issue by TusharSariya** [lwindolf/liferea#832]
autoconf, intltool & libtool need to be installed before running autogen.sh:
sudo apt install autoconf
sudo apt install intltool
sudo apt install libtool

in addition libgirepository1.0 is not avaliable on ubuntu 20.04

**Comment by lwindolf** [comment]
You are right, the libgirepository package has a "-dev" suffix. I've fixed the README.md

About autoconf intltool libtool... yes, but they are like gcc and make, they are not a library dependency. Just build tooling which under Debian AFAIK you install with `sudo apt install build-essential`
