### ISSUE TITLE
Opening apps from snap (and flatpak)

### ISSUE THREAD

**Issue by almejo** [lwindolf/liferea#836]
As reported in #825 liferea can't open other apps from inside a snap. This is because snap apps (and flatpak ones) are isolated from the rest of the system. 

I asked for 'classic' confinement. This way liferea can have access to the rest of the system. 

You can read here. 

https://forum.snapcraft.io/t/classic-confinement-request/17823

Also, if the snapcraft team says no, another way is to modify the interface of liferea to remove open file configurations (by parameter) and use xdg-open. Or use xdg-open as the default. This way, snap and flatpak can use that config by default. For downloading files I am not sure.

**Comment by bbhtt** [comment]
> Or use xdg-open as the default.

Alternatively I think Liferea can check if it is running under Flatpak and skip the open enclosure dialogue and execute `xdg-open`  directly.

The canonical way to check if a program is running under Flatpak is to check for `/.flatpak-info` I don't know if something similar exists for Snaps.

**Comment by lwindolf** [comment]
From project point of view Flatpak/snap are package managers (like Debian deb, or Redhat rpm). They are managed downstream and should apply patches implementing the desired behaviour.

Please raised downstream tickets with the snap/flatpak packagers.
