### ISSUE TITLE
Use a progressbar to indicate loading progress for built-in browser when previewing feed items

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#841]
Liferea has a per-feed "auto-load item link in configured browser when selecting articles" setting that can be very useful when subscribed to items listings such as on Kijiji, to be able to quickly weed through stuff that is no longer available/listed.

The problem is that it sometimes takes 3-5 seconds for the Kijiji website to respond / for the page to load, even with Javascript disabled, and the pages are very similar to each other, so you sometimes think the page loaded instantly but it just hadn't loaded yet, because liferea doesn't "clear" the browser view on feed item change.

Ideally it should reset the webkit view so that it is a blank page before loading, but also, it should make use of the GtkEntry widget used for the addressbar for that built-in browser and show loading progress with it, like Epiphany does. Specifically, GtkEntry has a native method for showing a progressbar in it, [gtk_entry_set_progress_fraction()](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-progress-fraction)

**Comment by lwindolf** [comment]
Great suggestion. 

Using the internal browser for web-stuff sometimes too I feel it lacks comfort ;-)
