### ISSUE TITLE
liferea startup fails : data disk image is malformed 

### ISSUE THREAD

**Issue by rich-coe** [lwindolf/liferea#848]
I recently was bringing up liferea on a new computer with nvme ssd.  
When I start liferea, it fails, trying to initialize the db.
If I run ````sqlite3 .local/share/liferea/liferea.db .dump````, I get the same error.
If I run ````sqlite3 .local/share/liferea/liferea.db .dump | tail````,  I do not get an error.
I moved the db file to a harddisk and soft linked the filename in .local/share/liferea as workaround.

I've googled for similar reports but I didn't find anything.

I'll open up an sqlite bug, but I wanted to warn any one facing the same issue.

**Comment by lwindolf** [comment]
Is there an actual error message indicating any reason? Could you post it?

**Comment by rich-coe** [comment]
I forgot to mention it's BTRFS on nvme sdd.
The error message was DATABASE CORRUPT or CORRUPT DATABASE.
The md5sum of the original file and the copied file were exactly the same.  I copied the db file to the slower media and did not have an issue.

**Comment by lwindolf** [comment]
Ok, that's wild. I guess this might be some to report against sqlite upstream. Because if it is reproducible with the sqlite CLI client it is not caused by Liferea. I guess the different behaviour when piping is just a race condition not triggering due to the different timing.

**Comment by rich-coe** [comment]
I copied the db back to the original location and have not had any issues since the original problem.
I cannot reproduce the issue and don't have time to track it down at the moment.
