### ISSUE TITLE
Tiny tiny RSS (1.10) sync not working with Liferea git: JSON UTF-8 BOM problem?

### ISSUE THREAD

**Issue by Zerwan** [lwindolf/liferea#85]
[Sorry for the issue titled "please delete this issue", it was made with a wrong github account, thus i had to start all over with the right one :(]

Hello,

I was having some troubles connecting Lifera to a Tiny tiny RSS server (version 1.10): nothing happened after adding the RSS source. When starting liferea with "--debug-all", the message when manually starting the sync was "Invalid JSON returned on login!", thus liferea was indeed communicating the server, but something was wrong with the JSON obtained.

To investigate, I cloned the git repo and I built liferea with some new error messages, including one to display the error of the JSON parser. The error I got from the parser was:
~~~
Erreur d'analyse : unexpected character `\357', expected value
~~~

To go further, I printed the first characters of the string of the JSON data, and I got this:
~~~
\xef\u0010\xb06\u0001
\xbb\u0010\xb06\u0001
\xbf\u0010\xb06\u0001
{\u0010\xb06\u0001
"\u0010\xb06\u0001
s\u0010\xb06\u0001
e\u0010\xb06\u0001
q\u0010\xb06\u0001
...
~~~

So the JSON string is there (starting with {"seq ), but there are three characters in front of is. I've tested with another ttrss server (1.9) that liferea can work with, and these 3 chars are not there. I think these chars are the always anoying UTF-8 BOM.

I've made very ugly adds to the code to detect this situation and remove the first 3 chars when required, and at last liferea could retrieve my ttrss feeds! Concretely, each time "json_parser_load_from_data" is called, I check and remove 3 chars, like this:

~~~C
// Copying the JSON string
gchar * my_data = g_strndup(result->data, strlen(result->data));

// Detecting if UTF8
if(g_utf8_validate (my_data,-1, NULL)) {
	// Detecting if UTF8 BOM
	if (my_data[0] == '\357') {
		g_warning("UTF-8 BOM detected!");
		// Removing the BOM
		my_data = my_data +3;
	}
}

GError *err = NULL;
parser = json_parser_new ();
if (!json_parser_load_from_data (parser, my_data, -1, &err)) {
	ttrss_source_set_login_error (source, g_strdup ("Invalid JSON returned on login!"));
	g_warning(err->message);
	...
~~~

I don't know why my ttrss server behaves like this, but I found no way to make it send nice JSON strings without these three chars. If this is the case for all 1.10 ttrss servers, maybe this is some situation liferea should take into account.

**Comment by lwindolf** [comment]
I know of no other reports so far of this issue.

**Comment by lwindolf** [comment]
Closing as won't fix.
