### ISSUE TITLE
Embedded youtube video bug

### ISSUE THREAD

**Issue by casanovagames** [lwindolf/liferea#850]
Hello, i recently began using Liferea and there's this bug that happens when you play embedded videos.

**This is how embedded youtube video look like before hitting the "play" button:**
Pretty normal.
![image](https://user-images.githubusercontent.com/48224013/86384517-3a0ef900-bc65-11ea-872d-5283e14052cb.png)

**And this is how it looks like after hitting the "play" button:**
The video just goes to the left and right and i can't see most of it, for some reason...
![image](https://user-images.githubusercontent.com/48224013/86384678-73dfff80-bc65-11ea-953e-18011f217beb.png)

This happens with all of my feeds:
![image](https://user-images.githubusercontent.com/48224013/86384848-b6a1d780-bc65-11ea-9b78-a46685cefb1e.png)

**Comment by lwindolf** [comment]
Reproduced. Probably is CSS fit-to-screen width caused with the complex ultra-100000-level-deep-nested-embed done by Youtube Javascript

**Comment by sblondon** [comment]
In case it helps, there is the same offset on video from vimeo too. However, the iframe is moved when the mouse is on hover the video (so before the user clicks on 'play' button).
Currently, it's visible with 'Art Piece Builds Up Images with Dots on Thread' post from [hackaday feed](https://hackaday.com/feed/).

```html
<div class="embed-vimeo" style="text-align: center;">
<iframe src="https://player.vimeo.com/video/431334666" width="800" height="480" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>
```

Seen with liferea 1.13.0, packaged in Debian.

**Comment by sblondon** [comment]
I can still stop the video in the previous area so the offset for displaying the video is not done for the control.
After stopping the video, liferea does not work properly. For example:
 - I can't display another post from the same feed
 - I can select another feed, click on a post title but the post is not displayed

**Comment by mikelolasagasti** [comment]
Same thing happens if MediaRSS videos are embedded (PR https://github.com/lwindolf/liferea/pull/765)

**Comment by lwindolf** [comment]
@mikelolasagasti Also happens with pure HTML embeds. I changed the CSS to remove "object-fit" which normally is a good choice, but fails with Youtubes insane element nesting.
