### ISSUE TITLE
Please add key-shortcut for attachment Save As

### ISSUE THREAD

**Issue by BillDietrich** [lwindolf/liferea#852]
Highlight an item in a feed, go to the list of attachments, right-click on an attachment, see context menu.  But there is no key-shortcut for the Save As menu item.  Please add a shortcut, either S or V.  Thanks.

Liferea 1.12.7 deb on Ubuntu GNOME 20.04

**Comment by lwindolf** [comment]
Having a shortcut would not solve the issue of having to select an attachment first. I'm not sure about this.

**Comment by BillDietrich** [comment]
Well, maybe it needs a couple of steps:
- a menu item (with key-shortcut) View / Attachments that takes you to the list of attachments for an item
- arrow keys work in the list of attachments so you can select an attachment
- a key-shortcut for SaveAs for the currently selected attachment

**Comment by lwindolf** [comment]
Sorry, I'm barely keeping the project alive. I wish I'd have the time to spend on this.

Please consider contributing!!!

**Comment by BillDietrich** [comment]
Please leave the issue open.  Maybe someone will implement it someday.  Or want to add their info to the request.

**Comment by BillDietrich** [comment]
The UI flow I would like to see:
- user selects an item in a feed
- user selects NEW menu item called "Item / Show Attachments (shortcut Ctrl+H)"
- NEW: attachment list for item is expanded and first attachment is selected
- user can use up or down arrow keys to move to previous or next attachment in the list
- user can right-click on attachment and select "Save As", or just type NEW shortcut Ctrl+S to save current attachment

So there would be three changes:
- a new menu item Show Attachments in the Item menu
- when that menu item is invoked expand the attachment list and select first attachment
- a new shortcut for Save As in the attachment context menu.

Please give feedback.  Thanks.
