### ISSUE TITLE
Autostart, notification options, and filters?

### ISSUE THREAD

**Issue by dairefagan** [lwindolf/liferea#853]
I have seen mention in the FAQ of individual notification options in individual feed preferences but the same checkboxes are not visible on my install. Is it possible to configure a custom sound for notifications? I would like to set a long ringtone to ensure I do not miss updates - I use RSS for something very specific.

Is the best way to autostart by adding a startup command in Ubuntu 18.04 for liferea %U?

Is there a way to filter updates by certain strings, say %string%, or %string1 string2% etc?

**Comment by lwindolf** [comment]
Per-feed notification: there is currently no feature to override notifications per-feed. Where in the FAQ did you find this? If there is such a mention it needs to be corrected. Also there is currently no way to have custom sounds. I think this is not possible at all when using libnotify

autostart: Yes, I consider this the right way for Ubuntu

filter updates: You can use so called "search folders" and add string matching rules on headline titles or content. When choosing "match all" rules you can combine this with "item is unread" rule to filter for new items only.

**Comment by lwindolf** [comment]
HTH. Closing this issue. Feel free to follow up on this though using this ticket.
