### ISSUE TITLE
More powerful search folders, filter by folder name and source

### ISSUE THREAD

**Issue by muhlinux** [lwindolf/liferea#854]
The search folders could be so much more powerful with a couple of extra filters:

- folder name -  Filters based on grouped items
- source -  Filters based on source URL (not feed title)

The reason I would like the `Source` one in particular is because I subscribe to quite a lot of YouTube feeds which clutters up my `Unread`. In cases Like this it would be beneficial to be able to create a filter like so:

`source` - `does not contain` - `youtube.com`
`read status` - `is unread`

Thank you for considering.

**Comment by lwindolf** [comment]
Good suggestion. As it this feature request has quite low complexity I've added an implementation.

Please note though that the folder match works only on title and only on title of the direct parent folder. This allows for constant execution time.
