### ISSUE TITLE
One request & one issue

### ISSUE THREAD

**Issue by Renegade-Apprentice** [lwindolf/liferea#855]
Issue: When I click on a feed to open in an external browser, a youtube video for example, I can hear the video playing, but can't see the external browser. Since it opens up in auto play, videos keep playing, but since I can't see it, I can't turn it off. I have to restart my laptop to get it to stop. This happens whether I have a browser open or not.

Request: On my feeds, is there a way to show the author of each feed? Other RSS feeders that I've used, allow for that function, but I can't see a way to show it with your feeder.

Thank You kindly,
Dennis

Just in case you need additional info, I'm using your feeder with Linux 19.2 Tina, 64 bit, Mate on a 2000 HP laptop.

**Comment by lwindolf** [comment]
About your first issue (next time please create 2 tickets!): which external browser setting do you have configured?

On the 2nd issue: do you have an example feed URI where the author is not shown? Because Liferea supports rendering the author information.
