### ISSUE TITLE
Main screen bar not translated in Spanish

### ISSUE THREAD

**Issue by nesfla** [lwindolf/liferea#864]
I install Liferea in linux mint MATE 20 and the main screen bar can't be set in Spanish although the Preference screen yes (but not completely done).
I went to the Translation github page and ut seems that the whole translation was just done.
![LifereaMainScreen](https://user-images.githubusercontent.com/11008671/91082401-ff02c380-e61e-11ea-9a1e-30aea5dc3d8d.png)
![LifereaPreferenceScreen](https://user-images.githubusercontent.com/11008671/91082418-02964a80-e61f-11ea-98ce-e6d4ebb71458.png)

**Comment by lwindolf** [comment]
@nesfla Which version do you use?

**Comment by nesfla** [comment]
1.12.7
which is the one available in linux mint 20 apps center

Néstor

**Comment by lwindolf** [comment]
Reproduced with other locales too.

**Comment by nesfla** [comment]
Maybe I don't understand your point but other apps doesn't have this issue

Néstor

**Comment by lwindolf** [comment]
@nesfla First thing done on a bug report is confirming it. Above I wanted to say, that I confirmed it on my setup. 

So your report is absolutely justified.

**Comment by Skif-off** [comment]
@nesfla 
Update Liferea from Groovy (download and install deb-files manually):
https://packages.ubuntu.com/groovy/liferea
https://packages.ubuntu.com/groovy/liferea-data
Current version of this packages are 1.13.1-1 and this version works on Xubuntu 20.04.

**Comment by lwindolf** [comment]
Fix was released with 1.12.9

**Comment by nesfla** [comment]
Ok, thanks for the support!

Néstor
