### ISSUE TITLE
1.13.2 tar bal: doc/html/reference_de.html not valid UTF-8

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#866]
I'm working on packaging liferea 1.13.2 for Debian as was warned by our lint tool lintian that reference_de.html isn't valid UTF-8. Indeed on inspection I can see that. However, the file in the tar ball doesn't seem to be in sync with the shipped file in doc/html/reference_de.html. I didn't spot where the source of that file for the tar ball lives, otherwise I would have provided a pull request.

```
Abspielen des nXchsten Audio/Video-Anhanges.
```

**Comment by lwindolf** [comment]
Fixed in master.

    $ file doc/html/reference_de.html 
    doc/html/reference_de.html: HTML document, ASCII text
