### ISSUE TITLE
problem with rss feed

### ISSUE THREAD

**Issue by cheese1** [lwindolf/liferea#867]
hi

i get errors while reading:
https://security.netapp.com/advisory/index.xml

i get:
> There were errors while parsing this feed!
> Details
> Could not detect the type of this feed! Please check if the source really points to a resource provided in one of the supported syndication formats!
> 
> XML Parser Output:
> Source points to HTML document.

adding "xmllint --recover -" did not help
how would i debug that?

ps.: the feed is quite huge

**Comment by cheese1** [comment]
Feeder under android parses that feed without problems

**Comment by Leiaz** [comment]
Huge indeed. It is 22M, and it chokes the libxml parser with `internal error: Huge input lookup`. libxml as a `XML_PARSE_HUGE` option but I don't see how to pass it to the SAX parser ...

**Comment by cheese1** [comment]
by reducing the file size i was able to read the feed.
i used a filter to remove empty lines and spaces/tabs at the start of lines
` sed -e 's/^\s*//' -e '/^$/d' `

seems to solve at least my problem

**Comment by lwindolf** [comment]
Having this feed in my test case set I noticed it suddenly working. I think at latest after the Ubuntu 22.04 upgrade. So I guess some limits in libxml2 might have become bigger (or the feed smaller).

@cheese1 Closing this as it is an old ticket (and works now).
