### ISSUE TITLE
privacy issue: can the new youtube auto viewer be disabled in the preferences?

### ISSUE THREAD

**Issue by paulgevers** [lwindolf/liferea#868]
It would be great if the new automatic renderer of youtube video can be disabled. There is already a privacy tab in the preferences, maybe add a second question there?

**Comment by lwindolf** [comment]
Feature-wise the HTML5 extraction itself can be enabled/disabled. 

Right now the HTML5 extraction is an opt-in feature (per-feed). There probably will be a global opt-in preference too.

Right now I tend to say it might be better to mark this a comfort vs. privacy tradeoff feature that privacy sensitive users should not use. 

There is the ethical dimension too. Using this feature will take away ad and page impressions from the websites. So IMO this needs to be a conscious choice taken by each end-user. The same way you decide to switch to reader mode in Firefox/Chrome/Safari/...

**Comment by paulgevers** [comment]
If I understand correctly the only thing I remain to want/need to fix this issue is that this is more clear in the "Extract full content from HTML5 and Google AMP" option?

**Comment by lwindolf** [comment]
@paulgevers Yes, I believe so. And at the same time I have no idea yet how to make this clear. After all this is almost like describing the features/behaviours of readability.js

On the other hand I guess most users are familiar with "Reader Mode" in Firefox/Chrome/... and referring to this might give them an impression of the behaviour to be expected.

Let's leave this ticket open until the GUI elements are finalized and you can once more review them!

**Comment by lwindolf** [comment]
Can be re-reviewed now...

**Comment by lwindolf** [comment]
@paulgevers I plan to change the implementation of the Youtube embed to this

- per default only the thumb nail is embedded (with a play button above)
- when hovering a text hint is shown like "click to embed Youtube player"
- when clicking on the play button the thumb is replaced with the actual embed

So it becomes a conscious choice. Is this ok from your perspective?

Complexity wise I'd like to avoid having a new preference. I'd like to have sane defaults instead.

**Comment by paulgevers** [comment]
I think this is sensible.

**Comment by lwindolf** [comment]
First implementation is done. It is not yet perfect (e.g. autoplay missing).

**Comment by lwindolf** [comment]
Autoplay in Webkit does not seem to be possible.

**Comment by lwindolf** [comment]
Solution provided with 1.14.0: embed on user click only

**Comment by paulgevers** [comment]
Thank you.
