### ISSUE TITLE
URL resolving wrong if base tag involved

### ISSUE THREAD

**Issue by DanMan** [lwindolf/liferea#87]
It seems that if you point Liferea to a HTML page that contains a link element which points to a news feed, it extracts the actual feed's URL from there. If not, ignore this ticket.

It doesn't work right, if the feed URL referenced in the link element is relative and the HTML document also contains a base tag. It's interpreting the feed URL relatively to whatever page you're currently on, instead of using the URL from the base tag. Resulting in a wrong final URL in the client.

**Comment by lwindolf** [comment]
@DanMan: Do you mean the following scenario?

1.) Open webpage in internal browser that has a relative feed link in it
2.) Right click on link to subscribe

**Comment by DanMan** [comment]
No, I meant adding a new feed via the usual dialog, providing a URL to a HTML page with a link element in it pointing to the actual feed.

**Comment by lwindolf** [comment]
I see, I understand your use case now.

The current tag soup parsing for extracting <link> tags doesn't try to get <base> tags at all. And so far it was not necessary, IIRC this is the first report about this being an issue.

**Comment by lwindolf** [comment]
@mozbugbox implemented a solution with #174

**Comment by DanMan** [comment]
This didn't fix it for me, it kinda made it worse because once Liferea is done, it replaces the feed URL I used with a wrong one in the settings. Example:

Let's say the URL is `http://www.homepage.com/de/blog` for both the HTML page and Atom feed, depending on the HTTP `Accept` header. Let's also say the HTML has a `base` tag that points to `http://www.homepage.com/` and the it contains a `link` element with the `application/atom+xml` `type` attribute.

Once the URL auto detection is done, the URL in the settings of the feed will read `http://www.homepage.com/en/blog`, if the `href` was absolute, or `http://www.homepage.com/de/en/blog`, if it was a relative URL or the feed doesn't have a `self` link in it.

Even if the original URL serves an Atom feed _only_ (no HTML), I get a parse error saying it couldn't determine the feed type. HTTP content-type header was set to `application/atom+xml` though. The feed itself must be valid XML because it works, if I import it from a file.

So something's going wrong in this combination.
