### ISSUE TITLE
Youtube channel feeds broken in liferea 1.13.2

### ISSUE THREAD

**Issue by ao2** [lwindolf/liferea#872]
Hi,

I noticed that items of Youtube feeds are not showed correctly anymore in liferea 1.13.2, I cannot see any of the MediaRSS info, like thumbnails and descriptions.

Here is an example feed:
https://www.youtube.com/feeds/videos.xml?channel_id=UCAzKFALPuF_EPe-AEI0WFFw

I am using the Debian packages and I experience the issue with the 1.13.2-1 package, the problem goes away if I downgrade to the 1.13.1-1 package.

I thought it was unlikely that the issue was specific to Debian so I am reporting it here, if I am wrong and you cannot reproduce it please let me know and I will report it to Debian.

Thanks,
Antonio

/cc @mikelolasagasti

**Comment by mikelolasagasti** [comment]
@ao2 I compiled Liferea master and I have no issues with you feed.

![image](https://user-images.githubusercontent.com/773148/92253823-4830fe00-eed0-11ea-86a5-fa16fd04ca0d.png)

Can you provide a screenshot?

**Comment by ao2** [comment]
Thanks a lot for checking @mikelolasagasti the master branch works fine indeed, but the issue is there if  compile the 1.13.2 tag.

Anyway it has been fixed in commit ff354eee64af0c1229fbde25597d8ccdce1b2353 so I am closing the issue here, sorry for the noise and thanks again for taking the time, it's appreciated.

I will report to Debian that there is a fix available.

Ciao, Antonio
