### ISSUE TITLE
[Request] Socks Proxy Support.

### ISSUE THREAD

**Issue by snakyjake1** [lwindolf/liferea#877]

**Comment by lwindolf** [comment]
https://lzone.de/liferea/blog/Liferea-Trick-5-Privacy-with-a-SOCKS-Proxy.html

**Comment by lwindolf** [comment]
@m3thm4th I may misinterpret your comment... how I read it it conveys a sense of entitlement for such a feature. Just saying there is no such entitlement. And suggesting to support arbitrary desktop environments is quite a number.

On the technical side: Liferea uses libsoup which does proxy detection via libproxy. Not having an option in Liferea was a design decision to actually account for your use case. Because with desktop environments standardizing on libproxy a SOCKS setting can automatically propagate into the application.

**Comment by lwindolf** [comment]
> > how I read it it conveys a sense of entitlement for such a feature
> 
> @lwindolf I have no idea how could you possibly read entitlement into what I wrote, I simply underlined the fact that the feature is very important, it's ever-present in all applications' network settings except this one's.

Well then I'm probably just very confused.

> > support arbitrary desktop environments is quite a number
> 
> indeed, that's why it makes little sense to only support Gnome's integrated network manager, while adding Socks proxy in settings would be useful for all users no matter what DE they use.
> 
> I was trying to connect to the Tor network, it usually boils down to adding a Socks proxy for localhost and Tor port, very easy and straightforward, but liferea does not allow such usage, I'm sure there are workarounds, but I fail to see what the issue is having the option to use a Socks proxy instead of HTTP.

I understand that you very politely fail to see the issue and I'm very sorry that I fail to convey the issue to you.

/s

**Comment by bbhtt** [comment]
From a cursory look, the network library liferea uses - libsoup, uses libproxy through glib-networking.

And looks like libproxy supports reading the proxy environment variables https://github.com/libproxy/libproxy/blob/cced536217f3a146d0d688c3ca40eab8eea528b9/src/backend/plugins/config-env/config-env.c#L131

So something line `http_proxy=socks5:://<address>:<port>` should work on Liferea too when in a non-GNOME desktop (unless I'm missing something)

Did you try?

**Comment by bbhtt** [comment]
> From a cursory look, the network library liferea uses - libsoup, uses libproxy through glib-networking.
> 
> And looks like libproxy supports reading the proxy environment variables https://github.com/libproxy/libproxy/blob/cced536217f3a146d0d688c3ca40eab8eea528b9/src/backend/plugins/config-env/config-env.c#L131
> 
> So something line `http_proxy=socks5:://<address>:<port>`, `https_proxy=socks5:://<address>:<port>` should work on Liferea too when in a non-GNOME desktop (unless I'm missing something)
> 
> Did you try?

> but I fail to see what the issue is having the option to use a Socks proxy instead of HTTP.

The current issue is that there isn't a standard way to know proxy settings for programs. liboroxy is supposed to be the solution to this problem. It implements different backends for GNOME/KDE/Networkmanager/env vars to get the proxy settings.

The other option is to have the program implement a bunch of different backends to get it to work cross desktop which isn't very nice/maintainable.
