### ISSUE TITLE
Feed with comments : last comment replaces all content

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#883]
This may be due to Readability.js. The feed is displayed correctly with c680b8e204282236dc21e08624d8, I didn't bisect though. I have (external now) javascript disabled.

Using master, when viewing https://www.pine64.org/feed/ the content of the article which is usually a summary of the blog item is completely replaced by the latest comment.

**Comment by lwindolf** [comment]
Ah yes, the comments are included in the <div id="content"> that is input to Readability. The XSLT stylesheet could to be changed to exclude the comments from Readability.js by placing them outside of <div id="content">
