### ISSUE TITLE
Refactor new item id generation

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#887]
Comment copied from #885

I think the actual root cause of #884 lies in this line from src/db.c

    sql = sqlite3_mprintf ("SELECT MAX(item_id) FROM items");

Which is a bad practice DB schema-wise. A better solution is to have an ever-increasing id (of course leading to overflow in the long term). Something like having a static "last_new_item_id" in src/db.c which is initialized on startup with said "SELECT MAX..." statement and only ever increased afterwards.

**Comment by Leiaz** [comment]
Why not just let Sqlite create the id ? The item_id column being an integer primary key, it is an alias for the sqlite rowid column. If we indicate a null value on inserting an item, sqlite should fill it with a rowid according to the algorithm described [here](https://sqlite.org/autoinc.html) (increasing, and then random when max is reached) ?

**Comment by lwindolf** [comment]
@Leiaz You are right, that's what an RDBMS is for taking care of keys. I was reinventing a wheel :-)
