### ISSUE TITLE
Error building v1.3.3

### ISSUE THREAD

**Issue by PandaJim** [lwindolf/liferea#896]
gla11y -s debian/gla11y-suppression glade/*.ui
glade/prefs.ui: FATAL ERROR: 'GtkCheckButton' 'itpbtn' has labelled-by, but is not label-for by 'GtkLabel' 'itpbtn_label' 
glade/prefs.ui: WARNING: 'GtkLabel' 'itpbtn_label' does not specify what it labels within 'GtkNotebook' 'notebook1' 
glade/prefs.ui: WARNING: 'GtkLabel' does not specify what it labels within 'GtkNotebook' 'notebook1' 
1 new error
2 new warnings (26 suppressed by debian/gla11y-suppression, please fix them, see https://github.com/hypra/gla11y/blob/master/HOWTO.md)
1 new fatal
4 suppressions unused:
debian/gla11y-suppression:24: glade/prefs.ui://GtkComboBox[@id='downloadToolCombo'] no-labelled-by
debian/gla11y-suppression:25: glade/properties.ui://GtkSpinButton[@id='refreshIntervalSpinButton'] no-labelled-by
debian/gla11y-suppression:26: glade/properties.ui://GtkComboBox[@id='refreshIntervalUnitComboBox'] no-labelled-by
debian/gla11y-suppression:33: glade/properties.ui://GtkSpinButton[@id='cacheItemLimit'] no-labelled-by
Explanations are available on https://github.com/hypra/gla11y/blob/master/HOWTO.md
make[1]: *** [debian/rules:51: override_dh_auto_test] Error 1
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:13: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
--------------------------------------------------------------------------------

**Comment by Leiaz** [comment]
That stray labelled-by was my fault. I tried fixing some other warnings too. I'll look at the remaining warnings, probably described-by should be used for the non mnemonic explanation labels ...
