### ISSUE TITLE
[Flatpak] icon is missing within GNOME Desktop

### ISSUE THREAD

**Issue by antistress** [lwindolf/liferea#897]
Hi,
I'm using the brand new flatpak version (thank you for it !)
Here is the bug I face :
I set Liferea 1°) to display toolbar and 2°) so that my vertical space is divided into two equal parts, with the internal browser at the bottom.
Each time I close Liferea, I have to re-set Liferea because toolbar is not displayed and internal browser is hidden at the bottom of the screen.
Thanks !

**Comment by antistress** [comment]
Also icon is missing within GNOME Desktop (Activities Overview mode and dash). Do you want me to fill a separate bug for that ?

**Comment by mikelolasagasti** [comment]
@antistress I'm able to show/hide toolbar and change views correctly after exiting Liferea flatpak. 

Can you check with something more simple like the "Default number of items per feed to save"? The default is 100, change it to 99 or 101 for example (`Tools` -> `Preferences`), close Liferea (<kbd>Ctrl</kbd>+ <kbd>Q</kbd> or `Subscriptions` -> `Quit`) and open again.

If it doesn't work, can you describe what platform are you using? It is working fine for me on Fedora 32 both Flathub build and local build.

About the icons, I submitted a patch to Flathub and next version should work fine. Build is ready but I don't know when it will published. Can you check when update is available for you?

@lwindolf I'll submit the patch as PR if @antistress can confirm icons are working in next update.

**Comment by mikelolasagasti** [comment]
@antistress build can be tested manually with:

    flatpak install --user  https://dl.flathub.org/build-repo/29172/net.sourceforge.liferea.flatpakref

**Comment by antistress** [comment]
> Can you check with something more simple like the "Default number of items per feed to save"? The default is 100, change it to 99 or 101 for example (`Tools` -> `Preferences`), close Liferea (Ctrl+ Q or `Subscriptions` -> `Quit`) and open again.

interesting.
I changed for 99 and 101 and the setting is saved.

But not for display toolbar of the size of the internal browser

Since it's about flatpak I don't think that the ref of the platform is important, but here it is :

Debian Testing 64 bits with Gnome 
~$ gnome-shell --version
GNOME Shell 3.38.0
~$ uname -a
Linux HAL 5.8.0-2-amd64 #1 SMP Debian 5.8.10-1 (2020-09-19) x86_64 GNU/Linux
~$ dpkg -s flatpak | grep ^Version
Version: 1.8.2-1
~$ dpkg -s libgtk-3-0 | grep ^Version
Version: 3.24.23-2

About my flatpak installation :
~$ flatpak list --runtime
Name                                     Application ID                                       Version   Branch  Origin        Installation
Locale                                   com.github.unrud.VideoDownloader.Locale                        stable  flathub       system
Locale                                   com.transmissionbt.Transmission.Locale                         stable  flathub       system
Locale                                   net.sourceforge.liferea.Locale                                 stable  flathub       system
Codecs                                   org.audacityteam.Audacity.Codecs                               stable  flathub       system
Locale                                   org.audacityteam.Audacity.Locale                               stable  flathub       system
Locale                                   org.filezillaproject.Filezilla.Locale                          stable  flathub       system
Freedesktop Platform                     org.freedesktop.Platform                             19.08.12  19.08   flathub       system
Freedesktop Platform                     org.freedesktop.Platform                             20.08.0   20.08   flathub       system
default                                  org.freedesktop.Platform.GL.default                            19.08   flathub       system
default                                  org.freedesktop.Platform.GL.default                            20.08   flathub       system
Intel                                    org.freedesktop.Platform.VAAPI.Intel                           19.08   flathub       system
Intel                                    org.freedesktop.Platform.VAAPI.Intel                           20.08   flathub       system
ffmpeg-full                              org.freedesktop.Platform.ffmpeg-full                           19.08   flathub       system
openh264                                 org.freedesktop.Platform.openh264                    2.1.0     2.0     flathub       system
Manual                                   org.gimp.GIMP.Manual                                           2.10    flathub       system
Locale                                   org.gnome.DejaDup.Locale                                       stable  flathub       system
Locale                                   org.gnome.Extensions.Locale                                    stable  flathub       system
GNOME Application Platform version 3.36  org.gnome.Platform                                             3.36    flathub       system
GNOME Application Platform version 3.38  org.gnome.Platform                                             3.38    flathub       system
Locale                                   org.gnome.Shotwell.Locale                                      stable  flathub       system
Locale                                   org.gnome.gitlab.YaLTeR.VideoTrimmer.Locale                    stable  flathub       system
Adwaita theme                            org.kde.KStyle.Adwaita                                         5.14    flathub       system
Adwaita theme                            org.kde.KStyle.Adwaita                                         5.15    flathub       system
KDE Application Platform                 org.kde.Platform                                               5.14    flathub       system
KDE Application Platform                 org.kde.Platform                                               5.15    flathub       system
QGnomePlatform                           org.kde.PlatformTheme.QGnomePlatform                           5.14    flathub       system
QGnomePlatform                           org.kde.PlatformTheme.QGnomePlatform                           5.15    flathub       system
QtSNI                                    org.kde.PlatformTheme.QtSNI                                    5.14    flathub       system
QtSNI                                    org.kde.PlatformTheme.QtSNI                                    5.15    flathub       system
QGnomePlatform-decoration                org.kde.WaylandDecoration.QGnomePlatform-decoration            5.14    flathub       system
QGnomePlatform-decoration                org.kde.WaylandDecoration.QGnomePlatform-decoration            5.15    flathub       system
Locale                                   org.libreoffice.LibreOffice.Locale                             stable  flathub       system
Locale                                   org.mozilla.Thunderbird.Locale                                 stable  flathub       system
Locale                                   org.mozilla.firefox.Locale                                     beta    flathub-beta  system
Codecs                                   org.pitivi.Pitivi.Codecs                                       stable  flathub       system
Locale                                   org.pitivi.Pitivi.Locale                                       stable  flathub       system
Locale                                   org.videolan.VLC.Locale                                        stable  flathub       system

**Comment by antistress** [comment]
> @antistress build can be tested manually with:
> 
> ```
> flatpak install --user  https://dl.flathub.org/build-repo/29172/net.sourceforge.liferea.flatpakref
> ```

Have I the choice between waiting for the update and that command ?
if that's the case I'd rather wait for the update
Thanks

**Comment by antistress** [comment]
> @antistress I'm able to show/hide toolbar and change views correctly after exiting Liferea flatpak.

I suppose you did the test with TrayIcon plugin deactivated ?

**Comment by antistress** [comment]
About the toolbar, the situation is weirder than announced since when Liferea is started, toolbar is not displayed AND "hide the toolbar" setting is not activated.
I have 1st to tick and then untick the setting to get the toolbar back

**Comment by antistress** [comment]
(I could make a screencast if needed)

**Comment by Leiaz** [comment]
@antistress You are using the Header bar plugin ? That plugin hides the toolbar, because the guidelines for the headerbar is that it is supposed to replace toolbars and menus. See #744

**Comment by antistress** [comment]
> You are using the Header bar plugin ?

Yes, that was the cause, nice point.

Therefore this bug is only about the vertical space division between titles and content page not being saved

**Comment by antistress** [comment]
(also the icon bug is now solved, thanks !)

**Comment by Leiaz** [comment]
That is not a Flatpak issue either. If the default max items value is saved, then this value is saved too. This is a duplicate of #901.

**Comment by antistress** [comment]
Ok, thanks !

**Comment by nekohayo** [comment]
Since this is a duplicate of issues #744 and #901, nothing remains to be done here, this ticket should be closed. #744 should probably be renamed for clarity too.

**Comment by antistress** [comment]
Finally the issue that have been adressed is icon missing within GNOME Desktop.
Title changed and bug is closed
