### ISSUE TITLE
Truncated articles

### ISSUE THREAD

**Issue by Leiaz** [lwindolf/liferea#899]
Some articles have missing paragraphs when viewed in Liferea.
I noticed this mostly for articles downloaded with the "Extract full content" option. The full page with the missing parts are in the database.

It happens with articles from https://www.lemonde.fr/rss/une.xml like this one [Le prix Nobel d’économie attribué aux Américains Paul Milgrom et Robert Wilson ...](https://www.lemonde.fr/economie/article/2020/10/12/le-prix-nobel-d-economie-attribue-aux-americains-paul-milgrom-et-robert-wilson-pour-leurs-travaux-sur-la-theorie-des-encheres_6055723_3234.html) In Liferea I only see the first two paragraphs.

I also saw it happen with some articles from https://www.francetvinfo.fr/titres.rss
This one : [Le prix Nobel d'économie est décerné aux Américains Paul Milgrom et Robert Wilson, spécialistes de la théorie des enchères](https://www.francetvinfo.fr/monde/prix-nobel/le-prix-nobel-d-economie-est-decerne-aux-americains-paul-milgrom-et-robert-wilson-specialistes-de-la-theorie-des-encheres_4138587.html#xtor=RSS-3-[lestitres]) In Liferea I only see up to the first tweet (included).

**Comment by lwindolf** [comment]
I can also reproduce this. And the same viewed in Firefox reader mode does show much more.

**Comment by lwindolf** [comment]
I found that the base64 encoded article passed to the HTML view already does not contain the other paragraphs. This rules out the Readability.js handling as cause. The actual cause might be earlier during the libxml2 HTML sanitation handling for example.

**Comment by lwindolf** [comment]
Seems like an HTML5 to XML to HTML conversion issue.

A tag structure that is originally

     <article>
          <p>....</p>
          <p>....</p>
          <div and some attributes></div>
          <p>....</p>
     </article>

is correctly converted to XML

     <article>
          <p>....</p>
          <p>....</p>
          <div and some attributes/>      <--- note the XML close
          <p>....</p>
     </article>

and incorrectly converted back


     <article>
          <p>....</p>
          <p>....</p>
          <div and some attributes>
              <p>....</p>
          </div>
     </article>

Which leads to Readability correctly ignoring the non-semantic <div> enclosed <p>'s and the difference to the reader mode display of the same page e.g. in Firefox.

**Comment by lwindolf** [comment]
Sorry accidentally pushed master, instead of creating a PR. Can you nonetheless please review/retest the solution? Thanks!!!

**Comment by Leiaz** [comment]
Good idea, but it doesn't solve the issue.

Here are two more articles from the same feeds : 
[On franceinfo, only up to the first tweet like the previous one](https://www.francetvinfo.fr/politique/emmanuel-macron/pourquoi-lenseignement-de-l-arabe-a-l-ecole-est-il-si-polemique_4133389.html#xtor=RSS-3-[lestitres])
[This one from Le Monde, this time stops one paragraph after the "Question existentielle" title](https://www.lemonde.fr/le-monde-evenements/article/2020/10/15/le-petrole-a-t-il-amorce-un-lent-declin_6056088_4333359.html)

**Comment by lwindolf** [comment]
I found out that while I fixed empty HTML tags "<div></div>" I did not account for empty XHTML tags "<div/>" (when the website source is XHTML). 

So use case HTML -> XHTML -> HTML was quite working, but XHTML -> XHTML -> HTML conversion does not yet work properly.

I'm also thinking about dropping the proposed solution in favour of a proper XSLT stylesheet that applies the logic and can strip empty tags, unwanted elements as scripts and maybe even attributes.

**Comment by lwindolf** [comment]
@Leiaz I reimplemented the handling in XSLT which should cover all the cases described above. I also added more test cases to cover those cases.

Please retest if you have the time!

BTW totally off-topic, I was wondering if you care for contributions attributed by your full name and mail. So far ChangeLog and AUTHORS only has "Leiaz". What do you prefer?

**Comment by Leiaz** [comment]
The fact that it doesn't happen with all articles and that it is extraction that was fixed make it a bit tricky to test, but I found two new articles that are bugged with the old extraction code and full with the new, so yes it works now :+1: 

I don't mind either way for the name. For the mail, my newer one `@mailbox.org` would be better. I keep the other too, but it is not so reliable ... the forgotten password system basically send the password back in plaintext, to the very address you lost the password of, if that was your "contact" address, despite clicking the link while logged in the subscriber page (different password) ... and some months back after failing to connect for a few days, it belched back some unread mailing lists emails from 2012 ...
