### ISSUE TITLE
Consider temporarily halving the transparency of the container holding the webkit view widget while loading?

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#905]
Thank you for the progressbar in #841, it already feels better now that 1.13.3 arrived in my Fedora package updates :)

Since Liferea still doesn't "blank" the webkit view while loading from one page to another though, here's a crazy suggestion for that, which could be an interesting middle-ground (less jarring than a full blank, but also makes it visually clear that the page is not yet ready for reading): until WebKit is ready to replace the previously shown page, use gtk_widget_set_opacity(0.25) (I thought of 50% at first, but 25% seems nicer on my end) on the LifereaWebView widget, until the page is ready to replace the previously displayed content, at which point it can be reset to 1.0 opacity.

It would probably look roughly like this while loading, from what I was able to simulate with the GTK Inspector, at 25% opacity:

![Screenshot from 2020-10-29 16-34-01](https://user-images.githubusercontent.com/479401/97629507-9a8c2800-1a04-11eb-9de7-30bbe64b1aad.png)

And then, when fully loaded (disregard the fact that it's still the same page in my screenshot ;) :

![Screenshot from 2020-10-29 16-31-46](https://user-images.githubusercontent.com/479401/97629329-56008c80-1a04-11eb-8bee-80c6e25e1f7c.png)

Not a dealbreaker "absolute must have" feature, just an idea of something that could potentially make things even clearer visually.

**Comment by lwindolf** [comment]
Nice and simple idea.

**Comment by lwindolf** [comment]
I liked the idea, but testing it I found it not to be suitable. At least not for the load-changed signal exposed by Webkits Webview object (https://webkitgtk.org/reference/webkit2gtk/1.7.5/WebKitWebView.html#WebKitWebView-load-changed).

When hooking the reset of the opacity to WEBKIT_LOAD_COMMITTED the reset comes to early before the first paint of webpage that hides the old one. So the opacity is gone 1-2 seconds (on fast connection) before the actual page loads.

Therefore I fear that's not as easy to do. A more complex hooking to DOM events might work, but would blow up the code complexity.
