### ISSUE TITLE
Ability to limit a search folder to a specific feed (by choosing the feed) as a pre-filtering mechanism

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#906]
I'm just making a guess here as I don't know how Liferea works behind the scenes, but I think it would make a lot of sense if, in the search folder properties dialog, you could specify first what feed(s) to limit the search to, separately from the rest of the matching conditions/logic.

Being able to tell it to limit the search to a specific feed, where you can pick and choose the feed from the list provided by Liferea, would probably greatly increase performance, since it wouldn't have to search all the feeds (or to apply the search to every feed during a feed update), it could skip 99.9% of the search domain.

**Comment by lwindolf** [comment]
I believe this feature was recently contributed. You can now add search folder rules selecting a feed title or feed source URL.

I believe this roughly covers your use case.

What's missing though is a user-friendly feed title combo box solution. But for simplicity sake I'd like to avoid implementing it.
