### ISSUE TITLE
Ability to show only the unread items of a search folder (or folder of subfolders)

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#907]
I use a dozen "search folders" to weed out all the noise/crap from my news, for example with search terms that match all the crazy politics going on in the USA and UK, or related to certain events like a plane crash, or anything related to web technologies or GAFAM (because I only care about FLOSS desktop news). I then use those to quickly mark as read all the noise (search results) so that I can focus on reading the signal.

The problem is that this is currently quite hard to achieve with Liferea 1.13.x. The difficulty I experience is a combination of factors:
* Most of those searches are using "OR" (any) conditions (instead of "and", a.k.a. "all these conditions must match", conditions), which means I can't tell Liferea to use "status is unread" as a condition...
* in Liferea 1.13.x, unlike in 1.12.x and older, if you sort a feed by items status (instead of by date), when you click on a feed item to mark it as read, the item instantly gets re-sorted so your scrollbar jumps with it way down the list (it didn't use to do that before) and then you've lost your position and need to scroll all the way back up to mark the next unread item as read.
* As explained in issue #728, folders containing search folders do not show ("on purpose") the content of the children search folders, so unlike regular feeds inside a folder, I can't simply use the folder and the "Hide read items" global folder preference to show the unread items of the (sub) search folders.

Result: I have no easy way to quickly go through the "unread items in various search folders" to mark them as read.

Potential solutions:
* Not immediately resorting the feed items by status when a status changes (like Liferea <= 1.12.x used to do)
* Allowing folders to show the children unread items of the search folders it contains (somehow solving issue #728)
* Making it so that the search syntax allows treating the read status as a completely separate logic group, i.e. expose that as a simple "Only show unread items" checkbox at the bottom of the search folder's properties, instead of treating that only as a regular search condition. Bonus point if there could be another special setting in that search parameters dialog to tell it to limit the search to a specific feed (issue #906).

**Comment by lwindolf** [comment]
I implemented a solution that

- adds a new search folder property to hide read items
- improves the search folder property dialog somewhat
- switches to showing the unread count for search folders

There is some performance risk with showing the unread count as it uses a SQL join between the search folder and the item tables. I this causes problems for large DBs I might have to revert it...
