### ISSUE TITLE
Searches are case-sensitive, unlike what the documentation / user manual says

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#908]
http://lzone.de/liferea/help110/searching_en.html says that everything in the table (such as the "item title does contain" rule) is case **in**sensitive, whereas I can reliably demonstrate that to be false. It has been case-sensitive for years, at least since 2016 if issue #332 is any indication.

Looking at the documentation tonight and reading that it is supposedly case-insensitive, I was very surprised, so I tested again tonight, and can confirm the app behavior contradicts the documentation. There is a difference in search results if I search for "marketing" vs "Marketing" in my feed item titles with a Liferea search folder. The results count, and the item results you can see with the naked eye, are completely different. For example:
* if I search for "arketing" I get 67 results;
* if I search for "marketing" I get only 27 results;
* if I search for "Marketing" I get 40 results.

40+27 = 67. Busted!

I'd like it all to be case-insensitive like the documentation states, or, even better, to have those conditions offer a case-insensitive vs case-sensitive variant of everything.

It would make my search queries much simpler and more reliable.

**Comment by antistress** [comment]
Indeed, and that's maybe quite even more subtle

I just tried to search for this article : "Debian Has Been Hosting A MiniDebConf Devoted To Linux/Open-Source Gaming"
Keying "**d**ebian **h**as **b**een" didn't provide any result, whereas "**h**osting" led me to the article whereas the article says "**H**osting" and not "**h**osting"
To sum up, I'm not sure to understand how Liferea search tool works..!
