### ISSUE TITLE
Items wrongly marked as read

### ISSUE THREAD

**Issue by samtygier** [lwindolf/liferea#91]
(orginally reported at http://sourceforge.net/p/liferea/bugs/1129/ ).

Sometimes all the unread items in Liferea will be suddenly marked as read. I am using Liferea 1.10.11

I think sometimes this happens when I am not intereacting with liferea. For example I might have 200 unread items, a few hours later, even though I have not interacted with liferea the count may have dropped to 50 (I suspect it dropped to zero, and then more items arrived).

I have also seen it happen while read through items in the unread folder. I will have for example 100 items in the unread folder, and as I press up to go from one to another, all of them will disapear. This is different from if I accidently hold down the up key, as in that case you can see them be removed 1 by 1.

**Comment by Leiaz** [comment]
From the errors in the linked bug, this looks similar to issue #208 and should be fixed by #489.
