### ISSUE TITLE
With 1.13.3, horizontal separator location is no longer saved

### ISSUE THREAD

**Issue by xxxxme** [lwindolf/liferea#910]
After upgrading from 1.12.8 to 1.13.3 on Arch Linux, the location of the horizontal separator between the headlines and content is no longer saved/loaded correctly.
To illustrate, a screenshot: https://postimg.cc/5Yz132Wc

**Comment by nekohayo** [comment]
This is a duplicate of issue #901 (that one would be worth retitling with keywords like pane, divider, separator, so that people can find it)

**Comment by Leiaz** [comment]
Duplicate of #901
