### ISSUE TITLE
"Focus mode" plugin suggestion

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#913]
This is simply an idea for a potentially easy (if actually doable) plugin for someone who would have time to tinker around and would be interested in this: a plugin to have an automatic visual "focus mode" for Liferea, that makes the "feedlist" GtkTreeView widget less prominent by setting its "opacity" property to 0.25 (instead of 1.0) when the mouse exits that widget's area, and sets it back to 1.0 when the mouse is over that widget's area (or when the plugin gets deactivated).

This would help me focus on reading the article, especially in horizontal view mode where my eyes would be able to go back to the left edge of a paragraph more easily after I'm done reading a line.

So when the mouse is outside the feedlist, it would look like this (it looks even better when using the Adwaita-dark theme, and when Liferea is in fullscreen mode):

![focus mode simulation - enabled](https://user-images.githubusercontent.com/479401/99924598-f6e31e80-2d08-11eb-89d1-e2a0db9c03f0.png)

When the mouse hovers the feedlist, it would look like this:

![focus mode simulation - disabled](https://user-images.githubusercontent.com/479401/99924606-ffd3f000-2d08-11eb-8079-475163bae015.png)

I'm throwing the idea out there in case someone wants an excuse to play with plugin development for Liferea and finds the idea interesting; I doubt I'll develop it myself, but I'm still filing this idea here, because an unspoken idea has a 100% probability of not being developed :)

**Comment by lwindolf** [comment]
Sounds like a cool plugin idea.

**Comment by sunwire** [comment]
@nekohayo @lwindolf I've written a plugin like suggested here, could you test it.
You can change the opacity in the preferences.
For now, there is no option to save the configuration. 
Any suggestions where I could save it?

![getfocus-plugin](https://user-images.githubusercontent.com/50745572/103485500-b0481000-4dee-11eb-921d-31605d8cbf7a.png)
https://github.com/sunwire/liferea/blob/getfocus-plugin/plugins/getfocus.py
https://github.com/sunwire/liferea/blob/getfocus-plugin/plugins/getfocus.plugin

**Comment by lwindolf** [comment]
@sunwire Works great. 

As for saving configuration:
- fully fledged .ini configuration file https://github.com/mozbugbox/liferea-plugin-studio/blob/master/webkit-setting/webkitsetting.py
- simple value saved in a file https://github.com/lwindolf/liferea/blob/94c57cfa7df81b230643c0d2cadd624d7e83c780/plugins/trayicon.py

**Comment by lwindolf** [comment]
With @sunwire PR merged this ticket is solved.

**Comment by nekohayo** [comment]
I forgot to mention my thanks, as I've been happily using this feature since. Thank you @sunwire for taking the time to create this plugin!

--------

P.s.: if I recall correctly, it _sometimes_ bugs a little bit under some circumstances (it "forgets" that it can set things to be transparent again) but I'm not sure under what conditions (maybe when the GTK theme changes, as my system alternates between Adwaita and Adwaita-dark depending on the time of the day?), and it's not a deal breaker.
