### ISSUE TITLE
Headline stuck sorting

### ISSUE THREAD

**Issue by jcalfee** [lwindolf/liferea#917]
I accidentally clicked on "Headline," now it always sorts.  How do I unselect the sort state?

![image](https://user-images.githubusercontent.com/204121/101101109-78e70900-358d-11eb-9cab-7625bfde74d4.png)

1.12-rc3

Thank you..

**Comment by lwindolf** [comment]
It's not really stuck, it was sorting by time per-default before too. So if you have the state with the sort arrow pointing down you have the identical behaviour as before you clicked it.

**Comment by jcalfee** [comment]
I thought that was sort by headline: Asc and Desc .. Ok, I'll try that next time.  I created a new folder and moved all the subfolders into it.  

Thanks!
