### ISSUE TITLE
[bug] Every favicon is Rainbow Dash

### ISSUE THREAD

**Issue by pavelbraginskiy** [lwindolf/liferea#926]
![image](https://user-images.githubusercontent.com/29113974/103152934-eb40a880-4749-11eb-9c7e-872bfd202e78.png)

A few days ago, I updated feeds with a spotty internet connection. The update went through, but Liferea dropped all the favicons that it previously knew about for the feeds and replaced them with a default image. 

I haven't been able to find a way to get the favicons back.

**Comment by Leiaz** [comment]
That is not Liferea's default feed icon, so not sure how you ended up with that icon. Maybe you were using a portal that returns a "can't connect" page instead of the connection just failing ?

To download them again, under Tools > Preferences > Folders, there is an "Update all favicons" button.

**Comment by JRDetwiler** [comment]
Did you ever figure out where it was coming from? My default favicon just randomly switched on me too.
