### ISSUE TITLE
german translation not complete

### ISSUE THREAD

**Issue by cheese1** [lwindolf/liferea#927]
i have a mix of german/english strings in my liferea 1.13.3
![Screenshot from 2020-12-26 15-57-23](https://user-images.githubusercontent.com/6437726/103153779-42b73680-4793-11eb-9025-362c7793eb97.png)

**Comment by cheese1** [comment]
in the po-file i see the translation commented as follows:
...
#~ msgid "_Update All"
#~ msgstr "_Alle aktualisieren"
...
that would translate the "Update All" string in the above menu, i activated.
maybe a wrong  translation-run.

**Comment by lwindolf** [comment]
Please note that 1.13 is a development release line where a call for translation is issued only before the first 1.14 release candidate to reduce translation efforts.

So when using unstable 1.13 release translation break all the time.

Nonetheless I updated the German translation.
