### ISSUE TITLE
Consider using libproxy

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#930]
A long time ago we discussed switching to libproxy to simplify proxy detection. Nowadays entire GNOME, Mozilla and others are on libproxy, so it make sense to follow suite. Doing so will give us support for proxy auto config (PAC) and Javascript proxy discovery (WPAD)

Preconditions:
- Research how preferences would be with libproxy
- Research regression on existing socks usage howto
- Research how multi proxies would be handled

**Comment by lwindolf** [comment]
Research 

- While it would work there is a serious problem with libproxy using the JS core library of Webkit (which we already use via WebkitGTK). This allows for library version collisions and crashes.
- Same would apply when using glib-networking.
- There should be no SOCKS regression
- Multiple proxies are handled by libproxy by returning an ordered list to try

Note: libproxy only handles proxy determination, everything else still has to be configured with libsoup.

**Comment by yaneti** [comment]
recent libproxy can be built with duktape for javascript (e.g. in Fedora)

**Comment by lwindolf** [comment]
@yaneti Might be, still it's most useful to rely on the distro provided libproxy which might have any JS backend.

**Comment by lwindolf** [comment]
For now I decide on not using libproxy.
