### ISSUE TITLE
Headerbar plugin: bind F10 keyboard shortcut to toggling the main menubutton

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#931]
Most/all GNOME apps use the de-facto standard F10 keyboard shortcut for toggling the main menubutton, so if possible, this app should as well.

This is also documented as a standard shortcut in https://developer.gnome.org/hig/stable/keyboard-input.html.en

**Comment by sunwire** [comment]
@nekohayo Can You test this PR https://github.com/lwindolf/liferea/pull/937 ?
