### ISSUE TITLE
Add Hotkeys (New Subscription, Delete Entry, Etc.) [enhancement]

### ISSUE THREAD

**Issue by mirrorsonthewall** [lwindolf/liferea#939]
Some hotkey ideas:

CTRL+N for new subscription

CTRL+ALT+N for new folder

Delete or Backspace key to delete a new story/item

Discuss other ideas

**Comment by lwindolf** [comment]
Please have a look at the "Help" menu under "References". The Delete key already does what you want.

Ctrl-N is already allocated to another function.

If you want special hotkeys you can modify your setup as described here https://lzone.de/liferea/blog/Liferea-Trick-8-Change-Menu-Accelerators.html

**Comment by mirrorsonthewall** [comment]
@lwindolf apologies about Delete (error on my part).

re: the link, it's four years old, with option one there is no "~/.config/liferea/accels" file (has it changed?)

option two - is it distro specific?

so I re-thought the problem and realized that alt (as used to navigate menus in other programs) gives close enough functionality for anyone looking for a quick fix (this solves the problem enough for me):

(comma means separate keystroke of combo/chord to press)

New Folder: ALT+S, F

New Subscription: ALT+S, N, RETURN/ENTER

(General form: ALT+[first letter of menu item, like "V" for View], then typing the underlined menu item's letter navigates to it and executes the menu item, unless there are two items with the same first letter being used and typing the letter will cycle between them and then you can hit return/enter to select the item)

**Comment by lwindolf** [comment]
@mirrorsonthewall thanks for trying to documentation, which you are right about this, is outdated. I updated it to document the correct procedure for 1.12 to 1.14 releases.

About using Alt combinations: that is not a way to go as Alt is more or less reserved for the Window Manager and menu access keys. For more details: https://developer.gnome.org/hig/stable/keyboard-input.html.en

Applications have to contend with Ctrl, Ctrl-Shift mostly.

But this is only true for default keybindings. For yourself you can define anything you want :-)
