### ISSUE TITLE
Notification plugin

### ISSUE THREAD

**Issue by sunwire** [lwindolf/liferea#949]
The behavior of the libnotify plugin has changed, previously only shows notifications when there were new items, now they show up with every update.
This issue was probably caused by commit
https://github.com/lwindolf/liferea/commit/aa8f77648b16819eff944b86df09dc9eb8b93f2c
file src/subscription.c line 240
By moving feedlist_node_was_updated (node) outside of if statement

Now it looks like this
![liferea](https://user-images.githubusercontent.com/50745572/104231089-57a7f100-5446-11eb-8352-dedbfcc7662f.png)

**Comment by lwindolf** [comment]
Reproduced

**Comment by lwindolf** [comment]
Fixed. Thank you for debugging this!!!
