### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by geoffm** [lwindolf/liferea#95]
Running liferea 1.10.3 on LinuxMint17. When launching liferea in terminal I get following errors:
(liferea:7652): Gtk-CRITICAL **: gtk_tree_store_get_path: assertion 'iter->stamp == priv->stamp' failed
(liferea:7652): Gtk-CRITICAL **: gtk_tree_view_set_cursor_on_cell: assertion 'path != NULL' failed
(liferea:7652): Gtk-CRITICAL **: gtk_tree_view_scroll_to_cell: assertion 'tree_view->priv->tree != NULL' failed
Only way to get it to launch is to reset feed list.

**Comment by lwindolf** [comment]
Closing as duplicate to #122
