### ISSUE TITLE
Number of unread in low right corner is exactly 2 times the correct number

### ISSUE THREAD

**Issue by GaryGate15** [lwindolf/liferea#952]
Liferea 1.3.5 / Linux Mint 20.1

The number of Unread shown is lower right corner of Liferea is exactly 2 times the correct number, and decreases in steps of 2 when articles are read. The Unread folder shows correct number.

**Comment by CydNoxzed** [comment]
Liferea 1.13.4-1 / Arch Linux

I cant confirm this behavior. The steps decreases by 1 if I read an item (and increase by 1, if I mark the item as 'unread' again). 

BUT it would decrease/increase by more than 1, if the same item is in multiple feeds (eg. one from a "planet" and the other one from the source). 

Just to be sure: Are you using version 1.3.5 or 1.13.5?

**Comment by GaryGate15** [comment]
I'm using version 1.13.5, of course. Sorry for the typo.

Here's a screenshot from a moment ago.

![Screenshot from 2021-02-20 12-53-27](https://user-images.githubusercontent.com/51757683
/108594642-7ec5dc80-737b-11eb-899c-ed1d7890e24b.png)

**Comment by sunwire** [comment]
> Here's a screenshot from a moment ago.

It is because of the "Unread" folder. The same items are in the "Unread" this is why they are doubled.
