### ISSUE TITLE
Feeds No Longer Updating on Launch

### ISSUE THREAD

**Issue by SenorFusion** [lwindolf/liferea#958]
Expected Behavior:
Tool > Preferences > Update all Feeds on Startup checked.
All feeds update on startup

Actual Behavior:
No feeds update on start
Manually click Subscriptions > update All > all feeds are updated

(I am not sure if this is related so I am including it.)
Window does not return to previous layout. 
Default setting of Wideview 
The "Headline" column (middle) stretches about 80% of screenwidth.
Regardless of how I arrange the window it returns the this layout on every startup.

1.13.4 and 1.13.5
Fedora 32

![liferea](https://user-images.githubusercontent.com/1929777/106313908-f7cb8b80-6236-11eb-81cb-01ebb116b5d0.png)

**Comment by sunwire** [comment]
Hi @SenorFusion
As for the update on startup, under Fedora 33, everything works fine.
The second issue see https://github.com/lwindolf/liferea/issues/901

**Comment by lwindolf** [comment]
Closing old ticket.

BTW the layout issue was improved with 1.14-RC1
