### ISSUE TITLE
Feed autodetection failing on some websites

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#959]
Taking this website as an example: https://www.suzanbond.com/articles

If you throw that URL directly at Liferea 1.13.4 to autodetect, you will get feed parsing errors, and the timestamps will be wrong, as it tries to parse the URL as-is:

![sbond autodetect](https://user-images.githubusercontent.com/479401/106967455-34a2f100-6715-11eb-8a9c-65ffe8c661df.png)

However, if you look at the source code of that page in a browser, we can see: `<link rel="alternate" type="application/rss+xml" title="RSS Feed" href="https://www.suzanbond.com/articles?format=rss" />`

...which, when given explicitly to Liferea, behaves correctly:

![sbond manual feeding](https://user-images.githubusercontent.com/479401/106968581-25bd3e00-6717-11eb-8170-b13f6d6853a9.png)

Strangely, when looking at some other website like https://yannickkhong.com/blog which is also on SquareSpace, that one gets parsed without problems by Liferea, because Liferea correctly adds the ?format=rss automatically.

The only notable difference, except the domain names, is that one is "/articles?format=rss" and the other is "/blog?format=rss".

Is there something Liferea could do to autodetect that properly? The W3 feed validator says the feed itself (with ?format=rss) is valid, so it seems to be something about autodetection.

**Comment by nekohayo** [comment]
Similarly, someone pointed out to me that if you tell Liferea to add `https://blog.onlinejobs.ph/` as a feed source, you'll get all those wrong timestamps (and the missing feed description metadata) even though that blog is a standard Wordpress blog. If you dig into the source code and instead give the `https://blog.onlinejobs.ph/feed` URL to Liferea explicitly, then it happily parses the dates _and_ the feed's description metadata too.

I'm a bit perplexed. Doesn't Liferea parse that source code and get the /feed/ URL (or other indicated rss+xml feed in the page's metadata) automatically? How else can it parse the feed if not from there?

**Comment by nekohayo** [comment]
Same goes for `https://lifeforbusypeople.com/` vs manually giving it the `https://lifeforbusypeople.com/feed/` URL to parse...

**Comment by lwindolf** [comment]
I believe this is a duplicate to #1033 which was fixed with 1.13.9
