### ISSUE TITLE
segmentation fault when opening the `feed` URL scheme

### ISSUE THREAD

**Issue by beroal** [lwindolf/liferea#960]
[It seems that the only way to pass feed URLs from Firefox to Liferea now is using a URL with the `feed` scheme.](https://github.com/Reeywhaar/want-my-rss/issues/23) When I press “Subscribe” on a feed preview for [this forum](https://bbs.archlinux.org/) shown by the “Want My RSS” Firefox extension, Liferea terminates with a segmentation fault:
```
(liferea:66008): GLib-GIO-WARNING **: 20:50:11.042: Invalid URI 'http://[https://bbs.archlinux.org/extern.php?action=feed&type=atom]:80/'

(liferea:66008): GLib-Net-CRITICAL **: 20:50:11.042: g_libproxy_resolver_lookup_finish: assertion 'g_task_get_source_tag (G_TASK (result)) == g_libproxy_resolver_lookup_async' failed
Segmentation fault (core dumped)
```
I determined that Liferea receives the URL `feed:https%3A%2F%2Fbbs.archlinux.org%2Fextern.php%3Faction%3Dfeed%26type%3Datom`. Liferea crashes even without Firefox if this URL is given to it on the command line.

**Comment by Leiaz** [comment]
It looks like it is the same crash as #892. In a way it could be a libsoup bug, as it "succeed" in parsing the url and creates a SoupMessage with a valid SoupURI but then crashes when trying to fetch it.

As noted in the extension's thread, it will work if you can pass the non encoded url, that is feed:https://bbs.archlinux.org/extern.php?action=feed&type=atom
The [Feed scheme](https://en.wikipedia.org/wiki/Feed_URI_scheme) is valid, but the url must not be encoded.

**Comment by beroal** [comment]
> It looks like it is the same crash as #892.

Yes, my bug is a duplicate.
