### ISSUE TITLE
Custom server URL for standard Google Reader API

### ISSUE THREAD

**Issue by tabic** [lwindolf/liferea#962]
Liferea already supports the Google Reader API but has no option to set a custom server URL. Adding an option to configure the server URL for the Google Reader API would add support for multiple (self) hosted RSS solutions.

For example:
FeedHQ - https://github.com/lwindolf/liferea/issues/515
FreshRSS - https://github.com/lwindolf/liferea/issues/172

Any other RSS app which wants to be added to Liferea or other clients could just implement the Google Reader API.

**Comment by lwindolf** [comment]
If it is actually just about providing standard Google Reader API this sounds easy. This needs some testing.

If it turns out there are too much deviations from the API we should not do it.

**Comment by tabic** [comment]
@Alkarex does FreshRSS provide the "standard" Google Reader API or are there deviations?

**Comment by Alkarex** [comment]
Quite standard, and feel free to report needs of additional compatibility

**Comment by lwindolf** [comment]
Just a note on Google reader API supporting aggregator servers:
- FreshRSS
- FeedHQ
- Reedah (some modifications)
- Miniflux https://github.com/miniflux/v2/pull/1115
- Bazqux https://github.com/bazqux/bazqux-api

Note: TheOldReader does not count as it only uses similar API endpoints but speaks JSON for content instead of XML.

**Comment by Alkarex** [comment]
@lwindolf If you need a FreshRSS test account, or spot any incompatibilities / misses, I could happily help

**Comment by lwindolf** [comment]
@Alkarex Yes, if you can provide an account for testing purposes would help saving the setup time, especially considering setting it up in a secure way on my webserver :-)

**Comment by lwindolf** [comment]
Generic Google Reader API support has landed in master. Please test for FreshRSS!
