### ISSUE TITLE
plugin-installer.py assumes git is present and available, which is not the case within a sandbox like Flatpak

### ISSUE THREAD

**Issue by nekohayo** [lwindolf/liferea#963]
If you install the flatpak version of Liferea ([from flathub](https://flathub.org/apps/details/net.sourceforge.liferea) for example), go into the Liferea plugins management UI, and try to download/install a new one, you will get this uncaught Python traceback (most recent call last):
```
  File "/app/lib/liferea/plugins/plugin-installer.py", line 198, in install
    model[treeiter][0] = self.install_plugin(self.get_plugin_by_name(model[treeiter][2]))
  File "/app/lib/liferea/plugins/plugin-installer.py", line 266, in install_plugin
    p = subprocess.Popen(["git", "clone", "https://github.com/%s" % plugin_info['source'], "."])
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'git'
```

**Comment by sunwire** [comment]
I don't know flatpak but I think it's a problem with the flatpak mainifest. During Liferea installation it should also install git.

**Comment by nekohayo** [comment]
Still, strictly speaking the code shouldn't just silently die in the background with an uncaught traceback either, that's still a bug.

But I do wonder if git can be part of @mikelolasagasti's flatpak too.

**Comment by sunwire** [comment]
> Still, strictly speaking the code shouldn't just silently die in the background with an uncaught traceback either,
You are right. I prepared PR. Now it looks like this:
![message](https://user-images.githubusercontent.com/50745572/108607124-66bf7e80-73b6-11eb-9693-509a15a5fa54.png)

**Comment by lwindolf** [comment]
Closing this as it was fixed with @sunwire's PR

**Comment by bbhtt** [comment]
> But I do wonder if git can be part of @mikelolasagasti's flatpak too.

I think we can add `git` to the flatpak manifest once 3. here is fixed https://github.com/lwindolf/liferea/issues/1077 

I have a branch with `git` included if you want to test: download flatpak bundle from https://github.com/bbhtt/net.sourceforge.liferea/blob/external-plugins/net.sourceforge.liferea.flatpak (built from [this](https://github.com/bbhtt/net.sourceforge.liferea/tree/external-plugins) branch) `flatpak install --user net.sourceforge.liferea.flatpak` and `flatpak run net.sourceforge.liferea`

But installing external plugins will still fail wit it as it tries to copy it to `~/.local/share/liferea/plugins`  (3.)
