### ISSUE TITLE
Not parsing feeds

### ISSUE THREAD

**Issue by jayheme** [lwindolf/liferea#966]
I am trying to subscribe to a few Physics journals but liferea gives an error of not being able to parse the feed. I tried feed reader and the feed was working fine. https://iopscience.iop.org/journal/1367-2630 This is one of the websites which is facing this error. I am using Liferea 1.13.1 on Pop OS 20.10.

**Comment by sunwire** [comment]
I use Liferea 1.13.5 and it works fine but I have to use [this link](https://iopscience.iop.org/journal/rss/1367-2630)
![2021-03-07_08-49](https://user-images.githubusercontent.com/50745572/110233239-a3dd5200-7f1a-11eb-9c89-e4d741300049.png)
It does not detect it automatically because of the lack of an appropriate entry in the <head> section of that page

**Comment by jayheme** [comment]
I am using that link. Will try upgrading to 1,13,5

**Comment by Lyokolux** [comment]
> I use Liferea 1.13.5 and it works fine but I have to use [this link](https://iopscience.iop.org/journal/rss/1367-2630)

It works fine with Liferea 1.12.7 too

**Comment by jayheme** [comment]
I have tried 1.13.5 and currently i changed to 1.13.4 and it is not working on both. I wanted to subscribe to a few journals from the same publisher and none are working. They all give the same error.

**Comment by sunwire** [comment]
@jayheme Sorry my bad. I  have checked and I am using the latest version (1.13.5 + other commits). So I install 1.13.4 and 1.13.5 and you are right version 1.13.4 and 1.13.5 does not work. 
Oddly enough, it stopped working after installing the previous version!

**Comment by sunwire** [comment]
There is a problem, sometimes it adds feed but mostly it does not. Its totally random.
![2021-03-07_16-47](https://user-images.githubusercontent.com/50745572/110246169-6d292b00-7f5e-11eb-8b6b-7628dd7d76eb.png)
![2021-03-07_16-52](https://user-images.githubusercontent.com/50745572/110246171-6dc1c180-7f5e-11eb-9f36-83a6f42db45e.png)

Version does not matter.

**Comment by jayheme** [comment]
Ya it is totally random. On refresh again the error pops up again.

**Comment by sunwire** [comment]
Update. I use wget to test this feed url and for the first time I get the feed but for the next time I got error 302 moved temporarily and [this link](https://hkvalidate.perfdrive.com/?ssa=56ec8561-9e2c-4b2f-8b94-f719d3e644a3&ssb=09100223726&ssc=https%3A%2F%2Fiopscience.iop.org%2Fjournal%2Frss%2F1367-2630&ssi=8a370344-8427-4bfc-8988-da37fb869cd3&ssk=support@shieldsquare.com&ssm=70316231493992323103492948541396&ssn=4355308e2b8f21186680102bbbbd8ba0da6484b0e53a-fc36-4cb5-ae0ff6&sso=6c6c081f-6b98c4ee79e00403503b38386302a888b354e1d4fbd82761&ssp=82945012531615141091161516208961410&ssq=79090253330448212955933304947806017821723&ssr=MTU5LjIwNS4xMzguMTg4&sst=Wget/1.21.1&ssv=&ssw=)
**It's some protection against robots this is why it doesn't work**
![2021-03-07_17-16](https://user-images.githubusercontent.com/50745572/110246783-e88bdc00-7f60-11eb-9dd9-6e979156b52f.png)

**Comment by jayheme** [comment]
But i was able to get the feeds in Feed Reader app. This issue did not arise in that app.

**Comment by sunwire** [comment]
Update 2. The same with curl. For the first time it works but next time it doesn't (error 302)
But if I set well know agent e.g. Firefox it works every time.
`curl -A "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0" https://iopscience.iop.org/journal/rss/1367-2630`

The solution would be to be able to set up a fake agent or write to the administrator of this problematic page to accept Liferea as a trusted agent

**Comment by jayheme** [comment]
Feedly also works quite well.

**Comment by lwindolf** [comment]
Closing old ticket.
