### ISSUE TITLE
Mobile interface support please?

### ISSUE THREAD

**Issue by 10leej** [lwindolf/liferea#968]
The client works on the Pinephone, but the interface is too cramped for efficient use. I can make it work, but would be nicer if I didn't have to constantly reposition the left pane and the verticle split.

**Comment by lwindolf** [comment]
Sorry the project just does not have any developer with time to do this.

**Comment by mozbugbox** [comment]
Maybe a mode, that would hide the left pane and the item list pane, will do.

This can be done in a plugin.

**Comment by mozbugbox** [comment]
I put together a simplistic plugin called `Mobile Mode`: [Mobile Mode Plugin](https://github.com/mozbugbox/liferea-plugin-studio/wiki/Mobile-Mode)

I've no way to run Liferea on a mobile phone. Therefore the "features" of the plugin came out of my imagination and was only tested on desktop Linux :grinning:.
