### ISSUE TITLE
Documentation request: How to hack the "Headline" font properties?

### ISSUE THREAD

**Issue by Ottaviocr** [lwindolf/liferea#970]
Hi, I'm running Liferea 1.12.6 on Debian Buster (I have problems compiling from sources at the moment). Previously, I was using Liferea 1.12~rc3-1 on Debian Oldstable. While the new version is much better, I find the "Headline" fonts too big, see:

![Screenshot from 2021-03-21 09-56-03](https://user-images.githubusercontent.com/34311351/111977593-d1212700-8afa-11eb-8e0e-6ab24d496e49.png)

I am aware of https://lzone.de/liferea/blog/Liferea-Trick-10-Custom-CSS-for-Article-Rendering.html, but it seems my .config/liferea/liferea.css gets ignored all the time, I have even deleted it or removed all entries, and it stills shows with the default properties.

Where and how do I have to intervene to make the new Liferea look like the old one? Thanks.

**Comment by lwindolf** [comment]
There is now good solution to styling GtkTreeView rows :-(

**Comment by Ottaviocr** [comment]
> There is now good solution to styling GtkTreeView rows :-(

Sorry, I don't get it. Do you mean "there is **no** good solution" or "there is **now** a good solution"?

In any case, I wonder why my custom css gets ignored.

**Comment by lwindolf** [comment]
I meant there is no good solution. You are right I need to explain in more detail

1. the item list is not a HTML widget and thus cannot be styled as described in https://lzone.de/liferea/blog/Liferea-Trick-10-Custom-CSS-for-Article-Rendering.html
2. the item list is a GtkTreeView widget and while GTK has styling for widget it is very complex and might not achieve what you intend: https://developer.gnome.org/gtk3/stable/chap-css-overview.html
