### ISSUE TITLE
Table cell in <description> cannot handle text longer than 24

### ISSUE THREAD

**Issue by mozbugbox** [lwindolf/liferea#971]
When loading a RSS feed with html in the `<description>`, if a table cell `<td>` contains text longer than 24 chars, then the Liferea will only show the table row with the long cell in it. Other rows in the table will not be shown.
```
<table>
    <tr>
        <td>line 1 cell 1</td>
        <td>line 1 cell 2</td>
    </tr>
    <tr>
        <td>line 2 cell 1</td>
        <td>line 2 cell 2</td>
        <td>123456789 123456789 12345</td>    <=== Cell with 25  chars
    </tr>
    <tr>
        <td>line 3 cell 1</td>
        <td>line 3 cell 2</td>
    </tr>
</table>
```

Sample Feed: [rss-long-table-cell.txt](https://github.com/lwindolf/liferea/files/6187637/rss-long-table-cell.txt)

**Comment by lwindolf** [comment]
That is the effect of the reader mode. Readability.js guesses this long line to be real content and drops the rest. If you disable reader mode (currently by the icon in the upper right corner of the title) it will render the table correctly.

**Comment by mozbugbox** [comment]
You are right. Turn off reader mode fixed it. Thanks
