### ISSUE TITLE
liferea.css is no longer applied after update webkit2gtk-2.30.6 to 2.32.0 in archlinux

### ISSUE THREAD

**Issue by mohafri** [lwindolf/liferea#973]
Liferea 1.13.5 and also newest version from master (commit b3de8af3c8b1a04df33211053cba9b6a74b8a2de).

With webkit2gtk-2.30.6 everything is fine, with webkit2gtk-2.32.0 liferea.css doesn't work - see screenshots with activated webkit2-inspector. 

![webkit2gtk-2 30 6](https://user-images.githubusercontent.com/81648697/113044236-b6efe480-919d-11eb-876c-c9abf11afb9b.png)
![webkit2gtk-2 32 0](https://user-images.githubusercontent.com/81648697/113044243-b8211180-919d-11eb-95f6-db94605c1a92.png)

With webkit2gtk-2.32.0 I get the message: "User Agent Style Sheet cannot be modified." and as error-message: "Not allowed to load local resource: file:///home/harald/.cache/liferea/style.css?1617130761"
Perhaps of this?: The changelog (https://webkitgtk.org/2021/03/26/webkitgtk2.32.0-released.html) states: "New API to remove individual scripts/stylesheets using WebKitUserContentManager."

The only workaround for me is to downgrade to webkit2gtk-2.30.6.

Am I missing something?

Best regards
harald

**Comment by sunwire** [comment]
I can confirm on Fedora 33 the same.

**Comment by sunwire** [comment]
It looks that all file:// urls are not allowed, style, js, pictures
![2021-04-03_20-19](https://user-images.githubusercontent.com/50745572/113487806-a5625180-94a9-11eb-945f-28322f97b5b2.png)

**Comment by sunwire** [comment]
Thanks @Leiaz it works well.

**Comment by mohafri** [comment]
@Leiaz
Many thanks - the issue is fixed for me too! Liferea.css works again.

**Comment by LiamDawe** [comment]
Would this be why as of the latest updates on Arch, the content window is white when the rest adhere to dark theme?

**Comment by Leiaz** [comment]
@LiamDawe Yes, that is due to the css file not loading.

**Comment by paulgevers** [comment]
@Leiaz just to confirm, your patch also works with older webkit2gtk versions, right?

**Comment by Leiaz** [comment]
@paulgevers Yes, it should, I'm not using anything marked in the doc as requiring a particular version.

**Comment by paulgevers** [comment]
@Leiaz thanks for confirming. One more request. I'm expecting the new webkit2gtk to also show up in Debian stable, which means that I also need to fix liferea 1.12.6. Your patch doesn't apply cleanly, can you double check that the patch looks good? I.e. I inserted it in the correct context?

I have prepared the following commit for this review: 
https://salsa.debian.org/debian/liferea/-/commit/78fa1f32078eb7a56073ed49fd4b5ce481250f83#73b185a6dfa8c05a7c51823326e97de1cf49b443

**Comment by Leiaz** [comment]
@paulgevers Yes, that patch is good.

**Comment by paulgevers** [comment]
@Leiaz awesome, thanks for confirming.
