### ISSUE TITLE
Webkit left-clicking links freezes and then blanks the HTML view

### ISSUE THREAD

**Issue by lwindolf** [lwindolf/liferea#981]
Introduced with 1.13.3 happens only when left-clicking a link. Does not happen on middle click or opening links via context menu in another tab.

**Comment by Leiaz** [comment]
I can't reproduce this.
I'm using Webkit2Gtk 2.32.0 and Liferea from master.

**Comment by lwindolf** [comment]
Thanks for the info. Being on Ubuntu libwebkit2gtk-4.0 2.30.6 I'll test an upgrade

**Comment by lwindolf** [comment]
Also happens with Ubuntu 21.04 libwebkit2gtk-4.0 2.23.0-1ubuntu3

**Comment by lwindolf** [comment]
Further debugging shows that doing this with Webkit inspector opened:

- on first non-internal load inspector network trace shows 2 loadings of "about:blank" at the end of the network resource list
- on second non-internal load inspector stop working shows blank page itself, sometimes causes flickering and rarely crashes
- gdb shows a "Thread 0x.... (LWP ....) exited" the moment the page goes blank, which I guess indicates the Webkit child process crashing

**Comment by lwindolf** [comment]
@Leiaz I tried a lot of things without success. I see no way than to switch back to the 1.13.3 code for now. This does not seem to affect too many users but for those it does it makes the internal browser completely useless.

**Comment by lwindolf** [comment]
Hmm... just found that it even affects 1.13.2 when Javascript is enabled. With later releases Javascript being mandatory for reader mode...

**Comment by lwindolf** [comment]
And I just learned about /usr/lib/x86_64-linux-gnu/webkit2gtk-4.0/MiniBrowser which reproducably crashes too.

So except disabling Javascript there is nothing that can be done (on Liferea side).

**Comment by lwindolf** [comment]
a209455f fixes a buggy code path that prevented the disabling of JS to work in 1.13.3+, no behaviour when JS is disabled is identical to 1.13.2.

With this there is a proper workaround in place.
