### ISSUE TITLE
Installation via Flatpak does not browse my file folders.

### ISSUE THREAD

**Issue by Neocazen** [lwindolf/liferea#982]
Hi, guys. I just installed the Flatpak version (1.13.5) and it does not allow me to browse my folders to search for a Feed file that I exported from the installed version via apt. Can you confirm there?

**Comment by bbhtt** [comment]
Looks like Liferea doesn't utilize the [File Chooser Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser). In that case `--filesystem=xdg-download` for `~/Downloads` or `--filesystem=home` for entire `~/` accordingly to the Flathub manifest should probably be added. (https://docs.flatpak.org/en/latest/sandbox-permissions.html > Filesystem access).

> Hi, guys. I just installed the Flatpak version (1.13.5) and it does not allow me to browse my folders to search for a Feed file that I exported from the installed version via apt. Can you confirm there?

You can use the `--filesystem=` (see https://manpages.debian.org/unstable/flatpak/flatpak-run.1.en.html) see option to grant access to the desired directory in the meantime like this:
```
flatpak run --filesystem=xdg-download net.sourceforge.liferea

```
gives access to `~/Downloads` (replace accordingly).

**Comment by Neocazen** [comment]
> Looks like Liferea doesn't utilize the [File Chooser Portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.FileChooser). In that case `--filesystem=xdg-download` for `~/Downloads` or `--filesystem=home` for entire `~/` accordingly needs to be added to the Flathub manifest (https://docs.flatpak.org/en/latest/sandbox-permissions.html > Filesystem access).
> 
> > Hi, guys. I just installed the Flatpak version (1.13.5) and it does not allow me to browse my folders to search for a Feed file that I exported from the installed version via apt. Can you confirm there?
> 
> You can use the `--filesystem=` (see https://manpages.debian.org/unstable/flatpak/flatpak-run.1.en.html) see option to grant access to the desired directory in the meantime like this:
> 
> ```
> flatpak run --filesystem=xdg-download net.sourceforge.liferea
> ```
> 
> gives access to `~/Downloads` (replace accordingly). You can copy the desktop file from `/home/user/.local/share/flatpak/exports/share/applications/net.sourceforge.liferea.desktop` to `~/.local/share/applications` and change the `Exec= ` line with that one.

Got. Thank you very much
