### ISSUE TITLE
Update screenshots

### ISSUE THREAD

**Issue by mikelolasagasti** [lwindolf/liferea#987]
Currently Liferea's flatpak build in flathub[1] shows screenshots found in the Liferea's homepage[2] that are from ~2013. Different "Software Center" applications like Gnome-software also use these screenshots.

New screenshot should follow AppStream's Metadata guide[3] and maybe show new features like plugins or MediaRSS/GeoRSS support. Screenshots URLs should be changed in `net.sourceforge.liferea.appdata.xml.in` and validate with `$ appstream-util validate-strict net.sourceforge.liferea.appdata.xml.in`

[1] https://flathub.org/apps/details/net.sourceforge.liferea
[2] https://lzone.de/liferea/screenshots.htm
[3] https://freedesktop.org/software/appstream/docs/chap-Quickstart.html#qsr-app-screenshots-info

**Comment by mikelolasagasti** [comment]
@lwindolf I can take news captures, but before taking them I wanted to check with you. I think it would be great to have them changed in the official webpage and if not be part of the repo. Would you be OK if I paste or link them here and you change them in the webpage?

**Comment by mikelolasagasti** [comment]
Some options:

Main window
https://mikel.olasagasti.info/tmp/liferea/screenshots/screenshot2.png
Error handling
https://mikel.olasagasti.info/tmp/liferea/screenshots/screenshot3.png
Reduced view
https://mikel.olasagasti.info/tmp/liferea/screenshots/screenshot4.png
Music player
https://mikel.olasagasti.info/tmp/liferea/screenshots/music-player.png
Comic
https://mikel.olasagasti.info/tmp/liferea/screenshots/comic.png
Preference window
https://mikel.olasagasti.info/tmp/liferea/screenshots/preferences.png
Plugin window
https://mikel.olasagasti.info/tmp/liferea/screenshots/plugins.png
Per feed options
https://mikel.olasagasti.info/tmp/liferea/screenshots/per-feed-options.png
GeoRSS
https://mikel.olasagasti.info/tmp/liferea/screenshots/georss.png

Ideas for other screenshots/features are welcome.

**Comment by lwindolf** [comment]
@mikelolasagasti Thanks for those screenshots. I updated the screenshot page with them. I did drop the georss picture though... I know that it might be important for you... but I think it is quite specific. I hope this is ok for you!

**Comment by mikelolasagasti** [comment]
Thanks @lwindolf and no worries about the GeoRSS.

Can you check the img src link for screenshot6, it has a typo.

I'll update the AppData manifest in the upcoming days.

**Comment by lwindolf** [comment]
@mikelolasagasti Thanks for the catch. Nr. 6 is fixed!
