### ISSUE TITLE
feed not working (missing title)

### ISSUE THREAD

**Issue by cheese1** [lwindolf/liferea#988]
https://www.us-cert.gov/ncas/all.xml

liferea finds the items, but is not able to parse them, eg.: title is set to *** No title ***
![Screenshot from 2021-05-13 16-33-57](https://user-images.githubusercontent.com/6437726/118140866-0fefa100-b409-11eb-91ff-e1c09f3ea4ad.png)

this is with version 1.13.6

**Comment by sunwire** [comment]
I think it's not a liferea bug but not properly formatted rss (there is a html tag <a> in the title)
I wrote to them a few weeks ago but there is no response.

**Comment by mozbugbox** [comment]
Filter with
```
sed -E -e 's|(<title>)<a[^>]+>|\1|' -e 's|</a>(</title>)|\1|'
```

**Comment by sunwire** [comment]
@mozbugbox Thanks! It works perfectly.

**Comment by cheese1** [comment]
works great
cert informed. they will not respond to my complaint either

**Comment by lwindolf** [comment]
Closing this
