### ISSUE TITLE
Unreal Engine feed issues with dates

### ISSUE THREAD

**Issue by LiamDawe** [lwindolf/liferea#989]
Hi, seems this feed: https://www.unrealengine.com/rss doesn't correctly parse in Liferea. It doesn't correctly grab the date, even though the XML is there causing it to repopulate the whole thing. Very annoying and ends up spamming the app.

**Comment by CydNoxzed** [comment]
@LiamDawe I can confirm this behavior on Arch Linux with Liferea 1.13.5

But the feed itself seems to be invalid. [see w3 feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.unrealengine.com%2Frss).

The datetime in the updated tag does have a wrong format:
>` <updated>Fri, 28 May 2021 14:00:00 GMT</updated>`

[RFC4287](https://datatracker.ietf.org/doc/html/rfc4287#section-3.3) wants the format to be like:
> `<updated>2003-12-13T18:30:02Z</updated>`

Maybe I'm wrong, but I don't think that's Liferea fault if the feed does not comply with the standard. 
Or do I read the wrong rfc and the first format is a valid one?

**Comment by LiamDawe** [comment]
Ah damn you're right, I didn't run it through that as I wrongly assumed a company with infinite money like Epic would know how to do an RSS feed properly :P

**Comment by LiamDawe** [comment]
Have reached out to them: https://twitter.com/gamingonlinux/status/1398932397920600065
